### ISSUE TITLE
unison package fails to install on OS X 10.8.4/Xcode Version 4.6.3 (4H1503)

### ISSUE THREAD

**Issue by gbruncot** [ocaml/opam-repository#1003]
lablgtk.2.16.0 fails its configure:

configure:3249: cc -o conftest    conftest.c  >&5
conftest.c:9:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^

I am new to developement on Mac. Somewhat the Xcode SDK for my MBP does not seems to be in the include path (which have an stdio.h). Is that at all under OPAM control? Is it purely a mishap in my Xcode environment setup?
Thanks!

**Comment by samoht** [comment]
Do you still have that issue with recent versions of labgtk? Please re-open if yes.
