### ISSUE TITLE
OPAM pin issue

### ISSUE THREAD

**Issue by OCamlPro-Iguernlala** [ocaml/opam-repository#10049]
I don't know if this is a known issue and/or if it is fixed in OPAM 2...
With OPAM 1.2.2, the following pin command fails silently:
```
opam pin add frama-c 20161101
```
Once debug activated, I realized that this is due to absence of `url` file for this package.
A message that explains the failure in missing in this case.

**Comment by dbuenzli** [comment]
This issue is not related to the `opam-repository` please file this there https://github.com/ocaml/opam

**Comment by OCamlPro-Iguernlala** [comment]
Oups ! sorry for that

**Comment by dbuenzli** [comment]
No problem ! Can happen.
