### ISSUE TITLE
ppx_deriving can't be installed on Mac OS X (OS Sierra) with new Homebrew ocaml due to version 4.05.0

### ISSUE THREAD

**Issue by sjmcdowall** [ocaml/opam-repository#10094]
Sorry if I am doing something wrong, but this is my first ocaml experience -- I am trying to follow instructions for installing various things and one of the steps has me do : 

`opam install uri qcow-format io-page.1.6.1 conf-libev`

But that fails for dependency reasons:

**
Your request can't be satisfied:
  - ppx_deriving is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.05" & opam-version >= "1.2".
  - sexplib<113.01.00 is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03".
  - sexplib<113.24.00 is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03".
**

I noticed that ppx_deriving has a ruleset for ocaml-version to be < "4.05" but we are at "4.05.0" which isn't less .. should the dependency be "<= "4.05.0" ??  

Thanks!

**Comment by dbuenzli** [comment]
Apparently ppx_deriving is incompatible with `4.05`. You should install another compiler. Try to do an  `opam switch 4.04.2` and then install the set of packages you want. Please report back if you succeed.

**Comment by sjmcdowall** [comment]
Yes indeed that worked like a charm!  Thanks @dbuenzli

**Comment by dbuenzli** [comment]
You are welcome.
