### ISSUE TITLE
ppx_tool.5.0 hash has changed

### ISSUE THREAD

**Issue by talex5** [ocaml/opam-repository#10183]
```
[ERROR] Bad checksum for
        /home/opam/.opam/packages.dev/ppx_tools.5.0/f70ca1d07d565989a0041e312e8efc00ff2ad87e:
          - 1e18ffaa90d51cba9e6d5eb7bd186637 [expected result]
          - 5e1a86ff323fe772d69ca2d25abc2c9d [actual result]
```

Contents look reasonable:

```
$ wget https://github.com/alainfrisch/ppx_tools/tarball/f70ca1d07d565989a0041e312e8efc00ff2ad87e -O 5.0.tgz
$ md5sum 5.0.tgz 
5e1a86ff323fe772d69ca2d25abc2c9d  5.0.tgz
$ tar tf 5.0.tgz 
ocaml-ppx-ppx_tools-f70ca1d/
ocaml-ppx-ppx_tools-f70ca1d/.depend
[...]
```

https://github.com/ocaml/opam-repository/blob/master/packages/ppx_tools/ppx_tools.5.0/url does give 1e18ffaa90d51cba9e6d5eb7bd186637 as the expected hash.

**Comment by dbuenzli** [comment]
@talex5 was this before or after https://github.com/ocaml/opam-repository/pull/10182 ?

**Comment by talex5** [comment]
Looks like these were reported at the same time, so closing as duplicate.

**Comment by avsm** [comment]
thanks -- I didnt realise checksums change after a repo move.
