### ISSUE TITLE
4.05.0+trunk+lto isn't 4.05.0

### ISSUE THREAD

**Issue by rleonid** [ocaml/opam-repository#10299]
```
$ ocaml --version
The OCaml toplevel, version 4.04.0+dev3-2016-07-07
$ opam var | grep switch
switch            4.05.0+trunk+lto             # The local name (alias) of the current switch
```

**Comment by dbuenzli** [comment]
I'm not sure this actually exists per se. According to what is see [here](https://github.com/ocaml/opam-repository/blob/3263259149987021b1a9db49f57cb02eb83c6411/compilers/4.05.0/4.05.0%2Btrunk%2Blto/4.05.0%2Btrunk%2Blto.comp#L3) this simply pulls from a tarball from @chambart. So maybe that compiler should simply be removed.

**Comment by chambart** [comment]
This was a trunk snapshot with a set of patches. I'm rebasing it on the 4.05 branch.

**Comment by chambart** [comment]
This is now the lto_4.05 branch instead of just lto

**Comment by dbuenzli** [comment]
Thanks ! Would you be as kind as to submit a PR to the opam repository ?

**Comment by rleonid** [comment]
Thanks guys!
