### ISSUE TITLE
Recent update to Camlp4 4.04+1 broke package's META file

### ISSUE THREAD

**Issue by darioteixeira** [ocaml/opam-repository#10307]
A recent update of Camlp4 `4.04+1` broke the package. I noticed the META file was modified, so I replaced it with the old META file, which seems to have fixed the problem.

**Comment by darioteixeira** [comment]
Funny thing is, the package version hasn't changed, which is why I reckoned it was a packaging issue and not an upstream problem. Anyway, I'm sure @diml knows better than anyone what is going on.

**Comment by avsm** [comment]
If this is still an issue, it should be reported to the https://github.com/camlp4/camlp4/ repository where new releases are cut from.  There have been quite a few intermediate releases since, so hopefully your original problem was fixed!
