### ISSUE TITLE
llvm.5.0.0: failed to install with LLVM_EXPERIMENTAL_TARGETS_TO_BUILD options

### ISSUE THREAD

**Issue by yutopp** [ocaml/opam-repository#10300]
`opam install llvm.5.0.0` is failed when llvm has already been built with options like `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="WebAssembly"`.

In this case, `llvm-config --targets-built` becomes to print `WebAssembly` in their outputs. However https://github.com/ocaml/opam-repository/blob/master/packages/llvm/llvm.5.0.0/files/install.sh#L14 uses these outputs into `-DLLVM_TARGETS_TO_BUILD` as is. Thus `opam install llvm.5.0.0` shows errors as below.

```
### stderr ###
# [...]
# + cmake -DCMAKE_BUILD_TYPE=Release '-DLLVM_TARGETS_TO_BUILD=X86;WebAssembly' -DLLVM_OCAML_EXTERNAL_LLVM_LIBDIR=/usr/local/lib -DBUILD_SHARED_LIBS=FALSE -DLLVM_OCAML_OUT_OF_TREE=TRUE -DLLVM_OCAML_INSTALL_PATH=/root/.opam/4.04.0/lib ..
# CMake Error at CMakeLists.txt:688 (message):
#   The target `WebAssembly' does not exist.
# 
#       It should be one of
# 
#   
#   AArch64;AMDGPU;ARM;BPF;Hexagon;Lanai;Mips;MSP430;NVPTX;PowerPC;Sparc;SystemZ;X86;XCore
# 
# 
```

It seems difficult to distinguish which targets are experimental form outputs of `llvm-config --targets-built`. 

Thanks.

**Comment by whitequark** [comment]
Without consulting the LLVMConfig.cmake file, the only option is to hardcode the non-experimental target list.

**Comment by yutopp** [comment]
Thank you for your reply.

How about removing a line of `-DLLVM_TARGETS_TO_BUILD` from install.sh? It worked fine when I tried.
Is it required from llvm.5.0.0? It seems there is no `-DLLVM_TARGETS_TO_BUILD` in install.sh until llvm.4.0.0.

**Comment by whitequark** [comment]
Then I think it will error out if the system LLVM e.g. only has the X86 target.

**Comment by jpdeplaix** [comment]
Sorry for not having seen this issue sooner.
I suppose the PR should fix this, could you confirm ? It is quite a quick and dirty fix but it should do the trick.

**Comment by dbuenzli** [comment]
@whitequark any opinions on @jpdeplaix's idea ?

**Comment by whitequark** [comment]
LGTM

**Comment by dbuenzli** [comment]
Thanks @whitequark. @jpdeplaix could you please PR your fix.

**Comment by jpdeplaix** [comment]
Ok sorry I didn't noticed that the PR wasn't liked to this one even if it links this issue in its name: https://github.com/ocaml/opam-repository/pull/10440

**Comment by dbuenzli** [comment]
Did you investigate the failures there ?

**Comment by jpdeplaix** [comment]
As usual with the llvm package, every failures come from the fact that llvm-5.0.0 is not available in any of the distros run by the CI. The only one that has the package and didn't fail is MacOS: https://travis-ci.org/ocaml/opam-repository/builds/286213400

**Comment by dbuenzli** [comment]
Always mention the expected failures and their reason on the PR once they occur (I did) otherwise maintainers might never merge it.

**Comment by jpdeplaix** [comment]
Sorry for that. Usually I wait less than a week but I was going to do it at one point. Next time I'll mention it directly in the main post. Thanks.
