### ISSUE TITLE
Fedora 26 uses pkgconf-pkg-config as an alternative to pkgconfig

### ISSUE THREAD

**Issue by mauny** [ocaml/opam-repository#10337]
(OPAM version 1.2.2)

Fedora 26 uses `pkgconf-pkg-config` as an alternative to `pkgconfig`:
  - `yum` correctly installs `pkgconf-pkg-config` when requested to install `pkgconfig`
  - but the test used by OPAM after installation (`rpm -q pkgconfig`) fails.

**Comment by mauny** [comment]
More info about this:
  - the change is mentioned [here](https://fedoraproject.org/wiki/Fedora_26_talking_points#pkgconf_as_system_pkg-config_implementation)
  - according to file depext.ml (line 214), Fedora seems to be the only distribution that double-checks (`yum install -y`, then `rpm -q`) that the package installation has been successful. If installation fails, `yum install` has a non-zero status AFAIK, which should be sufficient.

Unless I am missing something, a simple fix could be to suppress the call to `rpm -q`: `yum install -y pkgconfig` correctly installs, when necessary, `pkgconf-pkg-config`, and returns 0 status in both cases.

**Comment by dbuenzli** [comment]
@mauny I'm not what you are reporting here (erroring context is missing). Is it a problem with the `conf-pkg-config` package (i.e. a problem with `opam-repository`) or a problem with opam's `depext` functionality. If it's the later I suggest you report this on https://github.com/ocaml/opam-depext tracker.

**Comment by mauny** [comment]
You are right: the problem is with opam's `depext` functionality. I'll report it where you suggest. Thanks and sorry for the noise.

**Comment by dbuenzli** [comment]
No problem.
