### ISSUE TITLE
F* package version update

### ISSUE THREAD

**Issue by mindbound** [ocaml/opam-repository#10340]
When trying to install [F*](https://github.com/FStarLang/FStar) via OPAM, it reports that the latest available version is 0.9.4.0-beta0. Could the package be updated to reflect the release of v0.9.5.0?

**Comment by avsm** [comment]
cc @protz who is the maintainer of the package.

**Comment by msprotz** [comment]
@taramana-pro had an update in the pipeline, if I remember correctly... thanks for the ping

**Comment by dbuenzli** [comment]
@mindbound you should ask for a release upstream or the maintainer of the package. The opam-repository issue tracker does not deal with packaging request so I'm closing this.
