### ISSUE TITLE
old liquidsoap-daemon versions execute "sudo" at installation/removal time

### ISSUE THREAD

**Issue by gasche** [ocaml/opam-repository#10356]
cc @toots (package maintainer), @yallop (opam-repository maintainer).

I am running tests on opam packages, trying to automatically build them using [opam-builder](https://github.com/OCamlPro/opam-builder). My builder bot got stuck on liquidsoap-daemon because old version of its installation script use `sudo` at install and removal time, and in fact seem to try to start the daemon as part of the installation process (the depexts, `sudo sysv-rc`, also make little sense to me).

[current packages/liquidsoap-daemon directory](https://github.com/ocaml/opam-repository/tree/21da79c65c19a70e274adfb73e9bd210d69f9ee8/packages/liquidsoap-daemon)

The faulty opam files are the 0.1.* versions: [0.1.1](https://github.com/ocaml/opam-repository/blob/21da79c65c19a70e274adfb73e9bd210d69f9ee8/packages/liquidsoap-daemon/liquidsoap-daemon.0.1.1/opam), [0.1.2](https://github.com/ocaml/opam-repository/blob/21da79c65c19a70e274adfb73e9bd210d69f9ee8/packages/liquidsoap-daemon/liquidsoap-daemon.0.1.2/opam), [0.1.3](https://github.com/ocaml/opam-repository/blob/21da79c65c19a70e274adfb73e9bd210d69f9ee8/packages/liquidsoap-daemon/liquidsoap-daemon.0.1.3/opam). The new versions, [0.3.0](https://github.com/ocaml/opam-repository/blob/21da79c65c19a70e274adfb73e9bd210d69f9ee8/packages/liquidsoap-daemon/liquidsoap-daemon.0.3.0/opam) and [0.3.1](https://github.com/ocaml/opam-repository/blob/21da79c65c19a70e274adfb73e9bd210d69f9ee8/packages/liquidsoap-daemon/liquidsoap-daemon.0.3.1/opam), correctly separate installation and execution.

I believe that the faulty opam install scripts should be removed from the public repository. They are problematic for opam-builder and I expect them to be problematic for other testing tools as well, as well as for any future security-auditing tool, and in general they break the property that the only observable side-effect of running the installation script is to populate package-owned directories of the opam prefix.

What would be the appropriate solution to have these install scripts go away? We could consider removing the 0.1.* versions of the package (@toots, can you confirm that this would be acceptable, that 0.3.* provides the same functionality?), but in general opam-repository avoids removing package once they were introduced. We could also try to fix the installation scripts for those package versions, but I don't understand whether this is possible (if it is part of their expected behavior that they run the daemon, then I don't see a fix).

**Comment by dbuenzli** [comment]
> I believe that the faulty opam install scripts should be removed from the public repository.

FWIW I fully agree. @toots any opinion on that perspective ?

**Comment by toots** [comment]
Totally agree as well.

**Comment by toots** [comment]
Should I push a PR?

**Comment by dbuenzli** [comment]
That would be extremely welcome.

**Comment by toots** [comment]
#10491

**Comment by gasche** [comment]
Fixed by @toots' PR, thanks everyone.
