### ISSUE TITLE
Package melt fails to install with a dynamic linking error

### ISSUE THREAD

**Issue by ppedrot** [ocaml/opam-repository#10361]
Trying to install the melt package results in a failure, with the following relevant snippet:
```
+ /home/pm/.opam/4.04.0+fp/bin/ocamlc.opt -I /home/pm/.opam/4.04.0+fp/lib/mlpost -I /home/pm/.opam/4.04.0+fp/lib/bitstring -I /home/pm/.opam/4.04.0+fp/lib/cairo unix.cma str.cma bigarray.cma cairo.cma bitstring.cma mlpost.cma -I latex -I prelude -I melt latex/variable.cmo prelude/pqueue.cmo prelude/clist.cmo latex/latex.cmo melt/melt_common.cmo melt/mlpost_specific.cmo melt/melt.cmo melt_version.cmo totoconf.cmo melt/tool.cmo -o melt/tool.byte
File "_none_", line 1:
Error: Error on dynamically loaded library: /home/pm/.opam/4.04.0+fp/lib/stublibs/dllmlpost_ft.so: /home/pm/.opam/4.04.0+fp/lib/stublibs/dllmlpost_ft.so: undefined symbol: ml_FT_num_charmaps
Command exited with code 2.
```

I am unsure whether this is supposed to be an error in the mlpost package that does not export the corresponding `ml_FT_num_charmaps` function, or if it is a missing flag to the compiler in the melt package.

**Comment by dbuenzli** [comment]
Unfortunately this package has currently no maintainer, but I believe @rbardou is the author. He may be able to give a hand.

**Comment by ppedrot** [comment]
See backtracking/mlpost#7, it effectively doesn't seem to be due to melt itself but rather because of cairo, according to @backtracking.

**Comment by reubenrowe** [comment]
I think it may be a problem with the mlpost sources that OPAM pulls - see my comment in the discussion of [backtracking/mlpost#7](https://github.com/backtracking/mlpost/issues/7).

**Comment by dbuenzli** [comment]
Didn't realize the reported error was due to `mlpost` closing this in favour of #11013 which tracks the source of the problem.
