### ISSUE TITLE
How to properly advertize incompatibility with `-default-safe-string`?

### ISSUE THREAD

**Issue by gasche** [ocaml/opam-repository#10420]
The upcoming 4.06 release uses `-safe-string` mode by default, which breaks a lot of code that didn't move sooner. As a result, packagers that upload fixed packages are tempted to add `available: [ ocaml-version < "4.06.0" ]` to the older version of their packages, to prevent people on `-default-safe-string` systems from trying to install them.

This is not so good for me, as I am doing automated testing of OPAM packages, and I would like the opportunity to catch compilation errors due to *other* issues than safe-string so I use the `4.06.0+beta1+default-unsafe-string` switch.

Is there a good way for packagers to indicate that a package is compatible with the 4.06 compiler, but breaks if `-safe-string` is the default? Can we make such a possibility happen?

For example, we could have a package `base-safe-string` with versions `unsafe` (before 4.02), `default-unsafe`, `default-safe` and `safe` (once `-unsafe-string` disappears) that conflict with each other, but I don't know if there is a good way to populate it at switch-install time that does not add yet more complexity into the system.

(I'm sure opam 2.0 has better ways of doing this, let's switch after the release!)

**Comment by AltGr** [comment]
> For example, we could have a package base-safe-string with versions unsafe (before 4.02), default-unsafe, default-safe and safe (once -unsafe-string disappears) that conflict with each other, but I don't know if there is a good way to populate it at switch-install time that does not add yet more complexity into the system.

for 1.2, you would have to have dependencies or conflicts: either your compiler depends on `base-safe-string`, and then your packages can depend or conflict with it, or `base-safe-string` depends on a given selection of compilers and conflicts with the others, and your packages need to depend on the right version.

In the second case, the package may get installed lazily, while the first may need modification of existing compilers (which isn't well supported on 1.2 IIRC, and would require recompilation anyway on 2.0). Opam 2.0 can help, but not much, with the `{post}` dependencies, that can get installed after the package.

One thing that would help but isn't there yet is rehauled support for "features", e.g. declaring directly from the ocaml package and using e.g. `depends: "ocaml%safe-string"`, without needing a manually defined virtual package.

**Comment by avsm** [comment]
Creating the opam 1.2 virtual base package is probably the easiest for testing today.  I'll also create a container for the compiler variant so that we can rotate it into the DataKit CI testing, later on today.

**Comment by dbuenzli** [comment]
> This is not so good for me, as I am doing automated testing of OPAM packages, and I would like the opportunity to catch compilation errors due to other issues than safe-string so I use the 4.06.0+beta1+default-unsafe-string switch.

If the goal is only testing you could try to patch the switch so that `ocaml-version` reports `4.06.0~beta`, this should [order](https://opam.ocaml.org/doc/Manual.html#version-ordering) before `4.06.0`.

**Comment by dbuenzli** [comment]
It seems the @gasche it seems we have massively setteled on simply: 
```
available: [ ocaml-version < "4.06.0" ]
```
do you want to keep this issue open ?

**Comment by gasche** [comment]
I don't like the solution, but indeed there is no point in keeping it open. Thanks for the triaging help.
