### ISSUE TITLE
More CI boxes for the switch to 4.06.0

### ISSUE THREAD

**Issue by seliopou** [ocaml/opam-repository#10519]
Finding and fixing issues for 4.06.0 is going to involve changing version constraints for a lot of old versions of packages, which is going to kick off a lot of builds. This is going to increase the load on the CI system and slow regular releases down. It looks like the CI system only allows 24 concurrent jobs. It may be worthwhile expanding that pool of works while all the 4.06.0 kinks get worked out.

**Comment by avsm** [comment]
I'm working on an improvement to this situation that operates a distributed build. The current setup is single box only and so hard to scale beyond 24 jobs without IO bottleneck getting in the way.

**Comment by yomimono** [comment]
@avsm, is the solution you mention in this reply the now-deployed [obi](http://obi.ocamllabs.io/)?

**Comment by avsm** [comment]
not quite -- obi is a new CI system entirely.  Let's hold this one open until I get a chance to discuss with @jpdeplaix  :)

**Comment by dbuenzli** [comment]
@avsm do still want to keep this open ?
