### ISSUE TITLE
Travis 4.06 build

### ISSUE THREAD

**Issue by yallop** [ocaml/opam-repository#10537]
When https://github.com/ocaml/ocaml-ci-scripts/pull/189 is merged we can add an OCaml 4.06 build to the [Travis config](https://github.com/ocaml/opam-repository/blob/cf65c0499897fbabdd0e28d08b956f67046f1657/.travis.yml).

**Comment by yallop** [comment]
Update: https://github.com/ocaml/ocaml-ci-scripts/pull/191, which does the same thing as https://github.com/ocaml/ocaml-ci-scripts/pull/189, has been merged.

**Comment by hannesm** [comment]
@yallop thanks for the reminder, I just opened https://github.com/ocaml/opam-repository/pull/10707 for doing this
