### ISSUE TITLE
Should we retire broken 4.04+flambda compilers?

### ISSUE THREAD

**Issue by gasche** [ocaml/opam-repository#10646]
Some OCaml packages are broken by a compilation bug under 4.04+flambda, which I believe to be a manifestation of [MPR#7426](https://caml.inria.fr/mantis/view.php?id=7426). This shows up as failures against 4.04.2+flambda in our CI (which only tests this 4.04 version).

There are already two packages, namely `mm` and `ocamlnet`, that explicitly disable this "OCaml version" in their opam metadata. Today I encountered another example in https://github.com/ocaml/opam-repository/pull/10529#issuecomment-343169952 that fails because ocamlgraph fails. Given that the issue affects at least all objects with float values (not fields), I think that other packages may be affected in the future.

Instead of explicitly changing the metadata of all packages affected by this bug, or ignoring the CI failures, could we consider retiring 4.04+flambda compilers from the repository, or at least from the CI system?

cc @avsm and @jpdeplaix :-)

**Comment by dbuenzli** [comment]
Seems a good idea to me.

**Comment by avsm** [comment]
We can retire it from the CI, but I'd like to keep the released version in the opam-repo.

CI has been updated to use 4.05+flambda and 4.06+flambda, and change the default tested version of to 4.05.0 (from 4.04.2)
