### ISSUE TITLE
No constraint caused obsolete version preferred by OPAM

### ISSUE THREAD

**Issue by vvs-** [ocaml/opam-repository#10680]
biniou 1.0.6 has no constraint on OCaml compiler version. For some reason OPAM 2.0 solver chose that particular version to resolve yojson.1.3.3 dependancy. But that version is incompatible with OCaml 4.06.0, so installation of merlin.3.0.4 has failed.

This can be avoided if yojson is installed explicitly which caused a more recent version to be chosen.

BTW, conf-which caused OPAM to install more recent yojson also, but it's not considered during merlin dependency resolving.

**Comment by vvs-** [comment]
Ok. I see that the fix is already coming in #10678.

**Comment by avsm** [comment]
Fixed in opam-repository by #10678
