### ISSUE TITLE
Unable to install conf-pkg-config.1.0

### ISSUE THREAD

**Issue by MoiMagnus** [ocaml/opam-repository#10773]
Hi,
I have a fresh install of opam, so it is quite likely that something is missing in my install

When typing 
> opam install conf-pkg-config.1.0

It answers:
>The following actions will be performed:
  ∗  install conf-pkg-config 1.0
=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[conf-pkg-config: pkg-config] Command started
[ERROR] The compilation of conf-pkg-config failed at "pkg-config --help".
=== ERROR while compiling conf-pkg-config.1.0 ================================#
 opam-version         1.3.0~dev (2c2399d98ad0ebcb43a4bc856f3636030bb376db)
 os                   win32
 command              pkg-config --help
 path                 C:/OCaml64/home/Marc/.opam/4.06.0+mingw64c/build/conf-pkg-config.1.0
 exit-code            127
 env-file             C:/OCaml64/home/Marc/.opam/4.06.0+mingw64c/build/conf-pkg-config.1.0\conf-pkg-config-444
 stdout-file          C:/OCaml64/home/Marc/.opam/4.06.0+mingw64c/build/conf-pkg-config.1.0\conf-pkg-config-444
 stderr-file          C:/OCaml64/home/Marc/.opam/4.06.0+mingw64c/build/conf-pkg-config.1.0\conf-pkg-config-444
 stderr 
 dash: 1: pkg-config: not found
=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  λ  build conf-pkg-config 1.0
No changes have been performed
=-=- conf-pkg-config.1.0 troubleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing.
   `opam depext conf-pkg-config.1.0' may help you find the correct installation
   for your system.

When typing:
> opam depext conf-pkg-config.1.0

It answers:
> Detecting depexts using flags: x86_64 mswindows win32
 No extra OS packages requirements found.

And I am still unable to install conf-pkg-config.

For information, my config is:
> OPAM config report
 opam-version    1.3.0~dev (2c2399d98ad0ebcb43a4bc856f3636030bb376db)
 self-upgrade    no
 os              win32
 external-solver aspcud $in $out $criteria
 criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
 jobs            3
 repositories    0 (http), 1 (version-controlled)
 pinned          0
 current-switch  4.06.0+mingw64c
 last-update     2017-11-18 13:53

Thank you in advance

**Comment by dbuenzli** [comment]
I'm not sure depexts actually works at all on windows at the moment. You should find a way to install `pkg-config` by yourself since this: 

> dash: 1: pkg-config: not found

is the error.

**Comment by fdopen** [comment]
wrong repo, report it here (or just read the `README.md` there): https://github.com/fdopen/opam-repository-mingw
But anyway, it works on windows:
```bash
opam install -y depext depext-cygwinports # this installs opam depext and a windows helpers for depext and pkg-config
eval $(ocaml-env cygwin) # configure your environment
opam depext -y -i conf-pkg-config.1.0 # install it together with all necessary system packages```

**Comment by MoiMagnus** [comment]
Thank you!
