### ISSUE TITLE
conf-gmp-powm-sec failing to build on mac

### ISSUE THREAD

**Issue by pmetzger** [ocaml/opam-repository#10856]
Attempting to install cryptokit (OCaml 4.06.0) on my macOS 10.13.1 system leads to conf-gmp-powm-sec trying to install. It fails with:

    + cc -c -I/usr/local/include test.c
    test.c:1:10: fatal error: 'gmp.h' file not found
    #include <gmp.h>
             ^~~~~~~
    1 error generated.

Any ideas?

**Comment by dbuenzli** [comment]
IIRC you are on macports, `conf-gmp` [checks](https://github.com/ocaml/opam-repository/blob/master/packages/conf-gmp/conf-gmp.1/opam#L10) for both `/opt/local` and `/usr/local`. This one apparently only `/usr/local` hence the failure.

I suggest you simply setup the `C_INCLUDE_PATH` and `LIBRARY_PATH` in your `.profile` as suggested [here](https://github.com/ocaml/opam/issues/3049). This might save you quite a bit of time when dealing with `depexts`.

**Comment by pmetzger** [comment]
So far, this is the first time I've hit this.

I would rather not alter anything in my .profile because it could have effects outside of the OCaml opamverse, but is it possible to set such variables in my opam configuration somewhere as a stop gap?

**Comment by dbuenzli** [comment]
I don't think so. Note that these variables are actually made for this see [this comment](https://github.com/ocaml/opam-repository/issues/3093#issuecomment-312929998), so I wouldn't fear setting them.

**Comment by dbuenzli** [comment]
and I actually think we would be better off suggesting people to adjust these variables rather than have the `conf` packages hardcode all imaginable file paths package manager like to invent to install their stuff.

**Comment by pmetzger** [comment]
They're not made for this. Or rather, if you're setting things like that, you're telling every program on your system that it's open season depending on those things, and that's usually _not_ what I want — among other things, I'm known to blow away my macports install at times and I don't want unexpected things suddenly failing while I'm trying to rebuild it. I'd prefer to just tell the OCaml stuff that it is allowed to look at that stuff, selectively. Really it would be better still if it built it's own copy of gmp...

**Comment by emillon** [comment]
It seems that the fix you did for #9728 would work against `conf-gmp-powm-sec` as well. I'll prepare a PR.

I agree that a opam-global place to store these flags would be nice, but I don't think it's possible at the moment.

**Comment by dbuenzli** [comment]
Thanks for the fix @emillon.

> I agree that a opam-global place to store these flags would be nice, but I don't think it's possible at the moment.

There has been a long discussion in https://github.com/ocaml/opam-repository/issues/3093 and https://github.com/ocaml/opam-repository/issues/6271 about how to do these things and I believe, despite what @pmetzger thinks, that the comment I [linked to](https://github.com/ocaml/opam-repository/issues/3093#issuecomment-312929998),  is the right approach to take (and in particular we really do not want `opam-repository` to start rebuilding packages that are handled by other package managers for its own use). 

If your package manager installs stuff in non standard places it is its duty to make it available to the programs that needs them. We really don't want to start encoding all the linux distribution and other package manager idiosyncrasies into the `conf-*` packages, this simply doesn't scale.
