### ISSUE TITLE
Debian 9+ and Ubuntu Zesty conf-mysql wrong

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/opam-repository#10942]
Hi!

The current `conf-mysql` package depends on `libmysqlclient-dev`. Unfortunately, starting with Debian 9 and Ubuntu Zesty this package does not exist and is called `default-libmysqlclient-dev` instead. I could now create a PR, but that would break on older Debians and Ubuntus so I don't know what the right way to handle this is. It is basically a choice between "break old Debian" or "break new Debian".

**Comment by dbuenzli** [comment]
I guess this should be solvable with the ["better depexts"](https://github.com/ocaml/opam/issues/2919). I have no idea when that will be rolled in though /cc @AltGr.

**Comment by ygrek** [comment]
ftr `mysql` package doesn't depend on `conf-mysql`, and has the following instead : 
```
post-messages:
  """
This package requires mysql client library installed. Due to abundance of mysql forks with different names and
  opam not dealing very well with depext alternatives currently - they are not described as dependencies of this package.

  Please ensure that mysql client library is installed and mysql_config binary is available in PATH.
  Two most popular ways to achieve that are described in conf-mysql and conf-mariadb packages.

  See also discussion in https://github.com/ocaml/opam-repository/pull/10312"""
```
also I cannot not reference https://github.com/ocaml/opam/issues/3140 here
