### ISSUE TITLE
Problem with mlpost 0.8.2 Package

### ISSUE THREAD

**Issue by reubenrowe** [ocaml/opam-repository#11013]
There is a problem with the mlpost 0.8.2 package provided by OPAM, which causes errors when trying to install melt.

This has been observed with the 4.04.0 and 4.0.4.2 compilers.

I believe the problem is that the source provided by OPAM is out of date:

    http://mlpost.lri.fr/download/mlpost-0.8.2.tar.gz

Pinning OPAM to the following source seems to work fine:

    https://github.com/backtracking/mlpost/releases/tag/0.8.2

**Comment by reubenrowe** [comment]
Crossref with backtracking/mlpost#7

**Comment by reubenrowe** [comment]
Also, I think this is the reason for #10361

**Comment by dbuenzli** [comment]
Thanks @reubenrowe for the analysis. /cc @backtracking the maintainer of the `mlpost` package.
