### ISSUE TITLE
mpi does not build

### ISSUE THREAD

**Issue by Armael** [ocaml/opam-repository#1104]
Hello,

I get an error when trying to build the `mpi` package:

```
/bin/sh: /usr/bin/mpicc.openmpi: No such file or directory
```

I'm using Archlinux. In fact I wonder why the source of the opam package is the odd https://github.com/UnixJunkie/ocamlmpi github repo, while there is http://forge.ocamlcore.org/projects/ocamlmpi/ that seems to be more the official repository of ocamlmpi, and moreover, that successfully builds on my computer.

Armael

P.S: To get ocamlmpi (the one from the forge) building, i just had to change the variables `MPIINCDIR` and `MPILIBDIR` to respectively `/usr/include` and `/usr/lib/openmpi`, as indicated in the `README`.

**Comment by samoht** [comment]
@UnixJunkie as you are the maintainer of mpi can you have a look at it?

**Comment by samoht** [comment]
or simpler, @Armael can you report it to mpi's issue tracker https://github.com/HappyCrow/ocamlmpi/issues

**Comment by UnixJunkie** [comment]
@Armael try this:

    opam depext -i mpi

or install whatever system package that gives you the openmpi compiler.
