### ISSUE TITLE
nocrypto v 0.5.4 failed 

### ISSUE THREAD

**Issue by tsh-box** [ocaml/opam-repository#11075]
hello,
I cannot solve the problem yet.
Please could you tell me ,how can I solve it?

![tocon11](https://user-images.githubusercontent.com/29420329/34199987-d6fbe05c-e5b2-11e7-924b-3f251b266c73.png)

**Comment by dbuenzli** [comment]
This seems to be https://github.com/ocaml/opam-repository/pull/11039 did you `opam update` to make sure your constraints are up-to-date. Otherwise explicitely ask for the latest version of `topkg` by doing `topkg install topkg.0.9.1` and then install nocrypto.

**Comment by tsh-box** [comment]
Now I have solved :)

**Comment by dbuenzli** [comment]
Good, thanks for coming back to us.
