### ISSUE TITLE
Detect a package is not available for a compiler version before building the compiler

### ISSUE THREAD

**Issue by jberdine** [ocaml/opam-repository#11093]
I have noticed that when a PR for package which is only available for a subset of the compiler versions is sent, the Travis CI jobs get all the way through having build ocaml before realizing that the package is not available. This seems like a waste of resources, but I don't know how difficult it is to reliably check the available field of the opam file earlier.

**Comment by dbuenzli** [comment]
Any repo administrator (@ocaml/opam-repository) wants to chime in if something can be done ?

**Comment by gasche** [comment]
Currently the installability test is done with `opam install $pkg --dry-run`. Having this available requires opam. We could do with just the opam support libraries, and I think those are installed by Ubuntu's `opam` package (see [source code](https://anonscm.debian.org/git/pkg-ocaml-maint/packages/opam.git/tree/)). So installing a binary version of ocaml and opam should be enough to compile an installability-check OCaml script distributed within `opam-repository` or its Travis script. (Someone would have to write this script, and maintain it in the medium-term, which may not be that easy given that the opam-lib API has changed a lot between opam1 and opam2). We can cut before the initialization of the opam switch, which does the compiler build that @jberdine notices.

For platforms that don't install ocaml or opam without building them from sources (`brew` on OSX may be such a platform?), this wouldn't save as much. Then the question arise of writing a dirty shell script that would not properly parse the OPAM script and understand versions, but assume that the `available` script always has roughly the same shape and parse it (I think it suffices to collect all `ocaml-version {<,<=,>,>=} "[^"]*"` occurrences in the `opam` file), and then filter the version accordingly (this sounds like the most painful step).

If we think we are going to eventually do the second step, then we may as well do it right away.

**Comment by avsm** [comment]
@jberdine we're working on a new CI (https://github.com/ocurrent/ocaml-ci) which has a built-in solver that figures out the allowable OCaml versions before attempting a build. I'll close this as it'll be fixed as part of that deployment. Travis CI is largely deprecated for any real tests on opam-repository these days as datakit-ci has taken over (and the new ocaml-ci is an evolution of that one).
