### ISSUE TITLE
CAMLCity is down. OPAM's URLs are timing out for ocamlfind

### ISSUE THREAD

**Issue by jordwalke** [ocaml/opam-repository#11128]
The package download URL listed here does not work and it appears that camlcity.org (which hosts all the findlib tarballs) is down entirely:

https://opam.ocaml.org/packages/ocamlfind/ocamlfind.1.7.3/

**Comment by jordwalke** [comment]
Sorry if this is the incorrect place to post about this, but it seems like the closest match.
It would be great if ocamlfind used a reliable URL for hosting like github releases (I've found that they work wonderfully).
I recall opam has some kind of a cache/mirror that we can use instead of reading from the URLs directly? Our internal tools currently read directly from the opam metadata to fetch packages. Looking forward to hearing about ways to improve that, but can we get camlcity back up some how?

**Comment by jordwalke** [comment]
Also, the checksum for the `mirrors` section references the checksum for the *previous* ocamlfind release.

**Comment by samoht** [comment]
Which checksum is wrong? Seems to work well for me:

```
 $ curl -OL http://download.camlcity.org/download/findlib-1.7.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  251k  100  251k    0     0  1359k      0 --:--:-- --:--:-- --:--:-- 1360k
$ md5sum findlib-1.7.3.tar.gz
7d57451218359f7b7dfc969e3684a6da  findlib-1.7.3.tar.gz
```

**Comment by dbuenzli** [comment]
Indeed, sorry for the trouble. @jordwalke feel free to continue the discussion if you meant something else.

**Comment by jordwalke** [comment]
They may have been fixed.
