### ISSUE TITLE
question: should opam packages using jbuilder ship the .install file generated by jbuilder?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#11210]
in the files/ directory?
For example:  files/vpt.install.
Somewhere else?
If so, I will improve my pull request:
https://github.com/ocaml/opam-repository/pull/11205

But, since jbuilder creates this file at compile time, it would be nice
if I don't have to copy this file in the opam package.

Thanks,
F.

**Comment by mseri** [comment]
Unless you have some manually generated `.install` files, you don't need to add them to the opam package

**Comment by UnixJunkie** [comment]
that's what I thought, but then there were some uninstall failures during the CI tests: cf. the end of this log 
https://travis-ci.org/ocaml/opam-repository/jobs/327085336

    [WARNING] failure in package uninstall script, some files may remain:
          # opam-version 1.2.2
          # os           darwin
          # command      jbuilder uninstall -p vpt
          # path         /Users/travis/.opam/system/build/vpt.3.0.0
          # compiler     system (4.06.0)
          # exit-code    1
          # env-file
          /Users/travis/.opam/system/build/vpt.3.0.0/vpt-10561-1872ec.env
          # stdout-file
          /Users/travis/.opam/system/build/vpt.3.0.0/vpt-10561-1872ec.out
          # stderr-file
          /Users/travis/.opam/system/build/vpt.3.0.0/vpt-10561-1872ec.err
          ### stderr ###
          # The following <package>.install are missing:
          # - _build/default/vpt.install
          # You need to run: jbuilder build @install

**Comment by dbuenzli** [comment]
The answer is clearly no. `.install` files (should) depend on what has been built, which depends on the build environment, which you don't know before hand.

**Comment by UnixJunkie** [comment]
got it, thanks!
