### ISSUE TITLE
Cannot get ocamlfind to install.

### ISSUE THREAD

**Issue by Ketrel** [ocaml/opam-repository#11241]
I'm using alpine-linux in a docker container.

I've done the following steps
1. touch ~/.profile
2. apk update
3. apk add m4 pcre-dev opam
4. opam init -a
5. source ~/.profile
6. eval \`opam config env\`
7. opam install conf-m4

Finally I do `opam install --debug -v -v ocamlfind` and I get the following output and it fails

    [WARNING] Running as root is not recommended
    00:00.008  SYSTEM                  locking /root/.opam/lock
    00:00.008  STATE                   LOAD-STATE(switch-lock)
    00:00.010  CUDF                    Checking version of criteria accepted by the external solver
    00:00.012  SYSTEM                  [log-483-4438d8] (in 0.002s) aspcud -v
    00:00.012  CUDF                    Solver is aspcud > 1.9: using latest version criteria
    00:00.081  STATE                   Loaded /root/.opam/state.cache in 0.068s
    00:00.217  STATE                   ROOT      : /root/.opam
    00:00.217  STATE                   SWITCH    : system
    00:00.217  STATE                   COMPILER  : system
    00:00.217  STATE                   COMPILERS : { 3.07, 3.07+1, 3.07+2, 3.08.0, 3.08.1, 3.08.2, 3.08.3, 3.08.4, 3.09.0, 3.09.1, 3.09.1+metaocaml, 3.09.2, 3.09.3, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.11.2, 3.12.0, 3.12.1, 4.00.0, 4.00.0+debug-runtime, 4.00.0+fp, 4.00.1, 4.00.1+BER, 4.00.1+PIC, 4.00.1+annot, 4.00.1+debug-runtime, 4.00.1+french, 4.00.1+mirage-unix, 4.00.1+mirage-xen, 4.00.1+open-types, 4.00.1+raspberrypi, 4.00.1+short-types, 4.01.0, 4.01.0+32bit, 4.01.0+BER, 4.01.0+PIC, 4.01.0+armv6-freebsd, 4.01.0+fp, 4.01.0+lsb, 4.01.0+musl, 4.01.0+musl+static, 4.01.0+open-types, 4.01.0+profile, 4.02.0, 4.02.0+PIC, 4.02.0+improved-errors, 4.02.0+modular-implicits, 4.02.0+rc1, 4.02.0+trunk, 4.02.1, 4.02.1+32bit, 4.02.1+BER, 4.02.1+PIC, 4.02.1+fp, 4.02.1+modular-implicits-ber, 4.02.1+musl, 4.02.1+musl+static, 4.02.2, 4.02.2+improved-errors, 4.02.2+rc1, 4.02.3, 4.02.3+32bit, 4.02.3+PIC, 4.02.3+buckle-1, 4.02.3+buckle-master, 4.02.3+bytecode-only, 4.02.3+curried-constr, 4.02.3+fp, 4.02.3+musl, 4.02.3+musl+static, 4.02.3+termux, 4.03.0, 4.03.0+32bit, 4.03.0+beta1, 4.03.0+beta1+flambda, 4.03.0+beta1-no-debug, 4.03.0+beta2, 4.03.0+beta2+flambda, 4.03.0+beta2-no-debug, 4.03.0+fPIC, 4.03.0+flambda, 4.03.0+fp, 4.03.0+fp+flambda, 4.03.0+statistical-memprof, 4.03.0+termux, 4.03.0+trunk, 4.03.0+trunk+flambda, 4.03.0+trunk+fp, 4.03.0+trunk+fp+flambda, 4.04.0, 4.04.0+32bit, 4.04.0+BER, 4.04.0+afl, 4.04.0+beta1, 4.04.0+beta1+flambda, 4.04.0+beta2, 4.04.0+beta2+flambda, 4.04.0+bytecode-only, 4.04.0+copatterns, 4.04.0+fPIC, 4.04.0+flambda, 4.04.0+fp, 4.04.0+fp+flambda, 4.04.0+safe-string, 4.04.0+spacetime, 4.04.0+termux, 4.04.0+trunk+forced_lto, 4.04.1, 4.04.1+32bit, 4.04.1+bytecode-only, 4.04.1+fPIC, 4.04.1+flambda, 4.04.1+fp, 4.04.1+fp+flambda, 4.04.1+safe-string, 4.04.1+spacetime, 4.04.2, 4.04.2+32bit, 4.04.2+bytecode-only, 4.04.2+fPIC, 4.04.2+flambda, 4.04.2+fp, 4.04.2+fp+flambda, 4.04.2+safe-string, 4.04.2+spacetime, 4.04.2+statistical-memprof, 4.05.0, 4.05.0+32bit, 4.05.0+afl, 4.05.0+beta1, 4.05.0+beta1+flambda, 4.05.0+beta2, 4.05.0+beta2+flambda, 4.05.0+beta3, 4.05.0+flambda, 4.05.0+lto, 4.05.0+musl+static+flambda, 4.05.0+rc1, 4.05.0+rc1+flambda, 4.05.0+safe-string, 4.05.0+spacetime, 4.05.0+statistical-memprof, 4.05.0+trunk, 4.05.0+trunk+afl, 4.05.0+trunk+flambda, 4.05.0+trunk+fp, 4.05.0+trunk+fp+flambda, 4.05.0+trunk+safe-string, 4.06.0, 4.06.0+32bit, 4.06.0+afl, 4.06.0+beta1, 4.06.0+beta1+afl, 4.06.0+beta1+default-unsafe-string, 4.06.0+beta1+flambda, 4.06.0+beta1+force-safe-string, 4.06.0+beta1+fp, 4.06.0+beta1+fp+flambda, 4.06.0+beta2, 4.06.0+beta2+afl, 4.06.0+beta2+default-unsafe-string, 4.06.0+beta2+flambda, 4.06.0+beta2+force-safe-string, 4.06.0+beta2+fp, 4.06.0+beta2+fp+flambda, 4.06.0+default-unsafe-string, 4.06.0+flambda, 4.06.0+force-safe-string, 4.06.0+fp, 4.06.0+fp+flambda, 4.06.0+musl+static+flambda, 4.06.0+rc1, 4.06.0+rc1+afl, 4.06.0+rc1+default-unsafe-string, 4.06.0+rc1+flambda, 4.06.0+rc1+force-safe-string, 4.06.0+rc1+fp, 4.06.0+rc1+fp+flambda, 4.06.0+statistical-memprof, 4.06.1+trunk, 4.06.1+trunk+afl, 4.06.1+trunk+flambda, 4.06.1+trunk+fp, 4.06.1+trunk+fp+flambda, 4.06.1+trunk+safe-string, 4.07.0+trunk, 4.07.0+trunk+afl, 4.07.0+trunk+flambda, 4.07.0+trunk+fp, 4.07.0+trunk+fp+flambda, 4.07.0+trunk+unsafe-string, system }
    00:00.217  STATE                   REPOS     : { default }
    00:00.217  STATE                   PACKAGES  : 8233 packages
    00:00.218  STATE                   INSTALLED : { base-bigarray.base, base-threads.base, base-unix.base, conf-m4.1 }
    00:00.218  STATE                   ROOTS     : { base-bigarray.base, base-threads.base, base-unix.base, conf-m4.1 }
    00:00.218  STATE                   REINSTALL : {}
    00:00.218  STATE                   State switch-lock loaded in 0.207s
    00:00.233  SYSTEM                  [log-483-4bcc67] (in 0.002s) ocamlc -version
    00:00.233  SYSTEM                  locking /root/.opam/system/lock
    00:00.233  STATE                   LOAD-STATE(install)
    00:00.277  STATE                   Loaded /root/.opam/state.cache in 0.044s
    00:00.425  STATE                   ROOT      : /root/.opam
    00:00.425  STATE                   SWITCH    : system
    00:00.425  STATE                   COMPILER  : system
    00:00.425  STATE                   COMPILERS : { 3.07, 3.07+1, 3.07+2, 3.08.0, 3.08.1, 3.08.2, 3.08.3, 3.08.4, 3.09.0, 3.09.1, 3.09.1+metaocaml, 3.09.2, 3.09.3, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.11.2, 3.12.0, 3.12.1, 4.00.0, 4.00.0+debug-runtime, 4.00.0+fp, 4.00.1, 4.00.1+BER, 4.00.1+PIC, 4.00.1+annot, 4.00.1+debug-runtime, 4.00.1+french, 4.00.1+mirage-unix, 4.00.1+mirage-xen, 4.00.1+open-types, 4.00.1+raspberrypi, 4.00.1+short-types, 4.01.0, 4.01.0+32bit, 4.01.0+BER, 4.01.0+PIC, 4.01.0+armv6-freebsd, 4.01.0+fp, 4.01.0+lsb, 4.01.0+musl, 4.01.0+musl+static, 4.01.0+open-types, 4.01.0+profile, 4.02.0, 4.02.0+PIC, 4.02.0+improved-errors, 4.02.0+modular-implicits, 4.02.0+rc1, 4.02.0+trunk, 4.02.1, 4.02.1+32bit, 4.02.1+BER, 4.02.1+PIC, 4.02.1+fp, 4.02.1+modular-implicits-ber, 4.02.1+musl, 4.02.1+musl+static, 4.02.2, 4.02.2+improved-errors, 4.02.2+rc1, 4.02.3, 4.02.3+32bit, 4.02.3+PIC, 4.02.3+buckle-1, 4.02.3+buckle-master, 4.02.3+bytecode-only, 4.02.3+curried-constr, 4.02.3+fp, 4.02.3+musl, 4.02.3+musl+static, 4.02.3+termux, 4.03.0, 4.03.0+32bit, 4.03.0+beta1, 4.03.0+beta1+flambda, 4.03.0+beta1-no-debug, 4.03.0+beta2, 4.03.0+beta2+flambda, 4.03.0+beta2-no-debug, 4.03.0+fPIC, 4.03.0+flambda, 4.03.0+fp, 4.03.0+fp+flambda, 4.03.0+statistical-memprof, 4.03.0+termux, 4.03.0+trunk, 4.03.0+trunk+flambda, 4.03.0+trunk+fp, 4.03.0+trunk+fp+flambda, 4.04.0, 4.04.0+32bit, 4.04.0+BER, 4.04.0+afl, 4.04.0+beta1, 4.04.0+beta1+flambda, 4.04.0+beta2, 4.04.0+beta2+flambda, 4.04.0+bytecode-only, 4.04.0+copatterns, 4.04.0+fPIC, 4.04.0+flambda, 4.04.0+fp, 4.04.0+fp+flambda, 4.04.0+safe-string, 4.04.0+spacetime, 4.04.0+termux, 4.04.0+trunk+forced_lto, 4.04.1, 4.04.1+32bit, 4.04.1+bytecode-only, 4.04.1+fPIC, 4.04.1+flambda, 4.04.1+fp, 4.04.1+fp+flambda, 4.04.1+safe-string, 4.04.1+spacetime, 4.04.2, 4.04.2+32bit, 4.04.2+bytecode-only, 4.04.2+fPIC, 4.04.2+flambda, 4.04.2+fp, 4.04.2+fp+flambda, 4.04.2+safe-string, 4.04.2+spacetime, 4.04.2+statistical-memprof, 4.05.0, 4.05.0+32bit, 4.05.0+afl, 4.05.0+beta1, 4.05.0+beta1+flambda, 4.05.0+beta2, 4.05.0+beta2+flambda, 4.05.0+beta3, 4.05.0+flambda, 4.05.0+lto, 4.05.0+musl+static+flambda, 4.05.0+rc1, 4.05.0+rc1+flambda, 4.05.0+safe-string, 4.05.0+spacetime, 4.05.0+statistical-memprof, 4.05.0+trunk, 4.05.0+trunk+afl, 4.05.0+trunk+flambda, 4.05.0+trunk+fp, 4.05.0+trunk+fp+flambda, 4.05.0+trunk+safe-string, 4.06.0, 4.06.0+32bit, 4.06.0+afl, 4.06.0+beta1, 4.06.0+beta1+afl, 4.06.0+beta1+default-unsafe-string, 4.06.0+beta1+flambda, 4.06.0+beta1+force-safe-string, 4.06.0+beta1+fp, 4.06.0+beta1+fp+flambda, 4.06.0+beta2, 4.06.0+beta2+afl, 4.06.0+beta2+default-unsafe-string, 4.06.0+beta2+flambda, 4.06.0+beta2+force-safe-string, 4.06.0+beta2+fp, 4.06.0+beta2+fp+flambda, 4.06.0+default-unsafe-string, 4.06.0+flambda, 4.06.0+force-safe-string, 4.06.0+fp, 4.06.0+fp+flambda, 4.06.0+musl+static+flambda, 4.06.0+rc1, 4.06.0+rc1+afl, 4.06.0+rc1+default-unsafe-string, 4.06.0+rc1+flambda, 4.06.0+rc1+force-safe-string, 4.06.0+rc1+fp, 4.06.0+rc1+fp+flambda, 4.06.0+statistical-memprof, 4.06.1+trunk, 4.06.1+trunk+afl, 4.06.1+trunk+flambda, 4.06.1+trunk+fp, 4.06.1+trunk+fp+flambda, 4.06.1+trunk+safe-string, 4.07.0+trunk, 4.07.0+trunk+afl, 4.07.0+trunk+flambda, 4.07.0+trunk+fp, 4.07.0+trunk+fp+flambda, 4.07.0+trunk+unsafe-string, system }
    00:00.425  STATE                   REPOS     : { default }
    00:00.425  STATE                   PACKAGES  : 8233 packages
    00:00.425  STATE                   INSTALLED : { base-bigarray.base, base-threads.base, base-unix.base, conf-m4.1 }
    00:00.425  STATE                   ROOTS     : { base-bigarray.base, base-threads.base, base-unix.base, conf-m4.1 }
    00:00.425  STATE                   REINSTALL : {}
    00:00.425  STATE                   State install loaded in 0.189s
    00:00.426  FILE(export)            Wrote ~/.opam/system/backup/state-20180017162610.export in 0.000s
    00:00.516  CLIENT                  INSTALL ocamlfind
    00:01.420  CLIENT                  Orphans: full {}, versions {}
    00:01.553  SOLVER                  resolve request=install:(ocamlfind) remove:() upgrade:()
    00:01.554  SOLVER                  cudf_versions_map
    00:01.756  SOLVER                  Load cudf universe (depopts:false, build:true)
    00:06.477  CUDF                    resolve request=install:(ocamlfind) remove:() upgrade:() criteria:"-count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)"
    00:06.959  SYSTEM                  [log-483-9b8556] (in 0.008s) aspcud /root/.opam/log/solver-in-483-ccabea /root/.opam/log/solver-out-483-42bb52 -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
    00:06.959  SYSTEM                  rm /root/.opam/log/solver-in-483-ccabea
    00:06.959  SYSTEM                  rm /root/.opam/log/solver-out-483-42bb52
    00:07.003  SOLVER                  Load cudf universe (depopts:false, build:true)
    00:11.707  SOLVER                  Load cudf universe (depopts:true, build:false)
    00:16.528  SOLVER                  Load cudf universe (depopts:true, build:true)
    00:21.453  CUDF                    graph_of_actions root_actions={  - install ocamlfind.23 }
    00:21.464  SOLUTION                apply
    The following actions will be performed:
      - install ocamlfind 1.7.3-1
    00:21.464  SOLUTION                parallel_apply

    =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    00:21.464  PARALLEL                Iterate over 1 task(s) with 3 process(es)
    00:21.480  PARALLEL                Starting job 0 (worker 1/3): 0
    00:21.480  ACTION                  download_package: ocamlfind.1.7.3-1
    00:21.480  STATE                   get_archive ocamlfind.1.7.3-1
    00:21.480  CURL                    pull-archive
    00:22.044  SYSTEM                  mkdir /tmp/opam-483-5f1023
    00:22.044  PARALLEL                Next task in job 0: curl --write-out %{http_code}\n --insecure --retry 3 --retry-delay 2 -OL https://opam.ocaml.org/archives/ocamlfind.1.7.3-1+opam.tar.gz
    [ocamlfind: from default] Command started
    Processing  1/1: [ocamlfind: from default]
    + curl "--write-out" "%{http_code}\\n" "--insecure" "--retry" "3" "--retry-delay" "2" "-OL" "https://opam.ocaml.org/archives/ocamlfind.1.7.3-1+opam.tar.gz" (CWD=/tmp/opam-483-5f1023)
    - 200
    -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    -                                  Dload  Upload   Total   Spent    Left  Speed
    100  259k  100  259k    0     0   259k      0  0:00:01 --:--:--  0:00:01  470k
    00:22.614  PARALLEL                Collected task for job 0 (ret:0)
    00:22.614  PARALLEL                Next task in job 0: mv /tmp/opam-483-5f1023/ocamlfind.1.7.3-1+opam.tar.gz /root/.opam/repo/default/archives/ocamlfind.1.7.3-1+opam.tar.gz
    Processing  1/1: [ocamlfind: from default]
    00:22.618  PARALLEL                Collected task for job 0 (ret:0)
    00:22.618  SYSTEM                  rmdir /tmp/opam-483-5f1023
    [default] https://opam.ocaml.org/archives/ocamlfind.1.7.3-1+opam.tar.gz downloaded
    00:22.621  SYSTEM                  mkdir /root/.opam/archives
    00:22.630  SYSTEM                  [log-483-ffb3fd] (in 0.008s) cp /root/.opam/repo/default/archives/ocamlfind.1.7.3-1+opam.tar.gz /root/.opam/archives/ocamlfind.1.7.3-1+opam.tar.gz
    00:22.630  PARALLEL                Job 0 finished

    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    00:22.630  PARALLEL                Iterate over 1 task(s) with 4 process(es)
    00:22.632  PARALLEL                Starting job 871091801 (worker 1/4): install ocamlfind.1.7.3-1
    00:22.632  ACTION                  extract_package: ocamlfind.1.7.3-1 from /root/.opam/archives/ocamlfind.1.7.3-1+opam.tar.gz
    00:22.632  SYSTEM                  rmdir /root/.opam/system/build/ocamlfind.1.7.3-1
    00:22.632  SYSTEM                  mkdir /tmp/opam-483-1872ec
    + tar "xfz" "/root/.opam/archives/ocamlfind.1.7.3-1+opam.tar.gz" "-C" "/tmp/opam-483-1872ec"
    00:22.660  SYSTEM                  [log-483-d2c37b] (in 0.002s) tar xfz /root/.opam/archives/ocamlfind.1.7.3-1+opam.tar.gz -C /tmp/opam-483-1872ec
    + mv "/tmp/opam-483-1872ec/ocamlfind.1.7.3-1" "/root/.opam/system/build/ocamlfind.1.7.3-1"
    00:22.666  SYSTEM                  [log-483-e7966f] (in 0.005s) mv /tmp/opam-483-1872ec/ocamlfind.1.7.3-1 /root/.opam/system/build/ocamlfind.1.7.3-1
    00:22.666  SYSTEM                  rmdir /tmp/opam-483-1872ec
    00:22.668  ACTION                  ocamlfind: applying check-num-in-sitelib.patch.

    00:22.675  SYSTEM                  [log-483-d2d111] (in 0.004s) patch -p0 -i /root/.opam/system/build/ocamlfind.1.7.3-1/check-num-in-sitelib.patch --dry-run
    00:22.680  SYSTEM                  [log-483-d8a4ae] (in 0.000s) patch -p1 -i /root/.opam/system/build/ocamlfind.1.7.3-1/check-num-in-sitelib.patch --dry-run
    00:22.687  SYSTEM                  [log-483-a71bb4] (in 0.001s) patch -p2 -i /root/.opam/system/build/ocamlfind.1.7.3-1/check-num-in-sitelib.patch --dry-run
    00:22.692  SYSTEM                  [log-483-a00279] (in 0.001s) patch -p3 -i /root/.opam/system/build/ocamlfind.1.7.3-1/check-num-in-sitelib.patch --dry-run
    00:22.697  SYSTEM                  [log-483-d0f245] (in 0.001s) patch -p4 -i /root/.opam/system/build/ocamlfind.1.7.3-1/check-num-in-sitelib.patch --dry-run
    00:22.697  SYSTEM                  error: Patch /root/.opam/system/build/ocamlfind.1.7.3-1/check-num-in-sitelib.patch does not apply.
    00:22.697  ACTION                  ocamlfind: applying threads.patch.

    00:22.702  SYSTEM                  [log-483-6cc03f] (in 0.001s) patch -p0 -i /root/.opam/system/build/ocamlfind.1.7.3-1/threads.patch --dry-run
    00:22.709  SYSTEM                  [log-483-865888] (in 0.004s) patch -p1 -i /root/.opam/system/build/ocamlfind.1.7.3-1/threads.patch --dry-run
    00:22.715  SYSTEM                  [log-483-e4db2f] (in 0.000s) patch -p2 -i /root/.opam/system/build/ocamlfind.1.7.3-1/threads.patch --dry-run
    00:22.720  SYSTEM                  [log-483-0a5907] (in 0.000s) patch -p3 -i /root/.opam/system/build/ocamlfind.1.7.3-1/threads.patch --dry-run
    00:22.726  SYSTEM                  [log-483-c743ac] (in 0.000s) patch -p4 -i /root/.opam/system/build/ocamlfind.1.7.3-1/threads.patch --dry-run
    00:22.726  SYSTEM                  error: Patch /root/.opam/system/build/ocamlfind.1.7.3-1/threads.patch does not apply.
    00:22.726  PARALLEL                Exception while computing job 871091801: install ocamlfind.1.7.3-1

    #=== ERROR while installing ocamlfind.1.7.3-1 =================================#
    These patches didn't apply at /root/.opam/system/build/ocamlfind.1.7.3-1:
      - threads.patch
      - check-num-in-sitelib.patch

    =-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    The following actions failed
      - install ocamlfind 1.7.3-1
    No changes have been performed
    00:22.728  STATE                   LOAD-STATE(switch-backup-err)
    00:22.825  STATE                   Loaded /root/.opam/state.cache in 0.097s
    00:22.954  STATE                   ROOT      : /root/.opam
    00:22.954  STATE                   SWITCH    : system
    00:22.954  STATE                   COMPILER  : system
    00:22.954  STATE                   COMPILERS : { 3.07, 3.07+1, 3.07+2, 3.08.0, 3.08.1, 3.08.2, 3.08.3, 3.08.4, 3.09.0, 3.09.1, 3.09.1+metaocaml, 3.09.2, 3.09.3, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.11.2, 3.12.0, 3.12.1, 4.00.0, 4.00.0+debug-runtime, 4.00.0+fp, 4.00.1, 4.00.1+BER, 4.00.1+PIC, 4.00.1+annot, 4.00.1+debug-runtime, 4.00.1+french, 4.00.1+mirage-unix, 4.00.1+mirage-xen, 4.00.1+open-types, 4.00.1+raspberrypi, 4.00.1+short-types, 4.01.0, 4.01.0+32bit, 4.01.0+BER, 4.01.0+PIC, 4.01.0+armv6-freebsd, 4.01.0+fp, 4.01.0+lsb, 4.01.0+musl, 4.01.0+musl+static, 4.01.0+open-types, 4.01.0+profile, 4.02.0, 4.02.0+PIC, 4.02.0+improved-errors, 4.02.0+modular-implicits, 4.02.0+rc1, 4.02.0+trunk, 4.02.1, 4.02.1+32bit, 4.02.1+BER, 4.02.1+PIC, 4.02.1+fp, 4.02.1+modular-implicits-ber, 4.02.1+musl, 4.02.1+musl+static, 4.02.2, 4.02.2+improved-errors, 4.02.2+rc1, 4.02.3, 4.02.3+32bit, 4.02.3+PIC, 4.02.3+buckle-1, 4.02.3+buckle-master, 4.02.3+bytecode-only, 4.02.3+curried-constr, 4.02.3+fp, 4.02.3+musl, 4.02.3+musl+static, 4.02.3+termux, 4.03.0, 4.03.0+32bit, 4.03.0+beta1, 4.03.0+beta1+flambda, 4.03.0+beta1-no-debug, 4.03.0+beta2, 4.03.0+beta2+flambda, 4.03.0+beta2-no-debug, 4.03.0+fPIC, 4.03.0+flambda, 4.03.0+fp, 4.03.0+fp+flambda, 4.03.0+statistical-memprof, 4.03.0+termux, 4.03.0+trunk, 4.03.0+trunk+flambda, 4.03.0+trunk+fp, 4.03.0+trunk+fp+flambda, 4.04.0, 4.04.0+32bit, 4.04.0+BER, 4.04.0+afl, 4.04.0+beta1, 4.04.0+beta1+flambda, 4.04.0+beta2, 4.04.0+beta2+flambda, 4.04.0+bytecode-only, 4.04.0+copatterns, 4.04.0+fPIC, 4.04.0+flambda, 4.04.0+fp, 4.04.0+fp+flambda, 4.04.0+safe-string, 4.04.0+spacetime, 4.04.0+termux, 4.04.0+trunk+forced_lto, 4.04.1, 4.04.1+32bit, 4.04.1+bytecode-only, 4.04.1+fPIC, 4.04.1+flambda, 4.04.1+fp, 4.04.1+fp+flambda, 4.04.1+safe-string, 4.04.1+spacetime, 4.04.2, 4.04.2+32bit, 4.04.2+bytecode-only, 4.04.2+fPIC, 4.04.2+flambda, 4.04.2+fp, 4.04.2+fp+flambda, 4.04.2+safe-string, 4.04.2+spacetime, 4.04.2+statistical-memprof, 4.05.0, 4.05.0+32bit, 4.05.0+afl, 4.05.0+beta1, 4.05.0+beta1+flambda, 4.05.0+beta2, 4.05.0+beta2+flambda, 4.05.0+beta3, 4.05.0+flambda, 4.05.0+lto, 4.05.0+musl+static+flambda, 4.05.0+rc1, 4.05.0+rc1+flambda, 4.05.0+safe-string, 4.05.0+spacetime, 4.05.0+statistical-memprof, 4.05.0+trunk, 4.05.0+trunk+afl, 4.05.0+trunk+flambda, 4.05.0+trunk+fp, 4.05.0+trunk+fp+flambda, 4.05.0+trunk+safe-string, 4.06.0, 4.06.0+32bit, 4.06.0+afl, 4.06.0+beta1, 4.06.0+beta1+afl, 4.06.0+beta1+default-unsafe-string, 4.06.0+beta1+flambda, 4.06.0+beta1+force-safe-string, 4.06.0+beta1+fp, 4.06.0+beta1+fp+flambda, 4.06.0+beta2, 4.06.0+beta2+afl, 4.06.0+beta2+default-unsafe-string, 4.06.0+beta2+flambda, 4.06.0+beta2+force-safe-string, 4.06.0+beta2+fp, 4.06.0+beta2+fp+flambda, 4.06.0+default-unsafe-string, 4.06.0+flambda, 4.06.0+force-safe-string, 4.06.0+fp, 4.06.0+fp+flambda, 4.06.0+musl+static+flambda, 4.06.0+rc1, 4.06.0+rc1+afl, 4.06.0+rc1+default-unsafe-string, 4.06.0+rc1+flambda, 4.06.0+rc1+force-safe-string, 4.06.0+rc1+fp, 4.06.0+rc1+fp+flambda, 4.06.0+statistical-memprof, 4.06.1+trunk, 4.06.1+trunk+afl, 4.06.1+trunk+flambda, 4.06.1+trunk+fp, 4.06.1+trunk+fp+flambda, 4.06.1+trunk+safe-string, 4.07.0+trunk, 4.07.0+trunk+afl, 4.07.0+trunk+flambda, 4.07.0+trunk+fp, 4.07.0+trunk+fp+flambda, 4.07.0+trunk+unsafe-string, system }
    00:22.954  STATE                   REPOS     : { default }
    00:22.954  STATE                   PACKAGES  : 8233 packages
    00:22.955  STATE                   INSTALLED : { base-bigarray.base, base-threads.base, base-unix.base, conf-m4.1 }
    00:22.955  STATE                   ROOTS     : { base-bigarray.base, base-threads.base, base-unix.base, conf-m4.1 }
    00:22.955  STATE                   REINSTALL : {}
    00:22.955  STATE                   State switch-backup-err loaded in 0.226s
    00:22.955  SYSTEM                  rm /root/.opam/system/backup/state-20180017162610.export
    00:22.955  SYSTEM                  Lock released on /root/.opam/system/lock
    00:22.955  SYSTEM                  Lock released on /root/.opam/lock
    'opam install --debug -v -v ocamlfind' failed.

**Comment by jpdeplaix** [comment]
It looks like busybox's patch binary doesn't support the ```--dry-run``` option.
If you install patch from GNU it works.
```apk add patch```

I'm closing this issue for now. Feel free to reopen it if you encounter more problems.

**Comment by Ketrel** [comment]
I installed patch with `apk add patch` so I was no longer using busybox's.
It fails on the compile "[ERROR] The compilation of ocamlfind failed at "make opt"."

Did you have to do anything additional that I didn't mention in my original post other than installing gnu's patch?

**Comment by jpdeplaix** [comment]
Could you give me a Dockerfile where that fails ? I can't reproduce it locally

**Comment by Ketrel** [comment]
Sure

    FROM alpine:3.7

    RUN touch ~/.profile && \
        apk update && \
        apk add m4 pcre-dev make opam patch && \
        opam init -a && \
        opam install conf-m4

I build with `docker build -t alptest:alptest .`
Then I go in with `docker run -it --rm alptest:alptest /bin/sh`
Once in I run  
`opam install ocamlfind`
or
`opam install --debug -v -v ocamlfind`

**Comment by jpdeplaix** [comment]
Ok, I got it. ```libc-dev``` and ```gcc``` were wissing.
Here is a minimal Dockerfile that works:
```
FROM alpine:3.7

RUN apk update
RUN apk add m4 make opam patch libc-dev gcc
RUN opam init -a
```
