### ISSUE TITLE
feature request: verbose filter

### ISSUE THREAD

**Issue by jhwoodyatt** [ocaml/opam-repository#11317]
I would like to be able to pass the _--verbose_ flag to **omake** in various command lists, e.g., build, install, remove, et cetera, when the _-v_ flag is given to the **opam** command.

I was expecting something like this to work:

`build: [ "omake" "--verbose" { verbose } ]`

Any chance this is an easy thing for a newbie to contribute?

**Comment by dbuenzli** [comment]
This needs to be filed against the `opam` [issue tracker](https://github.com/ocaml/opam), so I'm closing this, please reopen there. (Regarding the idea while I think it may be a good idea to have something like this, I don't think it should be linked to `opam`'s verbosity itself).
