### ISSUE TITLE
Fail to install ocaml on Android (Termux)

### ISSUE THREAD

**Issue by giuliopaci** [ocaml/opam-repository#11562]
The command `opam init --comp=4.05.b0+termux termux https://github.com/camlunity/opam-repository.git` fails on Android using Termux.

The failure happens during the world.opt step, with the following error:

```
:(.text+0x784): dangerous relocation: unsupported relocation
/data/data/com.termux/files/usr/bin/ld: unix.a(unixLabels.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `camlUnixLabels' which may bind externally can not be used when making a shared object; recompile with -fPIC
:(.text+0x790): dangerous relocation: unsupported relocation
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
```

while

```
make[3]: Entering directory '/data/data/com.termux/files/home/.opam/4.04.0+termux/build/ocaml/otherlibs/unix'
../../boot/ocamlrun ../../ocamlopt -nostdlib -I ../../stdlib -c -absname -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -nolabels  unix.ml
../../boot/ocamlrun ../../ocamlopt -nostdlib -I ../../stdlib -c -absname -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -nolabels  unixLabels.ml
../../boot/ocamlrun ../../tools/ocamlmklib -o unix -oc unix -ocamlopt '../../boot/ocamlrun ../../ocamlopt -nostdlib -I ../../stdlib' -linkall unix.cmx unixLabels.cmx
../../boot/ocamlrun ../../ocamlopt -nostdlib -I ../../stdlib -shared -o unix.cmxs -I . unix.cmxa
```

**Comment by ygrek** [comment]
Please post more details about your platform and attach full configure and build log.

**Comment by giuliopaci** [comment]
Hi!
  My platform is Termux on Android 8 (I am using a Mi A1 with official
updates).

Can you tell me how to get the log that you want?

Best regards,
Giulio

Il lun 26 mar 2018, 15:11 ygrek <notifications@github.com> ha scritto:

**Comment by ygrek** [comment]
try add `-b` (keep build dir) flag to `opam init`, then look for log file (*.log *.out *.err) in build dir, presumably in /data/data/com.termux/files/home/.opam/4.04.0+termux/build/ocaml/

**Comment by giuliopaci** [comment]
I tried -b option, but it didn't work.
So I have run opam while continuously copying log files. I hope the important information has been copied.
[log.tar.gz](https://github.com/ocaml/opam-repository/files/1849276/log.tar.gz)

This is the command line that I have used:
```
opam init -b --comp=4.04.0+termux termux https://github.com/ocaml/opam-repository
```

**Comment by giuliopaci** [comment]
Last week I tried to install a newer version of ocaml (`4.06.0+beta2`) and with this version opam succeeded and now I have a working ocaml compiler.

So I think https://wiki.termux.com/wiki/Compiling_and_setting_up_OCaml should probably be updated to refer to 4.06+beta2.

Later I have tried to install `camlp4`, running this command

```
opam install camlp4
```
leaded to the following error
```
The following actions will be performed:
∗  install ocamlbuild 0.12.0 [required by camlp4]
∗  install camlp4     4.06+1
=====
∗  2
=====
Do you want to continue ? [Y/n]
Fatal error:
# opam-version    1.2.2 (b62f698e8b7be3dba4f20bc95d377ddc403aee90)
# os              unix
opam: "tcsetattr" failed: Permission denied
```
I have been able to install camlp4 by first installing ocamlbuild and then installing camlp4, so I guess this new issue originated from some operation in the dependency resolution in opam, which is not allowed on Android (the version shipped with my phone at least). Can you suggest me the best place where to notify this issue?

**Comment by ygrek** [comment]
indeed, current termux only works with OCaml >= 4.06, I have update the guide at http://ygrek.org.ua/p/ocaml-termux.html

> Can you suggest me the best place where to notify this issue?

idk, this is probably the place, or discuss.ocaml.org

**Comment by ygrek** [comment]
@gasche @kit-ty-kate I think this issue can be closed
