### ISSUE TITLE
ocamlnet.3.7.3 errors

### ISSUE THREAD

**Issue by kindnation** [ocaml/opam-repository#1169]
I'm trying to install google drive ocamlfuse with opam, and it requires ocamlnet 3.7.3, but it exits with errors in the file:

/.opam/system/build/ocamlnet.3.7.3/src/netstring/netencoding.mli

File "netencoding.mli", line 117, characters 1-3
Error: This comment contains an unterminated string literal
make[1]: *** [depend] Error 1
make: *** [all] Error 2

I tried compiling ocamlnet version 3.7.3 manually and can confirm the bug.  There must be some hidden characters because it looks like a normal comment so I just removed the comments from 117 and a few lines below it from netencoding.mli and then it is able to compile successfully.

**Comment by samoht** [comment]
Please re-open if newer version of ocamlnet didn't fix your problem.
