### ISSUE TITLE
easy-install.1.0.1 FTBFS on OCaml 4.06.1

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/opam-repository#11816]
I've tried installing Merlin on a switch with OCaml 4.06.1. For some reason, the OPAM 2.0.0~rc version solver picked a very old version of easy-format which fails to build:

```
> opam install merlin
The following actions will be performed:
 - install easy-format 1.0.1 [required by yojson]
 - install biniou      1.2.0 [required by yojson]
 - install yojson      1.4.1 [required by merlin]
 - install merlin      3.0.5
===== 4 to install =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[biniou.1.2.0] found in cache
[easy-format.1.0.1] found in cache
[merlin.3.0.5] found in cache
[yojson.1.4.1] found in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Processing  1/8: [easy-format: patch]
#=== ERROR while compiling easy-format.1.0.1 ==================================#
These patches didn't apply at /home/me/project/_opam/.opam-switch/build/easy-format.1.0.1:
 - easy-format-make.diff: "/usr/bin/patch -p1 -i
   /home/me/project/_opam/.opam-switch/build/easy-format.1.0.1/easy-format-make.diff"
   exited with code 1
 - meta-tpl.diff: "/usr/bin/patch -p1 -i
   /home/me/project/_opam/.opam-switch/build/easy-format.1.0.1/meta-tpl.diff" exited with
   code 1
```

(this build is running on macOS, so `patch` is the one that macOS uses)

Building newer versions of easy-format works, since they don't have these patches to begin with. I don't exactly know what broke it, since the checksum hasn't changed since 6 years ago when @vbmithr created it, so I am confused why they wouldn't apply anymore.

**Comment by bcc32** [comment]
Having the same problem on Arch.  It appears to attempt to patch Makefile.orig to Makefile, but there is no Makefile.orig file.  The patch applies cleanly to Makefile itself.

Installing easy-format by itself installs easy-format-1.3.1 successfully, and then installing merlin succeeds fine.
