### ISSUE TITLE
Missing external dependency for conf-gtksourceview

### ISSUE THREAD

**Issue by davidnowak** [ocaml/opam-repository#11899]
The installation of `conf-gtksourceview` fails if one does not install first `pkg-config`. This seems to be a missing external dependency that `opam depext conf-gtksourceview.2` does not detect:

```
$ opam depext conf-gtksourceview.2
# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - gtksourceview
#  - libxml2
# All required OS packages found.
```

**Comment by kit-ty-kate** [comment]
This PR should fix this: https://github.com/ocaml/opam-repository/pull/11900. Sorry for that.
