### ISSUE TITLE
Upgrade the Ubuntu version used by Travis

### ISSUE THREAD

**Issue by mor1** [ocaml/opam-repository#11939]
At present it seems that the Travis CI job runs on Ubuntu 14.04 by default.
This is quite old now. Given 18.04 is released and 16.04 still common, perhaps we could drop the third and oldest Ubunbtu LTS version now? :)

**Comment by kit-ty-kate** [comment]
According to Travis' documentation, only Ubuntu 12.04 and 14.04 are available (link to the github issue: https://github.com/travis-ci/travis-ci/issues/5821)

However what we can do is to use docker containers but I'm not really willing to spend time on this right now. Maybe later.

**Comment by XVilka** [comment]
See https://github.com/ocaml/opam-repository/pull/13200 - seems green enough.
