### ISSUE TITLE
build ocaml-base-compiler fails on versions 4.02-4.08 (`opam switch create . 4.06.1`)

### ISSUE THREAD

**Issue by mprevot** [ocaml/opam-repository#12050]
I'm using opam 2.0.0~rc2 and for `opam switch create . 4.06.1` I got:

```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-base-compiler failed at "/home/user/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /mnt/i/LangCompil/td1/_opam -with-debug-runtime".

#=== ERROR while compiling ocaml-base-compiler.4.06.1 =========================#
# context     2.0.0~rc2 | linux/x86_64 |  | https://opam.ocaml.org/2.0#b36f28db
# path        /mnt/i/LangCompil/td1/_opam/.opam-switch/build/ocaml-base-compiler.4.06.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /mnt/i/LangCompil/td1/_opam -with-debug-runtime
# exit-code   1
# env-file    ~/.opam/log/ocaml-base-compiler-3314-d2d111.env
# output-file ~/.opam/log/ocaml-base-compiler-3314-d2d111.out
### output ###
# Creating new namespace failed: Invalid argument
```

How to resolve this ?

**Comment by rjbou** [comment]
Can you run on verbose mode (-vv) and post the log?

**Comment by mprevot** [comment]
Can you please confirm if it's `opam switch create . 4.06.1 -vv` and tell me where I can find the log ?

**Comment by mprevot** [comment]
I didn't got more details unfortunately. But I have this new detail:
`bwrap: Creating new namespace failed: Invalid argument`

**Comment by rjbou** [comment]
`bwrap`, the [sandboxing tool](https://github.com/projectatomic/bubblewrap), seems to be unable to create a namespace. You can find all bwrap argument in `~/.opam/opam-init/sandbox.sh`.
Can you try this command, simplified version of opam bwrap command which should work and launch `pwd`:
```
bwrap \
--unshare-net \
--new-session \
--ro-bind /bin /bin \
--ro-bind /lib /lib \
--ro-bind /lib32 /lib32 \
--ro-bind /lib64 /lib64 \
--ro-bind /home /home \
pwd
```

**Comment by rjbou** [comment]
Indeed, `bwrap` is not supported by WSL (cf. [this issue](https://github.com/Microsoft/WSL/issues/2911)).
To be able to use opam in your case, you can disable sandboxing (use with caution) using the `--disable-sandboxing` option for a fresh opam initialisation. For an initialised opam, you can't use this option, but change the configuration, via an [`opamrc`](https://opam.ocaml.org/doc/2.0/Manual.html#opamrc) or directly in the [`config`](https://opam.ocaml.org/doc/2.0/Manual.html#config) file by removing / empty [`wrap-*-command`](https://opam.ocaml.org/doc/2.0/Manual.html#configfield-wrap-build-commands) fields.
See this [faq entry](https://opam.ocaml.org/doc/2.0/FAQ.html#Why-does-opam-require-bwrap) for further information.
And I repeat the warning here: **"Use [sanbdoxing disable option] wisely, broken Makefiles that run rm -rf / [do happen](https://github.com/ocaml/opam/issues/3231)."**

**Comment by mprevot** [comment]
Thanks for the details, the solution and the warning. In my case, I built a safely an opam local repo from a VM and copied it to WSL.

**Comment by bluddy** [comment]
Looks like the issue has been fixed in an insider build, which means we'll eventually get it.

**Comment by dra27** [comment]
This issue hasn't been fixed in WSL - for the foreseeable, sandboxing will need to remain disabled.

**Comment by mprevot** [comment]
If it's not fixed in insider build, can a developer explain what would be needed, so we create a feature request to MSFT ?

**Comment by rjbou** [comment]
It depends of the error cause. If it is a mount propagation flag error, it should [have been fixed](https://github.com/Microsoft/WSL/issues/2911#issuecomment-387884945).
As told in a [previous comment](https://github.com/Microsoft/WSL/issues/2911#issuecomment-376672366), bubblewrap contains some stuff that are not yet supported:
> Yes, but bubblewrap.c is a who's-who of stuff we don't have.

A bubblewrap developer would be more relevant for the feature request. Maybe opening an issue on their [tracker](https://github.com/projectatomic/bubblewrap/issues)?

**Comment by mprevot** [comment]
Done: [bubblewrap#272](https://github.com/projectatomic/bubblewrap/issues/272)

**Comment by rjbou** [comment]
thanks!

**Comment by dra27** [comment]
The feature request is still open, it's just a question of waiting. https://github.com/Microsoft/WSL/issues/2911 just notes a blocking feature for bubblewrap is now implemented, but more remain.

**Comment by rivy** [comment]
It looks like it's been almost two years now ... Is there a resolution besides disabling sandboxing?

**Comment by mprevot** [comment]
Theorically speaking, with WSL2 implementing a full kernel, its should not be an issue, and WSL very likely will fail forever. Few tests should assert this.

**Comment by rjbou** [comment]
I works now ow WSL2. With WSL1, sandboxing need to be disabled at init. See also related issue  https://github.com/ocaml/opam/issues/4089.

**Comment by AndrewPardoe** [comment]
I found that disabling sandboxing was still required for WSL2, Ubuntu 20.04.

**Comment by dra27** [comment]
@AndrewPardoe - are you sure the distro was running WSL2 (check `wsl -l --verbose` and run `wsl --set-version Ubuntu-20.04 2` or equivalent as needed). opam 2.0.5 is definitely working this morning with bwrap in WSL2 (Ubuntu 20.04/Linux 5.4.72) on my Windows 20H2 desktop...

**Comment by jiping-yu11** [comment]
user_namespaces issue

cat /proc/sys/user/max_user_namespaces
0

# grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
# echo "user.max_user_namespaces=10000" >> /etc/sysctl.conf

cat /proc/sys/user/max_user_namespaces
10000
