### ISSUE TITLE
unable to install Core

### ISSUE THREAD

**Issue by houndofsound** [ocaml/opam-repository#12193]
I was on switch 4.06.1 and tried
opam install core
and got
[ERROR] The sources of the following couldn't be obtained, aborting:
- ppxlib.0.2.0
- spawn.v0.12.0

then this:
$ opam install ppxlib
[NOTE] Package ppxlib is already installed (current version is 0.2.0).

$ opam install spawn
The following actions will be performed:

    install spawn v0.12.0

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

[spawn.v0.12.0] found in cache
[ERROR] The sources of the following couldn't be obtained, aborting:
- spawn.v0.12.0

so 1) the right version of ppxlib is already installed 2) the source for spawn is already in the cache.

**Comment by houndofsound** [comment]
I'm running opam2 on WinXP ...

**Comment by rjbou** [comment]
Can you share the result of the same command on verbose mode, adding option `-vv`?

**Comment by houndofsound** [comment]
thanks for that:  it turned out the downloaded spawn/core packages were in bzip2 format and I found that the bzip2 binary was simply failing (no feedback), so I uninstalled the cygwin pkg and ... the binary was still in the same place in the filesystem ... yet it ran correctly!  
all good thereafter.
cheers.

**Comment by rjbou** [comment]
Nice!
