### ISSUE TITLE
depext install error

### ISSUE THREAD

**Issue by jinxinslim** [ocaml/opam-repository#12269]
[WARNING] Running as root is not recommended
The following actions will be performed:
  - install opam-depext 1.1.2      [required by depext]
  - install depext      transition
===== 2 to install =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[opam-depext.1.1.2] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of opam-depext failed at "/root/.opam/opam-init/hooks/sandbox.sh build make".

#=== ERROR while compiling opam-depext.1.1.2 ==================================#
# context     2.0.0~rc3 | linux/x86_64 | ocaml-system.4.06.1 | https://opam.ocaml.org/2.0#9f513703
# path        ~/.opam/default/.opam-switch/build/opam-depext.1.1.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   2
# env-file    ~/.opam/log/opam-depext-26704-58c514.env
# output-file ~/.opam/log/opam-depext-26704-58c514.out
### output ###
# [...]
# make[4]: Leaving directory '/root/.opam/default/.opam-switch/build/opam-depext.1.1.2/src_ext'
# ../OCamlMakefile:801: recipe for target 'native-code-library' failed
# make[3]: *** [native-code-library] Error 2
# make[3]: Leaving directory '/root/.opam/default/.opam-switch/build/opam-depext.1.1.2/src_ext'
# ../OCamlMakefile:1226: recipe for target 'subproj_cmdliner' failed
# make[2]: *** [subproj_cmdliner] Error 2
# make[2]: Leaving directory '/root/.opam/default/.opam-switch/build/opam-depext.1.1.2/src_ext'
# Makefile:21: recipe for target 'build' failed
# make[1]: *** [build] Error 2
# make[1]: Leaving directory '/root/.opam/default/.opam-switch/build/opam-depext.1.1.2/src_ext'
# Makefile:2: recipe for target 'all' failed
# make: *** [all] Error 2

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build opam-depext 1.1.2
+- 
- No changes have been performed

**Comment by hannesm** [comment]
this looks like the issue in opam, reported and fixed there https://github.com/ocaml/opam/pull/3439
