### ISSUE TITLE
FrontC package is no longer available

### ISSUE THREAD

**Issue by ivg** [ocaml/opam-repository#12285]
The package URL returns the 404 error. The upstream author is contacted, the temporary workaround is proposed (#12284). Even a more temporal workaround (until the PR is merged) would be to put the [FrontC.3.4+opam.tar.gz](https://github.com/ocaml/opam-repository/files/2171798/FrontC.3.4.opam.tar.gz) file into your `~/.opam/archives/` folder.

**Comment by 251** [comment]
Unfortunately, the certificate of the mirror url in #12284 is invalid and the installation fails. I had to prefix the installation with `OPAMFETCH='cp <path>/Frontc-3.4.tgz %{out}%'` as `.opam/archives` seems to get ignored in opam 2.

**Comment by pmetzger** [comment]
This feels like a package that should get adopted by ocaml-community. @ivg, you willing to try to get that to happen?

**Comment by ivg** [comment]
we're currently in a process of vendoring FrontC under the BAP umbrella. Does anyone have the FrontC repository with the history?

**Comment by ivg** [comment]
For those who are interested in the answer, as of today (November 2018) FrontC is available from the mercurial repository at https://anon:anon@www.irit.fr/hg/TRACES/frontc/trunk

**Comment by ivg** [comment]
According to [opam][1] statistics it was installed more than 250 times in the last month, while `bap-frontc` was installed only 100 times, so the rest 150 installation are for projects that are not using BAP. Frontc, in fact, is quite popular among researches and is used in several courses. 

Concerning why not clang? Well, we use frontc to parse a DSL which is a subset of C, so FrontC works for us. We need something fast and easy, that won't involve lots of effort, and with FrontC it is only 60 lines of code, for parsing C headers, quite good result, I think :)

[1]: http://opam.ocaml.org/packages/FrontC/
