### ISSUE TITLE
ERROR: cannot verify opam.ocaml.org's certificate

### ISSUE THREAD

**Issue by rizo** [ocaml/opam-repository#12359]
Seems like opam.ocaml.org certificate has expired:

<img width="667" alt="opam-cert" src="https://user-images.githubusercontent.com/308413/42753180-fa37bb58-88e7-11e8-8d5d-64e3284282cd.png">

This affects repository updates, of course:

```
=> opam repo add default https://opam.ocaml.org/2.0                                                                                .opam
[ERROR] Could not update repository "default": Download command failed: "/usr/local/bin/wget --content-disposition -t 3 -O
        /private/var/folders/1c/7sytdqbs2hd32zmvynmp4_sw0000gn/T/opam-3173-5a61c5/index.tar.gz.part
        https://opam.ocaml.org/2.0/index.tar.gz -U opam/2.0.0~rc2" exited with code 5 "ERROR: cannot verify opam.ocaml.org's
        certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:"
[ERROR] Initial repository fetch failed
```

**Comment by kit-ty-kate** [comment]
@avsm ?

**Comment by pmetzger** [comment]
Most `Let's Encrypt` setups use a cron job to update their certs before they expire. I wonder if your cron job died.

**Comment by rjbou** [comment]
It's back!

**Comment by ralcr** [comment]
It does not work for me, but i see in Safari that is valid till November:
<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "Download command failed:
        \"/usr/local/bin/wget --content-disposition -t 3 -O
        /private/var/folders/8l/q1l9d_n51mdgthrr38hrtl980000gn/T/opam-51069-e7966f/index.tar.gz.part
        https://opam.ocaml.org/index.tar.gz -U opam/2.0.0\" exited with code 5 \"ERROR: cannot verify
        opam.ocaml.org's certificate, issued by \226\128\152CN=Let's Encrypt Authority X3,O=Let's
        Encrypt,C=US\226\128\153:\"")
[ERROR] Initial download of repository failed

**Comment by pmetzger** [comment]
@ralcr You probably lack a modern CA root store that includes "Let's Encrypt". Update your wget packages etc.

**Comment by ralcr** [comment]
Most probably, could you give me some guidance? I don't know what is CA root store or packages for wget, i have this version which probably came with osx updates: "GNU Wget 1.18 built on darwin15.5.0."

**Comment by ralcr** [comment]
Thank you, i succeeded to update wget from homebrew (not without problems though). Now opam works.

**Comment by abhi18av** [comment]
It seems I'm facing a similar issue here in https://github.com/ocaml/opam-repository/issues/13111

**Comment by informatimago** [comment]
Same in macOS Catalina 10.15.7 with ocaml 4.08.1 and opam 2.0.7 from MacPorts.
