### ISSUE TITLE
Install OCaml .el files into $(opam config var share --safe)/emacs/site-lisp

### ISSUE THREAD

**Issue by omasanori** [ocaml/opam-repository#12352]
The OCaml code base contains Emacs Lisp files in `emacs/` but the default `make install` does not install them into  the`site-lisp` directory.
It would be great if `opam switch` could do something like `cp emacs/*.el prefix/share/emacs/site-lisp`.

**Comment by pmetzger** [comment]
I'm not sure this would really be a good idea. There's some question as to whether those files are even going to be maintained for much longer, since at this point Tuareg has long since obsoleted them.
