### ISSUE TITLE
http opam repo unreachable: cannot init, install

### ISSUE THREAD

**Issue by andyli** [ocaml/opam-repository#12419]
Just noticed today that the `opam_installer.sh` script failed with error message:

```
wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin system
--2018-08-01 01:35:59--  https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh
Resolving raw.github.com (raw.github.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.github.com (raw.github.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/ocaml/opam/master/shell/opam_installer.sh [following]
--2018-08-01 01:35:59--  https://raw.githubusercontent.com/ocaml/opam/master/shell/opam_installer.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2566 (2.5K) [text/plain]
Saving to: ‘STDOUT’
     0K ..                                                    100% 6.35M=0s
2018-08-01 01:35:59 (6.35 MB/s) - written to stdout [2566/2566]
Downloading opam...
You don't have write access to /usr/local/bin: sudo may ask for your password
Initializing with compiler system
Checking for available remotes: rsync and local, git, mercurial.
  - you won't be able to use darcs repositories unless you install the darcs
    command on your system.
=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default: http]
[default: http]
[default: http]
[default: http]
[default] synchronized from https://opam.ocaml.org
[ERROR] Base package base-threads of compiler system not found! Ignored.
[ERROR] Base package base-bigarray of compiler system not found! Ignored.
[ERROR] Base package base-unix of compiler system not found! Ignored.
[ERROR] Inconsistent set of base compiler packages: {} needed but not included
        / { base-bigarray, base-threads, base-unix } extra
[ERROR] Initialisation failed
OpamGlobals.Exit(66)
```

For an existing opam installation, after I ran `opam update`, it fails to install any package:
```
opam install sha
[ERROR] No package named sha found.
```

Note that it starts happening today, but I can tell that everything was alright yesterday.

**Comment by mseri** [comment]
Thanks for the report. The issue is similar to the one affecting https://github.com/ocaml/opam-repository/issues/12420

Because of some temporary problems of `opam.ocaml.org`, (if my suggestion there works) download the script and replace the line
```
"$OPAM" init --comp "$COMP"
```
with
```
"$OPAM" init --comp "$COMP" git+https://github.com/ocaml/opam-repository
```

**Comment by andyli** [comment]
Indeed it is the same problem as #12420.

opam works for me if after `opam repository add git git+https://github.com/ocaml/opam-repository`.

I wonder whether it it a good idea to add `git+https://github.com/ocaml/opam-repository` as a backup repository with a lower priority by default?

**Comment by rjbou** [comment]
cf. [this comment](https://github.com/ocaml/opam/issues/3489#issuecomment-409530015).

> I wonder whether it it a good idea to add git+https://github.com/ocaml/opam-repository as a backup repository with a lower priority by default?

At `opam init`, as user chooses which backend/repo opam should use (`-k` option: http, local, git, hg, darcs), it is not directly clear to set the git backend as a backup repository. But it is a good idea, we could set a mechanism on the default case, and ask user / according its configuration.

Keeping this issue open for that point, and I'll change its title for tracking purpose. 

Thanks for reporting!
