### ISSUE TITLE
Sketch.sh and loading libraries

### ISSUE THREAD

**Issue by Drup** [ocaml/opam-repository#12517]
https://sketch.sh/ can now load arbitrary libraries that have been precompiled to Javascript.  @thangngoc89, @rgrinberg and I have been discussing the idea of precompiling opam packages to be able to load arbitrary OCaml and Reason libraries easily. Having a toplevel-like webpage like sketch.sh with instant access to the whole OPAM ecosystem where everyone can showcase ideas/gists/instructions would be a really big plus for the community!

The goal of his issue is to discuss how we can have an automatic prebuilding of libraries that can be loaded on sketch and what's the best stable and sustainable way to achieve that in the long run.

The current two command necessary to compile any library to javascript are (here for `re`):
```sh
js_of_ocaml --wrap-with-fun=reCma --pretty path/to/re.cma -o re.cma.js
jsoo_mkcmis re -o re.cmis.js # `re` here is the ocamlfind library. Can also be a list of cmi
```

Note here that we don't need to mention `re`'s dependencies, jsoo has separate compilation.

My idea was to have opam's CI perform these two steps at the end of the chain (it could simply be done by scanning available cm[ai]'s or something like that) and host the resulting js file somewhere, organized by opam packages. @rgrinberg proposed to rely on duniverse instead, which might be easier but has a smaller set of libraries and might not handle versioning just as well.

@avsm @AltGr : Though ? :)

cc @hhugo for technical jsoo aspects and @ejgallego who implemented jscoq and might have interesting insights.

**Comment by hhugo** [comment]
- Why do you need the `--wrap-with-fun=...` part ?
- I'm working on having a single command instead two
- Not all libraries will work in javascript, would it make sense to flag libraries explicitly

**Comment by thangngoc89** [comment]
@hhugo It didn't work without `--wrap-with-fun` 

```
re.cma.js:5 Uncaught TypeError: Cannot read property 'caml_bytes_get' of undefined
```

And having 1 command would be lovely :+1:  (maybe merge the result as well)

**Comment by hhugo** [comment]
single command it is: `js_of_ocaml --wrap-with-fun=reCma --toplevel --pretty path/to/re.cma -o re.cma.js`

**Comment by thangngoc89** [comment]
@hhugo I believe I have to have this commit in able for this to work right? 
https://github.com/ocsigen/js_of_ocaml/commit/c07c50936fccb60e47a888ec431a10bb4fa17fd9

Thank you very much for this

**Comment by avsm** [comment]
Out of curiosity, is there a Dune command that can generate this for a given library?  We have two options:

- run a heuristic over opam packages that use Dune, and just add this to the build step to generate the JavaScript
- use my experimental [duniverse](https://github.com/avsm/duniverse) framework (still a WIP but getting there) to generate a monorepo of many libraries that are known to be jsoo compatible, and build them directly out of the Dune monorepo.  I'm happy to try this out if someone can give me the Dune runes (e.g. on https://github.com/avsm/platform)

**Comment by pmetzger** [comment]
I think it might be reasonable to add information to the opam file saying if the package will work with jsoo. We could populate it initially from a CI run so it doesn't need to involve a lot of handwork to bootstrap the system.

**Comment by avsm** [comment]
> I think it might be reasonable to add information to the opam file 

That's very brittle -- consider what happens when a transitive dependency includes a C dependency.  That's why I suggested the Dune-based approach above to start with.

**Comment by Drup** [comment]
@hhugo Does it uses only the `.cmi` files that are in the same directory as the `.cma` ? I suppose that's good enough for 99% of the packages. :)

@avsm There is another solution: just `find` all the cma files installed by each package, and use @hhugo's command on them. Some of them will require primitives that are not available and will have some jsoo (non-fatal) messages because of that, but we can let the sketch.sh side deal with that.

**Comment by ejgallego** [comment]
That's very cool. IMVHO the biggest roadblock to achieve this is the lack of `Re` and `Unix` in jsoo.

**Comment by hhugo** [comment]
@Drup, js_of_ocaml will look for cmis in directories provided with `-I`
