### ISSUE TITLE
emacs files from ocaml install are not provided

### ISSUE THREAD

**Issue by yminsky** [ocaml/opam-repository#1257]
The emacs files from the ocaml mode are not provided by default, and really should be.  At least there should be an opam package you can install to get them (and ideally get them stashed in shared/emacs, where the merlin files go.)

**Comment by cakeplus** [comment]
Agreed. Just had to copy `caml-types.el` from the OCaml source tree, as Tuareg alone doesn't include support for parsing *.annot files.

**Comment by dbuenzli** [comment]
Would definitively be nice, I'm not very fond of having to install caml-mode manually.

**Comment by cakeplus** [comment]
Awesome. Thank you!
