### ISSUE TITLE
code 404 while downloading shine sources

### ISSUE THREAD

**Issue by toots** [ocaml/opam-repository#12692]
Here's the output, not sure what's going on but a direct hit on the source url confirms the `404`:
```
$ opam install -y shine
The following actions will be performed:
  ∗  install   shine      0.2.1
  ↻  recompile liquidsoap 1.3.4               [uses shine]
===== ∗  1   ↻  1 =====

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[liquidsoap] Archive in cache
[ERROR] curl: code 404 while downloading https://opam.ocaml.org/archives/shine.0.2.1+opam.tar.gz
[ERROR] The sources of the following couldn't be obtained, aborting:
          - shine.0.2.1
        (This may be fixed by running 'opam update')
```

**Comment by mseri** [comment]
Can you try to run it again? I am unable to reproduce the issue. Maybe also try to run `opam update` (although it was not needed for me)

**Comment by rjbou** [comment]
With opam 2.0.0 release and opam repository upgrade, redirections have been set for older repositories. As you use opam1.2, you need to update with `opam update` in order to have the good redirections, and retry you install.

**Comment by toots** [comment]
Gotcha, thanks!
