### ISSUE TITLE
CPUID package fails to build 

### ISSUE THREAD

**Issue by abhi18av** [ocaml/opam-repository#12777]
Hello everyone,

I have been trying to install the `tls` package in my linux machine and here's the info about the machine

```
[nightfury@localhost ~]$ uname -a
Linux localhost.localdomain 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
But for some reason I keep running into this error with the `tls` package. I need this package to get the `tls` package working for a project.

Here's the error log for the same

```

[nightfury@localhost ~]$ opam install tls
The following actions will be performed:
  ∗ install cpuid    0.1.1   [required by nocrypto]
  ∗ install nocrypto 0.5.4-1 [required by tls]
  ∗ install x509     0.6.2   [required by tls]
  ∗ install tls      0.9.2
===== ∗ 4 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[cpuid.0.1.1] found in cache
[nocrypto.0.5.4-1] found in cache
[tls.0.9.2] found in cache
[x509.0.6.2] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of cpuid failed at "/home/nightfury/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build
        --pinned false --tests false".

#=== ERROR while compiling cpuid.0.1.1 ========================================#
# context     2.0.0 | linux/x86_64 |  | https://opam.ocaml.org#0741623b
# path        ~/.opam/default/.opam-switch/build/cpuid.0.1.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --pinned false --tests false
# exit-code   1
# env-file    ~/.opam/log/cpuid-5412-0a5907.env
# output-file ~/.opam/log/cpuid-5412-0a5907.out
### output ###
# ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package ocb-stubblr myocamlbuild.ml /home/nightfury/.opam/default/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /bin/sh: opam: command not found
# Failure: Ocb_stubblr: error running opam.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' '-plugin-tag' 'package(ocb-stubblr)' 'opam'
#      'pkg/META' 'CHANGES.md' 'LICENSE.md' 'README.md' 'src/cpuid.a'
#      'src/cpuid.cmxs' 'src/cpuid.cmxa' 'src/cpuid.cma' 'src/cpuid.cmx'
#      'src/cpuid.cmi' 'src/cpuid.mli' 'src/dllcpuid_stubs.so'
#      'src/libcpuid_stubs.a']: exited with 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build cpuid 0.1.1
└─ 
╶─ No changes have been performed
# Run eval $(opam env) to update the current shell environment
[nightfury@localhost ~]$ 

```

**Comment by mseri** [comment]
Looks like ocb-stubblr tries to run opam: https://github.com/pqwy/ocb-stubblr/blob/master/src/ocb_stubblr.ml#L35

And I think this may be one of the things that you cannot do in the sandbox. Can you try running the command disabling the sandbox? If that works we will need to open an issue on ocb-stubblr

**Comment by mseri** [comment]
It may even be enough to have https://github.com/pqwy/ocb-stubblr/issues/12

**Comment by mseri** [comment]
Oh, sorry. Opam and the package index have been updated very recently to the new opam2 version. Among the improvements and new features that this provides, there is an enabled by default sandbox used when building the packages. This makes sure that broken build, install and remove scripts are not allowed to damage the rest of your systems. You can disable the sandbox when you initialise an opam repository if you do it as follows: `opam init --disable-sandboxing`. It is not recommended, but at tleast temporarily, using this should solve your issue.

**Comment by mseri** [comment]
Alternatively you could use a fixed version of `ocb-stubblr` by pinning it:
```
opam pin ocb-stubblr git+https://github.com/dra27/ocb-stubblr#sandboxing
```
I have just tried to install cpuid after pinning that version of ocb-stubblr and it worked (for me it also seems to work with the current version though)

**Comment by abhi18av** [comment]
Yup, this worked prefectly!

Thanks a lot  Marcello :)

**Comment by abhi18av** [comment]
This is related to an issue here https://github.com/ocaml/opam/issues/3602 

It seems that `no sandboxing` is important for many of the packages.

**Comment by mseri** [comment]
Thanks. In this case I think that a new `ocb-stubblr` should be released instead of having to generally disable the sandboxing though.
