### ISSUE TITLE
Q: what is the expected delay between package merge and availability

### ISSUE THREAD

**Issue by jberdine** [ocaml/opam-repository#12778]
I have looked around but have not found any info on how long to expect it to take between a package release PR being merged and it appearing in the repo.

In particular, I'm waiting for ocamlformat 0.8 to be installable, and #12771 was merged more than 24h ago. Is that sort of delay expected, or is something stuck?

**Comment by pmetzger** [comment]
I was under the impression that the system pulled from git. Have you done an "opam update"? Also are you on opam 2? Because if you're still on opam 1.2.2 you're probably going to be waiting forever, it's pretty much dead now.

**Comment by pmetzger** [comment]
That's very peculiar indeed, then. @avsm, any ideas what might be happening?

**Comment by mseri** [comment]
Something is wrong on the update scripts. Usually it is much faster. I think the maintainer of the index are aware and working on it, at least we were mentioning this already yesterday in opam's slack channel
