### ISSUE TITLE
Renaming old package versions

### ISSUE THREAD

**Issue by maroneze** [ocaml/opam-repository#12818]
We'd like to renumber all versions of the `frama-c` package, to ensure a proper ordering of upcoming releases, which will change the numbering scheme from `yyyymmdd` to `major.minor`.

For instance, the next release would be `frama-c.18.0` instead of `frama-c.20181101`.

However, since the current version is `20180501`, which is larger than `18.0`, we would need to do one of the following:

- add a prefix such as `v`, to make `v18.0` larger than `20180501`;
- backport the version number to previous versions, e.g. rename `20180501` to `17.0`, and so on until version `1.0`.

In the long term, the second approach seems better, since the `v` prefix is non-standard and somewhat of a hack. Renaming existing versions might break some things in the short term, but in the long term it should be better.

Is such a change acceptable? We would update each directory name and `opam` file inside the `frama-c` (and related) packages, which could trigger build errors from obsolete versions, due to the CI constraints being more strict now than back then. We would also notify our users that their next `opam update && opam upgrade` will reinstall the `frama-c` package, since their current version will no longer exist in the repository.

But other than that, we do not foresee much damage. Is there some past history of such a renaming attempt? Is there some unforeseen consequence or reason to avoid doing it?

**Comment by mseri** [comment]
When JaneStreet chaned versioning scheme they introduced the ‘v’. I don’t know if there are other examples

**Comment by dbuenzli** [comment]
In the long term the `v` is annoying because end-users need to be aware of the packages that follow the scheme and the ones who don't when they write their constraints. The best solution would maybe be [this proposal](https://github.com/ocaml/opam/issues/3537) but unfortunately it doesn't exist at the moment.

**Comment by hannesm** [comment]
I agree with @dbuenzli that the `v` prefix is slightly annoying, and for the time being I'm ok with a PR that renames all frama-c versions (+ fixing up reverse dependencies).

**Comment by maroneze** [comment]
Thanks, we're working on it in #12861.
