### ISSUE TITLE
Please consider making the EPEL package repository available in CI builds for CentOS and possibly other RHEL-based distros.

### ISSUE THREAD

**Issue by SylvainBoilard** [ocaml/opam-repository#12885]
Hello,

PR #12875 does not pass the CentOS CI build (and possibly other RHEL-based distros as well) at the moment because it has an external dependency on a package from EPEL. Would it be possible to make this package repository available in the appropriate CI builds ? If not, what steps should I take to have my PR merged ?

Cheers.

**Comment by kit-ty-kate** [comment]
There is a special meta package called `epel-release` just for this. Your issue is fixed

**Comment by SylvainBoilard** [comment]
Indeed. Thank you !
