### ISSUE TITLE
travis-ci images broken by `ocaml-config`

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam-repository#12936]
See for example <https://travis-ci.org/nunchaku-inria/logitest/jobs/451134278> in the log.  Not sure if it belongs here or in travis-opam, though, sorry.

**Comment by mseri** [comment]
See also https://travis-ci.org/mirage/ocaml-rpc/jobs/450940874

It seems that only ocaml 4.05.0 is failing. The issue seems to have appeared after https://github.com/ocaml/opam-repository/pull/12832 was merged but we don't know for sure, @dra27 is already aware of it

**Comment by hannesm** [comment]
fixed by https://github.com/ocaml/ocaml-ci-scripts/pull/268
