### ISSUE TITLE
Update the cduce package 

### ISSUE THREAD

**Issue by abhi18av** [ocaml/opam-repository#12963]
Hello `opam` team,

I'd like to know how to install the `cduce` package which depends on an old version of ocaml.

```none

The following dependencies couldn't be met:
  - cduce → ocaml < 4.02.0
      base of this switch (use `--unlock-base' to force)

No solution found, exiting

```

**Comment by abhi18av** [comment]
Hello @mseri 😄

However, in that case I'd have to recompile most of the other libraries that I've installed for `ocaml 4.07.1` right ?


I'll be closing this issue as my query has effectively been answered.

**Comment by mseri** [comment]
Yes you would indeed. You can use `opam source cduce` to get the sources and try to compile with 4.07. Maybe it is not hard to make it compatible, I don’t know
