### ISSUE TITLE
Update description for herelib

### ISSUE THREAD

**Issue by Kakadu** [ocaml/opam-repository#1301]
Current one is awful: part of Jane Street’s Core library 
The Core suite of libraries is an industrial strength alternative to OCaml's standard library that was developed by Jane Street, the largest industrial user of OCaml.

Why not description from [repo](https://github.com/janestreet/herelib) : Syntax extension for inserting the current location.

@diml ?

**Comment by samoht** [comment]
Can you report that issue upstream? Thanks.

**Comment by Kakadu** [comment]
`herelib` is deprecated. Let's just remove it from the repo.
