### ISSUE TITLE
How to pass brew options in the depexts field of an opam file?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#13078]
Hello,

I'd like to correct the conf-gnuplot package in the following way.
On mac OS X, we should say:
```
brew install gnuplot --with-qt
```
instead of the current
```
brew install gnuplot
```
because, the current state doesn't install a gnuplot which can create graphic windows right of the bat.
Which makes for a rather useless gnuplot being installed on mac by conf-gnuplot, currently.

Any idea on how to pass such options via the opam file depexts field?

Are there packages doing this already?

Thanks!
F.

**Comment by avsm** [comment]
Right now that's not supported, but could be an improvement to depext.
