### ISSUE TITLE
ackdo-reloaded installs into /usr/bin/

### ISSUE THREAD

**Issue by avsm** [ocaml/opam-repository#1311]
With a system compiler

```
# cp ackdo.native /usr/bin/ackdo
### stderr ###
# cp: cannot create regular file `/usr/bin/ackdo': Permission denied
# make: *** [opaminstall] Error 1
```

The OPAM package should direct it towards `%{bindir}%` instead.

Found as part of #1304 , /cc @rgrinberg as maintainer

**Comment by samoht** [comment]
This package doesn't exist anymore, so closing.
