### ISSUE TITLE
Is there any rules for maintainers to publish a library?

### ISSUE THREAD

**Issue by nekketsuuu** [ocaml/opam-repository#13439]
I would like to publish a package of our forked and **renamed** version of an existing open-source library. But I am worried if an approval of authors of the original library is necessary for publishing. Our library follows a license of the original library and ours has some updates which are difficult to merge, so it is fine to make our code public as a new open-source software whose authors are the original authors and us. Then how about publishing it as a new package?

It is good to tell our package to the original authors. We should thank their contributions. However I think the approval is not necessary.

But I haven't read a document saying such rules. Especially, [OPAM's manual for packaging](https://opam.ocaml.org/doc/Packaging.html#Publishing) doesn't. I searched for such a document like Code of Conduct, however I could not find one.

So my question is: Is there any document of rules for maintainers to publish a library, especially a forked library?

**Comment by avsm** [comment]
We deal with these issues on a case-by-case basis, as the right thing to do varies depending on the circumstances of the change.

Typically if there is a technical reason for a fork (e.g. an interface divergence or a licensing change), and there are maintainers for both forks, then opam-repository can accept both versions.  We would typically like both parties to have communicated and agreed on the need for a fork, but formal approval is not necessary.  The fork must have a distinct opam package name, and you need to be careful about naming to clearly distinguish it from the original to avoid confusion to users and any potential trademark or copyright issues with the original.

To proceed, it would be helpful to know more details about the specific library in question.

**Comment by nekketsuuu** [comment]
@avsm Thank you for your quick and easy-to-understand comment! I'll open another issue for the specific library (perhaps several days later).
