### ISSUE TITLE
Old ocaml-zmq package should be removed or deprecated

### ISSUE THREAD

**Issue by softmoth** [ocaml/opam-repository#13478]
The `Homepage` link on http://opam.ocaml.org/packages/ocaml-zmq/ is broken. It points to an old GitHub repo. But beyond that, the whole package is superseded by the `zmq` package. The `ocaml-zmq` package should ideally be removed, or else its description should begin with `DEPRECATED` or similar to alert users to not use it for new development.

Note that the `source` URL for this old `ocaml-zmq` points to a hard-coded older revision in the same github repo as the current `zmq` package. That is, `ocaml-zmq` is not a separate project that is being maintained, it is just a static old version.

**Comment by mseri** [comment]
Please send a PR that adds `[DEPRECATED in favour of zmq]` to the description or synopsys of the ocaml-zmq packages.
