### ISSUE TITLE
 ocamlfuse fails to compile on RPi

### ISSUE THREAD

**Issue by madlax72** [ocaml/opam-repository#13491]
Hello!

Having this issue on an RPi 3b with Fedora 29. 
```
[ERROR] The compilation of ocamlfuse failed at "/root/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlfuse -j 3".

#=== ERROR while compiling ocamlfuse.2.7.1-cvs6 ===============================#
# context     2.0.1 | linux/arm32 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org#7e911f4a
# path        ~/.opam/default/.opam-switch/build/ocamlfuse.2.7.1-cvs6
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlfuse -j 3
# exit-code   1
# env-file    ~/.opam/log/ocamlfuse-18416-c61e7b.env
# output-file ~/.opam/log/ocamlfuse-18416-c61e7b.out
### output ###
# [...]
# -> stderr:
# run: /usr/bin/pkg-config --cflags fuse
# -> process exited with code 0
# -> stdout:
#  | -I/usr/include/fuse -D_FILE_OFFSET_BITS=64
# -> stderr:
# run: /usr/bin/pkg-config --libs fuse
# -> process exited with code 0
# -> stdout:
#  | -lfuse -pthread
# -> stderr:
# Error: Could not query camlidl lib path



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocamlfuse 2.7.1-cvs6
└─
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    fuse-devel

fuse-devel  is installed

# rpm -qa | grep fuse-devel
fuse-devel-2.9.7-14.fc29.armv7hl

```
Thanks!

**Comment by avsm** [comment]
This should be reported to the upstream ocamlfuse repo... cc @astrada

**Comment by astrada** [comment]
That error is returned if this command:

    opam config var camlidl:lib

doesn't return 0 (see this [line](https://github.com/astrada/ocamlfuse/blob/master/lib/config/discover.ml#L19)).

**Comment by Tunglin-Inamin-TW** [comment]
It's ok, but when I install google-drive-ocamlfuse also show this like opam-repository issues#13491:

`<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocamlfuse failed at
        "/root/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlfuse
        -j 1".

#=== ERROR while compiling ocamlfuse.2.7.1-cvs6 ===============================#
# context     2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.0 | https://opam.ocaml.org#b878563b
# path        ~/.opam/4.07.0/.opam-switch/build/ocamlfuse.2.7.1-cvs6
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlfuse -j 1
# exit-code   1
# env-file    ~/.opam/log/ocamlfuse-3690-c61e7b.env
# output-file ~/.opam/log/ocamlfuse-3690-c61e7b.out
### output ###
# [...]
# -> stderr:
# run: /usr/bin/pkg-config --cflags fuse
# -> process exited with code 0
# -> stdout:
#  | -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse
# -> stderr:
# run: /usr/bin/pkg-config --libs fuse
# -> process exited with code 0
# -> stdout:
#  | -pthread -lfuse
# -> stderr:
# Error: Could not query camlidl lib path
`

and use "opam config var camlidl:lib" show this:
`/root/.opam/4.07.0/lib/camlidl`
