### ISSUE TITLE
Newer bytecode-only variants?

### ISSUE THREAD

**Issue by Niols** [ocaml/opam-repository#13581]
The last bytecode-only variant I could find is `4.04.2+bytecode-only`. I find it useful to have them, at least for my CI, and I would need newer version.

Is there a profound reason why it stopped there? Or are we just relying on people adding these variants (like in #8603) in which case I could do that?

**Comment by avsm** [comment]
Indeed, please go ahead and submit one.

**Comment by Niols** [comment]
Here we go: #13824
