### ISSUE TITLE
opam install conf-gtksourceview.2 failed on Mac OS

### ISSUE THREAD

**Issue by elhaddadyacine** [ocaml/opam-repository#13709]
Hi,
In order to install `why3-ide` with `opam`, I need to install both `gtksourceview` and `libxml2` where are already installed as brew shows here : 
```
brew install gtksourceview libxml2
Warning: gtksourceview 2.10.5_3 is already installed and up-to-date
To reinstall 2.10.5_3, run `brew reinstall gtksourceview`
Warning: libxml2 2.9.9_2 is already installed and up-to-date
To reinstall 2.9.9_2, run `brew reinstall libxml2`
```  
but when I run :
```bash
opam install why3-ide
```
I got this error message :
```
<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build conf-gtksourceview 2
└─ 
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please
make sure they are installed before retrying:
    gtksourceview libxml2
```
Is it related to my version of Mac OS which is `macOS Mojave version 10.14.3 (18D109)` or something else?

**Comment by mseri** [comment]
`libxml2` and `gtksourceview` may need a custom `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/path/to/libxml2/pkgconfig` or some other custom flag, to point the compiler to the right set of libraries. I am not sure about gtksourceview itself, but libxml2 is definitely not linked (to avoid conflicsts, as a different version is provided by osx)

**Comment by elhaddadyacine** [comment]
Thanks for your help,
It's fixed with
```bash
export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/
```

**Comment by Chris00** [comment]
A path that does not depend on the version is `PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig`.
