### ISSUE TITLE
conf-dbm

### ISSUE THREAD

**Issue by jteg68** [ocaml/opam-repository#13775]
conf-dbm version 1.0.0 always want's to recompile when doing 'opam upgrade', with cause being 'upstream changes'. This happens even when doing the two 'opam upgrade' immediately after each other.

opam --version is 2.0.3

/Jörgen

**Comment by kit-ty-kate** [comment]
Issue moved to https://github.com/ocaml/opam-repository/issues/16308. Closing this one.
