### ISSUE TITLE
conf-m4.1 fails to install on Linux for Windows

### ISSUE THREAD

**Issue by jfehrle** [ocaml/opam-repository#13858]
I'm running Ubuntu 18.04 on Linux for Windows.

I was trying to install Coq.

My first attempt produced this error:

```
#=== ERROR while compiling ocaml-base-compiler.4.02.3 =========================#
# context     2.0.2 | linux/x86_64 |  | https://opam.ocaml.org#137aeeea
# path        ~/opam-coq.8.9.0/ocaml-base-compiler.4.02.3/.opam-switch/build/ocaml-base-compiler.4.02.3
# command     ~/opam-coq.8.9.0/opam-init/hooks/sandbox.sh build ./configure -prefix /home/jfehrle/opam-coq.8.9.0/ocaml-base-compiler.4.02.3 -with-debug-runtime
# exit-code   1
# env-file    /tmp/opam-xxx-11509/ocaml-base-compiler-11509-f0f09f.env
# output-file /tmp/opam-xxx-11509/ocaml-base-compiler-11509-f0f09f.out
### output ###
# bwrap: Creating new namespace failed, likely because the kernel does not support user namespaces.  bwrap must be installed setuid on such systems.
```

After `chmod u+s` on `bwrap`, I get this failure:

```
$ opam install conf-m4.1
The following actions will be performed:
  ∗ install conf-m4 1

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of conf-m4 failed at "/home/jfehrle/opam-coq.8.9.0/opam-init/hooks/sandbox.sh build sh -exc echo
        | m4".

#=== ERROR while compiling conf-m4.1 ==========================================#
# context     2.0.2 | linux/x86_64 |  | https://opam.ocaml.org#137aeeea
# path        ~/opam-coq.8.9.0/ocaml-base-compiler.4.02.3/.opam-switch/build/conf-m4.1
# command     ~/opam-coq.8.9.0/opam-init/hooks/sandbox.sh build sh -exc echo | m4
# exit-code   1
# env-file    ~/opam-coq.8.9.0/log/conf-m4-12083-ccabea.env
# output-file ~/opam-coq.8.9.0/log/conf-m4-12083-ccabea.out
### output ###
# bwrap: Creating new namespace failed: Invalid argument



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build conf-m4 1
└─
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please make sure they are installed before
retrying:
    m4

$
```

No idea what options are being passed to `bwrap`.  `m4` is available from the bash command line.

Any ideas what's wrong or how to work around?  Thanks.

**Comment by jfehrle** [comment]
I had the clever idea of replacing the `bwrap` executable with `echo`, incorrectly thinking that that would show me the arguments passed to `bwrap`.  It doesn't actually show the arguments because `echo` doesn't fail.  But it did make OPAM think that the installation of `conf-m4.1` succeeded (correctly or incorrectly, I don't know).  After restoring `bwrap`, I tried the installation again out of curiousity.  Now I see the `Creating new namespace failed: Invalid argument` error while compiling 2 other modules: `ocamlfind.1.8.0` and `camlp5.7.06.10-g84ce6cc4`.  This suggests to me that the problem might be in OPAM itself.

**Comment by gasche** [comment]
Have you tried to see if `opam init --disable-sandboxing` gets you further?

**Comment by jfehrle** [comment]
Thanks, I'll see if that makes a difference.  (In the meantime, I built camlp5 and coq directly, which gave me a working Coq.)

**Comment by dra27** [comment]
This is neither opam nor opam-repository at fault - see https://github.com/ocaml/opam/issues/3505

`echo` "worked" because it returned a non-error exit-code from the wrapper script...

**Comment by Jmw150** [comment]
A year later and this problem still exists. Thanks...

**Comment by dra27** [comment]
@Jmw150 - which problem?

**Comment by Jmw150** [comment]
"conf-m4.1 fails to install on Linux for Windows #13858"

opam still can't find m4 on the system

**Comment by dra27** [comment]
Well, have you installed `m4`? `bwrap` continues not to work in WSL1, which isn't exactly something either `opam` or `opam-repository` can alter.

**Comment by Jmw150** [comment]
Wsl 2 is a Linux kernel and it passes most software tests outside of IO. Both are installed.

**Comment by geoangelotti** [comment]
This error tiggered when I had only `bwrap` installed on WSL2.
Installing `m4` fixes it.
