### ISSUE TITLE
cloning ocaml-repository with --branch 2.0.0 fails ....

### ISSUE THREAD

**Issue by progman1** [ocaml/opam-repository#13951]
in following the instructions at
https://opam.ocaml.org/doc/Packaging.html
when performing
git clone git@github.com:USER/opam-repository --branch 2.0.0
I get the error
"fatal: Remote branch 2.0.0 not found in upstream origin"

indeed upon following the 'release' and 'branches'  links on the ocaml-repository page
I see version 1.2.0 and prior but no mention of 2.0.0.

what am I doing wrong?

**Comment by progman1** [comment]
With USER duly changed to progman1 of course...

**Comment by hannesm** [comment]
@progman1 since September 2018, the master branch of opam-repository is in opam 2.0.0 format (according to [this announcement](https://opam.ocaml.org/blog/opam-2-0-0/)). Thus, a `git clone git@github.com:ocaml/opam-repository` should be all that is needed.
