### ISSUE TITLE
stalled opam index

### ISSUE THREAD

**Issue by xaki23** [ocaml/opam-repository#13962]
opam index updates seem to have been stalled for several days now.

right now (2019-04-15), fetching https://opam.ocaml.org/index.tar.gz gives me a file from 2019-04-12 that does not contain the last 30-40 commits to this repo.

the last/newest one i can find in there is https://github.com/ocaml/opam-repository/commit/5b9162fe5d249c1f5659e916d924cd291c555fbd
the first/oldest one that is missing is https://github.com/ocaml/opam-repository/commit/9d5403cca3fd1a0f51dcd274da92ddc93c221a05

not sure this is related, but i noticed ... 
this first-missing has a travis-ci fail complaining that the downloaded https://github.com/abeaumont/ocaml-pbkdf/releases/download/1.0.0/pbkdf-1.0.0.tbz doesnt have the expected checksum. (and yes, it doesnt)

**Comment by xaki23** [comment]
xref to the pr that made me "find" this https://github.com/mirage/mirage-nat/pull/26
and a ping for @hannesm

**Comment by rjbou** [comment]
There was an error on the job generating the website & the repository (cf. [opam2web issue](https://github.com/ocaml/opam2web/pull/170) for more details). It is fixed now, http repository will be updated in few hours.

Note that you can also add the git repository as a remote to not be stuck on those cases with
```
opam repo add <name-e.g-git-default> git+https://github.com/ocaml/opam-repository
```

Thanks for reporting!

**Comment by xaki23** [comment]
thanks for the fix, the link to the cause, and the workaround.
i can confirm that the index is updated now and this resolves the problem i had with dune.
(which i had worked around by pinning down dune to a working version)

closing this as resolved.
