### ISSUE TITLE
Where are the opam switches for ocaml 4.08 and 4.09 ?

### ISSUE THREAD

**Issue by jhjourdan** [ocaml/opam-repository#14145]
It seems like it is impossible to create a switch for ocaml >= 4.08.0, because the ocaml-base-compiler pseudo-packages have not been created.

At the very least, the command:

```
opam switch create . ocaml-base-compiler.4.09.0
```

fails, and I don't see any other way to create a switch on a (non-variant) released version of ocaml >= 4.08.

**Comment by mseri** [comment]
I think you need this: https://github.com/ocaml/ocaml-beta-repository

**Comment by jhjourdan** [comment]
Ah, indeed. Sorry for the noise !
