### ISSUE TITLE
opam add repository failing with error curl: code 404 while downloading in amd64 linux 

### ISSUE THREAD

**Issue by ossdev07** [ocaml/opam-repository#14217]
Dear Team,

Working with opam in x86_64 linux. opam version is 1.2.2 and opam init is working properly.

**Facing below issue with opam add repository command:**

opam repository add arm https://github.com/ossdev07/opam-cross-arm
[ERROR] curl: code 404 while downloading https://github.com/ossdev07/opam-cross-arm/urls.txt
[ERROR] Could not fetch repo

Do we need to install any specific dependencies? If any please suggest.

**Comment by mseri** [comment]
I think you are using the wrong url. Try with `git://github.com/ossdev07/opam-cross-arm` or `https+git://github.com/ossdev07/opam-cross-arm`. Also, looks like the repo has moved to opam 2, you may need to update that as well

**Comment by ossdev07** [comment]
@mseri Thanks for the reply. I have updated i was getting curl download failed while downloading https://github.com/ossdev07/opam-cross-arm/index.tar.gz. Updated url and it is working now.
