### ISSUE TITLE
Fails to compile with opam install cairo2

### ISSUE THREAD

**Issue by RBornat** [ocaml/opam-repository#14250]
Seems to require /usr/include/cairo.h, while brew installs /usr/local/include/cairo.h .

#=== ERROR while compiling cairo2.0.6 =========================================#
# context     2.0.4 | macos/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org/#c7c0bde9
# path        ~/.opam/4.07.1/.opam-switch/build/cairo2.0.6
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p cairo2 -j 3
# exit-code   1
# env-file    ~/.opam/log/cairo2-85403-e7966f.env
# output-file ~/.opam/log/cairo2-85403-e7966f.out
### output ###
# compiling c program:
# [...]
#  | };
#  | 
# run: cc -O2 -fno-strict-aliasing -fwrapv  -I/usr/include/cairo -I /Users/richard/.opam/4.07.1/lib/ocaml -o /var/folders/sb/gdj8vfrw8xjbfw0059bcnd6h0000gn/T/ocaml-configuratore157a5/c-test-3/test.o -c /var/folders/sb/gdj8vfrw8xjbfw0059bcnd6h0000gn/T/ocaml-configuratore157a5/c-test-3/test.c
# -> process exited with code 1
# -> stdout:
# -> stderr:
#  | /var/folders/sb/gdj8vfrw8xjbfw0059bcnd6h0000gn/T/ocaml-configuratore157a5/c-test-3/test.c:2:10: fatal error: 'cairo.h' file not found
#  | #include <cairo.h>
#  |          ^~~~~~~~~
#  | 1 error generated.
# Error: failed to compile program

**Comment by mseri** [comment]
Strange, you should also see the following message:   

    Try to re-run the install command with PKG_CONFIG_PATH pointing a pkg-config path including libffi, e.g. if you use homebrew you can try PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig

**Comment by mseri** [comment]
Can you try and see if following that does help?

**Comment by RBornat** [comment]
I did try it ... no effect. Why not /usr/local/include, where I do have a cairo.h?

Richard

> Richard-Bornats-MacAir:include richard$ PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
> Richard-Bornats-MacAir:include richard$ echo $PKG_CONFIG_PATH
> /usr/local/opt/libffi/lib/pkgconfig
> Richard-Bornats-MacAir:include richard$ opam install cairo2
...
# run: cc -O2 -fno-strict-aliasing -fwrapv  -I/usr/include/cairo -I /Users/richard/.opam/4.07.1/lib/ocaml -o /var/folders/sb/gdj8vfrw8xjbfw0059bcnd6h0000gn/T/ocaml-configuratorb8ded3/c-test-3/test.o -c /var/folders/sb/gdj8vfrw8xjbfw0059bcnd6h0000gn/T/ocaml-configuratorb8ded3/c-test-3/test.c
# -> process exited with code 1
# -> stdout:
# -> stderr:
#  | /var/folders/sb/gdj8vfrw8xjbfw0059bcnd6h0000gn/T/ocaml-configuratorb8ded3/c-test-3/test.c:2:10: fatal error: 'cairo.h' file not found
#  | #include <cairo.h>
#  |          ^~~~~~~~~
#  | 1 error generated.
# Error: failed to compile program

also

> Richard-Bornats-MacAir:include richard$ ls /usr/local/opt/libffi/lib/pkgconfig/
> libffi.pc

**Comment by RBornat** [comment]
I write to apologise. Your error message did explain what to do, but I use bash so rarely nowadays that I didn't understand it. Of course I had to write 

	PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig opam install cairo2

-- and that worked.

I do still have a problem, but it may not be your fault. To do with downgrading archimedes and cairo2 (jupyter-archimedes requires that). Doesn't work unless I first uninstall archimedes, install cairo0.5, and then install archimedes.0.4.18. Perhaps an opam glitch.

So sorry if you spent any time chasing my 'issue'. Do I close it, or do you?

Richard
