### ISSUE TITLE
-static switch: undefined reference to `secure_getenv'

### ISSUE THREAD

**Issue by copy** [ocaml/opam-repository#14318]
Compiling a program on a `4.08.0+musl+static+flambda` with `-ccopt -static -cc musl-gcc` fails:

```
(cd _build/default && ~/.opam/4.08.0+musl+static+flambda/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -ccopt -static -cc musl-gcc -g -o ping2.exe .ping2.eobjs/native/ping2.cmx)
/usr/bin/ld: ~/.opam/4.08.0+musl+static+flambda/lib/ocaml/libasmrun.a(unix_n.o): in function `caml_secure_getenv':
~/.opam/4.08.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.08.0+musl+static+flambda/runtime/unix.c:414: undefined reference to `secure_getenv'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
```

musl doesn't have `secure_getenv`, and I believe this case is handled by OCaml, so something must be going wrong while this switch is being configured.

**Comment by etanol** [comment]
Try the following:

1. Enable the switch you are using of the *musl+static* variant: `eval $(opam env)`
1. Get the source of the `ocaml-variants` package and pin it: `opam source --pin ocaml-variants.4.08.0+musl+static+flambda`
    - Don't build it yet
1. Go to the created directory: `cd ocaml-variants.4.08.0+musl+static+flambda`
1. Edit the `ocaml-variants.opam` file
    - Look for the `build` section and see if the call to `configure` looks like this:
      ```
      ["./configure" "--prefix=%{prefix}%"]
      ```
    - Replace it with the following:
      ```
      [
        "./configure"
        "--prefix=%{prefix}%"
        "CC=musl-gcc -Os"
        "ASPP=musl-gcc -c"
        "--enable-flambda"
        "LIBS=-static"
        "--disable-graph-lib"
        "--disable-shared"
      ]
      ```
1. Build it: `opam install .`
    - Don't worry about the version *downgrade*
1. Compile your program again
    - Note that you should **not** need `-cc musl-gcc`

**Comment by copy** [comment]
@etanol That fixed the problem, cheers!

**Comment by copy** [comment]
@etanol Testing this image a bit more, it seems to break ppx_deriving, which uses [Dynlink](https://github.com/ocaml-ppx/ppx_deriving/blob/3ef3739f8a9a177e147b5bb0a777f7531aeafd7c/src/ppx_deriving_main.cppo.ml#L11) at compile time (but not in the generated binary). Do you think we should remove the `--disable-shared` flag?

**Comment by etanol** [comment]
I'll try to build it that way and see what happens.
