### ISSUE TITLE
Trouble with "opam install frama-c"

### ISSUE THREAD

**Issue by jberner1997** [ocaml/opam-repository#14314]
Hi, 

I am having trouble installing Frama-c. 

I am on Windows.  I have installed Cygwin and I have installed Opam. 

I have run "opam install depext" and "opam depext frama-c"" and they both looked like they worked. 

When I run "opam install frama-c" I get this error message. Can you please advise me?

![image](https://user-images.githubusercontent.com/44206333/59712026-523ae400-91da-11e9-8aab-85befca824e0.png)

This is the config report. The version doesn't match the switch but I can't figure out how to match it. 
![image](https://user-images.githubusercontent.com/44206333/59712276-e86f0a00-91da-11e9-8777-5d5d7ca73d9e.png)

Thank you

**Comment by mseri** [comment]
It seems that curl had problem connecting to http://download.camlcity.org/download/findlib-1.8.0.tar.gz to download the latest curl. Can you try again, the link seems to work from my network.

**Comment by jberner1997** [comment]
@mseri Thank you very much for your reply. 

I tried again this morning and it seems to be failing again. Is there anything you know of that would be causing this if the url works from your network but seems not to from mine? 

Do you know if there is a way for me to manually install the sources that failed? so I can proceed to install frama-c??

**Comment by mseri** [comment]
I sincerely don't know. I have just installed it in my machine without problems. You can try `opam update` to make sure that everything is up to date, and `opam source alt-ergo` or `opam source ocamlfind` to check that you can actually download those files.

Do you have firewall rules or proxies that may block the access to the relative websites?

**Comment by jberner1997** [comment]
Thank you very much for your attention on this issue I've been having. I think I will start looking for alternative solutions to my needs. Thanks again
