### ISSUE TITLE
 The certificate of ‘opam.ocaml.org’ is not trusted and hasn't got a known issuer.

### ISSUE THREAD

**Issue by freyamehta99** [ocaml/opam-repository#14320]
root@md1ua0qc:~# wget https://opam.ocaml.org/1.2.2/archives/camlidl.1.05+opam.tar.gz
--2019-06-20 11:34:09--  https://opam.ocaml.org/1.2.2/archives/camlidl.1.05+opam.tar.gz
Resolving opam.ocaml.org (opam.ocaml.org)... 192.237.250.17, 2001:4801:7823:76:bb74:1f8e:ff10:627
Connecting to opam.ocaml.org (opam.ocaml.org)|192.237.250.17|:443... connected.
ERROR: The certificate of ‘opam.ocaml.org’ is not trusted.
ERROR: The certificate of ‘opam.ocaml.org’ hasn't got a known issuer.

Packages are not getting installed due to this issue. I need to install gmp package from opam but camlidl is a dependency which I am facing issues installing.

**Comment by pmetzger** [comment]
So I'm not having this problem:

```
$ wget https://opam.ocaml.org/1.2.2/archives/camlidl.1.05+opam.tar.gz
--2019-06-20 14:04:05--  https://opam.ocaml.org/1.2.2/archives/camlidl.1.05+opam.tar.gz
Resolving opam.ocaml.org (opam.ocaml.org)... 192.237.250.17
Connecting to opam.ocaml.org (opam.ocaml.org)|192.237.250.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 105805 (103K) [application/octet-stream]
Saving to: 'camlidl.1.05+opam.tar.gz'

camlidl.1.05+opam.t 100%[===================>] 103.33K  --.-KB/s    in 0.1s    

2019-06-20 14:04:05 (745 KB/s) - 'camlidl.1.05+opam.tar.gz' saved [105805/105805]
```

Is it possible that you have a bad certificate store on your machine?
