### ISSUE TITLE
Deprecate ulex in favor of ulex-campl5

### ISSUE THREAD

**Issue by XVilka** [ocaml/opam-repository#14344]
Because original ulex is abandoned, will never be updated it seems, and will not build with OCaml 4.08, because it depends on campl4, which is [not supporting 4.08](https://github.com/ocaml/camlp4/issues/151) either. Moreover, seems that [ulex-campl5](https://github.com/ocaml/opam-repository/tree/master/packages/ulex-camlp5) is a drop-in replacement for ulex, so shouldn't cause any issues.

See ulex [original](https://github.com/whitequark/ulex) repository, and ulex-campl5 [fork](https://github.com/sacerdot/ulex/tree/ulex-camlp5).

**Comment by pmetzger** [comment]
What still depends on ulex?

**Comment by XVilka** [comment]
@pmetzger: piqi and piqilib, I am working on making BAP work on OCaml 4.08, and those are dependencies.

**Comment by XVilka** [comment]
See the whole list at [opam site](https://opam.ocaml.org/packages/ulex/):
```
    beluga
    ccss<1.6
    cduce
    cow<2.0.0
    frenetic>=3.2.0 & <5.0.0
    fstar>=0.9.5.0
    higlo
    kremlin
    lambdoc
    mezzo
    opa-base
    piqi<0.7.0
    piqilib
    pxp
    rdf>=0.5 & <0.10.0
    sociaml-vcard
    wdialog
```

**Comment by XVilka** [comment]
Focusing on porting to sedlex instead.
