### ISSUE TITLE
conf-gmp fails to build with Macports

### ISSUE THREAD

**Issue by mebsout** [ocaml/opam-repository#1464]
When building conf-gmp "cc -c test.c" clang does not find gmp installed with Macports (this is under OS X 10.9). Maybe a solution is to provide a configure script which recognizes and uses LDFLAGS and CPPFLAGS (or use gcc).

-- Alain

**Comment by dbuenzli** [comment]
Closing in favour of the more recent #9389, the same issue with slightly more precise information.
