### ISSUE TITLE
No maintainer for `wyrd` package - port off camlp4

### ISSUE THREAD

**Issue by XVilka** [ocaml/opam-repository#14697]
`wyrd` currently depends on camlp4, but the release for OCaml 4.08 is the last release ever - see the official announcement. It is recommended to port the code to use ppx (extension points), or any external parser (like mehrir, sedlex, ocamllex, ansgtrom, etc). Opening an issue here since no external maintainer or repository information available: https://github.com/ocaml/opam-repository/blob/master/packages/wyrd/wyrd.1.4.6/opam

**Comment by pmetzger** [comment]
The fact that the distfile is coming from the NetBSD pkgsrc mirror would seem to indicate it's very very dead.
