### ISSUE TITLE
Metaocaml installation Unbound module Typedtree (4.07.1+BER)

### ISSUE THREAD

**Issue by fib1d** [ocaml/opam-repository#14699]
Hi @yallop,
creating a switch for 4.07.1+BER fails on my (quite clean) Fedora 29 installation with 
```
# File "trx.mli", line 14, characters 25-45:
# Error: Unbound module Typedtree
```

I have confirmed that there is no distribution ocaml installed, but opam was installed from the distributions package.
It appears that the module `Typedtree` in `ocaml-variants.4.07.1+BER/ocamldoc/stdlib_non_prefixed` is not compiled before use (it compiles correctly) and causes a subsquent failure of the overall installation.

Please find attached the logs.
[ocaml-variants-1354-d2c37b.env.txt](https://github.com/ocaml/opam-repository/files/3515790/ocaml-variants-1354-d2c37b.env.txt)
[ocaml-variants-1354-d2c37b.out.log](https://github.com/ocaml/opam-repository/files/3515791/ocaml-variants-1354-d2c37b.out.log)

Looking forward to using metaocaml :)
Marc

**Comment by yallop** [comment]
Thanks for the report, @fib1d.

I've tried to reproduce this using Docker, but the following set of commands (i.e. starting with a Fedora 29 base, installing `opam` via `yum`, then creating a `4.07.1+BER` switch) successfully installs MetaOCaml:

```dockerfile
FROM fedora:29
RUN yes | yum update
RUN yes | yum install opam
RUN opam init --yes --disable-sandboxing
RUN opam switch create --verbose 4.07.1+BER
```

I wonder if there's something wrong with the dependencies in the MetaOCaml patch that causes the build to fail on some systems.

**Comment by fib1d** [comment]
Hi yallop,
thanks for checking, I can confirm that it works in the docker container. But I'm unable to find the issue with my system configuration (it was set up fresh for the workshop and now I cannot reproduce it).
I'll try to use the docker container to go through the exercises.

Thank you very much!
Marc

**Comment by masahi** [comment]
Hi @fib1d, I've also met this error when trying to install BER 407 on a fresh ubuntu system. I've installed Metaocaml many times on different envs, but this error never happened to me.

Have you found a solution?

**Comment by fib1d** [comment]
Hi @masahi,
I was never able to find the reason for it and just continued to use containers and another VM, sorry :/
