### ISSUE TITLE
Cannot install lablgtk on MacOS + homebrew

### ISSUE THREAD

**Issue by dogfishbar** [ocaml/opam-repository#14718]
I had posted essentially the following on #4282 which was closed. I am reposting it as a new issue because the changes to PKG_CONFIG_PATH advised in #4282 did not work for my system.

--------------------
I am unable to opam install lablgtk on MacOS 10.14.5 with homebrew. 

```
rm:~\> # MacOS Mojave 10.14.5
rm:~\> brew --version
Homebrew 2.1.9
Homebrew/homebrew-core (git revision c9f34; last commit 2019-08-02)
Homebrew/homebrew-cask (git revision 2e02d; last commit 2019-08-02)

rm:~\> brew list | grep gtk
gtk+
rm:~\> brew list | grep expat
expat
rm:~\> ls /usr/local/Cellar/expat/2.2.7/lib/pkgconfig/
expat.pc
rm:~\> echo $PKG_CONFIG_PATH
/opt/X11/lib/pkgconfig/
rm:~\> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/Cellar/expat/2.2.7/lib/pkgconfig/
rm:~\> pkg-config --modversion expat
2.2.7
rm:~\> ls /usr/local/Cellar/gtk+/2.24.32_3/lib/pkgconfig/
gail.pc                 gdk-quartz-2.0.pc       gtk+-quartz-2.0.pc
gdk-2.0.pc              gtk+-2.0.pc             gtk+-unix-print-2.0.pc
rm:~\> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/Cellar/gtk+/2.24.32_3/lib/pkgconfig/
rm:~\> pkg-config --modversion gtk+-2.0
2.24.32

rm:~\> opam depext lablgtk
# Detecting depexts using vars: arch=x86_64, os=macos, os-distribution=homebrew, os-family=homebrew
# The following system packages are needed:
expat
gtk
# The following new OS packages need to be installed: gtk
Updating Homebrew...
Warning: gtk+ 2.24.32_3 is already installed and up-to-date
To reinstall 2.24.32_3, run `brew reinstall gtk+`
# OS packages installation successful

rm:~\> opam install lablgtk
The following actions will be performed:
  ∗ install lablgtk 2.18.8

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[lablgtk.2.18.8] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of lablgtk failed at "/Users/muller/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix
        /Users/muller/.opam/default LABLGLDIR=/Users/muller/.opam/default/lib/lablgl".

#=== ERROR while compiling lablgtk.2.18.8 =====================================#
# context     2.0.5 | macos/x86_64 | ocaml-base-compiler.4.08.0 | https://opam.ocaml.org#8355f6b0
# path        ~/.opam/default/.opam-switch/build/lablgtk.2.18.8
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix /Users/muller/.opam/default LABLGLDIR=/Users/muller/.opam/default/lib/lablgl
# exit-code   1
# env-file    ~/.opam/log/lablgtk-45226-c743ac.env
# output-file ~/.opam/log/lablgtk-45226-c743ac.out
### output ###
# [...]
# checking for suffix of object files... o
# checking whether we are using the GNU C compiler... yes
# checking whether cc accepts -g... yes
# checking for cc option to accept ISO C89... none needed
# checking whether C compiler accepts -fno-unwind-tables... yes
# checking platform... Unix
# checking native dynlink... checking for pkg-config... /usr/local/bin/pkg-config
# checking for GTK+ - version >= 2.0.0... no
# *** Could not run GTK+ test program, checking why...
# *** The test program failed to compile or link. See the file config.log for the
# *** exact error that occured. This usually means GTK+ is incorrectly installed.
# configure: error: GTK+ is required



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build lablgtk 2.18.8
└─ 
╶─ No changes have been performed

<><> lablgtk.2.18.8 troubleshooting <><><><><><><><><><><><><><><><><><><><>  🐫 
=> This package requires gtk+ 2.0 development packages installed on your system
=> To solve pkg-config issues, you may need to do
   'export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig' and retry

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    expat gtk

rm:~\>
```

**Comment by beurdouche** [comment]
Hello, I have the exact same problem and can reproduce with all these exact versions...
No idea how to solve it at the moment.

**Comment by crherlihy** [comment]
Same here.

**Comment by dogfishbar** [comment]
Hello. I also had this problem in attempting to prepare materials for an intro CS course that I teach in OCaml. It has been a bit of a disaster, I'm sorry to say, and students generally seem to have a negative view of OCaml because of it.

I'm sorry to say that I didn't write down all of the details so I can't give you precise steps on how to go forward. Essentially there are problems with 1. newer releases of MacOS, 2. homebrew and 3. lablgtk. In particular, a fair amount of ceremony was required to get the libraries to compile.  This involved a lot of misleading error messages and dependency tracking (and hackery). I can't guarantee it, but my notes show that I was building a search path for pkgconfig along the lines of:

`/usr/local/opt/gtk/lib/pkgconfig:/usr/local/opt/gtk+/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/gdk-pixbuf/lib/pkgconfig:/usr/local/opt/atk/lib/pkgconfig:/opt/X11/lib/pkgconfig/`

Once I got lablgtk to compile, I hit the wall. When I would run any program that attempted to change a graphical image I would get (many reports of) the following harmless warning:

`2019-11-20 00:09:34.909 go[63460:840679] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. `

But my program would also crash with the error:

`Assertion failed: (!x_link_empty_p(&s->stack)), function CGGStackRestore, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreGraphics/CoreGraphics-1348.12.4.3/CoreGraphics/Context/CGGStack.c, line 74.
Abort trap: 6`

This seems to be a problem with the more recent releases of MacOS. As a workaround. I've had to require my students to install a virtual box VM running Ubuntu, we run OCaml with lablgtk on that. It's really pretty awful and, as I say, most of my students think OCaml is sort of hideous, notwithstanding my claims otherwise.

It's really unfortunate. But lablgtk does not work on a Mac.

Good luck.
Bob Muller

**Comment by mseri** [comment]
@dogfishbar @beurdouche I have reported this thread in an issue on the lablgtk repository https://github.com/garrigue/lablgtk

From what I can see there is a new version in preparation with support for Gtk2 and 3, and I am sure they will take also these issues into account. Hopefully soon it will work again on osx.

**Comment by ejgallego** [comment]
Indeed the `lablgtk3` package does use a different build system and so far we are doing OK in OSX, @dogfishbar how does `lablgtk3` work for you?

**Comment by dogfishbar** [comment]
I haven't tried it but I'll take a look and let you know.
Thanks,
Bob

**Comment by garrigue** [comment]
As a side remark, I'm developing lablgtk2 and lablgtk3 on a MacOS machine, and so there should be no OS level problem. However, I'm using MacPorts rather than homebrew. Overall, MacPorts seems to have a better handling of developer needs.

**Comment by giltho** [comment]
This seems to have not been fixed yet :(

**Comment by avsm** [comment]
From an opam-repository perspective, if Homebrew is known-broken here, and MacPorts is recommended by @garrigue, we have two options:

- mark this package as unavailable on Homebrew, to prevent broken installations.
- fix the problem on Homebrew. 

If someone can step up to identify the root cause and whether lablgtk2 _vs_ 3 work, that would be useful to progress with fixing it. If there's no progress the next time I look at this issue, I'll submit the `unavailable` fix to opam-repository.

**Comment by giltho** [comment]
I'm investigating right now, but this is definitely not my area of expertise so I can't promise anything.
@avsm the ./configure step fails and says
```
# checking for GTK+ - version >= 2.0.0... no
# *** Could not run GTK+ test program, checking why...
# *** The test program failed to compile or link. See the file config.log for the
# *** exact error that occured. This usually means GTK+ is incorrectly installed.
# configure: error: GTK+ is required
```
Is there a way to access this `config.log` file that is generated at compile time or does opam wipe it when build fails ?

**Comment by avsm** [comment]
Thanks @giltho. You can set

```
       -b, --keep-build-dir
           Keep the build directories after compiling packages. This is
           equivalent to setting $OPAMKEEPBUILDDIR to "true".
```

and find it in `~/.opam`.

But the easiest way to debug is to install the dependencies, run `opam source PKG` and work on the source tree directly. opam is essentially a very fancy shell script executor :-)

**Comment by giltho** [comment]
So I solved it :) But it looks like it's missing a dependency or something.

The `configure` script tried to build a test program getting the include flags by running pkg-config, but the final command was
```
cc -o conftest -g -O2   conftest.c
```
without any include flags.

I tried running it by hand
```
 pkg-config gtk+-2.0 --cflags pkg-config gtk+-2.0 --libs
```
I lost the exact message but it was basically saying that it was missing `zlib` and that `zlib.pc`  should be somewhere in the `PKG_CONFIG_PATH`

I tried
```
brew install zlib
export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig
opam install lablgtk
```
and it worked :)

I don't really know if the fix is simply adding a message to the build failure, adding conf-zlib as a dependency ?

**Comment by garrigue** [comment]
The problem seems indeed to be that home-brew install pkg-config files in various locations, without an easy way to collect the paths. The problem is homebrew specific, so it is strange that lablgtk would have to specifically add dependencies for that. Isn't there a way to solve the problem globally at the opam level, by modifying conf-pkg-config for instance?
