### ISSUE TITLE
404 on opam update

### ISSUE THREAD

**Issue by jberdine** [ocaml/opam-repository#14747]
I'm not sure if this is the right place to mention this, but I'm seeing 404 errors when running opam update (with opam 2.0.4 and 2.0.5, but not 2.0.1). Maybe a redirect isn't working? I see the following command 404:
```
curl "--write-out" "%{http_code}\\n" "--retry" "3" "--retry-delay" "2" "--user-agent" "opam/2.0.5" "-L" "https://github.com/ocaml/opam-repository/index.tar.gz"
```
Just me?

**Comment by jberdine** [comment]
I'm not sure what is supposed to work, but the 404 errors are resolved by executing
```
opam repo set-url default https://opam.ocaml.org
```
Previously I had `https://github.com/ocaml/opam-repository` as the repo url, which used to work, perhaps by mistake/chance.

**Comment by avsm** [comment]
The latter should work as well. Could you try `opam repo set-url default git://github.com/ocaml/opam-repository` to see if that helps?

**Comment by jberdine** [comment]
Yes, `git:` also works.

**Comment by avsm** [comment]
So what's happening here is that `opam` is assuming you want the http format repository (which downloads an archive file and the packages directly via http/s).   You can either specify `-k git` and `https://`, or just use `git://` or `git+https://github.com/<...>`

**Comment by jberdine** [comment]
Ok, thanks for the info, and sorry for the bother. I wonder how I got myself into this state. :-/

**Comment by avsm** [comment]
I'm curious how it ever worked before (or did I misunderstand, and it never worked?). This is confusing behaviour from the opam CLI though due to the autodetection -- worth an issue on ocaml/opam to somehow warn against it.

**Comment by jberdine** [comment]
I'm not aware of having changed anything lately, so it seems to have worked before. It has been a few weeks since I updated opam, but prior to that it worked reliably.
