### ISSUE TITLE
32-bit switch for ARM

### ISSUE THREAD

**Issue by copy** [ocaml/opam-repository#14804]
I have an ARM device that is arm64 (`uname -m` reports aarch64) but only comes with a 32-bit loader (`/lib/ld-linux-armhf.so.3`) and all programs are compiled for 32-bit. A regular switch fails here, but a 32-bit switch would work. There are already +32bit variants of the regular OCaml switches, but they seem to be i386-specific. Maybe they could be made to work on ARM, too.

**Comment by avsm** [comment]
You can run [`setarch`](http://man7.org/linux/man-pages/man8/setarch.8.html) in this case to change the kernel personality into a 32-bit mode, so that the OCaml configure script just works?

**Comment by copy** [comment]
That works, cheers. Indeed it looks like an opam-specific solution is not necessary here, so I'll close this.

**Comment by mseri** [comment]
Should document this somewhere as a corner case?
