### ISSUE TITLE
Packages have depext with os-distribution = "debian" but not os-family

### ISSUE THREAD

**Issue by thomasblanc** [ocaml/opam-repository#14906]
A lot of packages have external dependencies configured for Debian and Ubuntu (usually the same) but do not indicate a dependency for the Debian family. This leads Debian-based distributions to install the opam packages without the depency properly checked.

This problem came to our attention while using Raspbian, but there is no reason to think that a Mint user would not encounter the same issue.

For reference:
```
$ grep -l 'os-distribution = "debian"' packages/*/*/opam | xargs grep -L 'os-family = "debian"' | wc -l
140 
```

I am willing to fix this via a script but there may be caveats I overlooked (or other os-families following the same pattern), so I'm not doing a PR before I get some input.

**Comment by thomasblanc** [comment]
ping @kit-ty-kate

**Comment by toots** [comment]
That script wasn't perfect, tho, I think it was missing some cases. Hope it can be useful!

**Comment by toots** [comment]
Yeah, I think it's missing the case where there's only a dependency on `debian` or `ubuntu` but not both. @kit-ty-kate do you think a check could be added during the CI for that kind of issue?

**Comment by thomasblanc** [comment]
> Yeah, I think it's missing the case where there's only a dependency on `debian` or `ubuntu` but not both. @kit-ty-kate do you think a check could be added during the CI for that kind of issue?

I'll do that. Thanks for the script!

**Comment by thomasblanc** [comment]
This was fixed. Closing.
