### ISSUE TITLE
llvm package size

### ISSUE THREAD

**Issue by jfeser** [ocaml/opam-repository#14962]
The LLVM 7 sources are a significant contribution to the size of my opam directory (350Mb). The test/ directory alone is 246Mb. Is there any way to cut down on this installed size?

**Comment by pmetzger** [comment]
250Mb of space is how many pennies worth at this point? I can now buy a 2T laptop hard drive for $85. That storage would therefore seem to be somewhere about $0.01 (one penny) worth of space. It would be significantly more for an SSD of course, perhaps even as much as ten cents. At current minimum wages in the US ($7.25/hour), that's a bit less than one minute's worth of work for the SSD storage.

**Comment by jfeser** [comment]
Related PR #14971
