### ISSUE TITLE
coqide.8.10 should use the same patch as coq.8.10 to avoid parallel build errors

### ISSUE THREAD

**Issue by eponier** [ocaml/opam-repository#15070]
I hit the "gramlib" bug when trying to install coqide.8.10.0 using opam (cf. https://github.com/ocaml/opam-repository/pull/15017). The bug was circumvented for coq by adding `-j1`. The same fix should be applied to coqide. (And indeed the installation is successful if I add `OPAMJOBS=1` to the command line)

**Comment by Blaisorblade** [comment]
Testing a fix.
