### ISSUE TITLE
broken urls for annexlib, missinglib and xmllight

### ISSUE THREAD

**Issue by yallop** [ocaml/opam-repository#1513]
The urls for 

* [missinglib](https://github.com/ocaml/opam-repository/blob/master/packages/missinglib/missinglib.0.4.1/url#L1) ([url](http://godi-backup2.camlcity.org/godi-backup/missinglib_0.4.1.tar.gz))
* [annexlib](https://github.com/ocaml/opam-repository/blob/master/packages/annexlib/annexlib.0.13.5/url#L1) ([url](http://godi-backup2.camlcity.org/godi-backup/annexlib-0.13.5.tar.gz))
* [xmllight.2.2](https://github.com/ocaml/opam-repository/blob/master/packages/xml-light/xml-light.2.2/url#L1) ([url](http://godi-backup2.camlcity.org/godi-backup/xml-light-2.2.tar.gz))

return 'Connection refused'.

**Comment by dsheets** [comment]
These appear to work now. Closing.
