### ISSUE TITLE
missing shared-memory-ring downloads

### ISSUE THREAD

**Issue by yallop** [ocaml/opam-repository#1514]
The urls for

* [shared-memory-ring.0.4.1](https://github.com/ocaml/opam-repository/blob/master/packages/shared-memory-ring/shared-memory-ring.0.4.1/url#L1) ([url](https://github.com/mirage/shared-memory-ring/archive/shared-memory-ring-0.4.1.tar.gz))

* [shared-memory-ring.0.4.2](https://github.com/ocaml/opam-repository/blob/master/packages/shared-memory-ring/shared-memory-ring.0.4.2/url#L1) ([url](https://github.com/mirage/shared-memory-ring/archive/0.4.2.tar.gz))

return 404

**Comment by dsheets** [comment]
This appear to exist now. Closing.
