### ISSUE TITLE
jst-config unmet availability conditions: os != win 32

### ISSUE THREAD

**Issue by miinguyen** [ocaml/opam-repository#15227]
I use win 64 and while I install package `core`, it requires `jst-config` but the error return is `jst-config unmet availability conditions: os != win 32`.

How can I fixe it? Thank you.

**Comment by mseri** [comment]
I think the best place to raise an issue about it is https://github.com/janestreet/core or https://github.com/janestreet/jst-config. Can you check if this has been fixed in the just released v0.13 first?

**Comment by avsm** [comment]
You may also work around this using WSL 1 or 2 on Windows.
