### ISSUE TITLE
ocp-indent: post message for vim configuration seems not working

### ISSUE THREAD

**Issue by zma** [ocaml/opam-repository#1524]
After install ocp-indent 1.4.0, opam prints:

    To use it from Vim, add to your .vimrc:
      autocmd FileType ocaml source
        (system("opam config var share")."/emacs/site-lisp/ocp-indent.vim").

However, this does not work with Vim for me.

I put a .vimrc configuration that works for me at https://github.com/zma/opam-repository/commit/13330ed597ef0003e77586b6dc8773f065084433 . (Note: I have not test the opam-repository --- haven't figured out how to configure opam to use my version of the opam-respository. Hence, just start an issue rather than a pull request.)

**Comment by samoht** [comment]
Can you please fill that issue upstream: https://github.com/OCamlPro/ocp-indent/issues

Thanks!
