### ISSUE TITLE
bad checksum for ocaml-migrate-parsetree

### ISSUE THREAD

**Issue by aryx** [ocaml/opam-repository#15281]
I use opam in a docker container to install some packages but I recently got this error in my CI:

[topkg.1.0.1] downloaded from http://erratique.ch/software/topkg/releases/topkg-1.0.1.tbz
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-migrate-parsetree.1.4.0: Bad checksum

Anyway I can fix that?

Here is the line in the Dockerfile:
Step 6/18 : RUN git pull && opam update && opam switch 4.07 &&   opam install dune yaml &&   opam install pfff pfff.0.39.3

I run this in the docker image FROM ocaml/opam2:alpine

**Comment by aryx** [comment]
Here is the relevant part of the Dockerfile:
FROM ocaml/opam2:alpine as build
USER root
RUN apk add --no-cache perl m4
USER opam
WORKDIR /home/opam/opam-repository
RUN git pull && opam update && opam switch 4.07 && \
  opam install dune yaml && \
  opam install pfff pfff.0.39.4
COPY --chown=opam src /build
WORKDIR /build/
RUN eval $(opam env); make

**Comment by ygrek** [comment]
```
$ opam info ocaml-migrate-parsetree
...
url.src:      "https://github.com/ocaml-ppx/ocaml-migrate-parsetree/releases/download/v1.4.0/ocaml-migrate-parsetree-v1.4.0.tbz"
url.checksum: "sha256=231fbdc205187b3ee266b535d9cfe44b599067b2f6e97883c782ea7bb577d3b8"
              "sha512=61ee91d2d146cc2d2ff2d5dc4ef5dea4dc4d3c8dbd8b4c9586d64b6ad7302327ab35547aa0a5b0103c3f07b66b13d416a1bee6d4d117293cd3cabe44113ec6d4"
...
$ curl -L https://github.com/ocaml-ppx/ocaml-migrate-parsetree/releases/download/v1.4.0/ocaml-migrate-parsetree-v1.4.0.tbz | sha256sum 
dcd77cd7090ce181a87df08a910ab2935da466f37db8e674e5a966d49743de64 -
```

**Comment by ygrek** [comment]
looks like upstream tarball was updated. cc @diml 
https://github.com/ocaml-ppx/ocaml-migrate-parsetree/releases/tag/v1.4.0
> v1.4.0
> @diml diml released this 6 hours ago

**Comment by ygrek** [comment]
ref https://github.com/ocaml/opam-repository/pull/15280#issuecomment-553974616

**Comment by mseri** [comment]
This may also be an issue with github for which we will need to either upload the old source tarball (should be available in the opam online cache) or change the checksum in the opam file. It turns out that if one doesn’t statically upload a source for the release, github sometimes rebuild the tarballs changing the checksums. Either way we should fix it asap

**Comment by mseri** [comment]
Looks like it happened here: https://github.com/notifications/beta/MDE4Ok5vdGlmaWNhdGlvblRocmVhZDYzMjA3MDE3ODo0MDQwNjIz?query=

**Comment by ygrek** [comment]
> It turns out that if one doesn’t statically upload a source for the release, github sometimes rebuild the tarballs changing the checksums. 

Do you know for sure that it may happen? I have heard it happens but never experienced myself. Curious for myself - if I should keep uploading tarballs for releases or use github tags.

**Comment by aryx** [comment]
This is annoying, that means I can't just simply git pull from my docker container the opam-repository
and hope that opam install a specific version of a package would simply work.
Now I need both to install a specific version of a package AND checkout a specific commit of opam-repository. This should have been caught by the CI of opam-repository.

**Comment by aryx** [comment]
So what is the best way to fix it right now? How can I force to install an ocaml-migrate-parsetree that will not generate the error?

**Comment by mseri** [comment]
The CI caught it, but only after the file had changed: see https://github.com/ocaml/opam-repository/pull/15279 and https://github.com/ocaml/opam-repository/pull/15280#issuecomment-553974616

**Comment by mseri** [comment]
@aryx, I think you can temporarily `opam install omp.1.3.1` before installing `pfff`. Hopefully it will be resolved soon

**Comment by mseri** [comment]
> Do you know for sure that it may happen? I have heard it happens but never experienced myself. Curious for myself - if I should keep uploading tarballs for releases or use github tags.

@ygrek It happened to multiple projects changing owner or with repos changing name but I think to remember also some PR when no change had happened and the tarballs had changed. I think both `dune-release` and `opam-publish` upload the binary tarballs before releasing the package for this reason.

**Comment by aryx** [comment]
@mseri I get [ERROR] No package named omp found.

**Comment by aryx** [comment]
Also is there a way from the command-line to disable the checksum check during opam install?

**Comment by aryx** [comment]
Ok got it, ... ocaml-migrate-parsetree for omp :)

**Comment by mseri** [comment]
Yes, sorry, I went too fast there and used the wrong name. I think you can disable the checks in some way, but in this case the tarball may have been changed by mistake. We are working on it

**Comment by samoht** [comment]
Can someone submit a PR to fix the checksum? (I don't have a Git cli nearby ;p)

**Comment by samoht** [comment]
and yes, sometimes GitHub rebuild the tag archive which is changing the checksum.  `dune-release` is creating (and uploading) its own archive to avoid this issue.

**Comment by ivg** [comment]
For the context: https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745
Basically, the archives in the `<pkg>/archive/<tagname>` are generated on the fly and are subject to change when any program involved in the pipeline changes, e.g., git changes its layout, order of files is changed, compressing options and so on.

The manually uploaded artifacts, i.e., that have path `<pkg>/releases/download/<tag>/<file>` are persistent as they are stored on their servers, so those artifacts will never change their md5sum. 

It is advised to manually upload a tarball with the source code to the releases folder of github (or use dune-release, when applicable). It is also a good idea to mirror your packages, as github.com is not always available, banned in some countries, and prone to various rate-limiting errors. 

Ideally, the opam linter should emit a warning, when it detects an unstable tarball url. 

Also, the issues like this could be prevented with mirroring, for example, if opam had a mirror which mirrors all (or the most important) packages, we won't be having this discussion :) So far, very few packages are using mirrors in the opam universe. The last time I checked it was only bap packages.

**Comment by hannesm** [comment]
@ivg the global cache at http://opam.ocaml.org/cache/ does not count as mirror? which seems to be used by default by opam!?

**Comment by ivg** [comment]
@hannesm, will opam try the cache to retrieve a package that has a mismatching checksum?

**Comment by kit-ty-kate** [comment]
> @hannesm, will opam try the cache to retrieve a package that has a mismatching checksum?

the cache shouldn't have changed so the checksum should be the right one. Only people who attempt to get the archive without the cache will experience the problem.

**Comment by hannesm** [comment]
@ivg I'm not sure I understand your question, sorry. AFAIU, opam takes the `hash` (`hash_algo` being md5, sha256, sha512) and attempts to download `http://opam.ocaml.org/cache/$hash_algo/$hash[0..1]/$hash` -- if successful this is the archive used for unpacking etc. if unavailable, (maybe? I'm not sure) move to the next `hash_algo`, and/or download from the URL specified in the opam file.

**Comment by ygrek** [comment]
So with opam cache in place there should be no upstream url downloads in perfect scenario and this problem should not have surfaced. So it means currently opam cache is not working well? Maybe more mirrors for cache needed?

**Comment by kit-ty-kate** [comment]
> So with opam cache in place there should be no upstream url downloads in perfect scenario and this problem should not have surfaced. So it means currently opam cache is not working well? Maybe more mirrors for cache needed?

The cache is working perfectly well. The problem arises only for people using the docker images/opam-repository's git repository directly (for CI for instance). In those cases the cache is not used, for normal users it is used as usual.

**Comment by ygrek** [comment]
ah, so when opam remote url is not default cache is not used, this makes sense.

**Comment by ivg** [comment]
> The cache is working perfectly well. The problem arises only for people using the docker images/opam-repository's git repository directly (for CI for instance). In those cases the cache is not used, for normal users it is used as usual.

We had a different experience this morning, as we were unable to install any package that is dependent on omp on our regular machines, that were using regular opam-repository, for example
```
opam@aa503157a9d1:~> opam install core_kernel.v0.11.1
The following actions will be performed:
  - install seq                     base       [required by re]
  - install conf-m4                 1          [required by ocamlfind]
  - install jbuilder                transition [required by core_kernel]
  - install ocaml-migrate-parsetree 1.4.0      [required by core_kernel]
  - install ocaml-compiler-libs     v0.12.1    [required by ppxlib]
  - install re                      1.9.0      [required by ppx_expect]
  - install ocamlfind               1.8.1      [required by num]
  - install sexplib0                v0.11.0    [required by base, sexplib]
  - install octavius                1.2.1      [required by ppx_js_style]
  - install jane-street-headers     v0.11.0    [required by core_kernel]
  - install num                     1.2        [required by sexplib]
  - install parsexp                 v0.11.0    [required by sexplib]
  - install base                    v0.11.1    [required by core_kernel]
  - install sexplib                 v0.11.0    [required by core_kernel]
  - install typerep                 v0.11.0    [required by core_kernel]
  - install stdio                   v0.11.0    [required by core_kernel]
  - install ppxlib                  0.8.1      [required by ppx_inline_test, ppx_assert, ppx_base, ppx_jane]
  - install configurator            v0.11.0    [required by core_kernel]
  - install variantslib             v0.11.0    [required by core_kernel]
  - install ppx_typerep_conv        v0.11.1    [required by ppx_jane]
  - install ppx_sexp_conv           v0.11.2    [required by core_kernel]
  - install ppx_pipebang            v0.11.0    [required by ppx_jane]
  - install ppx_optional            v0.11.0    [required by ppx_jane]
  - install ppx_optcomp             v0.11.0    [required by ppx_jane]
  - install ppx_let                 v0.11.0    [required by ppx_jane]
  - install ppx_js_style            v0.11.0    [required by ppx_base]
  - install ppx_inline_test         v0.11.0    [required by core_kernel]
  - install ppx_here                v0.11.0    [required by ppx_assert, ppx_jane]
  - install ppx_enumerate           v0.11.1    [required by ppx_base]
  - install ppx_compare             v0.11.1    [required by ppx_assert, bin_prot, ppx_base]
  - install fieldslib               v0.11.0    [required by core_kernel]
  - install ppx_variants_conv       v0.11.1    [required by bin_prot, ppx_jane]
  - install ppx_custom_printf       v0.11.0    [required by bin_prot, ppx_jane]
  - install ppx_bench               v0.11.0    [required by ppx_jane]
  - install ppx_sexp_value          v0.11.0    [required by ppx_jane]
  - install ppx_sexp_message        v0.11.0    [required by core_kernel]
  - install ppx_fail                v0.11.0    [required by ppx_jane]
  - install ppx_hash                v0.11.1    [required by core_kernel]
  - install ppx_assert              v0.11.0    [required by core_kernel]
  - install ppx_fields_conv         v0.11.0    [required by bin_prot, ppx_jane]
  - install ppx_base                v0.11.0    [required by core_kernel]
  - install ppx_expect              v0.11.1    [required by ppx_jane]
  - install bin_prot                v0.11.0    [required by core_kernel]
  - install ppx_bin_prot            v0.11.1    [required by ppx_jane]
  - install ppx_jane                v0.11.0    [required by core_kernel]
  - install splittable_random       v0.11.0    [required by core_kernel]
  - install core_kernel             v0.11.1
===== 47 to install =====
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[base.v0.11.1] found in cache
[bin_prot.v0.11.0] found in cache
[configurator.v0.11.0] found in cache
[core_kernel.v0.11.1] found in cache
[fieldslib.v0.11.0] found in cache
[jane-street-headers.v0.11.0] found in cache
[num.1.2] found in cache
[ocaml-compiler-libs.v0.12.1] found in cache
[ocamlfind.1.8.1] found in cache
[octavius.1.2.1] found in cache
[parsexp.v0.11.0] found in cache
[ppx_assert.v0.11.0] found in cache
[ppx_base.v0.11.0] found in cache
[ppx_bench.v0.11.0] found in cache
[ppx_bin_prot.v0.11.1] found in cache
[ppx_compare.v0.11.1] found in cache
[ppx_custom_printf.v0.11.0] found in cache
[ppx_enumerate.v0.11.1] found in cache
[ppx_expect.v0.11.1] found in cache
[ppx_fail.v0.11.0] found in cache
[ppx_fields_conv.v0.11.0] found in cache
[ppx_hash.v0.11.1] found in cache
[ppx_here.v0.11.0] found in cache
[ppx_inline_test.v0.11.0] found in cache
[ppx_jane.v0.11.0] found in cache
[ppx_js_style.v0.11.0] found in cache
[ppx_let.v0.11.0] found in cache
[ppx_optcomp.v0.11.0] found in cache
[ppx_optional.v0.11.0] found in cache
[ppx_pipebang.v0.11.0] found in cache
[ppx_sexp_conv.v0.11.2] found in cache
[ppx_sexp_message.v0.11.0] found in cache
[ppx_sexp_value.v0.11.0] found in cache
[ppx_typerep_conv.v0.11.1] found in cache
[ppx_variants_conv.v0.11.1] found in cache
[ppxlib.0.8.1] found in cache
[re.1.9.0] found in cache
[sexplib.v0.11.0] found in cache
[sexplib0.v0.11.0] found in cache
[splittable_random.v0.11.0] found in cache
[stdio.v0.11.0] found in cache
[typerep.v0.11.0] found in cache
[variantslib.v0.11.0] found in cache
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-migrate-parsetree.1.4.0: Bad checksum
```

**Comment by dirkjan111** [comment]
I encountered this issue when following instruction to install Dune from sources, using the documentation. When i try to install the newest version 'opam install ocaml-migrate-parsetree.1.4.1' it says '[Error] Package ocaml-migrate-parsetree has no version 1.4.1'. Basically the documentation on installing and running a Dune node is broken now.

**Comment by mseri** [comment]
Once https://github.com/ocaml/opam-repository/pull/15280 is fixed we can merge it and it will fix this issue
