### ISSUE TITLE
conf-openssl 1 not being available breaks lockfiles

### ISSUE THREAD

**Issue by Bronsa** [ocaml/opam-repository#15329]
a lot of our CI builds are now broken due to `conf-openssl {= "1"}` not being installable anymore:

```
'opam install -y project.opam.locked' returned a non-zero code: 20
No solution found, exiting

      unmet availability conditions: false
  - project -> conf-openssl < 2
```

**Comment by Bronsa** [comment]
Reading through https://github.com/ocaml/opam-repository/pull/14600 it seems like the intention was not to break lockfiles, but this is not the case 

\cc @kit-ty-kate

**Comment by Bronsa** [comment]
I'd like to point out that because of this issue and #15295 there is currently no working way to install `conf-openssl` on macos.

Moreover, this issue caused not only CI issues for us, but also broke our public installer for our commercial product which uses ocaml. We only noticed by a lucky accident, as we haven't made a release in a few days and assumed that already-tested releases wouldn't break.

I understand why the change happened but it could've been done in such a way as not to break backwards compatibility, most package repositories for other languages are guaranteed to be append-only for those reason.

**Comment by kit-ty-kate** [comment]
My bad, for some reason I thought lock files would override the `available: false` I added last minute. This should now be fixed.

**Comment by kit-ty-kate** [comment]
Sorry again.
