### ISSUE TITLE
fail to build 4.0xxx+musl+static+flambda

### ISSUE THREAD

**Issue by aryx** [ocaml/opam-repository#15344]
Here is the trace:
<pre><font color="#8AE234"><b>pad@yrax</b></font>:<font color="#729FCF"><b>~</b></font>$ opam switch create 4.07.1+musl+static+flambda

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Gathering sources</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
[<font color="#4E9A06">ocaml-variants.4.07.1+musl+static+flambda</font>] found in cache

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Processing actions</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#4E9A06">∗</font> installed <b>base-bigarray</b>.base
<font color="#4E9A06">∗</font> installed <b>base-threads</b>.base
<font color="#4E9A06">∗</font> installed <b>base-unix</b>.base
<font color="#CC0000">[ERROR]</font> The compilation of ocaml-variants failed at &quot;/home/pad/.opam/opam-init/hooks/sandbox.sh build make -j7 world&quot;.

<font color="#CC0000">#===</font> <b>ERROR</b> <b>while compiling ocaml-variants.4.07.1+musl+static+flambda</b> <font color="#CC0000">==========#</font>
<font color="#C4A000">#</font> <font color="#C4A000">context</font>     2.0.2 | linux/x86_64 |  | https://opam.ocaml.org#b0cb7bc2
<font color="#C4A000">#</font> <font color="#C4A000">path</font>        ~/.opam/4.07.1+musl+static+flambda/.opam-switch/build/ocaml-variants.4.07.1+musl+static+flambda
<font color="#C4A000">#</font> <font color="#C4A000">command</font>     ~/.opam/opam-init/hooks/sandbox.sh build make -j7 world
<font color="#C4A000">#</font> <font color="#C4A000">exit-code</font>   2
<font color="#C4A000">#</font> <font color="#C4A000">env-file</font>    ~/.opam/log/ocaml-variants-12980-6d07ae.env
<font color="#C4A000">#</font> <font color="#C4A000">output-file</font> ~/.opam/log/ocaml-variants-12980-6d07ae.out
<font color="#C4A000">### output ###</font>
<font color="#C4A000"># </font>[...]
<font color="#C4A000"># </font>/usr/bin/ld: spacetime.pic.o: relocation R_X86_64_32 against `.rodata.str1.8&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: afl.pic.o: relocation R_X86_64_32 against `.rodata.str1.1&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: unix.pic.o: relocation R_X86_64_32 against `.rodata.str1.1&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: bigarray.pic.o: relocation R_X86_64_32S against `.rodata&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: final link failed: Nonrepresentable section on output
<font color="#C4A000"># </font>collect2: error: ld returned 1 exit status
<font color="#C4A000"># </font>Makefile:208: recipe for target &apos;libcamlrun_shared.so&apos; failed
<font color="#C4A000"># </font>make[1]: *** [libcamlrun_shared.so] Error 1
<font color="#C4A000"># </font>make[1]: *** Waiting for unfinished jobs....
<font color="#C4A000"># </font>make[1]: Leaving directory &apos;/home/pad/.opam/4.07.1+musl+static+flambda/.opam-switch/build/ocaml-variants.4.07.1+musl+static+flambda/byterun&apos;
<font color="#C4A000"># </font>Makefile:389: recipe for target &apos;coldstart&apos; failed
<font color="#C4A000"># </font>make: *** [coldstart] Error 2

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Error report</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">┌─ </font>The following actions <font color="#CC0000">failed</font>
<font color="#CC0000">│ </font><font color="#06989A">λ</font> build <b>ocaml-variants</b> 4.07.1+musl+static+flambda
<font color="#CC0000">└─ </font>
<font color="#06989A">┌─ </font>The following changes have been performed (the rest was aborted)
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-bigarray</b> base
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-threads</b>  base
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-unix</b>     base
<font color="#06989A">└─ </font>

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>ocaml-variants.4.07.1+musl+static+flambda troubleshooting</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">=&gt; </font>A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
# Run <b>eval $(opam env)</b> to update the current shell environment
Switch initialisation failed: clean up? (&apos;n&apos; will leave the switch partially installed) [Y/n] Y
</pre>

**Comment by aryx** [comment]
I want to build a Linux static binary, but I can't with glibc.
I've read it's possible with musl, so I tried to opam switch using musl but I can't create
the switch.
I've tried the 4.07.1+musl+static, but also 4.08+musl+static and 4.09+... with the same issue.
I've tried using musl-gcc on a test.c program with -static and it works, so the C toolchain definitely can do it, but I can't build the ocaml toolchain on top of it.

**Comment by aryx** [comment]
<pre><font color="#8AE234"><b>pad@yrax</b></font>:<font color="#729FCF"><b>~</b></font>$ opam switch create 4.09.0+musl+static+flambda

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Gathering sources</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
[<font color="#4E9A06">ocaml-variants.4.09.0+musl+static+flambda</font>] found in cache

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Processing actions</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#4E9A06">∗</font> installed <b>base-bigarray</b>.base
<font color="#4E9A06">∗</font> installed <b>base-threads</b>.base
<font color="#4E9A06">∗</font> installed <b>base-unix</b>.base
<font color="#CC0000">[ERROR]</font> The compilation of ocaml-variants failed at &quot;/home/pad/.opam/opam-init/hooks/sandbox.sh build make -j7 world&quot;.

<font color="#CC0000">#===</font> <b>ERROR</b> <b>while compiling ocaml-variants.4.09.0+musl+static+flambda</b> <font color="#CC0000">==========#</font>
<font color="#C4A000">#</font> <font color="#C4A000">context</font>     2.0.2 | linux/x86_64 |  | https://opam.ocaml.org#b0cb7bc2
<font color="#C4A000">#</font> <font color="#C4A000">path</font>        ~/.opam/4.09.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+static+flambda
<font color="#C4A000">#</font> <font color="#C4A000">command</font>     ~/.opam/opam-init/hooks/sandbox.sh build make -j7 world
<font color="#C4A000">#</font> <font color="#C4A000">exit-code</font>   2
<font color="#C4A000">#</font> <font color="#C4A000">env-file</font>    ~/.opam/log/ocaml-variants-16272-6d07ae.env
<font color="#C4A000">#</font> <font color="#C4A000">output-file</font> ~/.opam/log/ocaml-variants-16272-6d07ae.out
<font color="#C4A000">### output ###</font>
<font color="#C4A000"># </font>[...]
<font color="#C4A000"># </font>/usr/bin/ld: spacetime_byt_bpic.o: relocation R_X86_64_32 against `.rodata.str1.8&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: afl_bpic.o: relocation R_X86_64_32 against `.rodata.str1.1&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: unix_bpic.o: relocation R_X86_64_32 against `.rodata.str1.1&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: bigarray_bpic.o: relocation R_X86_64_32S against `.rodata&apos; can not be used when making a shared object; recompile with -fPIC
<font color="#C4A000"># </font>/usr/bin/ld: final link failed: Nonrepresentable section on output
<font color="#C4A000"># </font>collect2: error: ld returned 1 exit status
<font color="#C4A000"># </font>Makefile:297: recipe for target &apos;libcamlrun_shared.so&apos; failed
<font color="#C4A000"># </font>make[1]: *** [libcamlrun_shared.so] Error 1
<font color="#C4A000"># </font>make[1]: *** Waiting for unfinished jobs....
<font color="#C4A000"># </font>make[1]: Leaving directory &apos;/home/pad/.opam/4.09.0+musl+static+flambda/.opam-switch/build/ocaml-variants.4.09.0+musl+static+flambda/runtime&apos;
<font color="#C4A000"># </font>Makefile:345: recipe for target &apos;coldstart&apos; failed
<font color="#C4A000"># </font>make: *** [coldstart] Error 2



<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Error report</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">┌─ </font>The following actions <font color="#CC0000">failed</font>
<font color="#CC0000">│ </font><font color="#06989A">λ</font> build <b>ocaml-variants</b> 4.09.0+musl+static+flambda
<font color="#CC0000">└─ </font>
<font color="#06989A">┌─ </font>The following changes have been performed (the rest was aborted)
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-bigarray</b> base
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-threads</b>  base
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>base-unix</b>     base
<font color="#06989A">└─ </font>

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>ocaml-variants.4.09.0+musl+static+flambda troubleshooting</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">=&gt; </font>A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    <b>musl-tools</b>

# Run <b>eval $(opam env)</b> to update the current shell environment
Switch initialisation failed: clean up? (&apos;n&apos; will leave the switch partially installed) [Y/n] Y
</pre>

**Comment by aryx** [comment]
same with 4.09 as shown above.
I do have musl-tools installed. musl-gcc test.c -static does work.

**Comment by aryx** [comment]
I'm under Ubuntu 18.04

**Comment by aryx** [comment]
I have opam switch create 4.07.1 correctly working

**Comment by XVilka** [comment]
Should it be closed in favor of https://github.com/ocaml/ocaml/issues/9131 ?

**Comment by avsm** [comment]
Should be fixed from 4.08 onwards now in opam -- please reopen if not.

**Comment by mro** [comment]
I found it work fine with a single-core, x86_64, Devuan Jessie Linux, but sadly failing on a

4-core, x86_64, Ubuntu Bionic Linux.

[ocaml-variants-9196-6d07ae.env.txt](https://github.com/ocaml/opam-repository/files/4375696/ocaml-variants-9196-6d07ae.env.txt)
[ocaml-variants-9196-6d07ae.out.txt](https://github.com/ocaml/opam-repository/files/4375681/ocaml-variants-9196-6d07ae.out.txt)

What's a bit strange, there's a `make -j 4 world` in the process list (`ps faux`) even though I set `OPAMJOBS` to 1.

**Comment by mro** [comment]
oh, I will try the recipe at https://github.com/ocaml/ocaml/issues/9131#issuecomment-599765888
