### ISSUE TITLE
Can't install mysql.1.2.4

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/opam-repository#15387]
`mysql.1.2.4` (but not older versions) depends on `conf-mysql` which in turn has a `depext` on `libmysqlclient-dev` for Debian systems. That package does not exist, at least not on Debian 9.

The package that we install is `default-libmysqlclient-dev` which allows installation of mysql.

**Comment by hcarty** [comment]
See https://github.com/ocaml/opam-repository/pull/15265#issuecomment-557730655 as well. This change has caused challenges in a few places (thankfully that macos issue was a quick fix!).
