### ISSUE TITLE
sqlite3.5.0.1 missing dune-configurator dependency?

### ISSUE THREAD

**Issue by mjambon** [ocaml/opam-repository#15430]
The previous version, sqlite3.4.4.1, has a dependency on `dune-configurator` specified in its `opam` file but not sqlite3.5.0.1. We have to install the `dune-configurator` package first otherwise the `dune.configurator` library isn't found during the build.

Possible fix:
 * add `dune-configurator` back to the dependencies in the opam file
* or remove `dune.configurator` from the libraries in the [dune file](https://github.com/mmottl/sqlite3-ocaml/blob/a77eb49b425594834a8de45b7a9632b18410717e/src/config/dune)

This is using OCaml 4.05.0.

cc @mmottl

**Comment by mseri** [comment]
Thanks for the report. Indeed the dependency needs to be added, I have sent a PR to the opam repository

**Comment by mseri** [comment]
Fixed in opam. We pinged the maintainer first updating also upstream

**Comment by mjambon** [comment]
Thanks a lot!

**Comment by mmottl** [comment]
Thanks for fixing this in the OPAM file, I've just done so upstream.  I'll also fix all other packages that may now require this additional dependency.
