### ISSUE TITLE
Set `OCAMLTOP_INCLUDE_PATH` to `%{toplevel}%`?

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/opam-repository#15547]
Since 4.08.0, OCaml supports a new environment variable `OCAMLTOP_INCLUDE_PATH` to specify additional include directories for the toplevel. Setting this variable would allow scripts installed in `%{toplevel}%` to be available in the OCaml toplevel without the user manually adding `%{toplevel}%` to the include path in the toplevel or package authors manually installing toplevel scripts in `%{lib_root}%/ocaml`.

opam already sets `OCAML_TOPLEVEL_PATH` to `%{toplevel}%`, however this variable is only recognised by utop and not by the vanilla OCaml toplevel.

I propose to start setting the `OCAMLTOP_INCLUDE_PATH` variable in the `ocaml` package, and eventually stop setting the `OCAML_TOPLEVEL_PATH` one. Thoughts?

**Comment by diml** [comment]
This is a not a super important issue, but is quite simple and still seems worth doing to me.

**Comment by jeremiedimino** [comment]
@dra27 do you think this change would break anything? This seems like a simple to change to make and it would make the life of people who want to install toplevel scripts easier in the future.
