### ISSUE TITLE
Broken link for findlib

### ISSUE THREAD

**Issue by rgladwell** [ocaml/opam-repository#1570]
Trying to install ocamlfind from a clean build always fails, looks as though the camlcity.org domain is down:

`$ sudo add-apt-repository ppa:avsm/ppa-testing`
`$ sudo apt-get update -qq`
`$ sudo apt-get install -qq m4 ocaml ocaml-native-compilers camlp4-extra opam`
`$ export OPAMYES=1`
`$ opam init`
`$ opam install ocamlfind`

Fails with the following error message:

```
The following actions will be performed:
 - install ocamlfind.1.4.0
1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove

=-=-= Installing ocamlfind.1.4.0 =-=-=
ocamlfind.1.4.0 Downloading http://download.camlcity.org/download/findlib-1.4.tar.gz
[ERROR] http://download.camlcity.org/download/findlib-1.4.tar.gz is not available


===== ERROR while installing ocamlfind.1.4.0 =====
Could not get the source for ocamlfind.1.4.0.
'opam install ocamlfind' failed.
```

**Comment by teohhanhui** [comment]
As a beginner, I was trying to follow the [installation instructions from Real World OCaml](https://realworldocaml.org/install) (of course).

But of course camlcity.org is down! :disappointed:

With the [official Docker image](https://hub.docker.com/r/ocaml/opam/), this is what I needed to do:

```Dockerfile
FROM ocaml/opam:alpine

RUN set -xe \
	&& { \
		echo 'archive: "https://opam.ocaml.org/archives/ocamlfind.1.7.3+opam.tar.gz"'; \
		echo 'checksum: "f566d686f364bf251ae79c5c891555d4"'; \
	} > /home/opam/opam-repository/packages/ocamlfind/ocamlfind.1.7.3/url \
	&& opam update \
	&& opam depext -i core
```

Related: ocaml/opam#807

I don't understand why opam does not attempt to use / fall back to the archived version...
