### ISSUE TITLE
conf-gmp-powm-sec: Missing load-time dependency

### ISSUE THREAD

**Issue by cfcs** [ocaml/opam-repository#15917]
The package `conf-gmp-powm-sec` adds a compile-time lower bound to the `libgmp` ABI version used in a given switch.

This is useful for changing the failure mode of a package relying on `libgmp`/`zarith` to provide the `powm_sec` function when that is not available; software that requires `powm_sec()` from `zarith` can declare an OPAM dependency on `conf-gmp-powm-sec` which will only be installable when the machine that the software is being built on links to a `libgmp` with the desired ABI.

The problem is that `zarith` will load `libgmp` dynamically using whatever `libgmp` is available on the *user's machine*, so it can still fail at runtime on the machine that *runs* the produced binary (e.g. if you distribute your program as a binary), [as pointed out by @hannesm](https://github.com/mirage/mirage-crypto/pull/15/files/de473492e7b4dc1fbf809bb71622d0c539402a73..9c996e188a129765a50933b9fa3cbea49117fe3c#r384584958).

If `conf-gmp-powm-sec` was made to have a hard dependency on the `powm_sec` ELF *symbol* (e.g. by referencing it) and was to be linked into the produced binary, this would cause a load-time error for the user in the scenario where the build machine had a good version of `libgmp` and the user does not.
That seems desirable compared to the current state where this can happen:
- Package author declares `conf-gmp-powm-sec` as a dependency
- Package build machine has intended version of `libgmp`, installation succeeds.
- Package author distributes to end-user
- End-user does not have recent enough `libgmp`
- Software will appear to work, but will [raise an exception when `powm_sec` is called](https://github.com/ocaml/Zarith/blob/a9a309d0596d93b6c0c902951e1cae13d661bebd/caml_z.c#L2726).

I propose:
- We keep the existing code to fail installations when the build machine has undesired `libgmp`, that is good.
- We add a small module to link against that does nothing but reference the `powm_sec` symbol from GMP. This will cause a load-time error for end-users with incorrect `libgmp` versions (which in some scenarios is much more desirable than a run-time exception that happens after e.g. your web server has been running for a month and someone presents a `PKCS1` TLS client signature)

Does this make sense, and do you want a PR for this? (ping @emillon @hannesm)

References:
- https://github.com/mirage/mirage-crypto/pull/15/files/de473492e7b4dc1fbf809bb71622d0c539402a73..9c996e188a129765a50933b9fa3cbea49117fe3c#r384552951
- (introducing PR) https://github.com/ocaml/opam-repository/pull/7954

**Comment by hannesm** [comment]
I think agree with the goal "fail early (at load/initialization-time) if powm_sec is not available". I don't think this is urgent.

**Comment by emillon** [comment]
I generally agree with this, but I think that using a `conf-` package to link an object in the target binary is a bit difficult to implement.

It might be worth putting this directly in zarith? 4 years ago it was a bit early to add an explicit dependency, but maybe now this function is old enough that it could be accepted.

**Comment by mseri** [comment]
Is there a related issue or a PR in zarith repository?
