### ISSUE TITLE
How to get the opam repository in a consistent state?

### ISSUE THREAD

**Issue by MdeLv** [ocaml/opam-repository#16309]
When the maintainer of an opam package has updated it and asks the opam-repository for getting it published via a PR, it can take several days before the updated opam packages are available. Then, if an issue is discovered and fixed, it can take approximately the same time to get the fixed package published.
In the mean time, the publicly available package and its dependent opam packages form an inconsistent set (i.e. "the installation is broken").

**Q1: Is there a way for the author of an opam package to ask to get an instant rollback to the last validated package in that situation?**

The [publishing process on opam-repository](https://opam.ocaml.org/doc/Packaging.html#Publishing) says:

> Publishing is done using Github's pull-request mechanism, which allows automated checks to be run, and discussion to happen with the maintainers before your contribution is merged

**Q2: Today, which automated checks are systematically done by the opam-repository when merging a PR?**
**Q3: Are opam package maintainers forced to declare that their package has been tested against the set of ocaml compiler versions an dependencies declared in the opam file?**

From my experience, I understand that there are no systematic checks and that the maintainer is probably responsible for testing his package. A simple `opam install foo` would be enough to detect main issues before they are propagated, however we can forget to do it.

**Q4: Would it be possible for opam-repository maintainers to set up automated checks against the set of the constraints declared within the opam file?
(in the meantime, would it be possible to ask maintainers to declare that their package installation has been tested against the constraints declared within the opam file?)**

###  Constraints validity in an opam file (discussion)
In addition, the constraints within an opam file are often not enough strict because they don't take care of other packages evolution. Large libraries are more concerned. For example, we can read  **ocaml>= "4.06.1**, but if a new compiler version is released, say **4.08.1**, with which the package can't be installed, the opam repository becomes **automatically inconsistent** for that package. The main victims are beginners, who get headaches instead of learning OCaml. And it can happen to everybody, each time a package is updated!

One recommendation would be to enforce that opam files define the set of compilers checked against available compilers, say **ocaml>= 4.06.1 & < 4.09**.

Asking maintainers to check their package is a poor solution. It seems that it would be more efficient and sustainable to:
- check automatically that an opam package proposed for publishing by its maintainer can be installed with all dependencies defined in its opam file (compiler versions other packages).
- enforce a range of tested opam compilers version, say **ocaml>=4.06.1 & < 4.09**  instead of **ocaml>=4.06.1** (i.e. no open bound version).
- repeat the automated check, each time a new compiler version is released; if the package is correctly installed, then automatically update the opam file against the test results, say **ocaml>=4.06.1 & < 4.10.0**.

I also found some weird situations when all nested constraints are computed.
So, ideally, each time a direct **and** not direct dependency is updated, a package must be tested against that set of computed dependencies.
If it does build-pass, then update its opam file according to its validated set of constraints. Else, notify the package maintainer that it doesn't build-pass. He may need to discuss with the maintainers of his package's dependencies.

I may have forgotten things (OS, distribution, etc.), but satisfying these requirements would prevent the community from a bunch of issues.
**What do you think about that recommendation?**
**Have you an idea of how setting up that, starting from the present resources and organization of opam-repository?**

Let's discuss.

**Comment by avsm** [comment]
To correct a misconception here:
> From my experience, I understand that there are no systematic checks and that the maintainer is probably responsible for testing his package. 

...is incorrect.  Consider a recent contribution such as [angstrom.0.14.0](https://github.com/ocaml/opam-repository/pull/16288).  Here are the checks [conducted against that contribution](https://ci.ocaml.org/ocaml/opam-repository/pr/16288?test=1%20Build) by our automated CI, involving checking multiple OCaml compiler versions, the reverse dependencies, and multiple Linux distributions.

To step back a little bit: which packages have you contributed to the opam-repository that you've had trouble with? I couldn't find any [on a quick search](https://github.com/ocaml/opam-repository/pulls?q=is%3Apr+author%3AMdeLv), and I'd like to understand what problems you encountered.

We could certainly use some assistance with improving the package submitter documentation on opam-repository though. Would you like to help with that?

**Comment by MdeLv** [comment]
1/ I've not yet  contributed to the opam-repository. However, as an opam/opam-repository user, I sometimes have trouble with some packages available on opam-repository and which installation becomes broken when a dependency is updated.

For example, js_of_ocaml.3.6.0 was released yesterday on opam-repository. The js_of_ocaml-ppx "broke" the installation of dependent packages such as ocsigen-toolkit and ocsigen-start, at least **because** these two packages were not updated accordingly and asked by their maintainers to be published on opam-repository at the same time as js_of_ocaml.
See [[BUG] ocsigen-toolkit.2.5.0 fails to compile after upgrade to js_of_ocaml.3.6.0#1005 ](https://github.com/ocsigen/js_of_ocaml/issues/1005).

I targeted the failing build commands and hhugo confirmed that `js_of_ocaml-ppx_deriving_json` should be used (instead of `js_of_ocaml-ppx.deriving`). I made 2 PR that were merged.
However, I don't know when the packages will be updated on opam-repository.
AFAIK, I have to do `opam update -u` and look at the result, or to monitor the package's repository information with smth like `opam list --all --all-versions` along with some filtering and monitoring command (cron, watch, or whatever). 
I didn't find yet a way to `opam search` and get the "published" date remotely. 
**Is there a notification service about the ongoing publishing procedure?**
**if no, what would be the simplest way to design and develop it?** 

2/ About the opam package submitting procedure, I only know what is written at https://opam.ocaml.org/doc/Packaging.html. This documentation is clear but is mainly about the syntax of the opam file and about the PR mechanism.

The [testing procedure](https://opam.ocaml.org/doc/Packaging.html#Testing) is very basic: the maintainer is invited to perform a local test. If he doesn't do it, the documentation doesn't tell if the  package will ever be tested before publishing.

The [publishing procedure](https://opam.ocaml.org/doc/Packaging.html#Publishing) is clear but incomplete:
> Publishing is done using Github's PR mechanism which **allows** automated checks to be run

**Are there systematic checks done by opam-repository for each new package asked for publishing, such as those you mentioned for angstrom ?**
 
My understanding is that even if a package has been thorougly checked by its maintainer or by opam-repository before being published, its installation may be broken afterwards, as in the case of the js_of_ocaml.3.6.0 I mentioned. Except if there is a continuous testing of **already published** packages each time one package is published.
**Is there such a _continuous testing of already published packages_ ?**

ocsigen-start seems to be more exposed to that problem because it's a pretty large library with many dependencies.

I see at least two possible solutions:

- Solution 1: the maintainer makes tests and sends a PR to opam-repository for publishing his updated package as well as dependent packages AND ask you to publish them at the same time [it's not reliable because we are humans and we will make mistakes; we are better at writing nice OCaml programs].

- Solution 2: each time opam-repository gets a PR for publishing a package, an automated test such as the one done on ansgtrom is done for the new package **and also** for each package dependent on this new package, even the already published ones.

3/ Yes, I would be happy to collaborate for improving the _opam-repository package submitter_ documentation .
I see that work as:
- first: understanding how it works today (Q/A as started herebefore)
- second: improve the documentation to instruct maintainers how to enforce testing of their package so that its installation is guaranteed, and inform them about the details of the publishing process
- third: detect features that could improve the experience with opam, opam-repository and opam packages.

Are you talking about improving this page: https://opam.ocaml.org/doc/Packaging.html? Or to add some documentation in this page: https://github.com/ocaml/opam-repository?

**Comment by avsm** [comment]
Just to systematically look at your report, the reason ocsigen-toolkit broke upstream is because it doesn't actually depend on the packages it uses.  The `opam` file for ocsigen-toolkit needs to add dependencies on (e.g.) js_of_ocaml, or else opam simply doesn't know that it uses them.

**Comment by MdeLv** [comment]
Here are the main dependencies of ocsigen-start package:

package | implicit dependency (opam files) |  explicit dependencies (computed)
-------------- | ---------------- | ----------------
ocsigen-start | eliom, ocsigen-toolkit | eliom, eliom, ocsigen-toolkit, js_of_ocaml
ocsigen-toolkit | eliom | eliom,  js_of_ocaml
eliom | js_of_ocaml | js_of_ocaml

(ref : opam files, see hereunder)

What I previously understood about the opam system is that dependencies **can** be defined relatively. So specifying explicit (or direct) dependencies is enough. It does the job but  can break an installation.

What I understand from what you are telling me is that an opam package maintainer **must** specify all its direct and indirect dependencies (to take advantage from opam-repository CI).

**Where is this rule expressed?**

**Can "opam-repository and its CI" enforce this rule?**
So the maintainer will be notified that the opam file of his package is illegal, because it has an implicit dependencies specification. 
In addition a testing tool (CLI or/and online service) could allow a package maintainer to check by himself that **all** the opam files of his package and its dependencies are legal, before making a PR (please consider that I know nothing about today's opam-repository CI). It will also save resources from opam-repository, and improve opam ecosystem global quality.
 
[https://github.com/ocsigen/**ocsigen-start**/blob/master/opam](https://github.com/ocsigen/ocsigen-start/blob/master/opam):
```
depends: [
  "ocaml" {>= "4.06.1"}
  "pgocaml" {>= "4.0"}
  "pgocaml_ppx" {>= "4.0"}
  "safepass" {>= "3.0"}
  "ocsigen-i18n" {>= "3.1.0"}
  "eliom" {>= "6.10.1"}
  "ocsigen-toolkit" {>= "2.3.1"}
  "yojson" {>= "1.4.1"}
  "resource-pooling" {>= "1.0" & < "2.0"}
  "cohttp-lwt-unix"
  "conf-npm" {>= "1"}
  "ocamlnet"
]
```

[https://github.com/ocsigen/**ocsigen-toolkit**/blob/master/opam](https://github.com/ocsigen/ocsigen-toolkit/blob/master/opam):
```
depends: [
  "ocaml" {>= "4.07.0"}
  "eliom" {>= "6.10.1"}
  "calendar"
]
```

[https://github.com/ocsigen/**eliom**/blob/master/opam](https://github.com/ocsigen/eliom/blob/master/opam):
```
depends: [
  "ocaml" {>= "4.07.1"}
  "ocamlfind"
  "ppx_deriving"
  "ppx_tools" {>= "0.99.3"}
  "js_of_ocaml-compiler" {>= "3.5.1"}
  "js_of_ocaml" {>= "3.5.1"}
  "js_of_ocaml-lwt" {>= "3.5.1"}
  "js_of_ocaml-ocamlbuild" {build}
  "js_of_ocaml-ppx" {>= "3.5.1"}
  "js_of_ocaml-ppx_deriving_json" {>= "3.5.1"}
  "js_of_ocaml-tyxml" {>= "3.5.1"}
  ...
]
```

**Comment by avsm** [comment]
While dependencies can be defined relatively just fine, in this case ocsigen-start also has a *direct* dependency on js_of_ocaml, as seen in your PR here: https://github.com/ocsigen/ocsigen-start/pull/590/files

If ocsigen-start uses js_of_ocaml directly, then it needs to express that dependency in its opam file.  This would then cause the opam-repository CI to test the ocsigen-start build with the newer package (including running tests). 

Since it wasn't expressed as a dependency to ocsigen-start, our CI only tested js_of_ocaml's immediate reverse dependencies, such as eliom, which built find with the new version.

**Comment by MdeLv** [comment]
I agree.
Now, if you/I/we want to improve the overall reliability of packages made available at opam-repository, an opam package MUST conform, at least, to rule 1 expressed hereafter.

Several rules for an opam package may be enforced via testing at CI level:

- Rule 1: _All and only all_ direct dependencies of an opam package are be specified in its opam file (field _depends_).
- Rule 2: All dependencies of an opam package respect rule 1 (the question of depext should be addressed by opam-repository CI - I saw that opam.2.1.0 improves the depext mechanism).
- Rule 3: All dependent opam packages of an opam package respect rule 1.
 
Enforcing these three rules would allow both to clean up opam-repository (maybe there are a few _opam file leaks_!) and to enforce that it stays clean. This will improve the experience of an Ocaml programmer, who should be more and more confident about each new installation.

opam-repository CI seems to be the best place for testing if this/these rules are respected. 
It can detect if the depends specified in the opam file match the packages called during compilation.

What do think about that?
How do you want to proceed to enforce these rules? (rule 1 to start with)

Also, the _opam package publishing service_ may be proposed with two flavors:
- propose an opam package: PR (as today)
- test an opam package against the available packages (some kind of _automated pre-PR_ in sandbox)

Would it be possible for you to propose this "testing service" in addition to the present publishing service?

**Comment by MdeLv** [comment]
Any feedback?

**Comment by MdeLv** [comment]
Hi,
I took time to make a proposal.
Can I get your feedback? What changed since I opened this issue?

**Comment by MdeLv** [comment]
Thanks for your quick feedback.

One question is:
What do "we" want regarding installation reliability? (thinking about newcomers and ordinary OCaml programmers)

Another question is:
How can "we" enforce the rule I suggested so that every author/publisher can guarantee that his opam file is fine over a defined and explicit range of OCaml compilers.
EACH TIME a new compiler is released, he would just need to test his package and dependencies for it and update his opam file.
Is there a tool such as the one used by opam-repository available for an ordinary author to test if his package builds (for defined targets)?
