### ISSUE TITLE
add post-messages for optional dependencies of ocamlsdl

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-repository#1649]
Would be nice to highlight the fact that you might need optional external deps to have more modules.

**Comment by dbuenzli** [comment]
@samoht do you plan to this ? It seems there is no maintainer for this package. Otherwise I'd suggest to close this issue.

**Comment by dbuenzli** [comment]
(Note that in general I find post-messages rather annoying since they show up in each recompiles)
