### ISSUE TITLE
travis: sanity test man page installation

### ISSUE THREAD

**Issue by avsm** [ocaml/opam-repository#1650]
See #1648 -- we should check before/after installation that other pages have gone into a sensible location.

I could modify the Travis scripts to show a diffstat of files within ~/.opam before/after the installation so we can eyeball these on merge. Any objections?

**Comment by dbuenzli** [comment]
It seems to me that `opam` v2 disallows packages to install outside their little prefix. So is this still relevant with `opam` v2 on sight ? If not I suggest we move on to close this.

**Comment by samoht** [comment]
ping @AltGr

**Comment by dbuenzli** [comment]
This request doesn't seem to move on so I'm closing this. If someone has a concrete plan, he should open a new issue with a precise plan on how to get this in the repo in a timely manner.
