### ISSUE TITLE
patch compiler packages for gcc 10

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam-repository#16538]
https://github.com/ocaml/ocaml/pull/9180 is neat but only applies to post 4.09.1 apparently.

I can propose a patch for 4.06, 4.07, 4.08, 4.09.0 that makes compilation succeed with gcc 10 with the change in https://discuss.ocaml.org/t/opam-switch-create-and-gcc10/5864/8

**Comment by avsm** [comment]
I'm taking a look at this, since it's a blocker to rebuilding the container images with Fedora 32.

**Comment by gmalecha** [comment]
It looks like #16583 was merged but it only updated the mainline compiler, not the variants, e.g. `+flambda` is there any plan to do that? Was #16583 prepared with a script that could be run on the variants as well?

**Comment by gmalecha** [comment]
#16854 seems to address this.

**Comment by damiendoligez** [comment]
@c-cube, @avsm I think this is superseded by the set { #16583, #16705, #16722, #16728, #16865 }. Right?
