### ISSUE TITLE
Relax janestreet "< v0.14.0" constraints for packages which does not need it.

### ISSUE THREAD

**Issue by andersfugmann** [ocaml/opam-repository#16569]
#16484 adds constraints on all packages depending on any Janestreet package, even for packages with works fine without it. 
 
Individual library maintainers will need to relax the constraints - which will take time and effort and will slow down adoption, esp for longer dependency chains (package a -> janestreet & package a -> package b -> janestreet)

I recommend that PR #16484 is rolled back, and only added for packages which really needs it, to allow any adoption of Janestreet v0.14 packages.

**Comment by avsm** [comment]
Please see https://discuss.ocaml.org/t/experimenting-with-a-new-opam-repository-release-strategy-for-large-libraries/2918 for an outline of the Core release strategy.  The idea is to bring in the new packages with upper bounds, to sort out any teething issues with the compilation of the v14.0 series.  Once they are settled and tested, then the upper bounds will can be relaxed.

So the next step is to start relaxing the upper bounds on packages which built (which can be done from the #16484 CI results).

**Comment by andersfugmann** [comment]
Perfect - Thanks.
