### ISSUE TITLE
Checking for external dependency installed via coreutils

### ISSUE THREAD

**Issue by maroneze** [ocaml/opam-repository#16689]
I'd like to add a package `conf-timeout` to check that the `timeout` command is installed in the machine, so that we can use it as a depext in our OCaml packages.

However, when using `conf-time` as inspiration for writing `conf-timeout`, I realized that in all systems I know of, `timeout` is installed via the `coreutils` package.

Therefore I wonder: is it useful to add such a package to opam-repository? Or can we assume that `coreutils` is always installed in the system? For instance, is it already an implicit dependency of installing opam? I think any VM/Docker having `opam` should probably already have `coreutils` installed, but I'm not entirely sure. From what I could gather, even FreeBSD and NetBSD have a `timeout` command, even if it is not POSIX; but I couldn't confirm whether OpenBSD does.

However, it seems that macOS does not contain a `timeout` command by default. In this case, a `conf-*` package might make sense. If you have more experience about the issue, could you please share it?

**Comment by maroneze** [comment]
By the way, a related question: when creating such a small `conf-` package, should I assign myself as maintainer or someone else?

**Comment by mseri** [comment]
If also in *BSD is part of some utils package, it could more generally be a `conf-coreutils` package, or something similar. Let's wait a few days, maybe somebody with OpenBSD knowledge can tell you about it.

As maintainer you can put yourself. For conf packages it's not really requiring much (if any) effort

**Comment by maroneze** [comment]
Ok, I'll wait and create if it makes sense. My macOS colleague told me that Homebrew also has a `coreutils` package, so it should help macOS users.

**Comment by maroneze** [comment]
Well, I was preparing a package, and I stumbled upon a very basic error: how to detect that `coreutils` is installed? Other than using a distribution-specific process (e.g. `dpkg` on Debian, `brew list coreutils` on Homebrew, etc), it seems that there is no generic way to check for them (e.g. `coreutils --version`). I could test a single utility (`timeout`, in my case), but it would not strictly guarantee that it is coreutils that is installed. In practice, I couldn't find any distribution where `timeout` was its own standalone package, so it might work, but then, would it be better than simply writing a `conf-timeout` package which uses `coreutils` as depexts?

**Comment by mseri** [comment]
That's a very good point. I don't have a good answer, but I agree that it seems to make more sense to depend on `conf-timeout` instead. There is the extra burden that `timeout` on osx with homebrew is called `gtimeout` instead. Online I could only find https://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x and https://unix.stackexchange.com/questions/43340/how-to-introduce-timeout-for-shell-scripting that suggest reasonable but maybe suboptimal solutions

**Comment by maroneze** [comment]
Are you sure about the `gtimeout`? I just tried on a Mac Mini running macOS 10.15 with Homebrew, and after installing `coreutils` both `timeout` and `gtimeout` commands were installed (both indicate `timeout (GNU coreutils) 8.32` when running with `--version`). I know there is a way to setup Homebrew so that it overrides the non-g-prefixed binaries, but I'm almost sure I didn't do it. Homebrew emits this message:

> Commands also provided by macOS have been installed with the prefix "g".
> If you need to use these commands with their normal names, you
> can add a "gnubin" directory to your PATH from your bashrc like:
>  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

`echo $PATH` does not show such a line in my case, and it seems coherent with the fact that *Commands **also** provided by macOS have been installed with the prefix "g"*. Since `timeout` is not provided by macOS, it seems Homebrew installs both, just in case.

However, if you know of a configuration where `timeout` is not installed by Homebrew coreutils, please tell me. Otherwise, I'll assume they changed it, and simply checking for `timeout` should work in every conceivable system.

**Comment by maroneze** [comment]
I just tried a centos Docker and got the same error. But what's worse, is that `which` is not available by default. I'll change the package to not require `conf-which`, using instead `command -v`, as recommended by [SO](https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script).
