### ISSUE TITLE
Sandboxing issue with package cairo and opam2

### ISSUE THREAD

**Issue by SchornacklabSLCU** [ocaml/opam-repository#16709]
Dear all,

This is a follow-up of [this issue](https://github.com/ocaml/opam-repository/issues/13849#issue-430463962).
I cannot install the `cairo` package due to sandboxing in opam 2. Unfortunately, `cairo2` is not an option for me.
Error is the same as previously reported:
`# Error: I/O error: ....opam/default/lib/lablgtk2/pango.cmi: Read-only file system`

Thanks for your help.

**Comment by mseri** [comment]
I don't know a nice solution for this. Does it work if you disable the sandbox? (You can do it with `opam init --disable-sandboxing --reinit`)

**Comment by SchornacklabSLCU** [comment]
Thanks for your fast reply. In the meantime, I noticed that cross-compilers require ocaml 4.08, while `cairo` requires ocaml 4.05 at most. I will have to migrate my code to `cairo2` anyway. However, for the sake of completeness, I tried again with your suggestion and **it works very well**. So, disable sandboxing does the job. Thanks again!
