### ISSUE TITLE
conf-sdl2: detect SDL version

### ISSUE THREAD

**Issue by sanette** [ocaml/opam-repository#16741]
this is a follow-up from https://github.com/dbuenzli/tsdl/issues/65#issuecomment-652891005
I don't know how to follow his advice.
maybe @blue-prawn or @kit-ty-kate would know?

**Comment by kit-ty-kate** [comment]
This is tricky issue for tsdl indeed. The solution here would be to limit each packages to some distributions / distribution-version.

For instance, if the lastest tsdl package will not compile with the version of SDL given with say Ubuntu 16.04, then we could constrain the package for it not to be available on ubuntu 16.04 as follows: `available: [!(os-distribution = "ubuntu" & os-version = "16.04")] `.

However adding this won't allow people who added extra repositories with the correct version of tsdl. There is currently no way in opam to detect the version of a package itself easily. The only way would be to modify the conf-sdl2 for it to create an opam.config file to add new variables. I'll try that today see if i can do something but I'm not totally sure it is possible
