### ISSUE TITLE
ocaml-zmq build is failed

### ISSUE THREAD

**Issue by zbroyar** [ocaml/opam-repository#1678]
with the following error and 'opam update' does not help

    =-=-= Installing ocaml-zmq.0 =-=-=
    Downloading https://github.com/pdhborges/ocaml-zmq/tarball/master.
    Error: invalid checksum.
    The compilation of ocaml-zmq.0 failed.
    Uninstalling ocaml-zmq.0:
      ocamlfind remove ZMQ
    
    
    ==== ERROR [while installing ocaml-zmq.0] ====
    Internal error:
      Wrong checksum for https://github.com/pdhborges/ocaml-zmq/tarball/master:
      - 8e845370b99630c2a84cf4495480522e [expected result]
      - 82abfe1922aa675b171f8b22acdc748e [actual result]
    ...

**Comment by samoht** [comment]
Is it still an issue? Please re-open if is.
