### ISSUE TITLE
opam.ocaml.org certificate has expired

### ISSUE THREAD

**Issue by bruce-ricard** [ocaml/opam-repository#16964]
as of 2020-08-04

see https://opam.ocaml.org/

>  wget https://opam.ocaml.org/                                          
--2020-08-05 00:19:17--  https://opam.ocaml.org/
Resolving opam.ocaml.org (opam.ocaml.org)... 2001:4801:7823:76:bb74:1f8e:ff10:627, 192.237.250.17
Connecting to opam.ocaml.org (opam.ocaml.org)|2001:4801:7823:76:bb74:1f8e:ff10:627|:443... connected.
ERROR: cannot verify opam.ocaml.org's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.

**Comment by dmbaturin** [comment]
Just noticed this too, my CI build failed.

**Comment by enigma62333** [comment]
Looks like the same thing happened 90 days ago: https://github.com/ocaml/opam/issues/4187

**Comment by dmbaturin** [comment]
Now opam.ocaml.org stopped responding to HTTP requests.

**Comment by mro** [comment]
to the web-admin: please use e.g. https://updown.io – the least frequency is fully sufficient to be aware of expiring certs 14 days ahead. Doing fine at https://updown.io/g1o2

**Comment by bruce-ricard** [comment]
Certificate has been renewed and
> Expires: Monday, November 2, 2020

I don't know why only 3 months.

**Comment by mro** [comment]
Thanks a lot!

> I don't know why only 3 months.

that's the way let's encrypt has always been. Please set up a routine to remember renewal when it's about due.
