### ISSUE TITLE
issue with opam init

### ISSUE THREAD

**Issue by youyutiancai** [ocaml/opam-repository#17082]
Hi I wanted to init opam with WCL, and I got this error. Could anyone tell me how to solve this? Thanks!

opam init
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!

<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not update repository "default": "/usr/bin/mv /home/youyutiancai/.opam/repo/default.new /home/youyutiancai/.opam/repo/default" exited with code
        1 "/usr/bin/mv: cannot move '/home/youyutiancai/.opam/repo/default.new' to '/home/youyutiancai/.opam/repo/default': Permission denied"
[ERROR] Initial download of repository failed

**Comment by mseri** [comment]
Are the permission on /home/youyutiancai/.opam and its subfolder correct? Looks like the user cannot write there

**Comment by youyutiancai** [comment]
I think so, since I could open the folder. At last I gave up using it and used coqide instead.

**Comment by kit-ty-kate** [comment]
What is WCL exactly?
