### ISSUE TITLE
opam init issue in docker

### ISSUE THREAD

**Issue by aruncgowda** [ocaml/opam-repository#17183]
@avsm  @tel @andreas 
i am gettig this error in docker

opam init --comp 4.05.0
default    Downloading https://opam.ocaml.org/urls.txt
Downloading https://opam.ocaml.org/repo
Updating ~/.opam/repo/compiler-index ...
Updating ~/.opam/compilers/ ...
Updating ~/.opam/repo/package-index ...
Updating ~/.opam/packages/ ...
Cannot find /root/.opam/compilers/4.05.0/4.05.0/4.05.0.comp: 4.05.0 is not a valid compiler name.

**Comment by kit-ty-kate** [comment]
This looks like opam 1.2. This version of opam is rather old and no longer maintained. Which docker image did you get?

**Comment by aruncgowda** [comment]
@kit-ty-kate    
This is the image of ubuntu 14.04 .I am trying to install opam for ubuntu 14.04
