### ISSUE TITLE
Version not set correctly in "lwt" version 4.2.1 (required by stog)

### ISSUE THREAD

**Issue by fccm** [ocaml/opam-repository#17185]
While trying to install "stog" with opam I got an error at configure time with stog checking which version of lwt.unix is available:
```
eval $(opam env --switch 4.06.0 --set-switch)
opam install stog.0.18.0-1
# checking for lwt.unix... Package lwt.unix found with version dev, but wanted >= 2.5
```
Indeed in `~/.opam/4.06.0/lib/lwt/META` there is:
```
version = "dev"
```
When I edit this `META` file to set a correct version:
```
version = "4.2.1"
```
(and same for `package "unix"` sub-section)
Then when I run `opam install stog.0.18.0-1` the install proceeds correctly as expected.

A patch for the package `lwt.4.2.1` is required to install `stog` correctly.

**Comment by mseri** [comment]
Can you send a PR, copying `lwt.4.2.1` into `lwt.4.2.1-1` and adding the required patch?

**Comment by fccm** [comment]
Yes, sure!
I expected to do so when I have a moment.

Why creating a new package version? I thought in opam we fix existing packages without renaming it.

**Comment by mseri** [comment]
We are trying to have patch versions when the change involves patches or functional modifications. We try to modify in place only if we need to fix the metadata (constraints, urls, maintainer names, ...).
