### ISSUE TITLE
Stronger checksums

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam-repository#17315]
Modern opam supports md5, sha256 and sha512; but many packages here are still only relying on a md5.
We should move them to all have a sha512 (a bit long, but actually faster to compute than sha256 on modern archs).
We can keep the existing md5 and just add more hashes, so there should be absolutely no disruptions; (that should not, in particular, trigger recompilations, but we'd better double-check)

**Comment by avsm** [comment]
Happy to rewrite the opam-repository with this as a bulk change to get historical packages.
