### ISSUE TITLE
Multiple definitions of Cairo functions when installing both Coqide 8.12.0 and Why3 ide 1.3.3

### ISSUE THREAD

**Issue by tofgarion** [ocaml/opam-repository#17364]
Hello,

I have a switch with OCaml 4.10.1 and I cannot install both Coqide 8.12.0 and Why3 ide 1.3.3. There is a multiple definition error at the why3-ide linking stage for several functions related to Cairo, e.g. :

```
/usr/bin/ld: /home/XXX/.opam/4.10.1/lib/cairo2/libcairo_stubs.a(cairo_stubs.o):/home/XXX/.opam/4.10.1/.opam-switch/build/cairo2.0.6.1/_build/default/src/cairo_ocaml.h:53: multiple definition of `caml_cairo_font_type'; /home/XXX/.opam/4.10.1/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o):/home/XXX/.opam/4.10.1/lib/cairo2/cairo_ocaml.h:53: first defined here
```

I am running a Debian distribution mixing testing and unstable. Notice that I can perfectly install both Coqide and Why3 ide on the same OCaml switch on an older machine running CentOS 7. The `ld` versions are not the same on the two machines, mine is more recent:

```
GNU ld (GNU Binutils for Debian) 2.35.1
Copyright (C) 2020 Free Software Foundation, Inc.
```

Reinstalling my OPAM installation from scratch does not solve the issue.

Here is the result of `opam config report`:

```
# opam config report
# opam-version      2.0.5 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=testing
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              4
# repositories      4 (http) (default repo at 43bcdfb7)
# pinned            0
# current-switch    4.10.1
```

Do you have any idea for solving this problem? Sorry if this kind of issue has already been reported, I have not found it.

Best,

Christophe

**Comment by kit-ty-kate** [comment]
If you're still having the issue I would suggest opening a ticket on `lablgtk`'s bugtracker: https://github.com/garrigue/lablgtk/issues

**Comment by tofgarion** [comment]
There was a conflict between GTK2 and GTK3 related librairies needed by Coqide and another library (AbSolute, cf. https://github.com/mpelleau/AbSolute). Reinstalling Coqide and AbSolute in the "correct" order solved the issue :) I am in contact with one of AbSolute main developers and he will solve the problem by switching the library to GTK3.
