### ISSUE TITLE
Package dose3 should require package ocamlfind as a dependency [Rereport from InriaForge repo]

### ISSUE THREAD

**Issue by yannl35133** [ocaml/opam-repository#17473]
When a dune upgrade is available, it will recompile everything that depends on dune.

- ocamlfind depends on dune through graphics
- dose3 depends on dune through cppo, re

Therefore, opam will recompile both packages in unspecified order. For me, it tried to compile dose3 before ocamlfind and, as every package is uninstalled before they start being reinstalled, an error occured.

Original issue [here](https://gforge.inria.fr/tracker/index.php?func=detail&aid=21853&group_id=4395&atid=13808)
Similar issue on another package [here](https://github.com/coq/coq/issues/12858)

Sorry for the double reporting, it seems that the original repo of dose3 is rarely visited.

**Comment by josch** [comment]
We now switched the build system of dose3 to dune and also have a new repository at https://gitlab.com/irill/dose3 because the inria gforge is shutting down.
