### ISSUE TITLE
Error with opam switch create

### ISSUE THREAD

**Issue by Adam-Alani** [ocaml/opam-repository#17673]
Im getting this when i try to make a switch:
![image](https://user-images.githubusercontent.com/71665039/99861733-5caf9900-2b97-11eb-958e-8027b1257be7.png)

**Comment by mseri** [comment]
I see this mentions cygwin. Is this running on windows? In that case maybe @fdopen knows better

**Comment by Adam-Alani** [comment]
@mseri Indeed, this is on windows on the cygwin terminal

**Comment by mseri** [comment]
In this case I think the right place for the report is https://github.com/fdopen/opam-repository-mingw/issues

**Comment by mseri** [comment]
I’ll keep the issue open until it is resolved, just in case there is action needed from our side

**Comment by Adam-Alani** [comment]
Problem was with ocaml version, had to install the 4.02.3 build
