### ISSUE TITLE
Can't update cohttp to 3.0, opam doesn't say why

### ISSUE THREAD

**Issue by spinlock-ml** [ocaml/opam-repository#17691]
Hi, if this isn't the right place to ask about this sort of thing, please direct me to a better place to ask this question.

I'm trying to use version 3.0.0 of [`cohttp`](https://github.com/mirage/ocaml-cohttp), but `opam` won't let me, and I can't figure out why or what I can do to resolve this. Here is the output I get when I try to upgrade:

```
~ $ opam show -f version cohttp
2.5.4
~ $ opam upgrade cohttp --verbose
Everything as up-to-date as possible.
The following newer versions couldn't be installed:
  - cohttp.3.0.0: unmet availability conditions: false
However, you may "opam upgrade" these packages explicitly, which will ask permission to downgrade or uninstall the conflicting packages.
Nothing to do.
```

I'm perplexed by the "unmet availability conditions: false" line. After extensive googling I still haven't been able to figure out what the problem is. I'm very reluctant to build my project on an old version of this package, but I can't figure out how to get an up-to-date version installed.

**Comment by mseri** [comment]
the release of cohttp.3.0.0 is marked as unavailable as there are probably more breaking changes pending and will be superseded by a 3.0.1 release “soon” (which is also why there is no announcement). To try 3.0.0 you can run `opam pin cohttp.3.0.0 --dev-repo`

**Comment by spinlock-ml** [comment]
Thanks!
