### ISSUE TITLE
Open 'ocaml-manual' with odig

### ISSUE THREAD

**Issue by MisterDA** [ocaml/opam-repository#17899]
The OCaml manual that is provided by the `ocaml-manual` package could be opened with odig. The manual is located in `.opam/default/doc/ocaml-manual/index.html`. `odig doc ocaml` opens Stdlib, Threads, and Compiler libs documentation.
`odig pkg` does not show `ocaml-manual`.

```
$ odig doc ocaml-manual
odig: [ERROR] Unknown package ocaml-manual.
```

**Comment by kit-ty-kate** [comment]
Isn't that rather an issue for https://github.com/b0-system/odig ? cc @dbuenzli

**Comment by dbuenzli** [comment]
The OCaml manual is not an `odoc` docset (yet ?-) so `odig doc ocaml-manual` won't show anything. Simply do `odig doc` and click on the link to the manual on the top-right menu of the index page.
