### ISSUE TITLE
System camlp4 no longer available on homebrew

### ISSUE THREAD

**Issue by patricoferris** [ocaml/opam-repository#18138]
With an `ocaml-system` compiler, trying to install `camlp4` results in getting a system version of `camlp4` from the OS package manager. On macOS this is defined for `homebrew` (https://github.com/ocaml/opam-repository/blob/master/packages/camlp4/camlp4.4.12+system/opam#L13) but as far as I can tell it is no longer available from any of the homebrew formulae. It was deleted in March 2020 https://github.com/Homebrew/homebrew-core/commit/880ac4197da50b1e8ba7c24961c88b14e2868029 currently if you run:

`brew install camlp4`

it results in: 

```
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "camlp4".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

I'm guessing the right thing to do is to remove that line for macOS homebrew in the `camlp4.4.12+system` package?

Also, I know pretty much nothing about Debian or how their packages work, but it looks like https://packages.debian.org/buster/camlp4 maybe only 4.05 is there so maybe that needs removing too?

(cc: @dra27 who helped me with this :))

**Comment by avsm** [comment]
Removed in #18261
