### ISSUE TITLE
conf-libev.4-1 finding libev on macOS M1 with /opt/homebrew installation

### ISSUE THREAD

**Issue by lindig** [ocaml/opam-repository#18167]
I'm not sure how to report this properly. The opam file for conf-libev.4-1 asks to file issues here:

`conf-libev.4-1` fails to find libev on macOS with a homebrew installation of libev, which is located under `/opt/homebrew/` for the new ARM-based Macs :

```
lindig@mini conf-libev.4-11 % sh build.sh 
testing for libev: ............................. unavailable
```

However, with a bit of direction it does find it:

```
lindig@mini conf-libev.4-11 % C_INCLUDE_PATH=/opt/homebrew/include LIBRARY_PATH=/opt/homebrew/lib sh build.sh
testing for libev: ............................. available
```

Is there a way to include this location in `conf-libev.4-11`?

**Comment by lindig** [comment]
I suspect all that is needed is adding `/opt/homebrew` here:

```
let search_paths = uniq (List.append [
  "/usr";
  "/usr/local";
  "/opt";
  "/opt/local";
  "/sw";
  "/mingw";] env_paths)
```

**Comment by mseri** [comment]
Can you try it locally and see if it fixes the issue for you? I'd be happy to merge the PR with the fix

**Comment by mseri** [comment]
I think this needs also some extra change somewhere.
The `discover.ml` file in there mentions:
```ocaml
(* Keep that in sync with the list in myocamlbuild.ml *)
```
I wonder to what package that belongs/belonged

**Comment by lindig** [comment]
I'll try it locally later today. Obviously this is just a test that look for the header files. Any actual package still needs to find the library to link against it. I'm not familiar with this distribution of labour between `conf-libev` and packages using `libev`.

**Comment by lindig** [comment]
The change (adding `/opt/homebrew`) makes it work for me and consequently I could install packages that depend on this one. I am still a bit mystified how all of this fits together because any code using `libev` must look in the correct place to begin with.

**Comment by mseri** [comment]
@kit-ty-kate has attempted a pkg-config based approach using conf-ssl which may simplify things moving forward. Of course, it depends a lot on what packages are doing to then link the libraries, if they use pkg-comfig or not, if they override the search paths, ...

in this case I don’t know, I would make a PR for a new version of conf-libev which includes the new search path

**Comment by zapashcanon** [comment]
I believe that [leveldb#15](https://github.com/mfp/ocaml-leveldb/issues/15) is exactly the same but for conf-leveldb. @charlesetc

@mseri is it needed to add @lindig's patch to every conf-* package ? Or does it fix the search paths for all packages ? I don't know where `let search_paths` is defined so I can't tell.

**Comment by mseri** [comment]
The patch is specific to conf-libev, and still would require whatever library using it (in this case lwt) to update its linking.

Right now every conf- package uses a different method, and the big issue is usually mac os with brew, which is very inconsistent in its paths. As an example, macports updates the PKG_CONFIG_PATH, so packages using pkg-config work out of the box also there.

**Comment by mseri** [comment]
For conf-leveldb the issue is here: https://github.com/ocaml/opam-repository/blob/master/packages/conf-leveldb/conf-leveldb.1/opam#L7

There is no flag passed and homebrew puts the files in a non-standard position. Ideally we should use pkg-config with the correct PKG_CONFIG_PATH or proceed with a route like the one taken for conf-ssl.3

**Comment by mseri** [comment]
@zapashcanon can you check one thing for me?
Does it work if you replace L7 above with
```
depends: ["conf-pkg-config" {build}]
build: [
  ["pkg-config" "leveldb"]
]
```

**Comment by zapashcanon** [comment]
OK, I see. I hoped homebrew would be consistent and it would be the same fix for every package...

I don't have access to macOS or a M1 machine. @charlesetc would be the one to ask. :)

**Comment by mseri** [comment]
@zapashcanon apparently my comment was partially incorrect. Homebrew does the right thing for packages in the default include paths but does not for many other which have nonstandard ones, like x11 or libssl

**Comment by charlesetc** [comment]
I'm not entirely sure how to check this, but I tried to clone this repo, made the following change:
```
$ git diff
diff --git a/packages/conf-leveldb/conf-leveldb.1/opam b/packages/conf-leveldb/conf-leveldb.1/opam
index 75bc6fdc30..1641c4161a 100644
--- a/packages/conf-leveldb/conf-leveldb.1/opam
+++ b/packages/conf-leveldb/conf-leveldb.1/opam
@@ -4,7 +4,10 @@ maintainer: "mfp@acm.org"
 bug-reports: "https://github.com/ocaml/opam-repository/issues"
 homepage: "http://code.google.com/p/leveldb/"
 license: "BSD-3-Clause"
-build: [["cc" "-c" "test.cc"]]
+depends: ["conf-pkg-config" {build}]
+build: [
+  ["pkg-config" "leveldb"]
+  ]
 depexts: [
   ["libleveldb-dev"] {os-family = "debian"}
   ["libleveldb-dev"] {os-family = "ubuntu"}
```
and then ran `opam pin conf-leveldb .` in the `packages/conf-leveldb/conf-leveldb.1` directory, which failed with the following: 

```
$ opam pin conf-leveldb .
[NOTE] Package conf-leveldb is already pinned to file:///Users/charleschamberlain/code/opam-repository/packages/conf-leveldb/conf-leveldb.1 (version 1).
[conf-leveldb.1] no changes from file:///Users/charleschamberlain/code/opam-repository/packages/conf-leveldb/conf-leveldb.1
conf-leveldb is now pinned to file:///Users/charleschamberlain/code/opam-repository/packages/conf-leveldb/conf-leveldb.1 (version 1)

The following actions will be performed:
  ∗ install conf-leveldb 1*
Do you want to continue? [Y/n] y
[conf-leveldb.1] synchronised from file:///Users/charleschamberlain/code/opam-repository/packages/conf-leveldb/conf-leveldb.1

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of conf-leveldb failed at "/Users/charleschamberlain/.opam/opam-init/hooks/sandbox.sh build pkg-config leveldb".

#=== ERROR while compiling conf-leveldb.1 =====================================#
# context     2.0.8 | macos/arm64 | ocaml-base-compiler.4.12.0 | pinned(file:///Users/charleschamberlain/code/opam-repository/packages/conf-leveldb/conf-leveldb.1)
# path        ~/.opam/default/.opam-switch/build/conf-leveldb.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build pkg-config leveldb
# exit-code   1
# env-file    ~/.opam/log/conf-leveldb-81931-c61e7b.env
# output-file ~/.opam/log/conf-leveldb-81931-c61e7b.out



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build conf-leveldb 1
└─ 
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    leveldb

[NOTE] Pinning command successful, but your installed packages may be out of sync.
```
Hope that helps! Let me know if there's anything more I can do to test.

**Comment by mseri** [comment]
Thanks for testing it. Looks like this library does is not shipped with a pc file for pkg-config :(

**Comment by thangngoc89** [comment]
I can't install leveldb recently as well on macOS 10.14.6 (non-M1).

Here is the error log: https://gist.github.com/thangngoc89/091cc21e3907f50c207cf55d5330135d

I edited and pinned `conf-level` with this modification:

```diff
──────────────────────────────────────────────────────────────────────────────────
modified: packages/conf-leveldb/conf-leveldb.1/opam
──────────────────────────────────────────────────────────────────────────────────
@ packages/conf-leveldb/conf-leveldb.1/opam:7 @ maintainer: "mfp@acm.org"
bug-reports: "https://github.com/ocaml/opam-repository/issues"
homepage: "http://code.google.com/p/leveldb/"
license: "BSD-3-Clause"
build: [["cc" "-c" "test.cc"]]
build: [["cc" "-std=c++11" "-c" "test.cc"]]
depexts: [
  ["libleveldb-dev"] {os-family = "debian"}
  ["libleveldb-dev"] {os-family = "ubuntu"}
```

Happy to send a PR to fix this but I'm not sure if this would work on other OSes

**Comment by mseri** [comment]
Yes, thanks. Can you please send it as a new release `conf-leveldb.2`?

**Comment by mseri** [comment]
If possible not replacing the pkg-config check, just overriding it in the case of homebrew on mac
