### ISSUE TITLE
Remark: speed of CI

### ISSUE THREAD

**Issue by Kakadu** [ocaml/opam-repository#18186]
We have two kinds of CI now: camelus and opam-ci. I have a feeling that the former runs much slower then the second one. I want to say that very often I'm waiting for camelus much longer that opam-ci. It feels very weird because  I can observe that camelus only checks that opam file is OK and doesn't recompile anything.

**Comment by mseri** [comment]
It is there historically imho at this stage. In the past it was useful to catch issues not seen in the CI a few times, it does no harm to leave in the extra check.

Overall you should not worry much about it,: on the one hand by the time we review the PRs it has usually completed, on the other if everything is green and the review does not point at any issue, we would like merge even if Camelus is still pending
