### ISSUE TITLE
In opam-base-compiler packages, do not suggest to file a bug report in ocaml/ocaml

### ISSUE THREAD

**Issue by xavierleroy** [ocaml/opam-repository#18479]
Currently, a failure in `opam switch create` prints a suggestion to file a bug in the ocaml/ocaml repository, e.g. https://github.com/ocaml/ocaml/issues/10331 .  This seems to come from the opam-base-compiler OPAM files, e.g. https://github.com/ocaml/opam-repository/blob/e248948afd8b084309f2db5165d753f2b056fc16/packages/ocaml-base-compiler/ocaml-base-compiler.4.11.1/opam#L34-L37

I can't remember the last time when the failure was an issue with the OCaml core package.  Recent "bug" reports were due to missing software components (e.g. XCode command-line tools not installed on macOS) or an unsupported platform (e.g. macOS-ARM64 with 4.11.1).  This is just noise in the ocaml/ocaml repository.

Could we please remove this suggestion from the ocaml-base-compiler packages?

**Comment by avsm** [comment]
Thanks for the prompt; I've done this in #18485 and also changed the 'bug-reports' fields. We can easily transfer issues across to ocaml/ocaml where appropriate, once they've been triaged.
