### ISSUE TITLE
Perhaps some bad data got into the repo? (ocaml.4.13.0 exists, but not ocaml-base-compiler.4.13.0)

### ISSUE THREAD

**Issue by chetmurthy** [ocaml/opam-repository#18547]
I just did an "opam update" and afterward, found that the "opam upgrade" offered an "ocaml.4.13.0".  Digging a little further, it's a virtual package that depends on "ocaml-base-compiler", but that package has no version at 4.13.0.  I fear that some dirty data entered the repo?  I attach what hopefully is useful info: last line is really the key one, where "4.13.0" appears.

```
$ opam version
opam: unknown command `version'.
Usage: opam COMMAND ...
Try `opam --help' for more information.
$ opam --version
2.1.0~beta3
$ opam repository list
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all configured repositories.

<><> Repository configuration for switch 4.12.0 <><><><><><><><><><><><><><><><>
 1 default https://opam.ocaml.org
$ opam show ocaml 

<><> ocaml: information on all versions <><><><><><><><><><><><><><><><><><><><>
name                   ocaml
all-installed-versions 4.00.0 [4.00.0]  4.00.1 [4.00.1]  4.01.0 [4.01.0]  4.02.0 [4.02.0]  4.02.1 [4.02.1]  4.02.2 [4.02.2]  4.02.3 [4.02.3]  4.03.0
                       [4.03.0]  4.04.0 [4.04.0]  4.04.1 [4.04.1]  4.04.2 [4.04.2]  4.05.0 [4.05.0]  4.06.0 [4.06.0]  4.06.1 [4.06.1]  4.07.0 [4.07.0]
                       4.07.1 [4.07.1]  4.08.0 [4.08.0]  4.08.1 [default ocaml-base-compiler.4.08.1 4.08.1]  4.09.0 [4.09.0]  4.10.0 [4.10.0]  4.10.1
                       [4.10.1]  4.10.2 [4.10.2]  4.11.0 [4.11.0]  4.11.1 [4.11.1]  4.11.2 [4.11.2]  4.12.0 [4.12.0]
all-versions           3.07  3.07+1  3.07+2  3.08.0  3.08.1  3.08.2  3.08.3  3.08.4  3.09.0  3.09.1  3.09.2  3.09.3  3.10.0  3.10.1  3.10.2  3.11.0
                       3.11.1  3.11.2  3.12.0  3.12.1  4.00.0  4.00.1  4.01.0  4.02.0  4.02.1  4.02.2  4.02.3  4.02.4  4.03.0  4.03.1  4.04.0  4.04.1
                       4.04.2  4.04.3  4.05.0  4.05.1  4.06.0  4.06.1  4.06.2  4.07.0  4.07.1  4.07.2  4.08.0  4.08.1  4.08.2  4.09.0  4.09.1  4.09.2
                       4.10.0  4.10.1  4.10.2  4.10.3  4.11.0  4.11.1  4.11.2  4.11.3  4.12.0  4.12.1  4.13.0
```

**Comment by kit-ty-kate** [comment]
The `ocaml` package can either depend on `ocaml-base-compiler`, `ocaml-system` or `ocaml-variants`. The later has a compatible version `4.13.0+trunk` which currently installs trunk. This is expected.

**Comment by chetmurthy** [comment]
This still seemed a bit odd to me, so I did some further investigation.  I have two OPAM installations on my machine: 2.0.5 and 2.1.0~beta3.  I did the following:
(1) removed the 4.12.0 switch
(2) created it again
(3) and then installed some packages
(4) and then did opam update, followed by opam upgrade

with 2.0.5, I did not get the error-message about ocaml 4.13.0; with 2.1.0-beta3, I did get that message.

I don't know what the status of opam 2.1.0 is, but I'd be happy to set up an instance and check it out, if you think it's worthwhile.

**Comment by mseri** [comment]
I cannot reproduce this with `opam 2.1.0~beta4`, maybe it was a bug in the beta?

**Comment by chetmurthy** [comment]
A little late here, but I'll install beta4 and see if it still occurs.

**Comment by chetmurthy** [comment]
@mseri, I can confirm reproducing your report.  That is to say:

(1) with 2.1.0-beta4, the bug I reported does not occur
(2) with 2.1.0-beta3, it *does* occur.

Thank you for thinking of and checking the beta4.  I'm now on beta4 also.
