### ISSUE TITLE
Make sure incompatibilities are properly represented as conflicts in the metadata

### ISSUE THREAD

**Issue by rdicosmo** [ocaml/opam-repository#1864]
If a package A conflicts with (some versions of) a package B, its metadata must contain an appropriate   conflicts:  line, otherwise the solvers will not know about this conflict and may provide unsound solutions.

As an example, all the versions of lwt in the current repository contain a line

 depopts: .... "react" {< "1.0.0"} 

that hints at such an incompatibility, but lack the 

conflicts: [ "react" { >= "1.0.0"} ]
line which is needed for proper dependency handling.

Package maintainers should look at their package metadata for instances of such patterns, and update their medatada accordingly.

**Comment by samoht** [comment]
I believe this is now fixed.
