### ISSUE TITLE
conf-gfortran failing on macos with homebrew

### ISSUE THREAD

**Issue by mseri** [ocaml/opam-repository#18677]
```
#=== ERROR while compiling conf-gfortran.0 ====================================#
# context     2.0.8 | macos/x86_64 | ocaml-system.4.11.2 | git+https://github.com/ocaml/opam-repository.git
# path        ~/.opam/ocaml-system.4.11.2/.opam-switch/build/conf-gfortran.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build gfortran --version
# exit-code   71
# env-file    ~/.opam/log/conf-gfortran-21419-899ac0.env
# output-file ~/.opam/log/conf-gfortran-21419-899ac0.out
### output ###
# sandbox-exec: execvp() of 'gfortran' failed: No such file or directory
```

Happens in the github actions, I don't have a homebrew installation to see what is going on (the gcc depext is installed correctly)

**Comment by kit-ty-kate** [comment]
mmh, I tried on a local macOS with homebrew and I could not reproduce (`gfortran` is indeed available in `/usr/local/bin`). Could you link the build logs if you can?

**Comment by mseri** [comment]
Sure: all here https://github.com/mseri/owl_ode/actions/runs/836049752

**Comment by mseri** [comment]
Seems to be an issue with the github actions, it is not happening reliably, just once every often. I don’t think it has to do with the conf package, thanks @kit-ty-kate
