### ISSUE TITLE
Bad checksum errors

### ISSUE THREAD

**Issue by mimoo** [ocaml/opam-repository#18738]
I've been getting these errors when installing dependencies with opam:

```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - fix.20200131: Bad checksum
          - menhir.20200211: Bad checksum
          - menhirLib.20200211: Bad checksum
          - menhirSdk.20200211: Bad checksum
```

**Comment by ivg** [comment]
This is a network connectivity error, quite often seen on CI, probably something bad with fix and menhir hostings, which is https://gitlab.inria.fr/ for both. 

Usually, it self-fixes after a couple of hours. But indeed it is quite annoying. We can probably mirror those packages, but ideally, we should ask maintainers to provide more reliable hosting, like github or gitlab.

**Comment by mseri** [comment]
I was trying them now. In this specific instance it is related to a new authentication requirement from the host: https://github.com/ocaml/opam-repository/pull/18529#issuecomment-842415400
The url were updated 9 days ago: https://github.com/ocaml/opam-repository/pull/18697

Trying it locally it works fine, @mimoo  you need to make sure that the Circle CI job uses an updated enough snapshot of opam (maybe add a `opam update` call or point at a more recent opam-repository commit, I don't know how that job works).
