### ISSUE TITLE
OCaml 4.13 Release Readiness

### ISSUE THREAD

**Issue by Octachron** [ocaml/opam-repository#18791]
This issue tracks the build and readiness information of core platform tools and libraries in preparation for the OCaml 4.13 release. It’s intended as a meta-issue / holding place for TODO lists and links to other milestones/issues rather than general discussion (which is welcomed on Discuss or on linked issues).

Packages that are fixed upstream, have a PR ready, or can be used as-is for testing purpose, are in https://github.com/kit-ty-kate/opam-alpha-repository

## Platform tools:

- [x] opam
- [x] dune
- [x] merlin (_Preview release available_ - https://github.com/ocaml/merlin/pull/1381)
- [x] lsp-server / vscode-plugin (_Preview release available_ - https://github.com/ocaml/ocaml-lsp/pull/506)
- [x] odoc
- [x] ocamlformat
- [x] ocp-indent

## Ecosystem:

- [x] ocamlfind
- [x] ocamlbuild
- [x] ppxlib
- [x] ocaml-migrate-parsetree
- [x] mdx
- [x] utop
- [x] dune-release
- [x] opam-publish

## Infrastructure:

- [x] ocaml.org
- [x] docker base containers (https://github.com/ocurrent/docker-base-images/pull/115)
- [x] ocaml-ci  (https://github.com/ocurrent/ocaml-ci/pull/345)
- [x] opam-repo-ci (https://github.com/ocurrent/opam-repo-ci/pull/86)

**Comment by avsm** [comment]
updated the infrastructure bit - no more datakit-ci so replaced it with opam-repo-ci, and marked the containers as working now.

**Comment by kit-ty-kate** [comment]
We've been testing OCaml 4.13 in opam-repo-ci for a few months already, I've updated that as well

**Comment by avsm** [comment]
utop now released

**Comment by dra27** [comment]
lsp-server and merlin are affected by a bug when `-principal` and `-short-paths` are both in use (see https://github.com/ocaml/merlin/issues/1389) which should be fixed by the their final 4.13-compatible releases.
