### ISSUE TITLE
An env var affects the build of coq

### ISSUE THREAD

**Issue by ana-borges** [ocaml/opam-repository#18836]
If `COQ_USE_DUNE` is set, then the opam installation of coq will try to use dune and end up not installing anything.

Steps to reproduce:
```shell
export COQ_USE_DUNE=true
opam switch create test 4.12.0
opam update
opam repo add coq-released https://coq.inria.fr/opam/released
opam install coq -vv # observe dune is being used and an error is produced
```

Cf. https://github.com/coq/coq/issues/14469, https://github.com/coq/opam-coq-archive/issues/1736, and the [zulip discussion](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/Installing.20coq.2Edev.20through.20opam.2C.20missing.20binaries).

**Comment by avsm** [comment]
We do need a coq package maintainer to submit these fixes to the opam-repository by forcing the variable to be unset in the build rules.
