### ISSUE TITLE
[lower bound] ocaml cstruct 1.6.0 sources changed

### ISSUE THREAD

**Issue by mseri** [ocaml/opam-repository#18989]
Error:
```
#=== ERROR while fetching sources for cstruct.1.6.0 ===========================#
OpamSolution.Fetch_fail("https://github.com/mirage/ocaml-cstruct/archive/v1.6.0.tar.gz (Bad checksum, expected md5=3104c76f548aeee8715e3ba0b98c28fe)")
```
The linked archive and the archive at https://opam.ocaml.org/cache/md5/31/3104c76f548aeee8715e3ba0b98c28fe have different contents.

**Comment by hannesm** [comment]
Thanks for your report, this issue has been fixed. I don't exactly know when, but the checksum wasn't modified in opam-repository. :)
