### ISSUE TITLE
Problem with the installation of tuareg

### ISSUE THREAD

**Issue by james-elliot** [ocaml/opam-repository#19024]
When installing tuareg, it complains that emacs-nox is not installed, even when emacs-gtk is installed, which provides the same functionality. Would it be possible to modify the dependency in order to depend on emacs-nox or on emcs-gtk?
Thanks

**Comment by dra27** [comment]
Transferred from opam - this affects the depexts specification on `conf-emacs`

**Comment by GoPavel** [comment]
I guess the actual issue is #21403

**Comment by kit-ty-kate** [comment]
Indeed. Closed as duplicate of https://github.com/ocaml/opam-repository/issues/21403
