### ISSUE TITLE
conf-mpfr fails on Apple Silicon M1 macOS due to /opt/homebrew instead of /usr/local

### ISSUE THREAD

**Issue by vogler** [ocaml/opam-repository#19042]
[Only found #18167 searching for similar issues. Tried to add some keywords in the title.]

`brew install gmp && opam install apron` fails with `fatal error: 'mpfr.h' file not found`.
`C_INCLUDE_PATH=/opt/homebrew/include LIBRARY_PATH=/opt/homebrew/lib opam install apron` installs `conf-mpfr` but then fails when compiling apron with `fatal error: 'gmp.h' file not found`.
(`opam install apron` only succeeded after `ln -s /opt/homebrew/{include,lib} /usr/local/`)

https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location
`echo $HOMEBREW_PREFIX` is `/usr/local` on Intel, but changed to `/opt/homebrew` on ARM and they advise against changing it.

The paths are set here:
https://github.com/ocaml/opam-repository/blob/c0e9300f14d3570da85aad7e6e0ae47484a597a9/packages/conf-mpfr/conf-mpfr.2/opam#L8-L9

Should we add another case for `arch = "arm64" & os = "macos" & os-distribution = "homebrew"`?

Does it make sense for opam to provide some [variable](https://opam.ocaml.org/doc/Manual.html#Global-variables) that can be used for `-I` and `-L`? Otherwise this switching would have to be duplicated in each opam file that does something like this.

**Comment by kit-ty-kate** [comment]
Testing it locally, it seem that mpfr already ship with a pkg-config file:
```
$ pkg-config --libs mpfr
-L/opt/homebrew/Cellar/mpfr/4.1.0/lib -lmpfr -lgmp
```
I’d be more in favour of changing this conf package to use pkg-config instead which is much more general

**Comment by vogler** [comment]
TIL :) Looks good. 
Then it needs `pkg-config` in `depexts`? How many opam packages do that?

**Comment by kit-ty-kate** [comment]
I just opened https://github.com/ocaml/opam-repository/pull/19043

> How many opam packages do that?

Most of the old conf packages do as conf-mpfr currently does but most of the new ones use pkg-config when available (older or more obscure libraries sometimes do not ship with their .pc files)
