### ISSUE TITLE
Missing older versions of psmt2-frontend

### ISSUE THREAD

**Issue by ploc** [ocaml/opam-repository#19086]
Some older versions of psmt2-frontend are missing.

$ opam install psmt2-frontend.0.1
[ERROR] The sources of the following couldn't be obtained, aborting:
          - psmt2-frontend.0.1: Download command failed

$ opam install psmt2-frontend.0.2
[ERROR] The sources of the following couldn't be obtained, aborting:
          - psmt2-frontend.0.2: Download command failed

$ opam install psmt2-frontend.0.3.0
[ERROR] The sources of the following couldn't be obtained, aborting:
          - psmt2-frontend.0.3.0: Download command failed

The following ones (0.3.1, 0.4.0) work.

**Comment by kit-ty-kate** [comment]
I can't reproduce the issue. Could you try again? If it works it must have been a temporary network.

If not, could you send the log for `opam install -vvv psmt2-frontend.0.1` (verbose mode). I suspect you don't have `unzip`, in which case, what distribution do you have? It would be a bug there (tar, gzip, bz2, lzma and zip are runtime dependencies)
