### ISSUE TITLE
Unable to install infer.

### ISSUE THREAD

**Issue by himgupta229** [ocaml/opam-repository#19222]
Hi,

I am trying to install infer on my system but unable to do so.
OS - Mac OS Big Sur (11.2.2)(20D80)
Chip - Apple M1

I am getting [this](https://gist.github.com/himgupta229/e991027cd27e7fde08faff6d633ee0d0) error.

**Comment by kit-ty-kate** [comment]
Hi, this looks like an issue on Homebrew's side. Could you transfer this issue to their bug tracker: https://github.com/Homebrew/homebrew-core/issues
This issue was also encountered by them a few months ago: https://github.com/Homebrew/homebrew-core/pull/73440#issuecomment-804469245
