### ISSUE TITLE
There should be a conf package that installs adwaita-icon-theme-full on Ubuntu

### ISSUE THREAD

**Issue by JasonGross** [ocaml/opam-repository#19243]
CoqIDE, at least, requires `adwaita-icon-theme-full`.  I'm not sure whether this means that we need a separate conf package, or if the existing conf package should be changed, but certainly one of these needs to happen.

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/14769#issuecomment-896963037_

**Comment by kit-ty-kate** [comment]
cc @MSoegtropIMC

**Comment by MSoegtropIMC** [comment]
@JasonGross : can you add a bit of background?

- are you getting error messages about missing icons if the normal adwaita icon package is installed?
- which icon package is installed by default on Ubuntu?

**Comment by JasonGross** [comment]
(The behavior of https://github.com/coq/coq/issues/14324 is with adwaita-icon-theme installed)

**Comment by MSoegtropIMC** [comment]
Ah, so we are discussing running GUI software on a headless Ubuntu - this is always a bit of a tricky business. It would be close to a miracle (or a sign of good quality of the opam and system package dependencies) if this would be the only issue.

I think we should investigate what adwaita packages other systems have (if they also distinguish between full and non full). If this is Ubuntu specific I would suggest to change the opam package. If other systems have this as well, I would suggest to have separate packages for the full and non full package and adjust the CoqIDE opam package.

Sorry I am super busy these days - otherwise I would do this myself. You know the usual package search engines? I left links to them in comments in some of the system opam packages I created, but would have to look it up myself.

**Comment by JasonGross** [comment]
> You know the usual multi platform package search engines?

>     # The package name for many Linux/BSD/macOS/cygwin/msys platforms can be searched here (thanks Théo)
>     #   https://repology.org specifically https://repology.org/project/bison/versions
>     #   Not listed above but supported by opam are suse, oraclelinix, ol, rhel

at e7217adbc4bf7397ced7a3bc522167cbcbd33b1d by doing `for i in $(git log --author='Michael Soegtrop' | grep '^commit' | sed s'/commit //g'); do git show $i; done | less` and reading through the output.

Interestingly, repology.org gives [nothing for adwaita-icon-theme-full](https://repology.org/projects/?search=adwaita-icon-theme-full&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=), even though [Ubuntu package search](https://packages.ubuntu.com/search?keywords=adwaita-icon-theme&searchon=names&section=all) has it.  [pkgs.org has adwaita-icon-theme-full only for Ubuntu](https://pkgs.org/search/?q=adwaita-icon-theme-full)

- Debian has [only adwaita-icon-theme](https://packages.debian.org/search?keywords=adwaita-icon-theme)
- Not sure where the package manager for amzn is online, [repology.org lists only adwaita-icon-theme](https://repology.org/projects/?search=adwaita-icon-theme&maintainer=&category=&inrepo=amazon_2&notinrepo=&repos=&families=&repos_newest=&families_newest=)
- Not sure what ol is
- [rhel has `adwaita-icon-theme` (Adwaita icon theme) and `adwaita-icon-theme-devel` (Development files for adwaita-icon-theme)](https://access.redhat.com/downloads/content/package-browser)
- Not sure where centos package search is, repology.org lists only adwaita-icon-theme for it
- [fedora has only adwaita-icon-theme](https://src.fedoraproject.org/rpms/adwaita-icon-theme)
- [AUR has adwaita-icon-theme-git](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=adwaita-icon-theme&outdated=&SB=n&SO=a&PP=50&do_Search=Go) and doesn't have adwaita-icon-theme, so, uh, it looks like the ArchLinux packages might be wrong

I'm disinclined to keep searching manually, since it looks like adwaita-icon-theme-full is just Ubuntu.  So I guess the fix is to make the Ubuntu package be adwaita-icon-theme-full

**Comment by kit-ty-kate** [comment]
> So I guess the fix is to make the Ubuntu package be adwaita-icon-theme-full

Sounds sensible indeed

**Comment by MSoegtropIMC** [comment]
> So I guess the fix is to make the Ubuntu package be adwaita-icon-theme-full

Yes, looking at your extensive data (thanks!) I agree that this is the most sensible solution.

`ol` is oracle linux (afaik).

**Comment by MSoegtropIMC** [comment]
I will take care of it.
