### ISSUE TITLE
Opam switch create fails - build parallelism?

### ISSUE THREAD

**Issue by nishand17** [ocaml/opam-repository#19373]
When trying to run ```opam switch create 4.12.0```, I get:
```
⬇ retrieved ocaml-base-compiler.4.12.0  (cached)
[ERROR] The compilation of ocaml-base-compiler.4.12.0 failed at "make -j7".

#=== ERROR while compiling ocaml-base-compiler.4.12.0 =========================#
# context     2.1.0 | macos/x86_64 |  | https://opam.ocaml.org#5c5a526e
# path        ~/.opam/4.12.0/.opam-switch/build/ocaml-base-compiler.4.12.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j7
# exit-code   2
# env-file    ~/.opam/log/ocaml-base-compiler-65549-347516.env
# output-file ~/.opam/log/ocaml-base-compiler-65549-347516.out
### output ###
# [...]
# /opt/local/bin/ranlib: object: libcamlrun.a(interp.b.o) malformed object (unknown load command 1)
# ar: internal ranlib command failed
# make[2]: *** [libcamlrun.a] Error 1
# make[2]: *** Waiting for unfinished jobs....
# /opt/local/bin/ranlib: object: libcamlrund.a(interp.bd.o) malformed object (unknown load command 1)
# ar: internal ranlib command failed
# make[2]: *** [libcamlrund.a] Error 1
# /opt/local/bin/ranlib: object: libcamlruni.a(interp.bi.o) malformed object (unknown load command 1)
# ar: internal ranlib command failed
# make[2]: *** [libcamlruni.a] Error 1
# make[1]: *** [coldstart] Error 2
# make: *** [world.opt] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build ocaml-base-compiler 4.12.0
└─
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray         base
│ ∗ install base-threads          base
│ ∗ install base-unix             base
│ ∗ install ocaml-options-vanilla 1
└─

<><> ocaml-base-compiler.4.12.0 troubleshooting <><><><><><><><><><><><><><>  🐫
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at
   https://github.com/ocaml/opam-repository/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
```

Opam config report: 
```
# opam config report
# opam-version         2.1.0
# self-upgrade         no
# system               arch=x86_64 os=macos os-distribution=homebrew os-version=10.15.6
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 7
# repositories         1 (http) (default repo at 5c5a526e)
# pinned               0
# current-switch       4.12.0
```

Any suggestions on solutions? I am on MacOS Catalina and saw [this thread](https://github.com/ocaml/opam/issues/4112), but wasn't sure how relevant it was

**Comment by kit-ty-kate** [comment]
Might it be a similar issue as https://github.com/ocaml/opam-repository/issues/19374 ?

**Comment by dbuenzli** [comment]
> /opt/local/bin/ranlib:

It is, this should point to /usr/bin/ranlib

You have a local install of binutils that is getting in the way.

**Comment by nishand17** [comment]
I'm not super sure, when I run env, type ld, type cc I get this 
<img width="965" alt="Screen Shot 2021-08-30 at 3 55 30 PM" src="https://user-images.githubusercontent.com/12012798/131416031-c0bea555-36e3-41ee-a628-7331232bc19e.png">

My PATH looks pretty funny - brew unlink binutils brought up a "no such keg", so I don't think that helps, right?

**Comment by dbuenzli** [comment]
It seems you installed binutils in some other way (`macports` ?), homebrew doesn not install stuff in `/opt/local/bin`, it install stuff in `/usr/local`.

**Comment by dbuenzli** [comment]
It's `type ranlib` that you should check.

**Comment by nishand17** [comment]
```type ranlib``` gives "ranlib is /opt/local/bin/ranlib" - what do I do with this?

**Comment by kit-ty-kate** [comment]
This tells you the `runlib` you are using comes from Macports. This messes up the default C compiler and linker on macOS which does not expect this to happen (mismatched tools).

The solution here is to either:
* move `/opt/local/bin` and `/opt/local/sbin` at the end of `PATH` instead of first before `/usr/bin`
* or find the macports package that installed `ranlib` and uninstall it

cc @pmetzger

**Comment by nishand17** [comment]
Apologies for the continuous questions, I'm a little new to this - I'm looking into editing my .bash_profile to set PATH (is this the right method?), and this is what I see:

```
# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

##
# Your previous /Users/nishandsouza/.bash_profile file was backed up as /Users/nishandsouza/.bash_profile.macports-saved_2016-11-24_at_11:09:23
##

# MacPorts Installer addition on 2016-11-24_at_11:09:23: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


test -r /sw/bin/init.sh && . /sw/bin/init.sh

# added by Miniconda2 4.2.12 installer
export PATH="/Users/nishandsouza/miniconda2/bin:$PATH"

# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH

# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH

# opam configuration
test -r /Users/nishandsouza/.opam/opam-init/init.sh && . /Users/nishandsouza/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
```

I'm not sure which ones are opt/local/bin+sbin and which is usr/bin - any guidance?

**Comment by nishand17** [comment]
Okay just did that but opam switch create resulted in what I believe is the same output: 

<img width="845" alt="Screen Shot 2021-08-31 at 10 17 52 AM" src="https://user-images.githubusercontent.com/12012798/131547387-7fa0c210-8309-4968-a314-2e00e522ec0b.png">

my PATH var is now ```PATH=/Users/nishandsouza/.opam/4.12.0/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/nishandsouza/miniconda2/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/local/bin:/opt/local/sbin```, so that looks alright.

**Comment by kit-ty-kate** [comment]
mmh the PATH still isn't right, `/opt/local/bin` is present twice: once at the end (good), and the in the middle too (meh). It might be worth making an issue in the macports bugtracker anyway. I believe ranlib shouldn't live in /opt/local/bin by default (unless you moved it there manually in the past)
