### ISSUE TITLE
Bad checksum error, with and without `opam update`

### ISSUE THREAD

**Issue by mooreryan** [ocaml/opam-repository#19474]
I'm not sure if this is an opam issue or a setup-ocaml github actions issue, but I'm having trouble installing opam packages in the context of a GitHub action.

```
$ opam install . --jobs 1 --deps-only --with-doc --with-test
... output ...
[ERROR] The sources of the following couldn't be obtained, aborting:
          - core_kernel.v0.14.2: Bad checksum
          - ppx_optcomp.v0.14.3: Bad checksum

Error: Process completed with exit code 40.
```

I have run that command, as well as running `opam update` first, and get the same answer.

* Here are the logs when running without opam update first: https://pastebin.com/raw/yfYSKUNy
* Here are the logs with `opam update` first: https://pastebin.com/raw/sEGLbFZM
* I created a repository to reproduce the error here: https://github.com/mooreryan/gh_action_checksum_error

Let me know if this should be instead reported on the setup ocaml github action.  Thanks!

**Comment by kit-ty-kate** [comment]
😱 I can reproduce it.. The upstream archives changed for some reason. I've pinged the janestreet maintainers about it

**Comment by kit-ty-kate** [comment]
The tags have been force-pushed back to their original commits. This is now fixed. If you still encounter such issue feel free to reopen it.

Hopefully the upcoming opam 2.2 will make this less of a high-priority with https://github.com/ocaml/opam/pull/4830, if that happens again in the future.

Thanks a lot for your bug-report.

**Comment by mooreryan** [comment]
Thanks for the fast fix!! :tada:
