### ISSUE TITLE
[ci] Test local switch installation

### ISSUE THREAD

**Issue by ejgallego** [ocaml/opam-repository#19809]
Dear opam reposotory devs,

we have found a few cases where opam packages are broken when:
- using a local switch [placed in `_opam`]
- the parent directory includes a `dune-project` file

in this case, dune may misdetect the root, and the package breaks. I'd say that this is a very specific problem of our package [coq] , however, it may be a good idea to test local opam switches in the CI.

**Comment by kit-ty-kate** [comment]
"transferred" (I can't transfer github issues accross different orgs apparently) to https://github.com/ocurrent/opam-repo-ci/issues/137
