### ISSUE TITLE
The result story

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam-repository#19880]
Hello,

- Since OCaml 4.03 a `type ('a, 'b) result = Ok of 'a | Error of 'b` is provided by the OCaml Stdlib (back then called Pervasives).
- Since OCaml 4.08 a `Result` module (with combinators and functions) is provided by the OCaml Stdlib
- There is a opam package called "result" which intention was initially to provide the result type for older OCaml versions. Before 1.5 this was the case. Since 1.5, it additionally provides the functionality from the OCaml 4.08 Stdlib module.

Now, I've been using in quite some packages the OCaml Stdlib Result module heavily (all of them are only supported on OCaml 4.08+ - namly ca-certs, ca-certs-nss, dns, ethernet, http-lwt-client, otr, x509, more to come -- a "git grep '"result" {< "1.5"}'" shows many more packages whose conflicts may be lifted), and the lower-bounds checks are telling me that I need to do something in respect to result < 1.5 (either add a dependency to result >= 1.5 or a conflict with result < 1.5). I don't think this is a good solution. The reasoning is that some libraries depend on result, and thus implicitly the result package is used instead of the Stdlib one.

My preferred solution would be to have result < 1.5 depend on "ocaml" {< "4.08.0"} -- than we'd be in an environment where if result is required (e.g. by lwt) and we have OCaml >= 4.08 (as required by e.g. ca-certs-nss), we'd be sure to have the whole Result module (as expected). I'm happy to PR such a change to opam-repository, but would first be interested (to avoid unneeded CI work) if there are arguments against an upper bound for early (< 1.5) result versions?

//cc @kit-ty-kate (as opam-repo hat) @aantron (who did the last result release) @jeremiedimino @xclerc  (who have been releasing earlier result versions) @avsm @dra27 (from the platform team)

**Comment by hannesm** [comment]
Just as a heads up: the `seq` package is in a similar state as `result 1.0` used to be -- with all current releases won't provide the Seq interface of OCaml 4.14. Since 4.14 is not released yet, eventually you could assign some upper bounds to avoid history repeating.

**Comment by mseri** [comment]
Should we think of releasing seq with the new interface and make all previous version incompatible with 4.14 before it is released?

**Comment by dra27** [comment]
I don't think this is the case, is it? IIUC the `seq` package has always provided an interface which is identical to the Stdlib's one (unlike `result`, which has an extra type alias). `seq.0.1` was always for OCaml 4.06 and earlier and `seq.0.2` and later create a new `Seq` module which uses `include`/`include module type of` on any version of OCaml which includes `Seq`.

**Comment by dra27** [comment]
(you can already see this working in both 4.11 and 4.13 - the `seq` package does not shadow the `cons`, `append` and `unfold` functions in 4.11, etc.)
