### ISSUE TITLE
opam git fetch fails for users who are not authenticated to GitHub

### ISSUE THREAD

**Issue by p4bl0-** [ocaml/opam-repository#19935]
Hi there,

This security policy change from GitHub needs to be taken into account: https://github.blog/2021-09-01-improving-git-protocol-security-github/

People who do not use GitHub or do not have an SSH key associated with their GitHub profile no longer can fetch from GitHub over git:// protocol.

For example, line 48 of `packages/ocaml-lsp-server/ocaml-lsp-server.1.9.0~4.13preview/opam` should be changed from:

    src: "git://github.com/kit-ty-kate/ocaml-lsp.git#413"

to:

    src: "https://github.com/kit-ty-kate/ocaml-lsp.git#413"

I guess other packages may be affected, but since most developers have their SSH keys associated with their GitHub profile it is rarely an issue.

**Comment by kit-ty-kate** [comment]
fixed in https://github.com/ocaml/opam-repository/pull/19932

**Comment by kit-ty-kate** [comment]
> I guess other packages may be affected, but since most developers have their SSH keys associated with their GitHub profile it is rarely an issue.

btw AFAIK it’s broken for everyone, the ssh key is not involved in the git:// protocol
