### ISSUE TITLE
PPA problem

### ISSUE THREAD

**Issue by alana92** [ocaml/opam-repository#19941]
When I try to start the process of installing opam in Ubuntu with this command:

`sudo add-apt-repository ppa:avsm/ppa`

I get the following error(s) after I input my password correctly:

`Cannot add PPA: 'ppa:~avsm/ubuntu/ppa'.`
`ERROR: '~avsm' user or team does not exist.`

Please advise.

**Comment by kit-ty-kate** [comment]
cc @avsm

**Comment by kit-ty-kate** [comment]
I do not use nor maintain the PPA so I cannot help but in the meantime you can use the official installer to install opam:
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
```

**Comment by alana92** [comment]
Thanks. I tried it, but it keeps timing out for some reason.

`curl: (28) Failed to connect to raw.githubusercontent.com port 443: Connection timed out`

There doesn't seem to be anything wrong with my internet connection either.

**Comment by avsm** [comment]
Which version of Ubuntu?

**Comment by alana92** [comment]
It says 2004.2020.424.0. It's Windows Subsystem for Linux.

**Comment by alana92** [comment]
@avsm Sorry it says it's Ubuntu 20.04 LTS, and it is indeed running on Windows Subsystem for Linux (not sure if that's relevant).

**Comment by alana92** [comment]
@avsm It says it's Ubuntu 20.04 LTS, and it is running on Windows Subsystem for Linux (not sure if that's relevant).

**Comment by dra27** [comment]
I think both errors are related - you say your internet connection is fine, but are you able to download anything else in WSL? e.g. `curl -s www.example.com`? Is this WSL 2 or WSL 1 (you should be able to tell by running `wsl -l -v` from a command prompt)

**Comment by dra27** [comment]
Please could you run `curl -s www.example.com` _in WSL_?

**Comment by alana92** [comment]
Sorry, didn't realise it had a separate console from Ubuntu (first time using it). Seems like it just times out, without any feedback. I'm assuming that's not good.

**Comment by dra27** [comment]
Yeah, that suggests that your Hyper-V configuration isn't working and the virtual switches have got messed up. Have you knowingly changed anything on it? (ping @MisterDA who I think has had something similar happen before with Windows docker)

**Comment by alana92** [comment]
Not that I know of, I hadn't even opened the WSL terminal before now. And in Ubuntu I've only tried to run the opam installation.

**Comment by alana92** [comment]
Is it really complicated to adjust the Hyper-V config & virtual switches yourself? Perhaps some kind of app interface that would make it a bit easier? Any suggestions would be greatly appreciated. I'm not very knowledgeable in this area, I'm mostly just trying to get opam to install the Links Programming Language for some experimental web & database projects.

**Comment by alana92** [comment]
@avsm Is the address for opam still correct? Should it not perhaps be any of the following:

`avsm/opam-repository`
`avsm/opam`
`avsm/opam2-ppa `

**Comment by dra27** [comment]
The address of the ppa is correct - add-apt-repository just has lazy error handling.

If you enable the Hyper-V Management tools, then you can see the configuration of the virtual switches directly - they’re a Windows Optional Feature. I’m afraid I’ve never seen a machine which has got itself into this state, so it’s a bit hard to help - once you’ve got a working Ubuntu box (either a VM or in WSL2), opam should be fine, but you have a lower-level problem at the moment!

**Comment by alana92** [comment]
I figured it out. It was my AVG installation that was blocking it, so I temporarily uninstalled it (creating exceptions didn't work). Thanks everyone.
