### ISSUE TITLE
error installing llvm package on mac

### ISSUE THREAD

**Issue by yunlanli** [ocaml/opam-repository#20009]
- issue: `opam intall llvm` failed with error `ld: library not found for -lLLVM-13.`
- system info (Macbook with M1 pro chip): Darwin 21.0.1 Darwin Kernel Version 21.0.1
- `llvm-config --libs`
![image](https://user-images.githubusercontent.com/25857014/141659938-8dd8d9c5-1cbe-41c7-9776-e5b1a898e0e9.png)

![image](https://user-images.githubusercontent.com/25857014/141659767-ba03bee7-cffc-453b-841b-195faf32f742.png)

**Comment by ColMcp** [comment]
I too have hit this problem (Intel-based MacBook). Does anyone have a work-around or suggestion?

**Comment by yunlanli** [comment]
> I too have hit this problem (Intel-based MacBook). Does anyone have a work-around or suggestion?

I got around this issue by installing an older version (9) of LLVM.

**Comment by ColMcp** [comment]
I'll give this a try. Thanks for responding.

**Comment by VisualDevelopment** [comment]
Using an older version while latest is supposed to be working isn't a solution.
Neither is using a different operating system while macOS is supposed to be supported.
This issue has stalled my workflow.
By copying libLLVM-13.dylib to /usr/local/lib, I have managed to bypass this particular error, but it still is failing.
```
[ERROR] The installation of llvm failed at "bash -ex install.sh llvm-config /Users/visualdevel/.opam/default/lib cmake make".

#=== ERROR while installing llvm.13.0.0 =======================================#
# context     2.1.2 | macos/x86_64 | ocaml.4.13.1 | https://opam.ocaml.org#788ed58b
# path        ~/.opam/default/.opam-switch/build/llvm.13.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh install bash -ex install.sh llvm-config /Users/visualdevel/.opam/default/lib cmake make
# exit-code   2
# env-file    ~/.opam/log/llvm-20491-6691dd.env
# output-file ~/.opam/log/llvm-20491-6691dd.out
### output ###
# [...]
# Copying OCaml library component llvm.cmxa to intermediate area
# Copying OCaml library component llvm.a to intermediate area
# Copying OCaml library component llvm.cmi to intermediate area
# Copying OCaml library component llvm.cmti to intermediate area
# Copying OCaml library component llvm.cmt to intermediate area
# Copying OCaml library component llvm.cmx to intermediate area
# Copying OCaml library component dllllvm.dylib to intermediate area
# Error copying file "/Users/visualdevel/.opam/default/.opam-switch/build/llvm.13.0.0/build/bindings/ocaml/llvm/dllllvm.dylib" to "/Users/visualdevel/.opam/default/.opam-switch/build/llvm.13.0.0/build/./lib/ocaml/llvm/".
# make[3]: *** [ocaml_llvm] Error 1
# make[2]: *** [bindings/ocaml/llvm/CMakeFiles/ocaml_llvm.dir/all] Error 2
# make[1]: *** [CMakeFiles/ocaml_all.dir/rule] Error 2
# make: *** [ocaml_all] Error 2
```
Please fix this. I'll be glad to help test solutions.
I would fix this by myself, but I have no idea where the error is coming from.

**Comment by kit-ty-kate** [comment]
I've had this error myself yesterday and haven't been able to find a solution yet

**Comment by VisualDevelopment** [comment]
Interesting.

**Comment by kit-ty-kate** [comment]
Ok I have a fix, I’ll send it in the next hour or so

**Comment by VisualDevelopment** [comment]
For the dllllvm.dylib issue, or for both -lLLVM-13 and dllllvm.dylib?

**Comment by kit-ty-kate** [comment]
both

**Comment by kit-ty-kate** [comment]
Could anyone double-check https://github.com/ocaml/opam-repository/pull/20324
```
opam repository add tmp git+https://github.com/kit-ty-kate/opam-repository.git#fix-llvm-macos
```

Then to remove the repository when you’re done with it:
```
opam repository remove tmp
```

**Comment by VisualDevelopment** [comment]
Well, it does install successfully, but I have not tested whether something using llvm works correctly
