### ISSUE TITLE
New menhir.20211125 does not compile alt-ergo.2.4.1 with OCaml <=4.10.1

### ISSUE THREAD

**Issue by maroneze** [ocaml/opam-repository#20107]
I'm having this issue:

```
      ocamlc src/plugins/AB-Why3/.ABWhy3Plugin.objs/byte/aBWhy3Plugin__Why3_parser.{cmo,cmt} (exit 2)
(cd _build/default && /home/andr/.opam/4.08.1-updated/bin/ocamlc.opt -w -40 -bin-annot -g -bin-annot -I src/plugins/AB-Why3/.ABWhy3Plugin.objs/byte -I /home/andr/.opam/4.08.1-updated/lib/alt-ergo-lib -I /home/andr/.opam/4.08.1-updated/lib/alt-ergo-parsers -I /home/andr/.opam/4.08.1-updated/lib/camlzip -I /home/andr/.opam/4.08.1-updated/lib/num -I /home/andr/.opam/4.08.1-updated/lib/ocplib-simplex -I /home/andr/.opam/4.08.1-updated/lib/psmt2-frontend -I /home/andr/.opam/4.08.1-updated/lib/seq -I /home/andr/.opam/4.08.1-updated/lib/stdlib-shims -I /home/andr/.opam/4.08.1-updated/lib/zarith -I /home/andr/.opam/4.08.1-updated/lib/zip -intf-suffix .ml -no-alias-deps -open ABWhy3Plugin -o src/plugins/AB-Why3/.ABWhy3Plugin.objs/byte/aBWhy3Plugin__Why3_parser.cmo -c -impl src/plugins/AB-Why3/why3_parser.ml)
File "src/plugins/AB-Why3/why3_parser.ml", line 461, characters 2-3051:
461 | ..fun _menhir_env _menhir_stack _menhir_s _v ->
462 |     match _menhir_s with
463 |     | MenhirState38 ->
464 |         let (_menhir_env : _menhir_env) = _menhir_env in
465 |         let (_menhir_stack : ('freshtv1629 * _menhir_state * 'tv_type_decl) * Lexing.position) = Obj.magic _menhir_stack in
...
510 |          in
511 |         (_menhir_goto_decl _menhir_env _menhir_stack _menhir_s _v : 'freshtv1632)) : 'freshtv1634)) : 'freshtv1636) : 'freshtv1638)) : 'freshtv1640)
512 |     | _ ->
513 |         _menhir_fail ()
Error: This definition has type
         'ttv_tail.
           _menhir_env ->
           'ttv_tail -> _menhir_state -> 'tv_type_decl list -> 'freshtv1630
       which is less general than
         'ttv_tail 'ttv_return.
           _menhir_env ->
           'ttv_tail -> _menhir_state -> 'tv_type_decl list -> 'ttv_return
```

If I switch to OCaml >= 4.11.1, then alt-ergo compiles again without problems.

I think we'll have to blacklist menhir.20211125 from alt-ergo, at least when `ocaml <= 4.10.1`.

**Comment by maroneze** [comment]
Is is reasonable to add a `depends` with a disjunction, such as `"ocaml" {>= "4.11.1" | "menhir" < "20211125"}`?

**Comment by mseri** [comment]
In principle yes, but I don't think that would work: I think you need `"ocaml" {>= "4.11.1" | menhir:version < "20211125"}` or something like that to specify that constraint

**Comment by kit-ty-kate** [comment]
```
"menhir" {>= "<your-usual-constraint>"}
"menhir" {< "20211125" & ocaml:version < "4.10.2"}
```
will work for that

**Comment by toots** [comment]
Similar error here: https://github.com/savonet/liquidsoap/issues/2083

Weirdly, it compiles on `liquidsoap.2.0.0` with pretty much the same code and deps as `2.0.0~rc1`, which does not compile. See: https://github.com/savonet/liquidsoap/issues/2083

**Comment by kit-ty-kate** [comment]
mmh, there seems to be a similar error in js_of_ocaml as well. I think this is getting bad enough that we might need to restrict menhir.20211125 itself to OCaml >= 4.11. I’ll make a PR right now

**Comment by TheRealMattLear** [comment]
Hi,

I'm still seeing the same problem occur in relation to the liquidsoap project on CentOS 8, will this still take some time or should it be effective already? I can replicate using:
```
opam init --bare -a -y;
opam switch create 4.08.1;
opam pin -y -n liquidsoap 1.4.4;
opam install -y faad fdkaac flac theora vorbis taglib mad lame cry samplerate liquidsoap;
```

**Comment by kit-ty-kate** [comment]
@TheRealMattLear the default repository sadly takes a couple of hours to rebuild. Hopefully this should be done soon enough. In the meantime if you need it really now you can use the git repository directly:
```
opam remote set-url default git+https://github.com/ocaml/opam-repository.git
```

**Comment by fpottier** [comment]
Incidentally, I would strongly recommend using Menhir's `--infer` mode. I am preparing major changes in Menhir's "code" back-end, allowing Menhir to produce well-typed OCaml code, but these changes will require `--infer`.
