### ISSUE TITLE
coq fails to compile its documentation

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam-repository#2013]
when trying to install coq 8.4pl2 on archlinux, compilation fails during the generation of the `RecTutorial.dvi`.

Here are the [error](http://cedeela.fr/~simon/files/temp/coq-15906-b76d46.err), [env](http://cedeela.fr/~simon/files/temp/coq-15906-b76d46.env) and [output](http://cedeela.fr/~simon/files/temp/coq-15906-b76d46.out) files.

A problem is that this fails after 52 minutes of compilation (after the whole library was built), which makes it pretty annoying to try and fix.

**Comment by samoht** [comment]
Could you please report that issue upstream at https://coq.inria.fr/bugs/ /cc @clarus 

Thanks!
