### ISSUE TITLE
 λ build ocaml-base-compiler 4.13.1 failed

### ISSUE THREAD

**Issue by kylergray** [ocaml/opam-repository#20369]
<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocaml-base-compiler 4.13.1
└─
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray         base
│ ∗ install base-threads          base
│ ∗ install base-unix             base
│ ∗ install ocaml-options-vanilla 1
└─

<><> ocaml-base-compiler.4.13.1 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/opam-repository/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
# Run eval $(opam env --switch=default) to update the current shell environment

**Comment by kit-ty-kate** [comment]
The error message is not shown. Could you paste the block above this? (such example can be found here: https://github.com/ocaml/opam-repository/issues/20319)

Could you also use the ` ``` ` blocks to wrap the error message. Otherwise github parse it as markdown
