### ISSUE TITLE
ocamlnet cannot be installed anymore on Linux and macos

### ISSUE THREAD

**Issue by gerdstolpmann** [ocaml/opam-repository#20387]
Looks like #20343 broke it. The symptom is that any attempt to use `nettls-gnutls` results in lots of errors like
```
/usr/bin/ld: /home/bb/.opam/4.12.0/lib/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): in function `net_gnutls_pubkey_verify_data2':
/home/bb/.opam/4.12.0/.opam-switch/build/ocamlnet.4.1.9-1/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:7536: undefined reference to `gnutls_pubkey_verify_data2
```
which is because `-lgnutls` is not passed to the system linker anymore.

`pkg-config` doesn't have `--keep-system-cflags --keep-system-libs`:

```
$ pkg-config --keep-system-cflags gnutls
Unknown option --keep-system-cflags
$ pkg-config --keep-system-libs gnutls
Unknown option --keep-system-libs
```

Can you please fix by checking whether the installed version of `pkg-config` supports these flags? Thanks.

**Comment by mseri** [comment]
Thanks for the report, both my test on macos+macports and the CI checks had successfully completed so I did not expect this failure when I merged.

I have reverted the patch for now and asked the author to submit a new one with more careful checks on these flags
