### ISSUE TITLE
"'opam switch create 4.11.0' failed"

### ISSUE THREAD

**Issue by morphismz** [ocaml/opam-repository#20475]
I am trying to install ocaml version 4.11.0. I am following the instructions here https://ocaml.org/docs/install.html . When running the command opam switch create 4.11.0 I keep running into the same problem. The script describes the problem as "The following actions failed│ λ build ocaml-base-compiler 4.11.0". I really have no clue what to do tho get this work. Any help would be greatly appreciated.

**Comment by kit-ty-kate** [comment]
Could you paste what is before the "The following actions failed" ?
The error message should look something like this: https://github.com/ocaml/opam-repository/issues/20408

**Comment by morphismz** [comment]
This is what precedes "the following actions failed" :
- signals_nat.c:198:13: error: variably modified ‘sig_alt_stack’ at file scope
-   198 | static char sig_alt_stack[SIGSTKSZ];
-       |             ^~~~~~~~~~~~~
- make[3]: *** [Makefile:343: signals_nat_n.o] Error 1
- make[3]: *** Waiting for unfinished jobs....
- make[3]: Leaving directory '/home/rymndbkr/.opam/4.11.0/.opam-switch/build/ocaml-base-compiler.4.11.0/runtime'
- make[2]: *** [Makefile:777: makeruntimeopt] Error 2
- make[2]: Leaving directory '/home/rymndbkr/.opam/4.11.0/.opam-switch/build/ocaml-base-compiler.4.11.0'
- make[1]: *** [Makefile:223: opt.opt] Error 2
- make[1]: Leaving directory '/home/rymndbkr/.opam/4.11.0/.opam-switch/build/ocaml-base-compiler.4.11.0'
- make: *** [Makefile:283: world.opt] Error 2
[ERROR] The compilation of ocaml-base-compiler.4.11.0 failed at "make -j7
        world.opt".

ERROR while compiling ocaml-base-compiler.4.11.0 ====================#
# context     2.1.1 | linux/x86_64 |  | https://opam.ocaml.org#d673d422
# path        ~/.opam/4.11.0/.opam-switch/build/ocaml-base-compiler.4.11.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j7 world.opt
# exit-code   2
# env-file    ~/.opam/log/ocaml-base-compiler-50739-77b0d5.env
# output-file ~/.opam/log/ocaml-base-compiler-50739-77b0d5.out
### output ###
# [...]
# gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall -Wdeclaration-after-statement -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o misc_n.o misc.c
# signals_nat.c:198:13: error: variably modified ‘sig_alt_stack’ at file scope
#   198 | static char sig_alt_stack[SIGSTKSZ];
#       |             ^~~~~~~~~~~~~
# make[3]: *** [Makefile:343: signals_nat_n.o] Error 1
# make[3]: *** Waiting for unfinished jobs....
# make[3]: Leaving directory '/home/rymndbkr/.opam/4.11.0/.opam-switch/build/ocaml-base-compiler.4.11.0/runtime'
# make[2]: *** [Makefile:777: makeruntimeopt] Error 2
# make[2]: Leaving directory '/home/rymndbkr/.opam/4.11.0/.opam-switch/build/ocaml-base-compiler.4.11.0'
# make[1]: *** [Makefile:223: opt.opt] Error 2
# make[1]: Leaving directory '/home/rymndbkr/.opam/4.11.0/.opam-switch/build/ocaml-base-compiler.4.11.0'
# make: *** [Makefile:283: world.opt] Error 2

<><> Error report ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

The following actions were aborted
│ ∗ install ocaml        4.11.0
│ ∗ install ocaml-config 1

End quote

Thank you for the reference to the other question as well.

**Comment by kit-ty-kate** [comment]
That’ll be fixed with #19855, probably tomorrow. The latest Glibc release broke all previous versions of the compiler.

In the meantime, is there a reason why you need an old version of OCaml? OCaml 4.13 should work fine

**Comment by morphismz** [comment]
Yes, I need a version of OCaml between 4.05 and 4.11 to run the UniMath repository. 
Thanks for the help!

**Comment by morphismz** [comment]
Hey, I'm wondering if there are any updates on this? I see here (https://discuss.ocaml.org/t/support-for-glibc-2-34-ubuntu-21-10-fedora-35-etc/9195) that repositories should be merged. I update opam and ocaml with dnf. Yet, when I run the command "opam switch create 4.11", I receive the same error.

**Comment by kit-ty-kate** [comment]
yes, this has been fixed 2 days ago by #19855. Are you sure you called `opam update` ?

**Comment by kit-ty-kate** [comment]
I’m going to close this since this was fixed but if you’re still having an issue please do reply here and I’ll reopen if needed.
