### ISSUE TITLE
Error installing 4.13.1 on Ubuntu 21.10

### ISSUE THREAD

**Issue by philsaxton** [ocaml/opam-repository#20476]
`
$ opam switch create 4.13.1

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><><><>
Switch invariant: ["ocaml-base-compiler" {= "4.13.1"} | "ocaml-system" {= "4.13.1"}]

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-options-vanilla.1
⬇ retrieved ocaml-base-compiler.4.13.1  (cached)
[ERROR] The compilation of ocaml-base-compiler.4.13.1 failed at "make -j3".

#=== ERROR while compiling ocaml-base-compiler.4.13.1 =========================#
# context     2.1.0 | linux/x86_64 |  | https://opam.ocaml.org#d673d422
# path        ~/.opam/4.13.1/.opam-switch/build/ocaml-base-compiler.4.13.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j3
# exit-code   1
# env-file    ~/.opam/log/ocaml-base-compiler-5065-18c18d.env
# output-file ~/.opam/log/ocaml-base-compiler-5065-18c18d.out
### output ###
# bwrap: execvp make: No such file or directory

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocaml-base-compiler 4.13.1
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray         base
│ ∗ install base-threads          base
│ ∗ install base-unix             base
│ ∗ install ocaml-options-vanilla 1
└─ 

<><> ocaml-base-compiler.4.13.1 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/opam-repository/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
`

**Comment by kit-ty-kate** [comment]
Same as https://github.com/ocaml/opam/issues/4112#issuecomment-996208463
You need GNU Make installed to compile OCaml (opam init warned you about it before)

https://github.com/ocaml/opam/pull/4971 will make the error easier to see in the next version of opam
