### ISSUE TITLE
jemalloc 0.2 fails to install on the m1 mac

### ISSUE THREAD

**Issue by chiumichael** [ocaml/opam-repository#20535]
I'm trying to install jemalloc through opam and I run into the following error on the m1 mbp. 

```sh
#=== ERROR while compiling jemalloc.0.2 =======================================#
# context     2.1.2 | macos/arm64 | ocaml.4.12.0 | https://opam.ocaml.org#37f80306
# path        ~/.opam/default/.opam-switch/build/jemalloc.0.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p jemalloc -j 9 @install
# exit-code   1
# env-file    ~/.opam/log/jemalloc-38060-c280c6.env
# output-file ~/.opam/log/jemalloc-38060-c280c6.out
### output ###
#        clang src/jemalloc_stubs.o (exit 1)
# (cd _build/default/src && /usr/bin/clang -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT -g -g -I /opt/homebrew/lib/ocaml -o jemalloc_stubs.o -c jemalloc_stubs.c)
# jemalloc_stubs.c:11:10: fatal error: 'jemalloc/jemalloc.h' file not found
# #include <jemalloc/jemalloc.h>
#          ^~~~~~~~~~~~~~~~~~~~~
# 1 error generated.
```

It seems to be unable to find jemalloc header. Opam installed the necessary dependency on my system via (native m1) homebrew. The difference between native vs rosetta homebrew is that a native version of homebrew is installed in the `/opt/homebrew` directory, so the installed headers for jemalloc are found in `/opt/homebrew/include`.  Maybe this is the cause of the failure since earlier issues on jemalloc 0.2 have been closed. 

Appreciate any help / suggestions in trying to fix this, thanks!

**Comment by mseri** [comment]
I would ask on the `dune` repository in this case. The `-I /opt/homebrew/lib/ocaml` flag is [not specified in the `jemalloc` sources](https://github.com/ahrefs/ocaml-jemalloc/blob/0.2/src/dune#L5-L7) but is inferred by `dune` itself when compiling the stubs. I don't know how that is done.

**Comment by mseri** [comment]
Feel free to reopen if it happens to be related to opam, but I think it is either related to homebrew's configuration or dune.

**Comment by chiumichael** [comment]
okay, thanks for the prompt reply.
