### ISSUE TITLE
Cannot use graphics package

### ISSUE THREAD

**Issue by ericd13** [ocaml/opam-repository#20678]
I'm trying to use the graphics package.
I was able to do so one year ago with versions <4.08, graphics was included or later versions.
But now, with graphics 5.1.2 the code
#use "topfind";;
#require "graphics";;
open Graphics;;
open_graph " ";;
let _ = wait_next_event [Button_down] in close_graph ();;
gives the error message
Cannot load required shared library dllgraphics_stubs.
Reason: dllgraphics_stubs.so

I receive this message with OCaml 4.10, 4.12 & 4.13 in OSX and in Linux, the end of the error message will change, saying where the dll was searched).

**Comment by dra27** [comment]
I assume you've trimmed some things from the original log above, what does the toplevel say at `#require "graphics";;` before the error?

There should at least be the first line of:

```
/Users/ericd13/.opam/4.13.1/lib/graphics: added to search path
/Users/ericd13/.opam/4.13.1/lib/graphics/graphics.cma: loaded
```
(I think that the error message for the stub library should appear before the second line is printed). Is the directory being added to the search path as shown? Was there anything else in the `Reason: dllgraphics_stubs.so` message, or was that it?
