### ISSUE TITLE
`conf-libev.4.12` doesn't find arm64 `libev` on macOS when both `x86_64` and `arm64` `libev` versions are installed via homebrew

### ISSUE THREAD

**Issue by rvem** [ocaml/opam-repository#20941]
It's possible two have two homebrew installations on mac with M1 CPU: native installation and x86_64 installation under rosetta.

When `libev` is installed by both of these homebrews an attempt to build something that depends on `conf-libev` under `arm64` fails due to the fact that `conf-libev` finds `x86_64` library in `/usr/local/lib` instead of `/opt/homebrew/lib`.

At the same time the build for `x86_64` succeeds under such conditions.

`arm64` build fails with the following error:
```
Undefined symbols for architecture arm64:
  "_ev_break", referenced from:
      _lwt_libev_unloop in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_invoke_pending", referenced from:
      _lwt_libev_loop in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_io_start", referenced from:
      _lwt_libev_io_init in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_io_stop", referenced from:
      _lwt_libev_io_stop in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_loop_destroy", referenced from:
      _lwt_libev_stop in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_loop_new", referenced from:
      _lwt_libev_init in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_now", referenced from:
      _lwt_libev_timer_init in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_run", referenced from:
      _lwt_libev_loop in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_set_invoke_pending_cb", referenced from:
      _lwt_libev_init in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_time", referenced from:
      _lwt_libev_timer_init in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_timer_start", referenced from:
      _lwt_libev_timer_init in liblwt_unix_stubs.a(lwt_libev_stubs.o)
  "_ev_timer_stop", referenced from:
      _lwt_libev_timer_stop in liblwt_unix_stubs.a(lwt_libev_stubs.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
```

Seems like [`discover.ml`](https://github.com/ocaml/opam-repository/blob/master/packages/conf-libev/conf-libev.4-12/files/discover.ml) should somehow consider the current architecture and pick the proper library directory.

**Comment by kit-ty-kate** [comment]
I’ve seen this type of error before. Does `brew unlink binutils` fix this issue?

**Comment by rvem** [comment]
Nope, since I don't have `binutils` installed

**Comment by mseri** [comment]
This depends on how `lwt` looks for `libev` and not the `conf-libev` package which only checks if a library to link against is present . I am not too familiar with `lwt` internals, but there may be a way to override it using some environment variable. 

On my mac I only have the arm64 version of the library installed via macports. The only thing that I can check is that in this case it works fine. @rvem you should raise an issue on the lwt repo if it is not already there.

**Comment by mseri** [comment]
Your issue is due to the fact that lwt [first looks](https://github.com/ocsigen/lwt/blob/master/src/unix/config/discover.ml#L180) in `/usr` and then in `/opt`, and homebrew had the idea of keeping x86 in usr and arm64 in opt. 

I think this is [how you help it by hand](https://github.com/ocsigen/lwt/blob/master/src/unix/config/discover.ml#L204), you need to set the `C_INCLUDE_PATH` and `LIBRARY_PATH` variables appropriately.
