### ISSUE TITLE
ERROR while installing lwt.2.4.5

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#2102]
Am I the only one getting this?
No lwt means no utop. That's not cool.
Here is the OPAM trace:
https://gist.github.com/UnixJunkie/9eab4cffa084ede9c6ff

**Comment by aantron** [comment]
This was fixed by 878ed9da54d64c1131effe10e54a0d24ed30a5d4 in OPAM, and current Lwt itself doesn't have this issue anymore because the "extra" library that was causing trouble has since been removed.

With the linked patch, Lwt 2.4.5 correctly compiles without `base-threads`.

**Comment by dbuenzli** [comment]
According to @aantron, this can be closed.
