### ISSUE TITLE
ocaml_intrinsics.v0.15.0: More restrictions

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam-repository#21055]
In https://github.com/ocaml/opam-repository/pull/20953/commits/2d4b7ed74d7b25e6896e847d7b306b4c7d26766e this package has been restricted to os = Linux only. This is unfortunate, since `core_unix` depends on `ocaml_intrinsics`, and it compiles fine on FreeBSD.

I couldn't find any insight why this available constraint ha been restricted, it would be great if it could be lifted.

**Comment by kit-ty-kate** [comment]
Feel free to propose a PR. also cc @aalekseyev just in case

**Comment by aalekseyev** [comment]
I think the reason this constraint was added was that the build didn't work on MacOS.
Maybe it should be `os != "win32" & os != "macos"` instead of `os = "linux"`.

**Comment by kit-ty-kate** [comment]
Closed by https://github.com/ocaml/opam-repository/pull/21075
