### ISSUE TITLE
failed to opam install ocaml-lsp-server on windows wsl2  with ocaml4.14

### ISSUE THREAD

**Issue by aresbit** [ocaml/opam-repository#21096]
aresyang@LAPTOP-MOGSN96P:/myleetcode$ opam install ocaml-lsp-server
The following actions will be performed:
∗ install ocaml-lsp-server 1.9.24.14preview

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] Could not synchronize /home/aresyang/.opam/cs3110/.opam-switch/sources/ocaml-lsp-server.1.9.24.14preview from
"git+[kit-ty-kate/ocaml-lsp.git#414](https://github.com/kit-ty-kate/ocaml-lsp.git#414)":
"/usr/bin/git fetch -q" exited with code 128
[ERROR] The sources of the following couldn't be obtained, aborting:
- ocaml-lsp-server.1.9.24.14preview

**Comment by sim642** [comment]
There are now official non-preview versions of ocaml-lsp-server for 4.14. Do they have the same problem?

**Comment by kit-ty-kate** [comment]
The preview was removed from opam-repository in https://github.com/ocaml/opam-repository/commit/8702a900d753f949637b4c5a6fc1f4c89bdbd765 more than 2 weeks ago. To fix the issue you need to call:
```
opam update
```
