### ISSUE TITLE
alt-ergo dependencies on cmdliner, menhir and dune are blocking upgrades

### ISSUE THREAD

**Issue by esope** [ocaml/opam-repository#21127]
Hi,

I am face with the following constraints, that block some upgrades:

- alt-ergo.2.4.1 requires cmdliner (>= 1.0.0 & < 1.1.0), which impedes upgrading to cmdliner.1.1.1
- alt-ergo-lib.2.4.1 requires dune (>= 2.0 & < 3.0), which impedes upgrading to dune.3.0.3
- alt-ergo.2.4.1 requires menhir < 20211215, which impedes upgrading to menhir.20220210

I understand the above constraints were necessary at some point. Are they still necessary?
I would love to be able to upgrade to the recent versions of cmdliner, dune, and menhir.

Thanks!

**Comment by kit-ty-kate** [comment]
cc @Gbury

**Comment by kit-ty-kate** [comment]
I’m closing this as this is an issue for the alt-ergo maintainers. I would suggest opening an issue over there instead.

**Comment by esope** [comment]
Sounds good! Thanks!
