### ISSUE TITLE
Missing dependency error while trying to install ocaml on Mac M1-Pro

### ISSUE THREAD

**Issue by GalRogozinski** [ocaml/opam-repository#21291]
I have tried to install ocaml aacording to the instructions [here](https://ocaml.org/learn/tutorials/up_and_running.html#Installing-OCaml) on macOS.

Currently I get:
```
 % opam switch create 4.11.1


<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><><><>
Switch invariant: ["ocaml-base-compiler" {= "4.11.1"} | "ocaml-system" {= "4.11.1"}]
[ERROR] Could not determine which packages to install for this switch:
  * Missing dependency:
    - ocaml-base-compiler = 4.11.1 | ocaml-system = 4.11.1
    unmet availability conditions: '!(os = "macos" & arch = "arm64")'
    unmet availability conditions: 'sys-ocaml-version = "4.11.1"'
```

I think something went wrong in the installation midway and now I can't install the compiler.
How do I resolve this?

Thanks

**Comment by kit-ty-kate** [comment]
```
    unmet availability conditions: '!(os = "macos" & arch = "arm64")'
```
is telling you that this version of the compiler is not available on macOS/arm64.

You can install `4.10.2` or any compilers above 4.12.0. e.g.
```
opam swtch create 4.14.0
```

**Comment by GalRogozinski** [comment]
Thanks!

It may be worth updating the tutorial. It currently says the instructions should work on macOS.

**Comment by kit-ty-kate** [comment]
cc @tmattio @patricoferris
