### ISSUE TITLE
build flag for dune >= 2.0

### ISSUE THREAD

**Issue by mseri** [ocaml/opam-repository#21414]
Since dune has a compulsory dune language field in the dune-project files, is it still needed to not use the build flag?

**Comment by kit-ty-kate** [comment]
Yes, the `dune-project` file is not the problem. The issue is in the `dune-package` file instead, which is installed with a minimal version (which breaks backward compatibility)

See https://github.com/ocaml/dune/issues/2147

**Comment by mseri** [comment]
Ah indeed!
