### ISSUE TITLE
depext for curl seems to fail?

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam-repository#21770]
hi! I think this is the place to report problems for conf-xxx packages? If not, sorry for the disturbance.

I've had CI runs fail recently because of libcurl failing to install via depext on ubuntu, for example: https://github.com/c-cube/tiny_httpd/runs/7274698508?check_suite_focus=true . Anyone knows what it's about?

**Comment by mseri** [comment]
I had recently a similar issue and needed to add an extra `apt get update && apt get upgrade` step, somehow the depext itself had failed to install leading to that error. Can you check if this is the case?

**Comment by mseri** [comment]
Looks like it is the same: https://github.com/c-cube/tiny_httpd/runs/7274698508?check_suite_focus=true#step%3A3%3A620=

**Comment by kit-ty-kate** [comment]
Looks like it is a bug in setup-ocaml IMO. The depext step should use `-u` cc @smorimoto
