### ISSUE TITLE
OPAM CI and GitHub CI differ in treatment of depexts on macOS?

### ISSUE THREAD

**Issue by mgree** [ocaml/opam-repository#21921]
Right now libdash-0.3 builds in OPAM CI but not in GitHub CI. There are a number of issues, but one of them seems to be how external dependencies are treated on macOS, namely that `conf-aclocal` isn't installing `automake`.

When running in the OPAM CI, depexts are installed at the beginning of the procedure, like you'd expect ([CI run](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/db9011d51d0d27b6ebdc47da7e23bbf618542420/variant/distributions,macos-homebrew,libdash.0.3)).

When running in the GitHub CI, virtual packages for depexts are run inline and fail their tests without invoking the host package manager ([CI run on macOS 11](https://github.com/mgree/libdash/runs/7591852085?check_suite_focus=true); [CI run on macOS 12](https://github.com/mgree/libdash/runs/7591852039?check_suite_focus=true); grep for `automake`).

Am I invoking things wrong, or is there a real discrepancy in the environment?

**Comment by mseri** [comment]
You should report this on the [setup-ocaml](https://github.com/ocaml/setup-ocaml) repository, this seems a bug in the depexts handling.

**Comment by mgree** [comment]
Will do, thanks for the prompt reply!
