### ISSUE TITLE
Failure with OCaml 4.00.x and 4.01.x

### ISSUE THREAD

**Issue by thierry-martinez** [ocaml/opam-repository#22015]
`setup-ocaml` now fails when `ocaml-compiler` is `4.00.x` or `4.01.x`:
- https://github.com/thierry-martinez/stdcompat/runs/7952976688?check_suite_focus=true
- https://github.com/thierry-martinez/stdcompat/runs/7952976827?check_suite_focus=true

The error is the following:
```
  Processing 13/21: [ocaml-base-compiler.4.01.0/bd7fa181cb64742c3b6cbb8ee13436554eb18cd7...fix-clang-build.diff: dl]
  [ERROR] Failed to get extra source "bd7fa181cb64742c3b6cbb8ee13436554eb18cd7...fix-clang-build.diff" of ocaml-base-compiler.4.01.0: curl error code 404
  
  #=== ERROR while fetching sources for ocaml-base-compiler.4.01.0 ==============#
  OpamSolution.Fetch_fail("https://github.com/jeremiedimino/ocaml/compare/bd7fa181cb64742c3b6cbb8ee13436554eb18cd7...fix-clang-build.diff (curl: code 404 while downloading https://github.com/jeremiedimino/ocaml/compare/bd7fa181cb64742c3b6cbb8ee13436554eb18cd7...fix-clang-build.diff)")
```

It used to work 10 days ago:
- https://github.com/thierry-martinez/stdcompat/runs/7802927146?check_suite_focus=true
- https://github.com/thierry-martinez/stdcompat/runs/7802927226?check_suite_focus=true

Moreover, `setup-ocaml` doesn't work with older versions of OCaml (<= 3.12), but this is not new as far as I can tell.
- With 3.07, it fails with the message `Error: No OCaml base compiler packages matched the version 3.07 in the opam-repository.`, whereas `opam switch create 3.07` should work as expected (https://github.com/thierry-martinez/stdcompat/runs/7952973003?check_suite_focus=true).
- With OCaml 3.08 to 3.12, it seems to fail because it tries to install `opam-depext` which requires OCaml >= 4.00.

**Comment by dra27** [comment]
From my .opam cache (md5 `faccda3b3ab092fa9ac7d5d4d8beb004`)
```diff
diff --git a/configure b/configure
index d45e88f70fc..25d872b60d8 100755
--- a/configure
+++ b/configure
@@ -322,7 +322,14 @@ case "$bytecc,$target" in
     bytecccompopts="-fno-defer-pop $gcc_warnings -DSHRINKED_GNUC"
     mathlib="";;
   *,*-*-darwin*)
-    bytecccompopts="-fno-defer-pop $gcc_warnings"
+    # On recent version of OSX, gcc is a symlink to clang
+    if $bytecc --version | grep -q clang; then
+        # -fno-defer-pop is not supported by clang, and make recent
+        # versions of clang to fail
+        bytecccompopts="$gcc_warnings"
+    else
+        bytecccompopts="-fno-defer-pop $gcc_warnings"
+    fi
     mathlib=""
     mkexe="$mkexe -Wl,-no_compact_unwind"
     # Tell gcc that we can use 32-bit code addresses for threaded code
```

**Comment by kit-ty-kate** [comment]
This should now be fixed.

> Moreover, `setup-ocaml` doesn't work with older versions of OCaml (<= 3.12), but this is not new as far as I can tell.
> 
>     * With 3.07, it fails with the message `Error: No OCaml base compiler packages matched the version 3.07 in the opam-repository.`, whereas `opam switch create 3.07` should work as expected (https://github.com/thierry-martinez/stdcompat/runs/7952973003?check_suite_focus=true).
> 
>     * With OCaml 3.08 to 3.12, it seems to fail because it tries to install `opam-depext` which requires OCaml >= 4.00.

I think these should be fixed in setup-ocaml. Could you open a new issue there for that?

**Comment by thierry-martinez** [comment]
Thank you very much for the quick fix! I reposted in `setup-ocaml` the part of the issue relative to OCaml ≤ 3.12 (https://github.com/ocaml/setup-ocaml/issues/615).
