### ISSUE TITLE
Opam server is down since > 6 hours

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam-repository#22133]
Since about 6 hours any attempt to update an opam repo failed for me, e.g. all CI tests in

https://github.com/coq/platform/actions/runs/3094687613/jobs/5008329266

Local opam repo update attempts on various machines / networks also fail.

```
Error:  Could not update repository "default": OpamDownload.Download_fail(_, "Curl failed: \"/usr/bin/curl --write-out %{http_code}\\\\n --retry 3 --retry-delay 2 --user-agent opam/2.1.3 -L -o /tmp/opam-2660-4c582a/index.tar.gz.part -- [https://opam.ocaml.org/index.tar.gz\](https://opam.ocaml.org/index.tar.gz/)" exited with code 7")
```

**Comment by mseri** [comment]
AFAIK this is being worked on with urgency: see also https://discuss.ocaml.org/t/opam-ocaml-org-is-currently-down-is-that-where-indices-are-kept-still/10502/4

A temporary workaround is to use git for the index: `opam repository set-url default git+https://github.com/ocaml/opam-repository `

**Comment by MSoegtropIMC** [comment]
Thanks! I somehow missed the discourse discussion - I guess because it is marked as solved.

**Comment by kit-ty-kate** [comment]
It looks like the website is back up
