### ISSUE TITLE
Removing naked pointers from the LLVM bindings

### ISSUE THREAD

**Issue by alan-j-hu** [ocaml/opam-repository#22221]
Hello all,

Over the past week, I have been converting the LLVM bindings to not use naked pointers, and I've managed to convert the file `llvm_ocaml.c`, the "main" and longest of the binding files. I was told [on the LLVM forum](https://discourse.llvm.org/t/eliminating-naked-pointers-from-the-ocaml-bindings-to-be-compatible-with-ocaml-5/65794) that @kit-ty-kate was planning on converting the bindings to not use naked pointers and I should try to sync up with her.

There are some definitely some design decisions that I would appreciate a second look at from LLVM or OCaml people. Example: When unboxing wrapped LLVM pointers into a temporary array to pass to LLVM, should I allocate the temporary array using `malloc`, bump the array on the OCaml heap (what I currently do), or have a per-domain "dynamic array" that is reused whenever LLVM pointers need to be copied into a temporary array?

**Comment by kit-ty-kate** [comment]
I replied in https://discourse.llvm.org/t/eliminating-naked-pointers-from-the-ocaml-bindings-to-be-compatible-with-ocaml-5/65794
Closing this as it is not related to opam-repository. If you want to talk in a more synchronous matter i'm also on the OCaml Discord server.
