### ISSUE TITLE
Mustache constraint on Menhir

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/opam-repository#22293]
+ @rgrinberg 

When I tried to compile a package that consumed the latest Mustache in Opam, the Mustache build failed on Menhir.

From https://github.com/ocaml/opam-repository/pull/22277 ...

> The lower bounds check that failed at https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/38354d83ef6811f9ec303c177955096c322dec7f was due to `mustache.3.1.0` not working with `menhir.20160303`
> 
> I've added the constraint `"menhir" {>= "20180528"}` (that was the earliest version to introduce the `--infer-write-query` flag; see https://gitlab.inria.fr/fpottier/menhir/-/blob/20180528/src/settings.ml#L127)

Since then I noticed:
* Mustache upstream contains a tighter constraint `"menhir" {>= "20180703"}` at https://github.com/rgrinberg/ocaml-mustache/blob/a86cab0ceb8d77d5045b4d6464b68affafb80e2e/mustache.opam#L23
* Issue [a new Mustache release?](https://github.com/rgrinberg/ocaml-mustache/issues/69) has been waiting for a while

For now can we update the Opam version constraint on mustache.3.1.0 to use `"menhir" {>= "20180528"}`? Thanks

**Comment by rgrinberg** [comment]
> For now can we update the Opam version constraint on mustache.3.1.0 to use "menhir" {>= "20180528"}? Thanks

That would be welcome. Thanks

**Comment by mseri** [comment]
Done
