### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by jpds** [ocaml/opam-repository#22603]
Not sure where else to file this, but `opam.ocaml.org` requires IPv6 to be enabled on the EC2 instance it's hosted on and a `AAAA` record added to its DNS.

I deploy MirageOS images onto various networks that do not have any IPv4 networking on them, however I cannot build the VM images on them directly as `opam` trips up on this and then I have to move various VM images between jump hosts before I can deploy them.

**Comment by kit-ty-kate** [comment]
cc @mtelvers @avsm

**Comment by mtelvers** [comment]
The correct place to track this is on the issue tracker for [ocaml/infrastructure](https://github.com/ocaml/infrastructure).  This could easily be included in Issue https://github.com/ocaml/infrastructure/issues/19

**Comment by jhwoodyatt** [comment]
It would be nice if GitHub.com had IPv6 support too. I had to deploy a personal NAT64/DNS64 gateway to resolve this problem in my own network.

**Comment by jpds** [comment]
This has been done, thanks team. :tada:
