### ISSUE TITLE
coqorg/base -> Missing release for ocamlfind-secondary version 1.9.5 (and 1.9.3, 1.9.2)

### ISSUE THREAD

**Issue by erikmd** [ocaml/opam-repository#22817]
Dear ocamlfind-secondary maintainers, Cc @gerdstolpmann @dra27,

I maintain the `coqorg/base` images, which are required for building the [`coqorg/coq` images](https://hub.docker.com/r/coqorg/coq#supported-tags) on the Docker Hub registry (all releases of `coq >= 8.4` using four different versions of ocaml).

I recently stumbled upon the following issue:

when building 8.7 ≤ Coq ≤ 8.15 with OCaml 4.07.1,
I would like to pin the latest versions of ocamlfind and dune.

However, installing dune 3.6.1 requires `("ocaml" {< "4.08~~"} & "ocamlfind-secondary")` and ocamlfind-secondary only exists in version 1.9.1, which requires `"ocamlfind" {= version}`, i.e., 1.9.1, while the latest version of the ocamlfind package is 1.9.5.

So, would it be possible for you to also release ocamlfind-secondary, version 1.9.5 ?

Thanks for your time!
best wishes,
Erik

**Comment by erikmd** [comment]
gently ping @gerdstolpmann @dra27
— all the more as I've just noticed that this will be a blocking issue for building `coqorg/base:5.0.0` as is:
https://gitlab.com/coq-community/docker-base/-/jobs/3549979172

**Comment by gerdstolpmann** [comment]
Hello @erikmd, honestly I don’t know what ocamlfind-secondary is. This is not my project, although I’m apparently mentioned in the opam file.

**Comment by kit-ty-kate** [comment]
> all the more as I've just noticed that this will be a blocking issue for building `coqorg/base:5.0.0` as is: https://gitlab.com/coq-community/docker-base/-/jobs/3549979172

I don't understand. Why is this dockerfile pinning ocamlfind 1.9.1?
```
RUN opam pin add -n -k version ocamlfind 1.9.1
````

**Comment by dra27** [comment]
@gerdstolpmann - indeed, I kept you as the author of ocamlfind, given that the package downloads its sources, but it's always had just me as the maintainer! `ocamlfind-secondary` is a companion to the `ocaml-secondary-compiler` package which is a horrible workaround I added to opam-repository to allow Dune 2.x+ to be installed on OCaml 4.02-4.07, as it makes OCaml 4.08.1 available with `ocamlfind -toolchain secondary`.

@erikmd - I've submitted a PR for 1.9.5 (I don't think there's a need for 1.9.2-1.9.4, as 1.9.5 is available on all of those). I don't know what your Docker infrastructure is, but I agree it's suspect that it's pinning ocamlfind at all on OCaml 5.0.0 ... is that just as a lockfile, or does Coq directly use ocamlfind?

**Comment by erikmd** [comment]
> @kit-ty-kate 
> I don't understand. Why is this dockerfile pinning ocamlfind 1.9.1?

Hi!, see below for a quick explanation :)

> @dra27 
> I don't know what your Docker infrastructure is, but I agree it's suspect that it's pinning ocamlfind at all on OCaml 5.0.0 ... is that just as a lockfile, or does Coq directly use ocamlfind?

Just to summarize:

* the main dependencies of coq are ocamlfind, zarith, dune (and zarith also depends on zarith)
* to save some build time and increase reproducibility, all `coqorg/coq` images (from Coq 8.4 to 8.17) rely on a `coqorg/base` image that [pins](https://github.com/coq-community/docker-base/blob/9e2bf085007f0929807a8b8ecb5178242c998a45/images.yml#L8-L10) ocamlfind, zarith and dune with the same version
* because of this issue [#22817](https://github.com/ocaml/opam-repository/issues/22817#issue-1515170184), it was impossible to have a single version of ocamlfind that works with both (8.7 ≤ Coq ≤ 8.15 ; OCaml 4.07.1) and (Coq 8.17 ; OCaml 5.0.0)

> @dra27
> I've submitted a PR for 1.9.5

Thanks a lot!
