### ISSUE TITLE
Cannot install lablgtk

### ISSUE THREAD

**Issue by fithisux** [ocaml/opam-repository#2283]
System opensuse 13.1 x86_64
hand compiled ocaml 4.01

Error description (2.18.0 can be compiled installed cleanly)

=-=-= Installing lablgtk.2.16.0 =-=-=
default    Downloading https://opam.ocaml.org/archives/lablgtk.2.16.0+opam.tar.gz
Downloading https://opam.ocaml.org/archives/lablgtk.2.16.0+opam.tar.gz
Applying lablgldir.patch.

===== ERROR while installing lablgtk.2.16.0 =====
Could not get the source for lablgtk.2.16.0:
# opam-version    1.1.1
# os              linux
Patch /home/vanag/.opam/system/build/lablgtk.2.16.0/lablgldir.patch does not apply.

=-=-= lablgtk.2.16.0 troobleshooting =-=-=
This package requires gtk+ 2.0 development packages installed on your system.

The former state can be restored with opam switch import -f "/home/vanag/.opam/system/backup/state-20140520152137.export"
'opam install lablgtk' failed.

**Comment by samoht** [comment]
Can you report that issue upstream: https://forge.ocamlcore.org/tracker/?group_id=220 ?

Ideally we should not carry patches in that repository, @garrigue do you think you could apply https://github.com/ocaml/opam-repository/blob/master/packages/lablgtk/lablgtk.2.18.5/files/lablgldir.patch upstream?

**Comment by garrigue** [comment]
The fix should be in `configure.in`, not in `configure`.
