### ISSUE TITLE
Installing conf-libssl on macos fails with: Operation not permitted @ apply2files

### ISSUE THREAD

**Issue by gridbugs** [ocaml/opam-repository#23324]
When I try to install conf-libssl on an M1 mac I get this error:
```
$ opam install conf-libssl
The following actions will be performed:
  ∗ install conf-libssl 4

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] The compilation of conf-libssl.4 failed at "sh -ex ./homebrew.sh check".

#=== ERROR while compiling conf-libssl.4 ======================================#
# context     2.1.3 | macos/arm64 | ocaml.5.0.0 | https://opam.ocaml.org#aa363b34
# path        ~/src/vendredi/_opam/.opam-switch/build/conf-libssl.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build sh -ex ./homebrew.sh check
# exit-code   1
# env-file    ~/.opam/log/conf-libssl-9451-e54ea6.env
# output-file ~/.opam/log/conf-libssl-9451-e54ea6.out
### output ###
# ++ brew --prefix openssl
# Error: Operation not permitted @ apply2files - /Users/s/Library/Caches/Homebrew/api/formula.json
# + brew_pkg_config=/lib/pkgconfig



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build conf-libssl 4
└─
╶─ No changes have been performed
```

I can run the command `sh -ex ~/src/opam-repository/packages/conf-libssl/conf-libssl.4/files/homebrew.sh check` (after checking out the opam-repository repo locally) and it works fine. If I run same command in a sandbox:
```
$ ~/.opam/opam-init/hooks/sandbox.sh build  sh -ex ~/src/opam-repository/packages/conf-libssl/conf-libssl.4/files/homebrew.sh check
++ brew --prefix openssl
Error: Operation not permitted @ apply2files - /Users/s/Library/Caches/Homebrew/api/formula.json
+ brew_pkg_config=/lib/pkgconfig
```
...it's error as I get during opam install

**Comment by kit-ty-kate** [comment]
Crap... i can reproduce.
It works with Homebrew 3.6.16
But as soon as I updated to Homebrew 4.0.1 it failed with the same error message.

**Comment by kit-ty-kate** [comment]
It fixes itself if you export `HOMEBREW_NO_INSTALL_FROM_API=1`. I’ll see if i can add it to the packages that uses the homebrew command.

**Comment by kit-ty-kate** [comment]
This should now be fixed. A simple `opam update` (right now if you have the git remote or in an hour or two if you have the http remote) should fix it. Feel free to reopen if you see something similar.

**Comment by kit-ty-kate** [comment]
I’ve opened a ticket upstream in Homebrew, in case this is an unwanted behaviour of Homebrew 4.0+: https://github.com/Homebrew/brew/issues/14663

**Comment by gridbugs** [comment]
thanks for fixing this so quickly!
