### ISSUE TITLE
Error: `bwrap: capset failed: Operation not permitted`

### ISSUE THREAD

**Issue by yviansu** [ocaml/opam-repository#23327]
I followed these steps to install opam in a linux docker:
```bash
apt update
apt install opam -y
opam init
eval $(opam env)
opam install ocamlbuild -y
```
I have installed opam successfully, my opam version is 2.0.3.
However, when running `opam install ocamlbuild -y` in docker, an error will occur:

![image](https://user-images.githubusercontent.com/103162767/219336009-0e7c4be0-8385-4669-9ee7-819eee74b4b8.png)

I have installed opam successfully in my native linux, is this error related to the docker environment? How to fix it?

**Comment by kit-ty-kate** [comment]
Yes the sandbox is not supported in a docker environment. You can either:
* Use docker with `--priviledged`
* or initialize opam with `--disable-sandboxing`

Actually I’m not sure how you managed to initialize opam inside docker with sandboxing enabled in the first place, maybe it wasn’t checked during the init in 2.0.3 (this is an extremely old version)
