### ISSUE TITLE
Installing conf-gmp fails, because of the include path.

### ISSUE THREAD

**Issue by RBornat** [ocaml/opam-repository#23329]
This is the same problem as #5588, I think. I tried the edit/pin add trick from that issue report, and failed. I note that the mingw repository referred to in the response is now discontinued. I am unable to install conf-gmp, because opam fails to notice gmp.h in /usr/include. 

richard@DESKTOP-9P95SLG ~
    $  ls -ld /usr/include/gmp.h
    -rw-r--r-- 1 richard Administrators 84217 Aug 21  2021 /usr/include/gmp.h

    richard@DESKTOP-9P95SLG ~
    $ opam install conf-gmp
    The following actions will be performed:
      ∗ install conf-gmp 4

    <><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

    <><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
    [ERROR] The compilation of conf-gmp failed at "C:\\OCaml64\\bin\\sh.exe -exc
        $(ocamlc -config | awk -F '[\t\r ]+' '/^bytecomp_c_compiler/
        {for(i=2;i<=NF;i++) printf \"%s \", $i}') -c $CFLAGS test.c".

    #=== ERROR while compiling conf-gmp.4 =========================================#
    # context     2.0.10 | win32/x86_64 | ocaml-variants.4.14.0+mingw64c | git+https ://github.com/fdopen/opam-repository-mingw.git#opam2
    # path        ~/.opam/4.14.0+mingw64c/.opam-switch/build/conf-gmp.4
     ]+' '/^bytecomp_c_compiler/ {for(i=2;i<=NF;i++) printf "%s ", $i}') -c $CFLAGS test.c
    # exit-code   1
    # env-file    ~/.opam/log/conf-gmp-984-5a61c5.env
    # output-file ~/.opam/log/conf-gmp-984-5a61c5.out
    ### output ###
    # ++ ocamlc -config
     ]+' '/^bytecomp_c_compiler/ {for(i=2;i<=NF;i++) printf "%s ", $i}'
    # + x86_64-w64-mingw32-gcc -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -c test.c
    # test.c:1:10: fatal error: gmp.h: No such file or directory
    #     1 | #include <gmp.h>
    #       |          ^~~~~~~
    # compilation terminated.

    <><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
    ┌─ The following actions failed
    │ λ build conf-gmp 4
    └─
    ╶─ No changes have been performed

    The packages you requested declare the following system dependencies. Please
    make sure they are installed before retrying:
        gmp

Is there now a workaround?

**Comment by mseri** [comment]
Does this change help? https://github.com/ocaml/opam-repository/pull/22954

**Comment by RBornat** [comment]
I forgot to say: it's a cygwin problem. homebrew and macports are in the wrong universe.

**Comment by RBornat** [comment]
Sorry. Misunderstood. Don't know. How do I test any of your changes?

**Comment by RBornat** [comment]
my conf-gmp.4 contains

    build: [
      ["sh" "-exc" "cc -c $CFLAGS -I/usr/local/include test.c"] {os != "macos" & os != "win32"    }
      [
    		"sh"
    		"-exc"
                   "$(ocamlc -config | awk -F '[\t\r ]+' '/^bytecomp_c_compiler/ {for(i=2;i<=NF;i++) printf \"%s \", $i}') -c $CFLAGS test.c"
    	] {os = "win32" & os-distribution = "cygwinports"}
      [
        "sh"
        "-exc"
        "cc -c $CFLAGS -I/opt/homebrew/include -I/opt/local/include -I/usr/local/include test.c"
    ] {os = "macos"}
    ]

Please forgive my ignorance: I would have thought that means (I'm running win64, I hope) -- look in /usr/local/include, where I have placed a copy of gmp.h

    richard@DESKTOP-9P95SLG ~
    $ ls /usr/local/include/gmp.h
    /usr/local/include/gmp.h

(I've also put a copy in /usr/include, but it doesn't find that either). I'm not an opam expert, as you can tell from this comment.

**Comment by mseri** [comment]
I think all versions of windows resolve to `win32` but I could be mistaken. I don't have a windows machine to check

**Comment by RBornat** [comment]
Understanding begins to dawn ... the line with 'awk' generates the name of the mingw C compiler, so it's that one that needs the -I/usr/local/include. And no space after -I (I think I made that mistake before). Then YES, conf-gmp loads, following the recipe in #5588. 

BUT THEN, oh dear, opam install zarith fails because it says it can't find gmp.h or mpir.h. Indeed I don't have mpir.h Perhaps if I look at .configure and see if I can tell it where gmp.h is ...

So, still lost in the woods.

**Comment by RBornat** [comment]
Belatedly, understanding dawns. The line with 'awk' generates the mingw C compiler name, so that's the one to modify. And using the #5588 trick I can get conf-gmp.4 to work.

But only a small hurrah, because then `opam install zarith` fails, saying it can't find gmp.h or mipr.h. Never heard of mipr.h, so perhaps if I can hack .configure to recognise gmp.h I might get there. 

Still on the road to nowhere ...

**Comment by RBornat** [comment]
Then I looked at #5591, because it was about cygwin and zarith. I added some stuff to zarith/zarith.1.12/opam, hoping that it was the right thing, but it wasn't 

    build: [
      ["./configure"] {os != "openbsd" & os != "freebsd" & os != "macos" & os!="win32" & os-distribution!="cygwinports"}
      [
        "sh"
        "-exc"
        "LDFLAGS=\"$LDFLAGS -L/usr/local/lib\" CFLAGS=\"$CFLAGS -I/usr/local/include\" ./configure"
      ] {os = "openbsd" | os = "freebsd"}
      [
        "sh"
        "-exc"
        "LDFLAGS=\"$LDFLAGS -L/opt/local/lib -L/usr/local/lib\" CFLAGS=\"$CFLAGS -I/opt/local/include -I/usr/local/include\" ./configure"
          ] {os = "macos" & os-distribution != "homebrew"}
          [
        "sh"    
        "-exc"
        "LDFLAGS=\"$LDFLAGS -L/opt/local/lib -L/usr/local/lib\" CFLAGS=\"$CFLAGS -I/opt/local/include -I/usr/local/include\" ./configure"
      ] {os = "macos" & os-distribution = "homebrew" & arch = "x86_64" }
      [
        "sh"
        "-exc"
        "LDFLAGS=\"$LDFLAGS -L/opt/homebrew/lib\" CFLAGS=\"$CFLAGS -I/opt/homebrew/include\" ./configure"
      ] {os = "macos" & os-distribution = "homebrew" & arch = "arm64" }
      [
        "sh"
        "-exc"
        "CFLAGS=\"$CFLAGS -I/usr/local/include\" ./configure"
      ] {os="win32" & os-distribution="cygwinports"}
    [make]
    ]

It wasn't because it said `/usr/bin/sh: ./configure: No such file or directory` . So still desperately in need of a hint from someone.

**Comment by RBornat** [comment]
so then I noticed I should have some spaces round the '=' and '!=', but it doesn't make any difference. Still this mod doesn't work.

    <   ["./configure"] {os != "openbsd" & os != "freebsd" & os != "macos" & os != "win32"}
    <   [
    <     "sh"
    <     "-exc"
    <     "CFLAGS=\"$CFLAGS -I/usr/local/include\" ./configure"
    <   ] {os = "win32" & os-distribution = "cygwinports"}
    ---
    >   ["./configure"] {os != "openbsd" & os != "freebsd" & os != "macos"}

**Comment by RBornat** [comment]
I used `opam pin add`, btw. I suspect that's the root of my problem, but I don't know what else to do.

**Comment by RBornat** [comment]
Even more belatedly, understanding dawns again. Of course, I just install zarith myself. opam is never going to work for me.
