### ISSUE TITLE
opam switch create 4.08.1 fails with clang

### ISSUE THREAD

**Issue by hannesm** [ocaml/opam-repository#23541]
Hello,

I would like to setup a OCaml 4.08 environment. I see there were some patches included (a) to "fix gcc 10" and (b) alt-signal-stack.patch, but unfortunately in my environment (FreeBSD, clang 13) the switch creation fails:
```
#=== ERROR while compiling ocaml-base-compiler.4.08.1 =========================#
# context     2.1.2 | freebsd/x86_64 |  | https://opam.robur.coop#c6df073e17897e3d5ffec6b44aebeebf5595d342
# path        /usr/home/hannes/.opam/4.08.1/.opam-switch/build/ocaml-base-compiler.4.08.1
# command     /usr/local/bin/gmake -j3 world
# exit-code   2
# env-file    /usr/home/hannes/.opam/log/ocaml-base-compiler-5886-e8a628.env
# output-file /usr/home/hannes/.opam/log/ocaml-base-compiler-5886-e8a628.out
### output ###
# [...]
# cc -c -O2 -fno-strict-aliasing -fwrapv -Wall -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/usr/home/hannes/.opam/4.08.1/lib/ocaml"'  -o prims.o prims.c
# cc -O2 -fno-strict-aliasing -fwrapv -Wall -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -DOCAML_STDLIB_DIR='"/usr/home/hannes/.opam/4.08.1/lib/ocaml"'  -Wl,-E -g -o ocamlrund prims.o libcamlrund.a -lm  -lpthread 
# ld: error: duplicate symbol: caml_debug_info
# >>> defined at backtrace_byt.c:47
# >>>            backtrace_byt_bd.o:(caml_debug_info) in archive libcamlrund.a
# >>> defined at backtrace.c:31
# >>>            backtrace_bd.o:(.bss+0x10) in archive libcamlrund.a
# cc: error: linker command failed with exit code 1 (use -v to see invocation)
# gmake[1]: *** [Makefile:295: ocamlrund] Error 1
# gmake[1]: *** Waiting for unfinished jobs....
# gmake[1]: Leaving directory '/usr/home/hannes/.opam/4.08.1/.opam-switch/build/ocaml-base-compiler.4.08.1/runtime'
# gmake: *** [Makefile:323: coldstart] Error 2
```

Now, this was reported upstream https://github.com/ocaml/ocaml/issues/9144, and fixed by https://github.com/ocaml/ocaml/commit/53327d777ddcacf829c77c0bd3569a8ade2c72b8 (just before 4.11).

Now, it's pretty unclear why a completely separate patch, "fix-gcc10.patch", got included in the opam-repository (in https://github.com/ocaml/opam-repository/pull/16728), and confused why the approach for "alt-signal-stack.patch" (to use a "extra-source") has been done. I was unable to find any documentation what "best current practises" are in this respect, anyone aware of such a document?

/cc @dra27 @avsm who seem to be involved in this area

**Comment by kit-ty-kate** [comment]
> Now, it's pretty unclear why a completely separate patch, "fix-gcc10.patch", got included in the opam-repository (in #16728), and confused why the approach for "alt-signal-stack.patch" (to use a "extra-source") has been done. I was unable to find any documentation what "best current practises" are in this respect, anyone aware of such a document?

There isn't any document that i know of but the reasoning for choosing `extra-source` over `files/` is simply that the backporting in https://github.com/ocaml/opam-repository/pull/19855 was a lot bigger than in https://github.com/ocaml/opam-repository/pull/16728 and `extra-source` patches is easier to iterate with and lighter for opam-repository. Also, in the case of https://github.com/ocaml/opam-repository/pull/19855 it has the advantage to point to an official commit in ocaml/ocaml so it makes it a bit more genuine. 

`extra-source` is preferred for those reasons but in practice there isn't any strict rules and as long as the patch isn't too big it should be fine.

Now for the issue with clang 13, if you want/have time to either modify `fix-gcc10.patch`, or upload a patch to https://github.com/ocaml/opam-source-archives/ if you prefer to go this route (if there isn't an official commit in ocaml/ocaml that applies cleanly already). If you don't have time we can try to have a look at it but we're already understaffed and busy with many other things so I can't promise it'll be done today.

**Comment by hannesm** [comment]
Thanks for your reply @kit-ty-kate. Unfortunately I'm not confident enough to touch any "ocaml-base-compiler" (and variants packages) in the opam-repository due to the desired platform support (and my lack of testing abilities) and required time to conduct such changes. FWIW, on a modern FreeBSD system, "Fix mergeable section flags and use .rodata.cst16 where appropriate (#9981)" is required as well.

**Comment by hannesm** [comment]
My interest in "OCaml 4.08.1" is non-existing. Closing.
