### ISSUE TITLE
OCaml 5.1.0 Release Readiness

### ISSUE THREAD

**Issue by Octachron** [ocaml/opam-repository#23669]
This issue tracks the build and readiness information of core platform tools and libraries in preparation for the OCaml 5.1 release. It’s intended as a meta-issue / holding place for TODO lists and links to other milestones/issues rather than general discussion (which is welcomed on Discuss or on linked issues).

Packages that are fixed upstream, have a PR ready, or can be used as-is for testing purpose, are in [kit-ty-kate/opam-alpha-repository](https://github.com/kit-ty-kate/opam-alpha-repository). A test run is done using this repository every 48 hours and the latest run can be seen [in opam-health-check](http://check.ocamllabs.io) and compared against OCaml 5.1.

## Platform tools:

- [x] opam
- [x]  dune
- [x]  merlin (https://github.com/ocaml/opam-repository/pull/23848)
- [x]  lsp-server / vscode-plugin 
- [x]  odoc (draft ocaml/odoc#956)
- [x]  ocamlformat
- [x]  ocp-indent

## Ecosystem:

- [x]  ocamlfind
- [x]  ocamlbuild
- [x]  ppxlib
- [x]  mdx
- [x]  utop (done in https://github.com/ocaml/opam-repository/pull/23681)
- [x]  dune-release
- [x]   opam-publish

## Infrastructure:

- [ ] ocaml.org (https://github.com/ocaml/ocaml.org/pull/1470)
- [x] docker base containers 
- [x] ocaml-ci
- [x] opam-repo-ci

**Comment by anmonteiro** [comment]
Reason is ready to go: https://github.com/reasonml/reason/pull/2714

**Comment by avsm** [comment]
updated with the merlin preview release https://github.com/ocaml/opam-repository/pull/23848/files

**Comment by kit-ty-kate** [comment]
OCaml 5.1.0 was released.
