### ISSUE TITLE
CI Request: Automatically add version upper-bounds to reverse dependencies as necessary when a package updates

### ISSUE THREAD

**Issue by gridbugs** [ocaml/opam-repository#23694]
When a package is updated with an API-breaking change, reverse dependencies which specify their dependency on the package without an upper bound on its version number will break. A reasonable way to address these breakages would be to set the upper bound in the version constraints in these packages to the previously released version of the newly-updated package. I think it would be useful to have the PR suggest these changes automatically.

**Comment by mseri** [comment]
Having an automatic procedure would be great however we don't yet have a good way to detect automatically the correct changes. Nevertheless, we regularly fix the upper bounds of the revdeps when new packages with breaking changes are released

**Comment by gridbugs** [comment]
Closing this and opening https://github.com/ocurrent/opam-repo-ci/issues/217 to continue this discussion as that's a more appropriate org/repo for this issue.
