### ISSUE TITLE
conf-postgres depext needs to be updated for homebrew

### ISSUE THREAD

**Issue by haochenx** [ocaml/opam-repository#23912]
- related: https://github.com/ocaml/opam-repository/pull/23909 ([detailed in this comment](https://github.com/ocaml/opam-repository/pull/23909#issuecomment-1586182484))

Currently the package `conf-postgres` is specifying `postgresql` as the homebrew package to install on macOS (when using homebrew) https://github.com/ocaml/opam-repository/blob/f016dc51d87d9323b994ea1d40c09a70187d0b12/packages/conf-postgresql/conf-postgresql.1/opam#L27

But recently with homebrew, one has to explicitly specify the major version of postgres to install, e.g. `brew install postgresql@14` or `brew install postgresql@15` and `brew install postgresql` will fail.

**Comment by haochenx** [comment]
@mmottl do you have an opinion about how we should deal with this?

**Comment by mmottl** [comment]
I believe specifying a particular version may be the only reasonable choice.  This is the way this problem is handled for other platforms.  You may want to settle on a really stable and popular version for that.

**Comment by haochenx** [comment]
All officially released major versions of Postgres are reasonably stable and has long support periods (e.g., the current newest stable release is Postgres 15, which is released last year and will be supported until 2027).

Also, it seems that the newest [Postgres 15 enjoys supports back to Big Sur on both Apple Silicon and Intel models](https://formulae.brew.sh/formula/postgresql@15#default), I think it's reasonable to default to the give the user the newest version (now Postgres 15) by default.

**Comment by haochenx** [comment]
I have opened PR #24105 to address this.
