### ISSUE TITLE
Is there a solotion like cocotb, pyuvm, pyvsc in ocaml?

### ISSUE THREAD

**Issue by davidmlw** [ocaml/opam-repository#23914]
I see big contributions of Ocaml in formal verification of hardware. How about simulation-based hardware verification? I saw some approaches in Python, like cocotb, pyuvm, and pyvsc. But pyton is dynamic typing and slow, which is vital for hardware simulation tasks (it may last weeks and months).

Ocaml is strict and fast, but I didn't see similar efforts. Would some colleagues point some link for me? Does it make sense to start Ocaml coroutine based solutions, and what tasks need to be done?

**Comment by avsm** [comment]
Thanks for the query, @davidmlw. This is a bug trucker for the opam-repository, and the best place to get an answer to your query would be to repost it to the discussion forums on discuss.ocaml.org.

Thanks!
