### ISSUE TITLE
Consider marking base.v0.16.2 as unavailable with MSVC

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/opam-repository#24151]
Not picking on this one package, but it is pretty essential. base.v0.16.1 worked fine with MSVC (and is included in DkML), so this is a regression.

See https://github.com/janestreet/base/issues/157 for the MSVC failure.

**Comment by avsm** [comment]
A PR to constrain this in the opam-repo is welcome... we don't have any automated testing for Windows yet, unfortunately.

**Comment by jonahbeckford** [comment]
What is the preferred filter to use in this scenario?

**Comment by kit-ty-kate** [comment]
there is no MSVC specific filter/packages currently in opam-repository so I would say:
```
available: os != "win32"
```
which makes the package unavailable on Windows as a whole.
