### ISSUE TITLE
Is the opam-ci test-apparatus having problems these  last two weeks?

### ISSUE THREAD

**Issue by chetmurthy** [ocaml/opam-repository#24221]
I submitted what should have been a tiny PR ( https://github.com/ocaml/opam-repository/pull/24147 ) a couple of weeks ago, and got a massive number of revdeps failures -- first over a thousand, then 140, then 1460, and now 871.   The test-failures are of all sorts -- missing files, corrupted tarballs, failures in "opam install --with-test") and on and on.

I investigated several of them (by copying the dockerfile script and running it locally) and each time, I found that if I removed the packages in my PR (which in any case weren't actually required for the revdep package to build -- @kit-ty-kate explained that it was a bug in the dependency-calculation algo: https://github.com/ocurrent/opam-repo-ci/issues/227 ) the docker script *still* failed in precisely the same way.  And then if I just run those same commands in my local opam environment (with the specified compiler version), it also fails.

So somehow these packages were accepted into opam even though they failed to pass tests ?  And there are hundreds of such packages ?  I have to believe something else is wrong, not the packages themselves.  I can't figure what I'm doing wrong, since I can eliminate my own pacakages and the failures persist.

Two examples: http-cookie.4.2.0, uring.0.1.  If it would be useful to produce more examples, I can do that.

I attach the files with and without my package, that I ran: 
[doit-without-camlp5.BASH.TXT](https://github.com/ocaml/opam-repository/files/12268345/doit-without-camlp5.BASH.TXT)
[doit-with-camlp5.BASH.TXT](https://github.com/ocaml/opam-repository/files/12268346/doit-with-camlp5.BASH.TXT)

**Comment by shonfeder** [comment]
I'm not sure what this was, but iiuc it has been resolved for a long while.
