### ISSUE TITLE
invisible character conf-unwind.0

### ISSUE THREAD

**Issue by tjm165** [ocaml/opam-repository#24580]
# Issue 
Package `conf-unwind.0` has an invisible character which causes an issue when building the package. This causes error 
```
     At /.esy/opam-repository/packages/conf-unwind/conf-unwind.0/opam:22:0-22:1::
     '�' is not a valid token
```

# Screenshot
<img width="1361" alt="Screenshot 2023-10-04 at 1 11 49 PM" src="https://github.com/ocaml/opam-repository/assets/32528539/b0e897ea-1010-47f6-9735-dc614d4547fe">

# Solution
Replace with standard space ` ` character

# Pull Request
Please merge this pull request to solve this issue
https://github.com/ocaml/opam-repository/pull/24579

**Comment by haochenx** [comment]
fixed in #24579
