### ISSUE TITLE
Integration tests using the gcc compiler mostly fail on MacOS

### ISSUE THREAD

**Issue by lukstafi** [ocaml/opam-repository#24885]
[Example of a failed run](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/c7587a53735325915d657e78c045f94efb66fec2/variant/macos,macos-homebrew-ocaml-5.1-arm64,conf-libgccjit.1).
[Example of a successful run](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/c7587a53735325915d657e78c045f94efb66fec2/variant/macos,macos-homebrew-ocaml-5.1-amd64,conf-libgccjit.1).

According to "the internet", the problem on a particular MacOS system can be fixed by installing the XCode commandline tools: `xcode-select --install`. I have not verified this since I cannot reproduce the problem.

For me, currently almost all runs fail (I'd guess 99%); a few weeks ago, it felt like ~ 50% runs were failing.

Error message:

```
# /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc/aarch64-apple-darwin23/13/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
#    78 | #include <_stdio.h>
#       |          ^~~~~~~~~~
```

**Comment by lukstafi** [comment]
Ah! Could this be https://github.com/ocaml/opam/issues/601#issuecomment-1075566540 "On macOS having a gcc or binutils install that overrides xcode tools"?

( https://github.com/ocaml/opam/issues/4837, https://github.com/ocaml/opam/issues/4912, https://github.com/ocaml/opam/issues/3650, https://github.com/ocaml/opam/issues/5783 )

**Comment by dbuenzli** [comment]
@lukstafi I don't think using `gcc` with macOS in the `opam-repository` is a supported workflow. Perhaps it ought to be documented somewhere, the question is where.

**Comment by lukstafi** [comment]
The functionality (gcc on MacOS) is no longer important / needed for me. If this issue is sufficiently discoverable to serve as documentation, maybe closing it is OK now.

**Comment by lukstafi** [comment]
Closing it as "won't fix".
