### ISSUE TITLE
archive index not updating

### ISSUE THREAD

**Issue by gares** [ocaml/opam-repository#24895]
Hello, #24889 was merged 20 hours ago but I still don't see the package (after doing a opam update).

**Comment by mseri** [comment]
It is back! Thanks for the notification

**Comment by samwgoldman** [comment]
Is this happening again? The latest package by date is [vscoq-language-server](https://opam.ocaml.org/packages/vscoq-language-server), which this issue is about. It seems like nothing merged since then has been published?

**Comment by gares** [comment]
I confirm the index is again outdated
