### ISSUE TITLE
readdir_with_kind_if_available_unix expects non-POSIX d_type

### ISSUE THREAD

**Issue by donncave** [ocaml/opam-repository#24901]
Per POSIX, the dirent struct has d_ino and d_name.

src_ext/dune-local/src/dune_filesystem_stubs/readdir.c doesn't compile successfully on Haiku, which doesn't have dirent.d_type nor the DT_REG etc. symbols that go with it.

One can of course get those values from stat(2) ... given the file name and relative or absolute path.  If I can't make that happen, would it be OK to just throw an exception here?  I haven't looked to see why this functionality is needed here and not the older version I have, 2.0.7.

**Comment by mseri** [comment]
Is this an issue in dune? In this case this issue should perhaps be opened in dune's repository
