### ISSUE TITLE
hevea URL changed.

### ISSUE THREAD

**Issue by olafhering** [ocaml/opam-repository#24934]
It seems the issue tracker in `https://opam.ocaml.org/packages/hevea/` changed from `http://github.com/herd/hevea/issues/` to `https://github.com/maranget/hevea/issues`.

**Comment by mseri** [comment]
That seems to be the correct official repository: http://hevea.inria.fr/

maybe it changed name since the old one is no longer present on github

**Comment by mseri** [comment]
I am closing since this seems to have been an intentional change from the maintainers
