### ISSUE TITLE
Opam repository API

### ISSUE THREAD

**Issue by vitoyucepi** [ocaml/opam-repository#25109]
## Summary

Is there a way to get version information about specific opam packages?
Some kind of API, preferably in JSON format, would be nice.

## Details

I'd like to pin and update opam package versions automatically.
To do this, I use renovate bot, but it doesn't have an internal module to retrieve version information from the opam package repository. So I have to rely on github tags or something to detect the version of some packages, but it may take some time to update until they will be available in the official repo.

There's already an implementation of opam datasource that uses this github repo, but it was rejected for some reason. I think I could create a new feature request, but I'd like to prepare.

I've found that I can use https://opam.ocaml.org/index.tar.gz to download the entire package database, but it's quite large. Are there any other urls that could be used for this purpose?

**Comment by sabine** [comment]
There's a GraphQL API at https://ocaml.org/graphql that can be explored here:

https://ocaml.org/graphiql

**Comment by vitoyucepi** [comment]
Thank you.

I've created a feature request in the renovate repository at https://github.com/renovatebot/renovate/discussions/27481. You can upvote it if you'd like.

Since the answer has been provided, I will close this issue for now.
