### ISSUE TITLE
OCaml 5.2.0 Release Readiness

### ISSUE THREAD

**Issue by Octachron** [ocaml/opam-repository#25182]
This issue tracks the build and readiness information of core platform tools and libraries in preparation for the OCaml 5.2 release. It’s intended as a meta-issue and a home for TODO lists and links to other milestones/issues rather than general discussion (which is welcomed on Discuss or on linked issues).

Packages that are fixed upstream, have a PR ready, or can be used as-is for testing purpose, are in [kit-ty-kate/opam-alpha-repository](https://github.com/kit-ty-kate/opam-alpha-repository).  The latest state of the opam ecosystem can be seen [in opam-health-check](http://check.ocamllabs.io) and compared against OCaml 5.2.

## Platform tools:

- [x] opam
- [x]  dune
- [x]  merlin
- [x]  lsp-server / vscode-plugin 
- [x]  odoc (https://github.com/ocaml/odoc/pull/1094)
- [x]  ocamlformat
- [x]  ocp-indent

## Ecosystem:

- [x]  ocamlfind
- [x]  ocamlbuild
- [x]  ppxlib
- [x]  mdx
- [x]  utop (https://github.com/ocaml-community/utop/pull/470)
- [x]  dune-release
- [x]   opam-publish

## Infrastructure:

- [x] ocaml.org
- [x] docker base containers 
- [x] ocaml-ci
- [x] opam-repo-ci

**Comment by anmonteiro** [comment]
Reason https://github.com/reasonml/reason/pull/2734

**Comment by hhugo** [comment]
@Octachron, should this be closed ?

**Comment by Octachron** [comment]
Indeed, it seems that the infrastructure has been updated; thanks for the ping!
