### ISSUE TITLE
Invalid_argument("OpamEnv.unzip_to") opam error after installing conf-openblas

### ISSUE THREAD

**Issue by pklehre** [ocaml/opam-repository#25194]
The following sequence of commands on a fresh opam init (opam v2.1.3) leads to an error that renders the opam switch in an unusable state (e.g., impossible to install new packages)

```
opam switch create 5.1.1+flambda ocaml-variants.5.1.1+options ocaml-option-flambda
opam install conf-openblas
```

Error:

```
[pkl@zeta ~]$ opam env
Fatal error:
Invalid_argument("OpamEnv.unzip_to")
```

**Comment by mseri** [comment]
I see, I think it is due to a bug in opam < 2.1.5:
```
2.1.5:
* [BUG] Variables are now expanded in build-env (as for setenv) [#5352 @dra27]
* Correctly handle empty environment variable additions [#5350 @dra27]
* Skip empty environment variable additions [#5350 @dra27]
[…]
```

**Comment by mseri** [comment]
Ping @dra27, what do you suggest to keep openblas installable? I think we should probably revert your commit and simply ask people to configure PKG_CONFIG_PATH appropriately in a post message
