### ISSUE TITLE
ocaml lru cache changed signature

### ISSUE THREAD

**Issue by mseri** [ocaml/opam-repository#25361]
```
#=== ERROR while fetching sources for lru-cache.0.3.0 =========================#
OpamSolution.Fetch_fail("https://framagit.org/zoggy/ocaml-lru-cache/-/archive/0.3.0/ocaml-lru-cache-0.3.0.tar.gz (Bad checksum, expected md5=33da0c73f5cb1d671d2e6158c5d0edd1)")
```
Ping @zoggy

**Comment by zoggy** [comment]
It seems to be the same problem as for css package reported here: https://github.com/ocaml/opam-repository/issues/25344 . Do you have the original tarball and could you upload it to opam source archive ?

**Comment by hannesm** [comment]
Dear @zoggy:

there are archives available, e.g.:
- ocaml-lru-cache-0.1.0.tar.gz (md5 = 0d5398118c2c7d1e5d5a86f1ed23b893) https://opam.robur.coop/cache/md5/0d/0d5398118c2c7d1e5d5a86f1ed23b893
- ocaml-lru-cache-0.2.0.tar.gz (md5 = 9217dd7dc3c74e7fe52665efc2785a4d) https://opam.robur.coop/cache/md5/92/9217dd7dc3c74e7fe52665efc2785a4d
- ocaml-lru-cache-0.3.3.tar.gz (md5 = 33da0c73f5cb1d671d2e6158c5d0edd1) https://opam.robur.coop/cache/md5/33/33da0c73f5cb1d671d2e6158c5d0edd1

Hope to help,

Hannes

**Comment by zoggy** [comment]
Thanks @hannesm . I wait for a suggestion regarding a decent place to upload :-)
