### ISSUE TITLE
debug switch

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-repository#2557]
One thing I find myself doing often is pinning a package so that I can compile it with -debug, in order to get meaningful information for profiling/debugging (e.g. stacktraces). Do you think it would be possible to provide a switch that compiles everything with `-g`. Or is there a better solution to that problem ?

**Comment by dbuenzli** [comment]
Let's see the story that will be brought by spacetime in 4.04.

**Comment by whitequark** [comment]
@dbuenzli spacetime?

**Comment by dbuenzli** [comment]
https://github.com/ocaml/ocaml/pull/585
