### ISSUE TITLE
`arm32-ocaml-4.14` is broken: image's platform mismatch

### ISSUE THREAD

**Issue by thierry-martinez** [ocaml/opam-repository#25929]
Checks fail on `arm32-ocaml-4.14` with the following error:
```
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
For instance: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/4f286db2006c405a0f54f789422cb3fca35daa49/variant/extras,arm32-ocaml-4.14,conf-libclang.10

**Comment by shonfeder** [comment]
This warning is expected and doesn't itself cause tests to fail (see, e.g., https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/c584987fc1055c455c37fd7896c6e24894401b2c/variant/extras,arm32-ocaml-5.2,reanalyze.2.25.0,tests). Our understanding is that this is a benign waning and should not cause any problems. If you can identify how this is causing problems, please open an issue with that information on https://github.com/ocurrent/opam-repo-ci/issues

Thanks!
