### ISSUE TITLE
Unison missing fsmonitor

### ISSUE THREAD

**Issue by koumak55** [ocaml/opam-repository#26006]
Hi, I am installing via Opam Ocaml 4.02.1 and Unison 2.51.2 on Ubuntu 24.04 but fsmonitor is missing. Any idea? Thanks for your help.

**Comment by dbuenzli** [comment]
Could you be more specific about what's not working here ?

**Comment by koumak55** [comment]
When I install unison from other sources, fsmonitor is included. fsmonitor is required for the `repeat = watch` parameter, which provides "real-time" synchronization. When I install unison via opam, the fsmonitor is missing.

**Comment by dbuenzli** [comment]
It seems the package was added by @jhjourdan in https://github.com/ocaml/opam-repository/pull/25291. He may be able to answer the question. 

In general the `opam-repository` issue tracker is for dealing with    build problems and not packaging requests. So I'm going to close this but feel free to continue the discussion here.
