### ISSUE TITLE
`opam switch create 5.0.0` fails

### ISSUE THREAD

**Issue by fpottier** [ocaml/opam-repository#26050]
Hello,
The creation of a fresh `5.0.0` switch fails with the following error message. I have just run `opam update` and I have removed the pre-existing `5.0.0` switch prior to running `opam switch create 5.0.0`. I am running MacOS with an Apple processor.

```
⬇ retrieved ocaml-config.3  (cached)
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed host-arch-arm64.1
∗ installed host-system-other.1
∗ installed ocaml-options-vanilla.1
⬇ retrieved ocaml-base-compiler.5.0.0  (cached)
∗ installed ocaml-base-compiler.5.0.0
∗ installed ocaml-config.3
[ERROR] The compilation of ocaml.5.0.0 failed at "ocaml
        /Users/fpottier/.opam/5.0.0/share/ocaml-config/gen_ocaml_config.ml
        5.0.0 ocaml".

#=== ERROR while compiling ocaml.5.0.0 ========================================#
# context     2.1.5 | macos/arm64 | ocaml-base-compiler.5.0.0 | https://opam.ocaml.org#25082ca0
# path        ~/.opam/5.0.0/.opam-switch/build/ocaml.5.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml /Users/fpottier/.opam/5.0.0/share/ocaml-config/gen_ocaml_config.ml 5.0.0 ocaml
# exit-code   2
# env-file    ~/.opam/log/ocaml-68161-44c623.env
# output-file ~/.opam/log/ocaml-68161-44c623.out
### output ###
# Cannot find file /Users/fpottier/.opam/5.0.0/share/ocaml-config/gen_ocaml_config.ml.
```

**Comment by fpottier** [comment]
And running `opam` 2.1.6.

**Comment by rleonid** [comment]
I've also tried several switches and the problem seems to be that either the `share` or `ocaml-config` directory in `~/.opam/<switch>share/ocaml-config/gen_ocaml_config.ml` is not created or correctly unpacked.

**Comment by hannesm** [comment]
Dear @fpottier and @rleonid, sorry for your inconvenience.

It seems to be caused by the removal of files, and discussed in https://github.com/ocaml/opam-repository/issues/25961 and https://discuss.ocaml.org/t/the-compilation-of-ocaml-5-1-1-failed-at-ocaml-gen-ocaml-config-ml-5-1-1-ocaml/14731

So, the quick workaround: `rm -rf ~/.opam/repo/default{,.tar.gz} && opam update default` -- in the long run, ensure that you have a GNU patch installed (via homebrew or macports).

**Comment by fpottier** [comment]
Thanks @hannesm for the work-around, which worked. I had installed `gpatch` already but did not know how to fix my broken state. I am closing this issue.

**Comment by rleonid** [comment]
Thank you @hannesm !!!
