### ISSUE TITLE
Policy about adding multiple packages in a single PR ?

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-repository#26386]
With the tooling I have to publish on the opam repository it's easy for me to release multiple packages to the opam repo. 

I usually do so for the Unicode release where the packages are related. 

But what's the maintainers take on doing so with packages that are possibly unrelated ? Do the maintainters prefer single atomic PRs or is it ok to bundle a few packages in the same PR ?

**Comment by avsm** [comment]
Bundling is just fine, within reason. In some ways, it’s even better since the revdeps run will be consistent across the batch of packages being changed or added

**Comment by dbuenzli** [comment]
Thanks!
