### ISSUE TITLE
Discussing the release of a `loc` package

### ISSUE THREAD

**Issue by mbarbin** [ocaml/opam-repository#26604]
I am using a type to represent a range of lexing positions from a file, which I called `Loc.t`. It's [here](https://github.com/mbarbin/loc).

I use it as dependency to decorate AST nodes built by parsers, enabling located error messages during file processing (compilers, interpreters, linters, refactor tools, etc.).

I am considering submitting it to the opam-repository, but I have some reservations.

- Firstly I am unsure how to package it for publication. Would there be push-back about grabbing the global "loc" name on opam?
- Secondly, this is very similar to Dune's `Stdune.Loc` module (and actually uses `stdune` under the hood). Perhaps it would make more sense to work on extracting the Dune one as a foundational package (such as `pp`, `dyn`, and `ordering`), rather than maintaining this one separately.

My motivation is that I have other libraries that I'd like to eventually publish to opam that depend on it. Some examples below:

- [file-rewriter](https://github.com/mbarbin/file-rewriter)
- cmdlang's [Err](https://github.com/mbarbin/cmdlang/blob/main/lib/err/src/err.mli) module

Similar libraries or modules:

- Dune's [Loc.t](https://github.com/ocaml/dune/blob/dedfb76837bad6ea6de97de07e61f2ac10442127/otherlibs/stdune/src/loc.mli#L1)

- Parsexp's [ranges](https://github.com/janestreet/parsexp/blob/14af9ab942251783de6abb20e0d0e0eec6080062/src/positions.mli#L59)

- Ppxlib's [Location.t](https://github.com/ocaml-ppx/ppxlib/blob/456d1a99d354f8b3f34f01d1a7b61dc43ef678b6/src/location.ml#L4)

- Compilerlibs's [loc](https://github.com/ocaml/ocaml/blob/81003f23918729fa730c01ccffec25939cd730ff/utils/warnings.mli#L23)

I would appreciate any thoughts or feedback on this matter. Thank you!

**Comment by mbarbin** [comment]
I've asked the question about Dune to the Dune devs here https://github.com/ocaml/dune/discussions/10948

**Comment by avsm** [comment]
Thanks for all your work in establishing consensus here, @mbarbin. From the opam-repo perspective, we have no objection...

**Comment by mbarbin** [comment]
Thank you. With this feedback, I feel comfortable opening #26625 for review.

I will be closing this issue then, the Dune discussion part can stay open as needed.

Thanks a lot!
