### ISSUE TITLE
cannot install lablgl on ocaml 5.2

### ISSUE THREAD

**Issue by sanette** [ocaml/opam-repository#26701]
I am having a hard time understanding the opam error messages.

The first one  ` lablgl → ocaml < 5.0 `: but `lablgl` does not have this restriction in its opam file, only `"ocaml" {>= "4.14"}`

The second one ` lablgl → camlp5 → ocaml < 5.2.0 `: but in fact nothing says that `campl5` cannot be installed in ocaml 5.2.0 (and in fact it can: `opam install camlp5` works)

etc.

so how to understand these messages?

thanks

```
$ opam install lablgl
[ERROR] Package conflict!
  * No agreement on the version of ocaml-base-compiler:
    - (invariant) → ocaml-base-compiler = 5.2.0
    - lablgl → ocaml < 5.0 → ocaml-base-compiler (= 3.08.0 | = 3.08.3 | = 3.09.3 | = 3.10.0 | =
      3.11.0 | = 3.11.1 | = 4.02.0 | = 4.02.1 | = 4.02.2 | = 4.05.0 | = 4.06.0 | = 4.09.1 | =
      4.10.0)
    You can temporarily relax the switch invariant with `--update-invariant'
  * No agreement on the version of ocaml:
    - (invariant) → ocaml-base-compiler = 5.2.0 → ocaml = 5.2.0
    - lablgl → camlp5 → ocaml < 5.2.0
  * Incompatible packages:
    - lablgl → camlp5
    - lablgl
  * Incompatible packages:
    - (invariant) → ocaml-system >= 5.2.0
    - lablgl → ocaml < 5.0 → dkml-base-compiler < 4.14.1~
  * Incompatible packages:
    - (invariant) → ocaml-system >= 5.2.0
    - lablgl → ocaml < 5.0 → ocaml-base-compiler (= 3.08.0 | = 3.08.3 | = 3.09.3 | = 3.10.0 | =
      3.11.0 | = 3.11.1 | = 4.02.0 | = 4.02.1 | = 4.02.2 | = 4.05.0 | = 4.06.0 | = 4.09.1 | =
      4.10.0 | >= 4.13.2~)
  * Incompatible packages:
    - (invariant) → ocaml-base-compiler = 5.2.0
    - lablgl → ocaml < 5.0 → ocaml-variants
  * Incompatible packages:
    - (invariant) → ocaml-system >= 5.2.0
    - lablgl → ocaml < 5.0 → ocaml-variants
  * Missing dependency:
    - lablgl → ocaml < 5.0 → ocaml-variants → ocaml-beta
    unmet availability conditions: 'enable-ocaml-beta-repository'
  * Missing dependency:
    - lablgl → ocaml < 5.0 → ocaml-variants → system-msvc
    unmet availability conditions: 'os = "win32"'

No solution found, exiting
```

**Comment by shonfeder** [comment]
Re: the difficulty in understanding the conflict message, please see https://github.com/ocaml/opam/discussions/5130 and consider adding your example and asking your question there. You may also find help via https://discuss.ocaml.org/ .  Unfortunately there's nothing we can do about this at the package repository level. Sorry!

**Comment by talex5** [comment]
For anyone else stuck with this problem, you can get a better error message with opam-0install:
```
$ opam-0install ocaml.5.2.0 lablgl
Can't find all required versions.
Selected: base-threads.base base-unix.base camlp-streams.5.0.1
          conf-freeglut.1 conf-libgl.1 conf-libglu.1 conf-pkg-config.4
          dune.3.18.2 lablgl.1.07 ocaml-base-compiler.5.3.0 ocaml-config.3
          ocaml-options-vanilla.1 ocamlfind.1.9.8 ocaml&lablgl ocaml-variants
          ocaml-base-compiler ocaml-base-compiler
- camlp5 -> (problem)
    Rejected candidates:
      camlp5.8.03.04: Requires lablgl not(<= 1.07)
      camlp5.8.03.02: Requires lablgl not(<= 1.07)
      camlp5.8.03.01: Requires lablgl not(<= 1.07)
      camlp5.8.03.00: Requires lablgl not(<= 1.07)
      camlp5.8.02.01: Requires ocaml >= 4.10 & < 5.02.0
```

So, the problem is that camlp5 says it conflicts will all known versions of lablgl. This conflict was added in https://github.com/camlp5/camlp5/commit/cb1d3450cedc11b463baca4338a25332ff9d1814 by @chetmurthy with the commit message "meh".

**Comment by talex5** [comment]
Also, https://github.com/garrigue/lablgl/blob/master/CHANGES says:
```
LablGL 1.06:
------------
2019-08-07:
* remove dependency on camlp4/camlp5 for installation
  (only use camlp5 during development to generate stream parsers)
```
So probably this dependency isn't needed anyway.

/cc @garrigue

**Comment by chetmurthy** [comment]
> This conflict was added in [camlp5/camlp5@cb1d345](https://github.com/camlp5/camlp5/commit/cb1d3450cedc11b463baca4338a25332ff9d1814) by [@chetmurthy](https://github.com/chetmurthy) with the commit message "meh".

Since this was added to the opam file, I pretty sure it was due to a CI failure -- lablgl failing to build at (probably) 1.06.

I admit I don't write very informative commit messages, and that's bad.
