### ISSUE TITLE
conf-pkg-config.3 is broken in macos

### ISSUE THREAD

**Issue by fdagnat** [ocaml/opam-repository#26876]
brew seems to have deprecated the package pkg-config. The consequence is that opam wants to reinstall it everytime it is run. In my cas, I have the brew package pkgconf that includes the same elements so there is no problem but the recompilation of a bunch of ocaml package each time opam is executed.

**Comment by mseri** [comment]
Thanks for the report. If youy can suggest a fix in a PR it would be very useful

**Comment by emjin** [comment]
We're running into this as well. I believe this is the necessary fix https://github.com/ocaml/opam-repository/pull/26878.

**Comment by mseri** [comment]
Should be fixed

**Comment by mseri** [comment]
Thanks a lot!!
