### ISSUE TITLE
why3ide

### ISSUE THREAD

**Issue by jnarboux** [ocaml/opam-repository#2712]
I am using opam 1.1.1, under Ubuntu 14.04.1 LTS.

I installed why3 0.84 but I did not obtain why3ide. Is it normal ?
Here is the list of my installed packages:

Installed packages for system:
alt-ergo              0.95.2  Automatic theorem prover based on SMT technology and dedicated to program verification
base-bigarray           base  Bigarray library distributed with the OCaml compiler
base-threads            base  Threads library distributed with the OCaml compiler
base-unix               base  Unix library distributed with the OCaml compiler
camlp4                4.01.0  Camlp4 is a system for writing extensible parsers for programming languages
camlp5                  6.11  Preprocessor-pretty-printer of OCaml
camlzip                 1.05  Provides easy access to compressed files in ZIP, GZIP and JAR format
conf-gmp                   1  Virtual package relying on a GMP lib system installation.
conf-gnomecanvas           2  Virtual package relying on a Gnomecanvas system installation.
conf-gtksourceview         2  Virtual package relying on a GtkSourceView system installation.
coq                   8.4pl4  Formal proof management system
frama-c             20140301  Platform dedicated to the static analysis of source code written in C
lablgtk               2.16.0  OCaml interface to GTK+
ocamlfind              1.5.2  A library manager for OCaml
ocamlgraph             1.8.5  A generic graph library for OCaml
why3                    0.84  Why3 is a platform for deductive program verification.
zarith                   1.2  Implements arithmetic and logical operations over arbitrary-precision integers

Cheers,

Julien

**Comment by dbuenzli** [comment]
Ping @silene the maintainer of the why3 package. This is quite an old report, did the situation improve since then ? If this is an external configuration issue you might want to specify what to install in the `message:` field as @samoht suggest.

**Comment by dbuenzli** [comment]
This concerns an old version of the package almost three years ago. I'm unsure if the issue persists. In any case if it does I suggest maybe [reporting](http://why3.lri.fr/#contact) this upstream on the user mailing list as notifying the maintainer who seems to be one of the developer of the system was not successful for now.
