### ISSUE TITLE
pgocaml.2.1 fails in 4.02.0

### ISSUE THREAD

**Issue by fchyzak** [ocaml/opam-repository#2740]
In switch 4.02.0, the library pgocaml at its default version 2.1 itself compiles well against (ocaml.4.02.0 + camlp4.4.02.0+1), but then compiling an application using pgocaml will fail. For example, 'make test' will fail with

Camlp4: Uncaught exception: Unix.Unix_error (20 | CstTag21, "connect", "")

By contrast, either of:
- ocaml.4.01.0 + camlp4.4.01.0 + pgocaml.2.1 (that is: recent ocaml+camlp4 + last pgocaml)
- ocaml.4.02.0 + camlp4.4.02.0+1 + pgocaml.2.0 (that is: last ocaml+camlp4 + penultimate pgocaml)
will not have the error at execution.

**Comment by samoht** [comment]
Could you report that issue to pgocaml issue tracker? https://github.com/darioteixeira/pgocaml/issues

Thanks!
