### ISSUE TITLE
Ocamleditor does not install on mac os 10.6

### ISSUE THREAD

**Issue by hervetan** [ocaml/opam-repository#2784]
Installing ocamleditor via opam stops because of a 'cp -vru ...' command.
On Mac Os X (my install: Snow Leopard 10.6) the -u option to 'cp' is not recognised, which induces install failure.

Extract:
 cp: illegal option -- u
 usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
        cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory

**Comment by jordwalke** [comment]
Any fix discovered?

**Comment by samoht** [comment]
Can you report that issue in the ocamleditor issue tracker? Thanks!
