### ISSUE TITLE
Travis script: check uninstall

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam-repository#2805]
Would it be fair to check that uninstall doesn't leave artifacts in the travis script ?
This doesn't sound too difficult using autoremove, but i might be missing something:

```
opam init
cp -a $(opam config var prefix) .../backup
opam install pkg
opam remove -a pkg
diff $(opam config var prefix) .../backup || echo "bad remove"
```

**Comment by dbuenzli** [comment]
@Altgr this is quite old. I believe `opam2` is getting smarter on that front. Is this still worth being kept open ?

**Comment by dbuenzli** [comment]
This issue is lacking feedback from the initial requester and a concrete action plan so I'm closing this. If someone has a concrete plan, he should open a new issue with a precise plan on how to get this in the repo in a timely manner.
