### ISSUE TITLE
zarith and conf-gmp need to be smarter on macos x

### ISSUE THREAD

**Issue by avsm** [ocaml/opam-repository#3000]
gmp.h is in `/usr/local/include` but there's no pkg-config.  So to compile `zarith` on MacOS X I need to:

```
LDFLAGS=-L/usr/local/lib CFLAGS=-I/usr/local/include opam install zarith -v
```

I suspect we need to pkg-config up gmp to make this opam-friendly

**Comment by amirmc** [comment]
I just hit this issue again on a fresh switch (and came back here for the appropriate incantation).  How do we fix this?

**Comment by aluuu** [comment]
Ran into this issue during following Mirage [tutorial screencast](https://mirage.io/blog/getting-started-screencasts). 
Defining `LDFLAGS` and `CFLAGS` worked for me.

**Comment by MagnusS** [comment]
It's not possible to override CFLAGS and LDFLAGS on OS X anymore, as they are now set to `/usr/local/*` in [opam](https://github.com/ocaml/opam-repository/blob/master/packages/zarith/zarith.1.4/opam). If homebrew/gmp.h is installed in a different location than `/usr/local` installation fails.

**Comment by jbulow** [comment]
Macports installs in /opt/local/include. Does this mean that opam is completely broken on OSX by design?

**Comment by francesco-zappa-nardelli** [comment]
Dear all, I have encountered the same problem of jbulow: 

> Macports installs gmp.h in /opt/local/include. Does this mean that opam is broken on OSX and it will not be fixed?

This is a showstopper for me.  Is there any workaround (using brew instead of macport is not a workaround)?  Can it / will it be fixed?  Thanks.  

-francesco

**Comment by jbulow** [comment]
Still broken in opam2-beta

**Comment by psilord** [comment]
I have run into the same problem as jbulow as well, any suggestions on a decent workaround to tell opam that /opt/local and /usr/local can both exist at the same time? Thank you!

**Comment by dbuenzli** [comment]
So basically on `macOS` by checking two locations it seems that we catch `99%` of the install base of `gmp`. 

So in #9728 I simply move to the solution of checking both locations. If I got my shell quoting right I also reinstated the ability @MagnusS mentioned was lost to explicitely specify LDFLAGS and and CFLAGS.

This may not be the best solution but it should work reasonably well for the time being.

The problem should be revisited in `opam` v2 when packages will be able to set environment variables (and thus extend PKG_CONFIG_PATH) by having simple `conf-*` packages that create and install `.pc` file according to where C packages that lack one are discovered. 

Using such a custom `.pc` packages for `gmp` will allow to use `pkg-config` in zarith build instructions.

**Comment by jberdine** [comment]
I just want to note that I ran into a minor issue caused by this fix. As part of debugging some linker trouble, a `ld: warning: directory not found for option '-L/opt/local/lib'` warning sent me on a bit of a wild goose chase, only to find that it is a spuriously added option by the zarith opam file.

It would be an improvement to add only the directive to the needed path, although I don't know how to reliably achieve that.

**Comment by mimoo** [comment]
I still get these messages btw
