### ISSUE TITLE
ocsigenserver 2.5 is not compatible with lwt 2.4.7

### ISSUE THREAD

**Issue by pveber** [ocaml/opam-repository#3324]
The compilation of `ocsigenserver.2.5` fails with `lwt.2.4.7` with the following error:
```
# File "ocsigen_server.ml", line 1043, characters 7-20:
# Error: Unbound module Lwt_util
```
and indeed, this module disappeared between 2.4.6 and 2.4.7, as shown by this [commit](https://github.com/ocsigen/lwt/commit/e84929fd6f4fbd0216d55307c2255a5b8f4978ef).

**Comment by rgrinberg** [comment]
Pretty sure that's fixed in ocsigenserver/master. You can either pin or ask them for a release.

**Comment by Drup** [comment]
Can confirm it's fixed in ocsigenserver's master branch.
