### ISSUE TITLE
Installing ocamlfind fails - ./configure: line 547: cd: src: No such file or directory

### ISSUE THREAD

**Issue by rogergl** [ocaml/opam-repository#3354]
runing opam install utop leads to the following error output. This happens on Mac OS 10.10.

Building ocamlfind.1.5.5:
  ./configure -bindir /Users/roger/.opam/system/bin -sitelib /Users/roger/.opam/system/lib -mandir /Users/roger/.opam/system/man -config /Users/roger/.opam/system/lib/findlib.conf -no-topfind
  make all
  make opt
  make install
[ERROR] The compilation of ocamlfind.1.5.5 failed.
Removing ocamlfind.1.5.5.
  ocamlfind remove bytes
  ./configure -bindir /Users/roger/.opam/system/bin -sitelib /Users/roger/.opam/system/lib -mandir /Users/roger/.opam/system/man -config /Users/roger/.opam/system/lib/findlib.conf -no-topfind
  make uninstall

 opam-version 1.2.0
 os           darwin# command      ./configure -bindir /Users/roger/.opam/system/bin -sitelib /Users/roger/.opam/system/lib -mandir /Users/roger/.opam/system/man -config /Users/roger/.opam/system/lib/findlib.conf -no-topfind
 path         /Users/roger/.opam/system/build/ocamlfind.1.5.5
 compiler     system (4.02.1)
 exit-code    1
 env-file     /Users/roger/.opam/system/build/ocamlfind.1.5.5/ocamlfind-81890-e4db2f.env
 stdout-file  /Users/roger/.opam/system/build/ocamlfind.1.5.5/ocamlfind-81890-e4db2f.out
 stderr-file  /Users/roger/.opam/system/build/ocamlfind.1.5.5/ocamlfind-81890-e4db2f.err
 stdout ###
 ...[truncated]
 Configuration for str written to site-lib-src/str/META
Configuration for threads written to site-lib-src/threads/META
 Configuration for unix written to site-lib-src/unix/META
 Configuration for stdlib written to site-lib-src/stdlib/META
 Configuration for bigarray written to site-lib-src/bigarray/META
 Configuration for camlp4 written to site-lib-src/camlp4/META
 Configuration for ocamlbuild written to site-lib-src/ocamlbuild/META
 Configuration for compiler-libs written to site-lib-src/compiler-libs/META
 Configuration for bytes written to site-lib-src/bytes/META
 Detecting compiler arguments: FAILED (see the file ocargs.log for details)
stderr
 ./configure: line 547: cd: src: No such file or directory

**Comment by samoht** [comment]
Did you try with a more recent version of ocamlfind? Please re-open the issue if this is still a problem.

**Comment by drautb** [comment]
I'm getting a similar error for ocamlfind 1.6.2 on OSX 10.11.6:

```
➜  ~ opam install ocamlfind
The following actions will be performed:
  ∗  install ocamlfind 1.6.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ocamlfind] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of ocamlfind failed at "./configure -bindir /Users/drautb/.opam/system/bin -sitelib /Users/drautb/.opam/system/lib -mandir /Users/drautb/.opam/system/man -config /Users/drautb/.opam/system/lib/findlib.conf -no-custom -no-topfind".
Processing  1/1: [ocamlfind: rm]
#=== ERROR while installing ocamlfind.1.6.2 ===================================#
# opam-version 1.2.2
# os           darwin
# command      ./configure -bindir /Users/drautb/.opam/system/bin -sitelib /Users/drautb/.opam/system/lib -mandir /Users/drautb/.opam/system/man -config /Users/drautb/.opam/system/lib/findlib.conf -no-custom -no-topfind
# path         /Users/drautb/.opam/system/build/ocamlfind.1.6.2
# compiler     system (4.03.0)
# exit-code    1
# env-file     /Users/drautb/.opam/system/build/ocamlfind.1.6.2/ocamlfind-38653-6d07ae.env
# stdout-file  /Users/drautb/.opam/system/build/ocamlfind.1.6.2/ocamlfind-38653-6d07ae.out
# stderr-file  /Users/drautb/.opam/system/build/ocamlfind.1.6.2/ocamlfind-38653-6d07ae.err
### stdout ###
# [...]
# Configuration for str written to site-lib-src/str/META
# Configuration for threads written to site-lib-src/threads/META
# Configuration for unix written to site-lib-src/unix/META
# Configuration for stdlib written to site-lib-src/stdlib/META
# Configuration for bigarray written to site-lib-src/bigarray/META
# Configuration for ocamldoc written to site-lib-src/ocamldoc/META
# Configuration for camlp4 written to site-lib-src/camlp4/META
# Configuration for compiler-libs written to site-lib-src/compiler-libs/META
# Configuration for bytes written to site-lib-src/bytes/META
# Detecting compiler arguments: FAILED (see the file ocargs.log for details)
### stderr ###
# ./configure: line 553: cd: src: No such file or directory



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install ocamlfind 1.6.2
No changes have been performed
```
