### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by ttamttam** [ocaml/opam-repository#3369]
Hello,

- I had a working 4.02.1 opam installation (with lwt and utop installed and working)
- I then `opam update`, `opam upgrade`: it did not work, because `lwt` configuration failed. The `pthread` library was not detected. (see https://github.com/ocaml/opam/issues/1940)
- I then switch to 4.02.0 and installed `lwt` and `utop` with success
    - opam switch export mon421
    - opam switch 4.02.0
    - eval $(opam config env)
    - opam switch import mon421
    - opam install lwt
    - opam install utop

- Removed 4.02.1. Installed 4.02.1 and  `lwt` and `utop` with success
    - opam switch remove 4.02.1
    - opam switch 4.02.1
    - eval $(opam config env)
    - opam switch import mon421 
    - opam install lwt
    - opam install utop

Do you have any idea of what could be the reason of my problem?

**Comment by AltGr** [comment]
Possibly the lwt package got fixed in the meantime ? You may see the dates of updates at https://github.com/ocaml/opam-repository/tree/master/packages/lwt

**Comment by vasilisp** [comment]
I had similar trouble installing lwt. In my case it was an installation from scratch, not as part of an upgrade.

For what is worth, the solution for me was to install `libncurses5-dev` (under Ubuntu). The lwt build system detects whether libpthread is available by attempting to link OCaml bytecode against it. This involves `ocamlc -custom`, which introduces an unexpected dependency on ncurses-related development files. I still don't understand why just `libncurses5` (i.e., without the `-dev` package) is not enough, though.

**Comment by samoht** [comment]
This should now probably be fixed so closing.
