### ISSUE TITLE
package conf-ocaml-zmq is missing

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#3370]
Hello,
It should check for the presence of the header file zmq.h .
On Ubuntu, it must check that the system package libzmq-dev is installed
and zeromq with MacOS X's brew (probably).
I'll try to do the package since I already did some conf package in the past.

**Comment by UnixJunkie** [comment]
The ocaml-zmq package has a depexts field in its opam file.
To me, this section is wrong: it should mention libzmq-dev instead
of libzmq3-dev.
I need to have libzmq-dev installed on my system so that the package compiles.
If I have libzmq3-dev installed: opam fails to install ocaml-zmq.

**Comment by UnixJunkie** [comment]
Apparently, ocaml-zmq is in fact outdated ...

**Comment by UnixJunkie** [comment]
In fact, it is the zmq package that needed to be fixed.
I tried to fix it there:
https://github.com/ocaml/opam-repository/pull/3371

**Comment by yallop** [comment]
Can this be closed now that #3371 is merged?
