### ISSUE TITLE
Travis failure due to `[ERROR] global-config does not define the variable version.` of `ppx_deriving.1.1.0` with `opam 1.1.0`

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam-repository#3395]
My package failed to be Travis-tested with opam 1.1.0: https://github.com/ocaml/opam-repository/pull/3391 , it fails at `opam install ppx_deriving.1.1`.

```
=-=-= Installing ppx_deriving.1.1 =-=-=
ppx_deriving.1.1 Downloading https://github.com/whitequark/ppx_deriving/archive/v1.1.tar.gz
[ERROR] global-config does not define the variable version.
```

The same process succeeds with opam 1.2.0. Why? Does `ppx_deriving` uses `opam` file which does not work with opam 1.1.0?

**Comment by AltGr** [comment]
Indeed: see #3359

**Comment by camlspotter** [comment]
Ok, this is a dup.
