### ISSUE TITLE
sqlite3.2.0.8 fails to build

### ISSUE THREAD

**Issue by edwintorok** [ocaml/opam-repository#3495]
```
$ opam install sqlite3.2.0.8
[...]
# Failure: pkg-config failed for cflags.
### stderr ###
# E: Failure("Command ''/home/edwin/.opam/4.02.1/bin/ocamlbuild' lib/libsqlite3_stubs.a lib/dllsqlite3_stubs.so lib/sqlite3.cma lib/sqlite3.cmxa lib/sqlite3.a lib/sqlite3.cmxs -tag debug' terminated with error code 2")
```

The message comes from `myocamlbuild.ml`:
```ocaml
          let cmd = "pkg-config --cflags sqlite3" in
          match read_lines_from_cmd ~max_lines:1 cmd with
          | [cflags] when cflags <> "" -> S (ocamlify ~ocaml_flag:"-ccopt" cflags)
          | _ -> failwith "pkg-config failed for cflags"
```

My pkg-config output is an empty line for cflags because `sqlite3.h` is in `/usr/include`:
```
$ pkg-config --cflags sqlite3

$ pkg-config --libs sqlite3
-lsqlite3
```

**Comment by xpseudonym** [comment]
Just came here to discover the bug I'm looking for is at the top of the heap.
I can confirm this bug.
Here's my output:

# yes | opam install sqlite3
The following actions will be performed:
 - install   sqlite3.2.0.8
1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove

=-=-= Synchronizing package archives =-=-=

=-=-= Installing sqlite3.2.0.8 =-=-=
Building sqlite3.2.0.8:
  ocaml setup.ml -configure --prefix /root/.opam/system
  ocaml setup.ml -build
  ocaml setup.ml -install
[ERROR] The compilation of sqlite3.2.0.8 failed.
Removing sqlite3.2.0.8.
  ocamlfind remove sqlite3

[ERROR] Failure while processing sqlite3.2.0.8


===== ERROR while installing sqlite3.2.0.8 =====
# opam-version 1.1.1 (71b2a01ee571507c1819fbd282b0500d628f92d3)
# os           linux
# command      ocaml setup.ml -build
# path         /root/.opam/system/build/sqlite3.2.0.8
# compiler     system (4.00.1)
# exit-code    1
# env-file     /root/.opam/system/build/sqlite3.2.0.8/sqlite3-30072-ffb3fd.env
# stdout-file  /root/.opam/system/build/sqlite3.2.0.8/sqlite3-30072-ffb3fd.out
# stderr-file  /root/.opam/system/build/sqlite3.2.0.8/sqlite3-30072-ffb3fd.err
### stdout ###
# ...[truncated]
# Turn ocaml profile flag on: .......................... false
# Compiler support generation of .cmxs.: ............... true
# OCamlbuild additional flags: ......................... 
# Strict compile-time checks: .......................... true
# Create documentations: ............................... true
# Compile tests executable and library and run them: ... false
# ocamldoc: ............................................ /bin/ocamldoc
# 
# /usr/bin/ocamlopt.opt -I /usr/lib64/ocaml/ocamlbuild unix.cmxa /usr/lib64/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib64/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# Failure: pkg-config failed for cflags.
### stderr ###
# E: Failure("Command ''/bin/ocamlbuild' lib/libsqlite3_stubs.a lib/dllsqlite3_stubs.so lib/sqlite3.cma lib/sqlite3.cmxa lib/sqlite3.a lib/sqlite3.cmxs -tag debug' terminated with error code 2")


=-=-= Error report =-=-=
The following failed
 - install   sqlite3.2.0.8
#

I discovered this following various instructions to install google-drive-ocamlfuse, for example:
http://forums.fedoraforum.org/showpost.php?p=1695923&postcount=16
http://www.fclose.com/4687/mounting-google-drive-on-linux/

**Comment by edwintorok** [comment]
More info here: https://github.com/mmottl/sqlite3-ocaml/issues/4, https://github.com/mmottl/sqlite3-ocaml/commit/967198e2b9adb38844d296d1f6b0803d25d04006#commitcomment-9547447

**Comment by samoht** [comment]
This should now be fixed, so closing.
