### ISSUE TITLE
FreeBSD 10 amd64 failures - bin_prot, re2, core_extended

### ISSUE THREAD

**Issue by dch** [ocaml/opam-repository#3523]
meta-ticket for portability issues found while installing core, core_extended and similar modules.

Generally these are assumptions about use of `GCC/G++` instead of `$CC` and `$CXX`.

trivial:
- [x] `bin_prot` needs to be pushed to opam https://github.com/janestreet/bin_prot/issues/6 this is almost sorted
- [x]  `re2` needs to pass CXX=clang++ and CC=clang through to `libre2` environment for compilation. A partial fix is here https://github.com/skunkwerks/re2/commit/acade76951785ba1e4bf432882ea17ac6e353e40 see commit comments for limitations

complex:
- [x]  `core_extended` is broken https://github.com/janestreet/core_extended/issues/2 due to different quota functionality

**Comment by avsm** [comment]
The core_extended issue has an openbsd-only patch, iirc. (and thanks, this is a very helpful metaticket)

**Comment by dch** [comment]
wrt core_extended, @avsm I haven't found a patch in either your nor the Janestreet version's branches, if you have time to find it I'll see if within my meagre C* skills.

**Comment by bmillwood** [comment]
I think the re2 issues should be fixed now. core_extended is still on the way.

**Comment by dch** [comment]
We are good to go now, as a bonus, patdiff works too. I am a very happy camper! I'll open any more issues related to RWOC if I find them, but so far all of these work, for future reference:

```
dch   /u/l/l/ocaml ❯❯❯opam install core utop async yojson core_extended core_bench cohttp async_graphics cryptokit menhir patdiff
[NOTE] Package core is already installed (current version is 112.35.01).
[NOTE] Package utop is already installed (current version is 1.18).
[NOTE] Package async is already installed (current version is 112.35.00).
[NOTE] Package yojson is already installed (current version is 1.2.3).
[NOTE] Package core_extended is already installed (current version is 112.35.00).
[NOTE] Package core_bench is already installed (current version is 112.35.00).
[NOTE] Package cohttp is already installed (current version is 0.19.3).
[NOTE] Package async_graphics is already installed (current version is 0.5.1).
[NOTE] Package cryptokit is already installed (current version is 1.10).
[NOTE] Package menhir is already installed (current version is 20150921).
[NOTE] Package patdiff is already installed (current version is 112.24.00).
dch   /u/l/l/ocaml ❯❯❯opam --version
1.2.2
dch   /u/l/l/ocaml ❯❯❯opam switch
--     -- 3.11.2  Official 3.11.2 release
--     -- 3.12.1  Official 3.12.1 release
--     -- 4.00.0  Official 4.00.0 release
--     -- 4.00.1  Official 4.00.1 release
--     -- 4.01.0  Official 4.01.0 release
--     -- 4.02.0  Official 4.02.0 release
--     -- 4.02.1  Official 4.02.1 release
--     -- 4.02.2  Official 4.02.2 release
--     -- 4.02.3  Official 4.02.3 release
system  C system  System compiler (4.02.1)
dch   /u/l/l/ocaml ❯❯❯
```
