### ISSUE TITLE
opam 1.1.0 transitive compatibility check in Travis not consistent

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam-repository#3539]
Depending on how opam 1.1.0 prints the conflict. For instance, take a look at:
<https://travis-ci.org/ocaml/opam-repository/jobs/49430933>

**Comment by avsm** [comment]
I've rotated out 3.12.1/1.1.0 to reduce the Travis load for now. 3.12.1 is still tested in 1.2.0
