### ISSUE TITLE
Create a virtual package "starter-pack" to get a base (student?) system ready?

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam-repository#3582]
As was discussed on teaching@. An example is at https://gist.github.com/AltGr/f570c3189a50296d6357

There is already a pretty easy way to provide a custom set of dependencies to users described on OPAM's [tricks](opam.ocaml.org/doc/Tricks.html#Easilyprovideasetofpackagesforagroupofuserstoinstall) page, but _if_ there is a consensus of a generally good set of base packages, it would be even easier to add that directly in the repository (and maybe use it for some tests ?).

The idea is to have starters just run `opam install starter-pack` after init. (Well, or `opam install depext; opam depext -i starter-pack` if there are depexts and until OPAM has some built-in support for them...)

**Comment by dbuenzli** [comment]
IIRC the opam-repository issue tracker does not deal with packaging requests so I think this can be closed.

**Comment by AltGr** [comment]
I can do it, I was just curious if there would be some agreement on the idea.

**Comment by dbuenzli** [comment]
It seems to me that classes will usually have their own requirements for what packages to install.

**Comment by samoht** [comment]
Closing as this is indeed not the right place to discuss about new packages.

**Comment by AltGr** [comment]
Then [this link](https://github.com/ocaml/opam2web/blob/51cc9d9bec830138f00eeda428a74649faee187a/content/home.xhtml#L50) (opam.ocaml.org homepage) should be fixed. Where is the right place ?

**Comment by samoht** [comment]
Probably https://discuss.ocaml.org/ ? Only 28 people are watching this repo, so it's not a very good place to have this kind of discussion.
