### ISSUE TITLE
Error installing conf-gnutls

### ISSUE THREAD

**Issue by amirmc** [ocaml/opam-repository#3738]
This lib is listed as a dependency for building ocaml.org so I tried to install it manually.
@vbmithr Am I doing something wrong?

```
#=== ERROR while installing conf-gnutls.1 =====================================#
# opam-version 1.2.0
# os           darwin
# command      pkg-config gnutls
# path         /Users/amir/.opam/4.01.0/build/conf-gnutls.1
# compiler     4.01.0
# exit-code    1
# env-file     /Users/amir/.opam/4.01.0/build/conf-gnutls.1/conf-gnutls-92009-c743ac.env
# stdout-file  /Users/amir/.opam/4.01.0/build/conf-gnutls.1/conf-gnutls-92009-c743ac.out
# stderr-file  /Users/amir/.opam/4.01.0/build/conf-gnutls.1/conf-gnutls-92009-c743ac.err
```

```
$ opam config report
# OPAM status report
# opam-version    1.2.0
# self-upgrade    no
# os              darwin
# external-solver no
# criteria        -removed,-notuptodate,-changed*
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  4.01.0
# last-update     2015-03-15 22:30
```

```
$ brew info gnutls
gnutls: stable 3.3.13 (bottled)
http://gnutls.org
/usr/local/Cellar/gnutls/3.3.12 (1020 files, 9.0M)
  Poured from bottle
/usr/local/Cellar/gnutls/3.3.13 (1020 files, 9.0M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gnutls.rb
==> Dependencies
Build: xz ✔, pkg-config ✔
Required: libtasn1 ✔, gmp ✔, nettle ✔
Optional: guile ✘, p11-kit ✘, unbound ✘
==> Options
--with-guile
	Build with guile support
--with-p11-kit
	Build with p11-kit support
--with-unbound
	Build with unbound support
```

**Comment by vbmithr** [comment]
On 15/03/2015 23:58, Amir Chaudhry wrote:
> This lib is listed as a dependency for building ocaml.org so I tried to
> install it manually.
> @vbmithr <https://github.com/vbmithr> Am I doing something wrong?

You need to have gnutls installed on your system. Is gnutls available
for mac ? If yes, try to install gnutls.

The aim of this package is precisely to fail to install if gnutls is not
installed on your system.

Cheers!

-- 
Vincent

**Comment by amirmc** [comment]
I thought I had gnutls via homebrew (as shown in the third snippet above). 

Perhaps there's something about how this package checks/uses gnutls on a Mac? 

Best wishes,
Amir

--
sent via mobile

**Comment by vbmithr** [comment]
On 17/03/2015 11:53, Amir Chaudhry wrote:
> Perhaps there's something about how this package checks/uses gnutls on a
> Mac?

Exactly. On Linux, it is checked by running `pkg-config gnutls`. This
commands exits with code 0 when gnutls is installed on the system (and
pkg-config knows about it).

I don't know about pkg-config on MacOSX. Try to run `pkg-config gnutls`
and figure if pkg-config is installed and that it knows about gnutls.

One possible issue is that the gnutls package on Mac does not provide
pkg-config files.

-- 
Vincent

**Comment by amirmc** [comment]
Thanks for the info! That gives me a starting point and it seems `pkg-config` does know about `gnutls`

```
$ pkg-config --list-all | grep gnutls
gnutls                              GnuTLS - Transport Security Layer implementation for the GNU system
```

I'll see what I can figure out about the mac version of `pkg-config` as I believe issues like this have cropped up before.

**Comment by ffreling** [comment]
I have the same issue when trying to install conf-gnutls on a Mac.
Any update on a workaround?

**Comment by amirmc** [comment]
I'm closing this as it's been open for a while with no other reports. Someone can reopen or file a more specific issue if it's still a problem.

**Comment by ffreling** [comment]
I upgraded gnutls by building from sources with pkg-config support with brew. I was then able to install conf-gnutls via opam.

The issue is fixed for me at least.
