### ISSUE TITLE
Is it possible to mention archlinux in the depexts field of a package?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#3907]
And same question for gentoo.
Would it be just "archlinux" and "gentoo"?
Thanks!

**Comment by avsm** [comment]
If you could add support for these into http://github.com/ocaml/opam-depext, then that will help establish a standard for these two distributions.  We need to hook them into automated testing via Docker in http://opam.ocaml.org/builds

**Comment by UnixJunkie** [comment]
https://github.com/ocaml/opam-depext/pull/11

**Comment by UnixJunkie** [comment]
My pull request was accepted into depext
