### ISSUE TITLE
LLVM 3.6 fails to build on Mac OS X

### ISSUE THREAD

**Issue by toroidal-code** [ocaml/opam-repository#3942]
I was trying to install the llvm.3.6 package, and kept getting an error about moving `.so` files. 

Looking at the package file, the shared libraries aren't being built on Darwin (`--disable-shared`), but the install script was still trying to copy them into place. Removing the loop starting at [Line 35](https://github.com/ocaml/opam-repository/blob/master/packages/llvm/llvm.3.6/files/install.sh#L35) solves the problem for me, and I'm able to load and use the package normally.

I don't know what would be a good solution here, so I'm posting this as an issue instead of a PR.

**Comment by wtetzner** [comment]
I'm running into the same problem. I tried to get around it for now by editing the install.sh file in my local opam archive, but then opam will just download the original again. How did you get around that?

It seems like the right fix would be to have the copy loop do nothing if there are no .so files to copy.

**Comment by dsheets** [comment]
@jpdeplaix

**Comment by wtetzner** [comment]
So I managed to work around the problem for now. If anyone else is having the same problem, I got around it by updating install.sh as in toroidal-code's comment, and kept a copy of my modified llvm.3.6+opam.tar.gz in my home directory. I then created a shell script that copied that file to llvm.3.6+opam.tar.gz, and set the OPAMFETCH environment variable to use my script.

**Comment by jpdeplaix** [comment]
I'm sorry, I'm not skilled enough to resolve that. @whitequark certainly is.

**Comment by nojb** [comment]
You can solve the problem by adding
```
shopt -s nullglob
```
right before the `for` loop.  This will cause the loop not to execute if there aren't any `*.so` files.  See
http://wiki.bash-hackers.org/syntax/expansion/globs.
