### ISSUE TITLE
dose3: please build rpm support library optionally

### ISSUE THREAD

**Issue by edwintorok** [ocaml/opam-repository#4075]
Dose3 has support for rpm too but it is not built by default, it can be activated with `--with-rpm4` or `--with-rpm5`
The opam package should have a way to optionally enable this based on `conf-rpm`
(which detects presence of `librpm`, not the distribution), and probably needs some flags to put the stublibs in the correct place.

**Comment by samoht** [comment]
Could you report that issue upstream? /cc @abate 

```
$ opam info -f bug-reports dose3
https://gforge.inria.fr/tracker/?group_id=4395
```

Thanks!
