### ISSUE TITLE
use bin deltas instead of full archives

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#4080]
opam upgrades could go faster with smaller downloads.
The opam infrastructure could use less bandwidth and ~/.opam could
be way smaller.
An algorithm: http://www.daemonology.net/bsdiff/
For some time now, some RPM-based distros use delta-rpms, the user experience
is significantly accelerated by them.

**Comment by dsheets** [comment]
Closing this as ocaml/opam#2148 is better for tracking.
