### ISSUE TITLE
ocamlnet.4.0.2 fails due to missing tend.c

### ISSUE THREAD

**Issue by neojski** [ocaml/opam-repository#4107]
I tried to `opam install ocamlnet.4.0.2` but it fails with:

```
### stdout ###
# Checking operating system... Linux
# Checking for findlib... found
# Checking multi-threading support... posix (ok)
# Checking word size... 64 bit
# Checking endianess... /home/neo/tmp
### stderr ###
# Welcome to Ocamlnet version 4.0.2
# gcc: error: tend.c: No such file or directory
# gcc: fatal error: no input files
# compilation terminated.
```

Basically, I tried to `opam install google-drive-ocamlfuse` but ocamlnet failed as dependency of it.

I also did `ocaml upgrade` because it was failing with a lot of `Camlp4: Uncaught exception: DynLoader.Error` errors.

Any ideas?

**Comment by dsheets** [comment]
I cannot reproduce this issue with `opam install ocamlnet.4.0.2`.

I recommend using the ocamlnet SourceForge site or mailing list <http://sourceforge.net/p/ocamlnet/mailman/> to report this issue.
