### ISSUE TITLE
Zarith now depends on "mirage-no-xen" or ("mirage-xen" and "gmp-xen")

### ISSUE THREAD

**Issue by iguer** [ocaml/opam-repository#4117]
The sources of zarith 1.3 seem to compile without the dependencies "mirage-no-xen" or ("mirage-xen" and "gmp-xen"). These deps are not present in previous versions. Is it a good idea to put them as optional ?

https://github.com/ocaml/opam-repository/blob/master/packages/zarith/zarith.1.3/opam

**Comment by samoht** [comment]
`mirage-no-xen` is a virtual package which installs nothing (it is just in conflict with `mirage-xen`). Does it cause a problem somewhere?

**Comment by samoht** [comment]
See https://github.com/ocaml/opam/issues/2074 for the rational

**Comment by iguer** [comment]
1) When I try to upgrade, I get the following message

```
$ opam upgrade
The following actions will be performed:
  ∗  install   mirage-no-xen 1                [required by zarith]
  ↻  recompile zarith        1.3              [upstream changes]
  ↻  recompile why3-base     0.86             [uses zarith]
  ↻  recompile frama-c-base  20150201         [uses zarith]
  ↻  recompile altgr-ergo    0.99.1           [uses zarith]
  ↻  recompile alt-ergo      0.99.1           [uses zarith]
  ↻  recompile why3          0.86             [uses zarith]
       Coq realizations of Why3 theories are only available if Coq is installed
  ↻  recompile frama-c       20150201         [uses zarith]
  ↻  recompile satML-plugin  0.99.1           [uses zarith]
===== ∗  1   ↻  8 =====
```

It is quite disturbing for me to be obliged to install mirage-no-xen to have zarith 1.3 works correctly (and it is not clear from the message above that mirage-no-xen is a virtual package).

2) What happens if I decide to install mirage-xen after the upgrade ?

**Comment by samoht** [comment]
1) I perfectly understand your point. @AltGr is there any trick we can use to turn `mirage-no-xen` into some sort of `depopts`? I don't see how we can do that properly...

Does adding a message will help:

The following actions will be performed:
  ∗  install   mirage-no-xen 1                [required by zarith]
        This is a virtual package <or something similar>
  ↻  recompile zarith        1.3              [upstream changes]
```

2) it will install `mirage-xen` and `mirage-xen-entropy` and recompile `zarith` and all of its dependencies. I understand that this situation is not ideal. But that the only way we have currently to express complex optional dependencies. @hannesm and @pqwy do you think we can have a separate `zarith-xen` instead to avoid this kind of problems?

**Comment by hannesm** [comment]
@samoht a zarith-xen should be doable (and is a matter of which package depends on which, and how to resolve linker flags etc)... the patches to zarith originated from @talex5 (maybe he knows more how to do so).. I agree that the invasive mirage-no-xen in zarith is bad

**Comment by samoht** [comment]
@hannesm we can revert that patch the time we decide for a proper work-around? Later adding `{build}` predicate could be enough.

**Comment by hannesm** [comment]
I filed #4122 to revert, and introduce zarith-xen... works on this cubieboard here

**Comment by samoht** [comment]
Changes are reverted by https://github.com/ocaml/opam-repository/pull/4122, thanks Mohamed for the feedback.
