### ISSUE TITLE
dns optional deps

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam-repository#4189]
What is the point in [adding a `lwt` flag](https://github.com/ocaml/opam-repository/blob/master/packages/dns/dns.0.15.0/opam#L25) if `lwt` is [required](https://github.com/ocaml/opam-repository/blob/master/packages/dns/dns.0.15.0/opam#L32)?

**Comment by dsheets** [comment]
I believe `--enable-lwt` means "enable use of `Lwt_unix`" and is a shorthand for the non-Mirage network backend.

From the `ocaml-dns` `_oasis` file:

```
Library "dns-lwt"
  Path: lwt
  Build$: flag(lwt)
  Install$: flag(lwt)
  Findlibname: lwt
  Modules: Dns_server_unix, Dns_resolver_unix
  BuildDepends: lwt.unix (>= 2.4.1), cstruct.lwt, lwt.syntax, dns, dns.lwt-core, ipaddr.unix
  XMetaRequires: lwt.unix, cstruct.lwt, dns, dns.lwt-core, ipaddr.unix
  FindlibParent: dns
```

**Comment by Chris00** [comment]
Right.  Sorry for the noise, I used my convention that flag names should reflect those of the triggering package and did not check the details.
