### ISSUE TITLE
package lz4 does not install on mac

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#4238]

**Comment by UnixJunkie** [comment]
https://gist.github.com/UnixJunkie/ad8cb99d02cf5818a8a8

**Comment by dsheets** [comment]
This looks like the depext declaration for `homebrew osx` is missing in the opam file. If you can find the appropriate homebrew package and test it, I'm sure @whitequark would appreciate the contribution.

**Comment by UnixJunkie** [comment]
I think I tried to install lz4 with brew but it did not help

**Comment by dsheets** [comment]
If you could provide versions of OS X, homebrew, and the `lz4` package, it would be helpful.

**Comment by UnixJunkie** [comment]
brew 0.9.9
osx 10.12
brew-provided lz4r117
I have also this file on my machine:
/usr/local/include/lz4.h

**Comment by whitequark** [comment]
@dsheets Hm, sounds like -I /usr/local is missing in CFLAGS... what was the OPAM policy again? IMO on OS X /usr/local should be included in the compiler CFLAGS, not by every package.

**Comment by dsheets** [comment]
@whitequark we don't really have a policy about compile flags. It would certainly be nice to have `CPPFLAGS` (I think because include path is a pre-processor stage concept) fixed globally on OS X. @michipili also has done some work to help clean up flag discovery across platforms so that each package does not have to embed the same platform-specific knowledge.

**Comment by whitequark** [comment]
> CPPFLAGS (I think because include path is a pre-processor stage concept)

Not really, it should be CFLAGS. CPPFLAGS looks like one of those things you want to use but it almost never is (and besides autoconf-based build systems, which in practice support it badly, nothing else I know of even bothers).

**Comment by dsheets** [comment]
I believe the difference is between C-specific flags and those that may be understood by C++/Fortran etc. It doesn't really matter but my understanding based on some GNU material is that `CPPFLAGS` is the appropriate variable for include path modifications.

Regardless, I suggest adding it to the specific package for now or helping fix the issue globally.

**Comment by whitequark** [comment]
@dsheets Do you have any idea if this can even be fixed on OPAM side, with OASIS?

**Comment by whitequark** [comment]
@dsheets ping?

**Comment by dsheets** [comment]
@whitequark there is a fix in #7618 that, while not the prettiest, does build on my machine. Fixing include paths across package managers and operating systems still needs work in the longer term.

**Comment by whitequark** [comment]
@dsheets ack. I believe that fixes the immediate problem that @UnixJunkie has.

**Comment by UnixJunkie** [comment]
thanks
