### ISSUE TITLE
package conf-zmq does not install on mac

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#4239]

**Comment by UnixJunkie** [comment]
https://gist.github.com/UnixJunkie/da2a4709113a1757d27d

**Comment by dsheets** [comment]
This looks like a missing depext. Have you tried `opam depext conf-zmq`?

**Comment by UnixJunkie** [comment]
Of course I tried, doesn't help.

**Comment by dsheets** [comment]
Could you provide versions of OS X, homebrew, and homebrew's zeromq package?

**Comment by samoht** [comment]
ping @UnixJunkie

**Comment by UnixJunkie** [comment]
I need to be at home to access my Mac ...

**Comment by UnixJunkie** [comment]
It installs after opam update now.
