### ISSUE TITLE
ocamlnet 4.x requires nettle-dev when gnutls is used on Debian

### ISSUE THREAD

**Issue by edwintorok** [ocaml/opam-repository#4276]
When `gnutls` is enabled and installed but `nettle-dev` is not installed I get this error (note that GnuTLS _is_ installed, and if I install `nettle-dev` then the build succeeds):

```
# command      ./configure -bindir /home/edwin/.opam/system/bin -disable-gssapi -enable-gnutls -enable-pcre -enable-gtk2 -disable-zip -with-nethttpd
[...]
# Checking whether lablgtk2 has GMain.Io.add_watch with list support... yes
# Checking for GnuTLS... not found
# Required library GnuTLS not found!
### stderr ###
# Welcome to Ocamlnet version 4.0.2
# Package nettle was not found in the pkg-config search path.
# Perhaps you should add the directory containing `nettle.pc'
# to the PKG_CONFIG_PATH environment variable
# No package 'nettle' found
# Package nettle was not found in the pkg-config search path.
# Perhaps you should add the directory containing `nettle.pc'
# to the PKG_CONFIG_PATH environment variable
# No package 'nettle' found
```

**Comment by dbuenzli** [comment]
Ping at @vbmithr who is the maintainer of the ocamlnet package.

**Comment by vbmithr** [comment]
Yes, this is normal.
See opam package `conf-gnutls`:

```
depexts: [
  [["debian"] ["libgnutls28-dev" "nettle-dev"]]
  [["ubuntu"] ["libgnutls28-dev" "nettle-dev"]]
  [["alpine"] ["gnutls-dev"]]
  [["fedora"] ["gnutls-devel" "nettle-devel"]]
  [["osx" "homebrew"] ["gnutls"]]```

I'm wondering how you could install this package without having `nettle-dev` installed.

**Comment by dbuenzli** [comment]
Thanks @vbmithr for looking into this. 

In fact it seems that at the time this was reported, things were not checked properyl if I believe this [blame](https://github.com/ocaml/opam-repository/blame/master/packages/conf-gnutls/conf-gnutls.1/opam) on the `conf-gnutls`. 

I think we can close this though if you feel like it you could try to expand the depexts a bit using [these online list of system packages](https://gist.github.com/dbuenzli/eecc31ab3ee10ef3ccfe60efcbc51630).
