### ISSUE TITLE
ocaml-expat fails to build on OS X with Clang

### ISSUE THREAD

**Issue by dlowd** [ocaml/opam-repository#4310]
On OS X, gcc typically links to the Clang compiler.  In this context, running `opam install ocaml-expat` leads to the following error:

    ### stdout ###
    # gcc -MM *.c > depend	
    ### stderr ###
    # Makefile:100: depend: No such file or directory
    # expat_stubs.c:23:10: fatal error: 'caml/mlvalues.h' file not found
    # #include <caml/mlvalues.h>
    #          ^
    # 1 error generated.
    # make: *** [depend] Error 1

The source of this error is the `gcc -MM *.c > depend` command in the Makefile.  Unlike GCC, Clang includes header files when building dependencies.  Since Clang does not know where the OCaml include files are, this results in an error.

The user workaround is:

    export C_INCLUDE_PATH=`ocamlc -where`:$C_INCLUDE_PATH

However, it would be better if OS X users did not need to do this.  A general-purpose fix would be to change the line `gcc -MM *.c > depend` to the following:

    gcc -I `ocamlc -where` -MM *.c > depend

Please consider making this fix.  Thanks!

**Comment by samoht** [comment]
Seems to be fixed upstream so closing.
