### ISSUE TITLE
archives using gforge.inria.fr/frs/download.php are broken

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam-repository#4317]
```
[ERROR] Bad checksum for /home/dsheets/.opam/packages.dev/cudf.0.7/cudf-0.7.tar.gz:
          - 2047222fcf78278c6a24ac619fc39abb [expected result]
          - 60a3dba657a726f476101932e336c796 [actual result]
```

```
[ERROR] Bad checksum for
        /home/dsheets/.opam/packages.dev/dose.3.2.2+opam/dose3-3.2.2.tar.gz:
          - 3ffed1987a040024076c08f4a7af9b21 [expected result]
          - b1e7816fccdabe79da7b3bd59e918373 [actual result]
```

Fetching https://gforge.inria.fr/frs/download.php/33593/cudf-0.7.tar.gz and https://gforge.inria.fr/frs/download.php/file/33677/dose3-3.2.2.tar.gz are 303 -> 200 text/html which is actually a login page but FusionForge 6 or whatever it is doesn't know HTTP error codes. Manually browsing the project pages yields empty 'files' areas with no archive links. @abate @rdicosmo?

**Comment by dsheets** [comment]
This also affects:

- heptagon
- javalib
- nit
- sawja
- tplib
- why3-base
- why3

**Comment by rdicosmo** [comment]
Thanks David for reporting this... unfortunately, it is a yet unresolved bug in
the new version of the INRIA's forge, that ends up resetting the visibility of
project's files each time the code is updated.

Bug upstream already reported, while they fix it, we'll need to manually reset
things each time this happens :-(

--
Roberto

On Fri, Jun 26, 2015 at 08:57:55AM -0700, David Sheets wrote:
> [ERROR] Bad checksum for /home/dsheets/.opam/packages.dev/cudf.0.7/cudf-0.7.tar.gz:
>           - 2047222fcf78278c6a24ac619fc39abb [expected result]
>           - 60a3dba657a726f476101932e336c796 [actual result]
> 
> [ERROR] Bad checksum for
>         /home/dsheets/.opam/packages.dev/dose.3.2.2+opam/dose3-3.2.2.tar.gz:
>           - 3ffed1987a040024076c08f4a7af9b21 [expected result]
>           - b1e7816fccdabe79da7b3bd59e918373 [actual result]
> 
> Fetching https://gforge.inria.fr/frs/download.php/33593/cudf-0.7.tar.gz and
> https://gforge.inria.fr/frs/download.php/file/33677/dose3-3.2.2.tar.gz are 303
> -> 200 text/html which is actually a login page but FusionForge 6 or whatever
> it is doesn't know HTTP error codes. Manually browsing the project pages yields
> empty 'files' areas with no archive links. @abate @rdicosmo?
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Roberto Di Cosmo
 
------------------------------------------------------------------
Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann       
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:
 
Bureau 3020 (3rd floor)
Batiment Sophie Germain
8 place Aurélie Nemours
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by AltGr** [comment]
Yes, we reported it already several times, and they "are on it"... not much we can do except rely on the mirrored archives on opam.ocaml.org, and let the project maintainers take the hint to host a mirror of their archives somewhere more reliable.

Well, while we are in the automated testing of packages, we could also automatically notify the maintainers as soon as their archive is detected unavailable. With some safeguards, for e.g. not spamming everyone in the event GitHub goes down for a couple hours ?

**Comment by dsheets** [comment]
Archive availability checking and metadata link checking with hysteresis are both planned.

**Comment by abate** [comment]
It seems the archives are now back online. I hope they are there to stay ...
https://gforge.inria.fr/tracker/index.php?func=detail&aid=19308&group_id=1&atid=110
