### ISSUE TITLE
meta-data review : opam-legacy or soft removal policy

### ISSUE THREAD

**Issue by abate** [ocaml/opam-repository#4347]
While playing with `opam lint` I've noticed that a very large number of packages in the repository contain meta-data errors according to opam lint. Many errors and warnings are due to deprecated fields, that were not mandatory or part of the meta-data specification when the package was first uploaded. Since the opam-repository does not encourage to remove old versions of a package, this situation is due to repeat over time. As new versions of a package are uploaded using the most recent meta-data specification, old packages are left in the archive using outdated meta-data. `opam` tries to be backward compatible with old previous version of the specification, but clearly this adds a burden on the opam developers and over time over time, the quality of meta data is due to decay. 

I'm not sure if this is a concern for the opam community, but from a Quality Assurance prospective, leaving old packages in the repository, without keeping their meta-data up-to-date, is in general, not good practice. I imagine that this is not an ideal situation for a package maintainer as well, as, with time, the number of packages (and opam files) to be regularly updated will grow leaving the maintainer with a lot of work for little gain. 

As the opam format is stabilizing, this problem is only temporary and it is just the consequence of the natural bootstrap process of a package repository.  Work is underway to limit this problem in the future adding an automatic linting step for each PR to the repository.

However, to this day, there are many packages in the repository that are not installable for one reason or the other (see OWS), or that have their meta-data outdated, according to opam lint. To fix the actual state of the repository from a QA prospective, I think that is now time to develop a policy to slowly clean up all the old packages and pave the way for more features and enhancement without dragging old outdated packages along. 

My idea would be to enforce a soft removal policy where if a package does not pass the QA test for a period of time (say one month), it is automatically removed from the repository or moved to a `opam-legacy` repository where it can keep living and be available (as an additional repository) but without QA constraints. This will allow on one hand a tighter control on the health of individual packages and the repository, and on the other, to remove from opam many backward compatibility routines and clean up the code accordingly. 

I'm pretty new to this opam world, but I'd like to know if I'm completely off track here with this proposition or it is something the community has already considered. I'll be very happy to work on the infrastructure to make this happen.

**Comment by avsm** [comment]
One thing we've done several times in the past is to do a mechanised rewrite of the repository to a new metadata format.  For a number of lint errors (such as missing homepage or dev-repo fields), this could be done by a reasonable guess (particularly for GitHub projects).

I think this is important to do -- since as you note, out of date metadata is not good for the long term health.  However, I think we should do this before any policy of removing packages (which is something of a nuclear option if we can't fix the metadata issues).

Note that I'm distinguishing between uninstallable packages and out of data metadata (like missing fields).  The former is more serious than the latter, but hopefully much rarer.  It's difficult to tell how bad the uninstallability situation is when it's adjusted for "installs on at least one OCaml compiler version".  Since every package installed successfully at one point, this might simply be a matter of adding appropriate upper bounds -- this s something that Damien and I have been doing work on with regular package bulk builds.

-a

**Comment by dbuenzli** [comment]
> My idea would be to enforce a soft removal policy where if a package does not pass the QA test for a period of time (say one month), it is automatically removed from the repository or moved to a opam-legacy repository where it can keep living and be available (as an additional repository) but without QA constraints.

I'm a little bit wary about these kind of automated purging. Human review should be performed before committing the removal.


> I think this is important to do -- since as you note, out of date metadata is not good for the long term health.

But also you cannot reinvent metadata that what not there at the time of publication (or at least I think it would be unreasonable). In the ideal world metadata rewrites should keep the information from which opam metadata version it rewrote from and opam lint should use the `rewritten-from` field to actually base its warnings upon. E.g. you it should not report warnings for missing `bug-report` fields on opam metadata rewritten from version 1.

**Comment by abate** [comment]
The idea of "automatic removal" will work together with a period of grace to allow for human review. If the maintainer (or somebody else) of a package that was flagged for removal does not do anything in <insert arbitrarily long period of time> months, then the package will be moved to a legacy repository or removed altogether. If we want to converge, we need some kind of mechanism to enforce an action after a specified period of time... /methink 

@dbuenzli you make a fair point about old meta-data. Adjusting warnings and errors w.r.t. the ```opam-version``` field sound like a good idea. This will distinguish between old but correct packages accordingly to their compatibility version, and new packages. And this could then be used to trim the repository or simply instruct opam to consider only packages with a specific compatibility version.

**Comment by abate** [comment]
here https://github.com/ocaml/opam/issues/2534 another good reason to cleanup the repository regularly ...

**Comment by avsm** [comment]
@AltGr : one feature in OPAM 2 that would significantly simplify this is to be able to depend on a `remote` as a package.  It would be very cool if installing OCaml 3.12.1 also added in a remote for those packages that only support that version of the compiler.  This would let us split the package repository much more easily into versioned chunks based on compiler support.

**Comment by dbuenzli** [comment]
It seems that the new CI already goes at long way at least guaranteeing some quality in the constraints metadata which seems the most important. 

So is there anything concrete that can be taken out of this issue ? If not I suggest we choose to close and move this (not uninteresting) discussion to another medium like discuss.ocaml.org or opam-devel list and come back with an issue once a concrete plan is designed.
