### ISSUE TITLE
caml-mode.4.02 installation fails

### ISSUE THREAD

**Issue by db4** [ocaml/opam-repository#4420]
`make` fails with
`grep: opam/opam: Not a directory`

The problem is that there is no "opam/opam" in the build directory (needed by VERSION=...). Is it expected to be generated by newer/older opam? (I'm using 1.2.1). Instead, I see "opam" file in the build root, but it does not contain "version:"  attribute (somehow it's stripped from the repository "opam" file)

**Comment by samoht** [comment]
Could you try with opam 1.2.2?

**Comment by dbuenzli** [comment]
Cannot reproduce this on 1.2.2. Version earlier to opam 1.2.2 are [now deprecated](https://discuss.ocaml.org/t/rfc-deprecating-opam-1-2-0/332). I'm closing this. 

@db4 feel free to continue the discussion on this issue if you need any help.
