### ISSUE TITLE
Download issue of omake-0.9.8.6-0

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam-repository#4570]
I am afraid the following URL is now 404:

http://omake.metaprl.org/downloads/omake-0.9.8.6-0.rc1.tar.gz

**Comment by domsj** [comment]
Just had the same problem ... fixed it by having my local opam repository point to the file I found at http://pkgs.fedoraproject.org/repo/pkgs/ocaml-omake/omake-0.9.8.6-0.rc1.tar.gz/fe39a476ef4e33b7ba2ca77a6bcaded2/
but don't know if that's how we want this to be solved in opam...

**Comment by avsm** [comment]
For now, this fedora mirror is fine to patch into the repo
