### ISSUE TITLE
Package opam-installer

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam-repository#4634]
`opam-bundle` wants to use `opam-installer` on the target host and it would be much simpler if there was an opam package that installed it. Do you think it wil make sense to have such package in repo or better tweak `opam-lib` to install binary?

**Comment by dbuenzli** [comment]
@AltGr does the new `opam-bundle` change anything to the situation ? 

In any case this looks like a packaging request which is out of scope for this issue tracker, this should be filed on `opam-bundle` issue tracker and this issue should be closed.

**Comment by ygrek** [comment]
I doubt I will continue work on "old" opam-bundle anyway given there is upstream effort now, so closing
