### ISSUE TITLE
Windows does not permit file/directory names containing colons

### ISSUE THREAD

**Issue by infidel** [ocaml/opam-repository#4673]
Cloning opam-repository using "GitHub for Windows" results in the following (without making any changes):

```
On branch master
Your branch is up-to-date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        deleted:    packages/coq:shell/coq:shell.1/descr
        deleted:    packages/coq:shell/coq:shell.1/opam
        deleted:    packages/coq:shell/coq:shell.1/url
        deleted:    packages/tidy/tidy.0:2009-0.1.1/descr
        deleted:    packages/tidy/tidy.0:2009-0.1.1/opam
        deleted:    packages/tidy/tidy.0:2009-0.1.1/url
        deleted:    packages/tidy/tidy.1:4.9.30-0.1.1/descr
        deleted:    packages/tidy/tidy.1:4.9.30-0.1.1/opam
        deleted:    packages/tidy/tidy.1:4.9.30-0.1.1/url
```

This is because these directory names contain ':' characters.

**Comment by dra27** [comment]
Just hit this too! Git-for-Windows can't even do the checkout!
@avsm - given that at this stage it's only one package, would it be possible to require opam-repository names not to include colons and rename this one?
Perhaps further down the road opam-lint should warn that having a colon in a package name **destroys** Windows support (given that it's virtually impossible even to check out the repository!)

**Comment by samoht** [comment]
This has been done, so closing.
