### ISSUE TITLE
zarith-xen build script is closely tied to `opam`'s destination layout

### ISSUE THREAD

**Issue by timbertson** [ocaml/opam-repository#4752]
In order to build zarith-xen with `opam2nix`, I rewrote the install script into this:

https://github.com/gfxmonk/opam2nix/blob/71887935dc30a744aa26f1f5af75678355d2d74e/src/nix/overrides/zarith-xen/install.sh

This script has allowed me to get `zarith-xen` and packages relying on it to build, although I have not attempted to run the result yet (unrelated to this package - I'm having trouble getting Xen to play well with EFI).

I'm not sure how best to resolve this (I was unable to come up with a script which would build inside `opam` and in `opam2nix`), but perhaps the maintainer(s) of this package have an idea? In particular it seems bad form to modify files installed by another package.

**Comment by hannesm** [comment]
I agree that `zarith-xen` should not do what it does atm.  It is a hack (messing around with other packages META file), does not compose with `zarith-freestanding` (the solo5 thing), and will hopefully be forbidden by opam 2.0.  A proper solution needs to be engineered with the single user of that package (nocrypto).  I believe/hope @pqwy has ideas... one option would be to embed the build scripts into nocrypto, and its build products into nocrypto as well.

**Comment by dbuenzli** [comment]
What is the status of this issue ?

**Comment by dbuenzli** [comment]
None seems to be interested in advancing this issue and in any case that's not an opam-repository issue but an upstream packaging issue so I'm closing this.
