### ISSUE TITLE
Incorrect ./configure options for OCaml compiler?

### ISSUE THREAD

**Issue by db4** [ocaml/opam-repository#4825]
`opam switch` configures Ocaml as

```
  ["./configure" "-prefix" prefix "-with-debug-runtime"]
```

It means that OCaml itself is installed into `$opam/$SWITCH/lib/ocaml` while other packages go to
`$opam/$SWITCH/lib/<package name>`

This is not a problem until some package uses `+dir` notation. E.g. camlp4's META contains

```
directory = "+camlp4"
```

and so every package that uses camlp4 tries to find it in `$opam/$SWITCH/lib/ocaml/camlp4` while camlp4 is actually installed into `$opam/$SWITCH/lib/camlp4`

I would say OCaml should be configured as

```
  ["./configure" "-prefix" prefix "-libdir" lib "-with-debug-runtime"]
```

But maybe I'm just missing something?

**Comment by samoht** [comment]
This seems like an interesting idea. @lefessan do you think that this will work?

**Comment by db4** [comment]
At least it works for me and I have not hit any problem yet. Of course, OCaml standard libraries are also installed into `$opam/$SWITCH/lib` but I find this pretty normal.

**Comment by samoht** [comment]
That seems quite a simple and elegant solution to https://github.com/ocaml/opam/issues/2149 I'm not sure why anyone has proposed that (I did not know that `-libdir` existed). Can you comment on that thread with your proposal so maybe people can express their concerns (if any)? Thanks!

**Comment by dbuenzli** [comment]
I find this a little bit dirty since all the files currently in `lib/ocaml` will be present in `lib`.  #2149 and other `META` files can be fixed by simply doing a `+../$PKG` to reflect the new package structure enforced by opam which is frankly not big deal to fix. 

I think we should move away from the idea of installing OCaml packages in the OCaml library directory (I'm not sure OS level package managers do like that idea anyway).

**Comment by dbuenzli** [comment]
Btw. this also won't play nice with compilers as packages.

**Comment by lefessan** [comment]
It is a good idea, but indeed, the content of lib/ would become a mess. However, it could be done in two steps: (1) convince the OCaml core team that the standard library files should go into some some "stdlib/" subdirectory of $OCAMLLIB (it would not change anything as that dircetory would be automatically added by the compiler), and (2) when its done, move the OCaml `lib` to the opam `lib`. It would take at least one year before having it working, but would be nice on the long term.

**Comment by dbuenzli** [comment]
It seems pretty clear that using `-libdir` as it exists now won't cut it. 

The rest is speculation on a possible change upstream and AFAIK there's not even a MPR on this in mantis. So if nobody objects I'd move on to close this. An issue can be reopened once we get signs of upstream changes.
