### ISSUE TITLE
package "result" 1.0 fails to build

### ISSUE THREAD

**Issue by mwweissmann** [ocaml/opam-repository#4837]
I get the following error when trying to install "result" (1.0) on both OS X and Linux:

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] File "$HOME/.opam/4.02.3/build/result.1.0/result.install", line 1, character 0-1: '-' is not a valid token.

#=== ERROR while installing result.1.0 ========================================#
OpamTypesBase.Lexer_error("'-' is not a valid token")

**Comment by avsm** [comment]
What version of OPAM do you have?

**Comment by avsm** [comment]
Looks like an OSX only problem /cc @diml @lpw25

The `.install` file has a `-n` prefix before every line.

**Comment by diml** [comment]
I replaced the commands in the Makefile by an ocaml script. It should be more portable...

I'll do a release this afternoon

**Comment by mwweissmann** [comment]
on OS X its 1.2.1, on Linux 1.2.0
