### ISSUE TITLE
Make camelus mention package owner

### ISSUE THREAD

**Issue by whitequark** [ocaml/opam-repository#4897]
To avoid the sad situation with https://github.com/ocaml/opam-repository/pull/4896, I think @camelus should @-mention every GitHub username included in the `dev-repo` field of the packages that have been changed.

And I also think it is reasonable that, unless the package was broken in an obvious way or there is no functional change, maintainers should wait a day or two before merging to give the package maintainer a chance to respond.

**Comment by avsm** [comment]
+1

**Comment by OCamlPro-Henry** [comment]
Cc: @AltGr 

I was thinking hacking this.

Unfortunatly, I did not find a direct way in the github API to find the Github account associated to an email. I imagine two ways : 

- listing all contributors of the project, then build our own association table (email -> account) ;
- asking mainteners willings to have feedbacks to add a 'github' account in the opam package.

Obviously, the former works only for accounts that allow github to publish there email adress. Any others ideas ?

**Comment by AltGr** [comment]
Indeed. The question of identity of maintainers is indeed important, is anyway something that will have to sort out for signing. Gathering Github ids in advance might even help ; anyone willing to write clever git hacks to track meaningful PRs submitted to packages and extract their owner ?

Using the dev-repo field is indeed a good idea, although the author may not be the maintainer...

**Comment by samoht** [comment]
maybe we can start creating a `/maintainer` subdirectory and start filling it with useful info? That'll pave the way for signing and that's already useful.

**Comment by rgrinberg** [comment]
@samoht But we already have a maintainer email field in the opam file? Why can't we just extend it to cover github usernames (among other things).

My own 2 cents: I'm not a fan of scattering this information on the file system.

**Comment by dbuenzli** [comment]
Closing in favour of duplicate #6819 in which @hannesm mentions he has a solution to the map between github usernames and email addresses.
