### ISSUE TITLE
 conf-mpfr is broken on OS X El Capitan 10.11

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#4949]

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml/opam-repository/pull/4951

**Comment by samoht** [comment]
Can this be closed? (not clear if #4951 is supposed to fix the issue: if yes, please state it clearly in the related PR so we don't have orphans issues)

**Comment by UnixJunkie** [comment]
Yes, sorry.
