### ISSUE TITLE
Workflow on how to update opam-repository

### ISSUE THREAD

**Issue by schmidh** [ocaml/opam-repository#4958]
First of all: opam-repository is great!

Having a little problem though and don't know exactly what the intended workflow should be. I want to install some XEN related opam packages. But I'm running into some nasty resolving issues. (Thought first it could be the package solver but it's not.)

As far as I can see the problem is that some packages referenced in opam-repository might be a little obsolete. For example I want to install the XAPI package but instead of using the latest version 1.9.80 opam-repository references version 1.9.56.

So my understanding is that I should clone the opam-repository, make my changes and make a pull request. Is that correct? Actually the question behind the question is who is responsible for updating opam-repository?

Thanks!

**Comment by avsm** [comment]
ccing @jonludlam -- the maintainers of the packages usually submit updates to opam-repository, although anyone can do so via a PR.
