### ISSUE TITLE
missing post-message for sqlite3-ocaml

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-repository#50]

**Comment by dsheets** [comment]
This should be fixed and preferably with an automatic solution (not just a message).

smondet/trakeva#16 is the kind of annoying downstream breakage that results. If someone has easy test access to OS X/homebrew, please help out!

P.S. nearly 3 years to fix a packaging bug is a bit long...

**Comment by dsheets** [comment]
Oh, I should also mention that this error came up while testing revdep updates for lwt 2.5.0 (#4365) so if we want to test that thoroughly, this should be fixed.

**Comment by rleonid** [comment]
@dsheets In regard to this issue, would it be possible to pass arguments (via environment variables?) to opam targets? I can't seem to find anything to this effect, but I would like to be able to say `opam install sqlite3.brewed` and then modify the [sqlite3-ocaml](https://github.com/mmottl/sqlite3-ocaml) build accordingly.

**Comment by samoht** [comment]
sqlite3-ocaml now compiles with the right flags to avoid this.
