### ISSUE TITLE
Broken per-package variables in Travis CI tests with OPAM 1.1.2

### ISSUE THREAD

**Issue by nberth** [ocaml/opam-repository#5003]
Travis CI tests with `OPAM_VERSION=1.1.2` now emits `[ERROR] apron does not define the variable share.` and subsequently fails to correctly construct command lines for building and installing packages using per-package variables. Previous versions of the same package used the very same per-package variable (`"%{apron:share}%"`) and used to pass the Travis integration tests perfectly even with OPAM 1.1.2.

The pull request with which I am facing this new problem is https://github.com/ocaml/opam-repository/pull/4999

**Comment by dbuenzli** [comment]
This error occured on an opam version that is no longer supported and has been solved by not using  package variables in f324174b66260dc3d523ff50cb7c3ae.
