### ISSUE TITLE
"opam install mpi" fails on Fedora

### ISSUE THREAD

**Issue by russel** [ocaml/opam-repository#5023]
It seems that the Fedora installation of OpenMPI does not add symbolic links of executables into /usr/bin, header files into /usr/include, and libraries into /usr/lib. The build rule for OCaml MPI therefore fails because it cannot find the necessary header files, compilers, and libraries.

**Comment by dbuenzli** [comment]
Ping @UnixJunkie who is the maintainer of the package.

**Comment by dbuenzli** [comment]
@russel do you have an idea on how the headers can be found on the platform ?

**Comment by UnixJunkie** [comment]
I created the package, however I don't use it, so I'm not very keen on maintaining it.

**Comment by UnixJunkie** [comment]
@russel find how to properly compile and install
https://github.com/xavierleroy/ocamlmpi on your system then come back to us
with the commands you used (configure [...]).

**Comment by dbuenzli** [comment]
@UnixJunkie it's nice if you can stay around for it as we'd like to minimize the number of orphan packages. But if you really think it's too much of a burden for you proceed [that way](https://github.com/ocaml/opam-repository/commit/1d7c0d35a9ff4e66319a3bde6190eedc7906900b) to relinquish maintenance.

**Comment by UnixJunkie** [comment]
related to https://github.com/xavierleroy/ocamlmpi/issues/1
Cc @examachine @coti

**Comment by russel** [comment]
For some reason known only to the Fedora packagers, the OpenMPI stuff resides in /usr/lib64/openmpi, with bin and lib subdirectories (no problem so far) but no use of the alternatives system to populate /usr/bin and the standard library places (this is bizarre). Debian uses the alternatives system to ensure the compilers are in /usr/bin and the libraries in one of the usual library places. In a sense this is a fault of packaging by Fedora, on the other hand this is clearly how they want it, as it has been this way for ages. Thus you have to have /usr/lib64/openmpi/bin in the path to get the compilers, and /usr/lib64/openmpi/lib in the library path to get the libraries.

**Comment by UnixJunkie** [comment]
Dear Russel, please send the exact commands you use to compile ocamlmpi on your system: I don't have access to a fedora system so will not be able to test.
Then, the opam package might be updated by someone.
Or, even better, send yourself a pull request here https://github.com/ocaml/opam-repository to fix the opam package for ocamlmpi.
If you are one of the rare users of ocamlmpi (there are very, very few), please consider becoming the maintainer of this opam package. It is best when something is maintained by a user, because he is able to test things and will notice if something is broken.
I already maintain too many packages and have no more interest into this one.

    opam info --raw mpi

will tell you how this package is compiled.
It is clear that the configure step is missing.
I guess I hardcoded everything I needed to make it compile on my system in the Makefile.
In theory, I think the mpi bindings are supposed to work with whatever mpi you have installed.
I remember I pinned it to use only openmpi, because I think it's the high performance and open
source mpi implementation most users have access to.

**Comment by russel** [comment]
I haven't actually compiled the OCaml OpenMPI stuff on Fedora, I am just using opam. I am not an OCaml person, this was all to try and provide an OCaml version of a small example I have to play with scaling. To be honest given D, Go, Rust, Chapel, etc. I can't see much future for OCaml. My only real reason for using it is to compile Unison which is the best synchronisation tool there is. Maybe with this point and the above comments, I should forget using OCaml and MPI on Fedora, and we should just close this issue?

**Comment by UnixJunkie** [comment]
I see much future for Haskell and Ocaml, but that's a different story.
Don't close if it is not fixed, at some point, someone might help.

**Comment by UnixJunkie** [comment]
unison relies on MPI ?! opam doesn't say so.

**Comment by UnixJunkie** [comment]
you really want to distribute the computation? You need MPI, not parmap?

**Comment by dbuenzli** [comment]
Thanks for the details @russel. It seems we have Fedora on the CI  so I may try to give it at shot at some point. It seems the package metadata also need a bit of work (e.g. ocamlmpi is now on [github](https://github.com/xavierleroy/ocamlmpi))

**Comment by russel** [comment]
@UnixJunkie I suspect the Haskell, OCaml, everything else debate is for elsewhere. :-)

I am fairly sure Unison does not use MPI, I suspect it does use multiple processes. I assume OCaml still has a GIL.

I agree with using parmap for local parallelism, using MPI for clustering though remains the norm.

**Comment by dbuenzli** [comment]
Just in case here is the beginning of a patch
```
diff --git a/packages/mpi/mpi.1.01/opam b/packages/mpi/mpi.1.01/opam
index 206ec8bba..50e302459 100644
--- a/packages/mpi/mpi.1.01/opam
+++ b/packages/mpi/mpi.1.01/opam
@@ -1,14 +1,20 @@
 opam-version: "1.2"
 maintainer: "francois.berenger@inria.fr"
+author: "Xavier Leroy"
+homepage: "https://github.com/xavierleroy/ocamlmpi"
+dev-repo: "git+https://github.com/xavierleroy/ocamlmpi"
+bug-reports: "https://github.com/xavierleroy/ocamlmpi/issues"
 build: [
   [make "all"]
-  [make "opt"]
+  [make "opt"] {ocaml-native}
 ]
-remove: [[make "uninstall"]]
+install:[[ make "install" ]]
+remove: [[ "ocamlfind" "remove" "ocamlmpi" ]]
 depends: ["ocamlfind"]
 depexts: [
+  # FIXME a conf-mpi package should be devised.
   [["debian"] ["mpi-default-dev"]]
   [["ubuntu"] ["mpi-default-dev"]]
+  [["homebrew"] ["open-mpi"]]
+  [["fedora"] ["openmpi-devel"]]
 ]
-dev-repo: "git://github.com/HappyCrow/ocamlmpi"
-install: [make "install"]
diff --git a/packages/mpi/mpi.1.01/url b/packages/mpi/mpi.1.01/url
index f4153ad6f..8a1f637d3 100644
--- a/packages/mpi/mpi.1.01/url
+++ b/packages/mpi/mpi.1.01/url
@@ -1,2 +1,2 @@
-archive: "https://github.com/HappyCrow/ocamlmpi/archive/opam_package_v00.tar.gz"
-checksum: "bca4a7d120756555d1adb20762db75cf"
+archive "https://github.com/xavierleroy/ocamlmpi/archive/rel101.tar.gz"
+checksum: "9cb6010c71d33163787b7cf722c05ce8"
```

**Comment by gasche** [comment]
I submitted a bugreport against the Fedora package: [redhat bugzilla bug 1471512](https://bugzilla.redhat.com/show_bug.cgi?id=1471512).

**Comment by dbuenzli** [comment]
I'm reopening this since @gasche has timely [plan](https://github.com/ocaml/opam-repository/pull/9846#issuecomment-315611412) for revamping the package, he can update about his progress here.

**Comment by gasche** [comment]
Xavier merged the Makefile-fixing PR and made a release (the first to support ocamlfind). I included in the PR an [opam file](https://github.com/xavierleroy/ocamlmpi/blob/master/opam) following along Daniel's suggestions above, so it should be easy to provide a more robust package now. Detecting a working MPI installation (openmpi or mpich seem to be the standard) is more of a challenge, but we should be able to at least provide depexts and the package.

I'm in holidays starting today so I don't expect to be working on this more in the next few days.

**Comment by dbuenzli** [comment]
@gasche any progress on this ?

**Comment by examachine** [comment]
There is no openmpi package any more in opam?

**Comment by dbuenzli** [comment]
@examachine as you can read in this issue the package had to be removed due to quality issues. It's being reworked in the limited time of one the opam repository maintainer. If you would like to help and/or volunteer to become the maintainer of the package you are welcome.

**Comment by examachine** [comment]
I use ocamlmpi regularly, I'll see if I can make a package and then I'll make a PR about it. Does that sound alright?

**Comment by dbuenzli** [comment]
I guess this should be fine but please sync with @gasche.

**Comment by dbuenzli** [comment]
Here's the [procedure](https://github.com/ocaml/opam-repository/blob/master/CONTRIBUTING.md#adopting-and-relinquishing-package-maintainership) to adopt a package.

**Comment by gasche** [comment]
Yes, I would be very happy to let @examachine take care of this, especially if they are regular user of the package -- I think it's best if people that rely on the package maintain it. As I wrote above, I think the components to have a robust package definition should be in place now (although pkg-config detection still won't work, at least under Fedora), so hopefully that is not too much work.

**Comment by examachine** [comment]
Ok, I'll give a shot. Cheers..

**Comment by dbuenzli** [comment]
@examachine any news ?

**Comment by dbuenzli** [comment]
It seems not progress is being made. In any case `opam-repository` does not deal with packaging requests and as far as this issue tracker is concerned there is no issue here. I'll let @examachine and @gasche coordinate so that a new `mpi` package can make it to the `opam-repository`.
