### ISSUE TITLE
omake-mode URL is 404

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam-repository#5031]
Several ppl have asked me about omake-mode in OPAM whose URL is now 404.

Well, I wrote an elisp called `omake-mode.el` once and made it available online at https://bitbucket.org/camlspotter/omake-mode for years and using it now, but I have no idea about this `omake-mode` in OPAM.  Is it a fork or a completely independent implementation?

**Comment by lefessan** [comment]
It looks like a newer omake mode by Jane Street (@yminsky), but the sources are not available anymore (I couldn't find them on Github or Bitbucket). I don't know what we should do with it...

**Comment by yminsky** [comment]
Huh.  I have no idea, actually.  What was the old URL?

**Comment by lefessan** [comment]
The former URL was:
https://github.com/seanmcl/omake-mode/archive/1.1.1.tar.gz

**Comment by lefessan** [comment]
It is also linked from here:
https://bitbucket.org/yminsky/js-elisp

**Comment by dsheets** [comment]
Without an archive for over a year, I propose we remove the package in #5679. It is not clear what the relationship is between @camlspotter's `omake-mode` and Jane Street's `omake-mode`.

**Comment by yminsky** [comment]
Fine by me.
