### ISSUE TITLE
Sticky optdep ? 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-repository#5083]
I'm in a weird state where trying to install `lwt` will absolutely want to install `ssl` which is broken on osx el capitan (see https://github.com/savonet/ocaml-ssl/issues/22). Why is the system insisting on installing all of this when I try to install lwt ? 

```
> opam install lwt
The following actions will be performed:
  ∗  install ssl         0.5.0                [required by lwt]
  ∗  install lwt         2.5.0 
  ∗  install lambda-term 1.9   
  ∗  install cstruct     1.7.0 
  ∗  install conduit     0.9.0 
  ∗  install cohttp      0.19.3
  ∗  install github      1.0.0 
===== ∗  7 =====
Do you want to continue ? [Y/n] n
> opam config report
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            1
# repositories    1* (http), 1 (local), 1 (version-controlled)
# pinned          1 (path), 24 (version control)
# current-switch  4.02.3
# last-update     2015-11-04 13:46
```

**Comment by dbuenzli** [comment]
Worked around by installing `ssl` to pickup my homebrew ssl install via:
```
CFLAGS=-I/usr/local/include opam install ssl
```
but still wondering why all these packages wanted to be installed without me wanting to (they were however installed in an upgrade that failed because of `ssl`'s failure).

**Comment by dsheets** [comment]
I believe if there are root packages deeper in the dep hierarchy that are currently uninstalled, e.g. because of an upgrade failure, the solver will be told to satisfy their installation as well. If you think this behavior is erroneous, I recommend filing an issue on [ocaml/opam](https://github.com/ocaml/opam).
