### ISSUE TITLE
Opam fail to build ocamlfind

### ISSUE THREAD

**Issue by tychota** [ocaml/opam-repository#5098]
cc @gerdstolpmann
tested with 

| plateform | opam version | ocaml compilateur |
| --- | --- | --- |
| ubuntu 15.10 | stable repo opam | stable repo ocaml |
| ubuntu 15.10 | ppa opam | ppa ocaml |
| ubuntu 15.10 | curl opam | stable repo ocaml |
| ubuntu 15.10 | curl opam | build from source ocaml |

_(Zsh is my main shell but switching to bash is exactly the same.)_

running `opam install ocaml`

get me 

``` bash
for p in findlib; do ( cd src/$p; make all ) || exit; done
make[1]: Entering directory '/home/me/.opam/system/build/ocamlfind.1.5.6/src/findlib'
ocamllex fl_meta.mll
22 states, 392 transitions, table size 1700 bytes
ocamldep *.ml *.mli >depend
USE_CYGPATH="0"; \
export USE_CYGPATH; \
cat findlib_config.mlp | \
    ../../tools/patch '@CONFIGFILE@' '/home/me/.opam/system/lib/findlib.conf' | \
    ../../tools/patch '@STDLIB@' '/usr/lib/ocaml' | \
    sed -e 's;@AUTOLINK@;true;g' \
        -e 's;@SYSTEM@;system: linux;g' \
         >findlib_config.ml
Makefile:79: recipe for target 'findlib_config.ml' failed
make[1]: Leaving directory '/home/me/.opam/system/build/ocamlfind.1.5.6/src/findlib'
Makefile:13: recipe for target 'all' failed
```

and 

``` bash
Makefile:175: depend: No such file or directory
sed: -e expression #2, char 20: unknown option to `s'
make[1]: *** [findlib_config.ml] Error 1
make: *** [all] Error 2
```

but running 

``` bash
cat findlib_config.mlp | ../../tools/patch '@CONFIGFILE@' '/home/me/.opam/system/lib/findlib.conf' | ../../tools/patch '@STDLIB@' '/usr/lib/ocaml' | sed -e 's;@AUTOLINK@;true;g' -e 's;@SYSTEM@;system: linux;g' > findlib_config.ml
```

in `~/.opam/system/build/ocamlfind.1.5.6/src/ocamlfind` produces not issue (at all) 

after doing this if I did `make install` in  `~/.opam/system/build/ocamlfind.1.5.6` then relaunch `opam install ocaml`, I get the same issue.

I'm clueless :sad:

**Comment by peterfrey** [comment]
turns out (after some googling) that a bunch of ncurses related libraries must be in the system.
(this is not obvious, I think, from the error messages)
I lost the backup list of all the installed packages.  This not a problem, i can add them all again and leave out things I have never used ...

**Comment by vshender** [comment]
I have the same issue on Mac OS X with brew-installed opam.

**Comment by dbuenzli** [comment]
There were 5 new `ocamlfind` versions since the first report. Can anyone confirm this is still a problem ?  If not I'd move on to close this issue.

**Comment by dbuenzli** [comment]
I'll close this now. Feel free to reopen if there is still a problem.
