### ISSUE TITLE
Packages expecting ocaml-version >= 4.02.1 fail to install with 4.02.0+trunk compiler

### ISSUE THREAD

**Issue by eponier** [ocaml/opam-repository#5131]
This can be overcome with "OPAMVAR_ocaml_version = 4.02.3", but this is cumbersome to add to all requests, and this does not work with all packages (it seems that opam files containing "ocaml-version" directly, and not "available: [ocaml-version: ...]" ignore the environment variable).

The solutions I see:
- rename the compiler, so that its name is greater than any 4.02.{0,1,2,3,...} version, e.g. "4.02.+trunk".
- check "ocamlc -version" or a similar command to check the version instead of the name of the compiler

**Comment by samoht** [comment]
I think this is not an issue anymore, so closing.
