### ISSUE TITLE
melt package lacks C compilation flags

### ISSUE THREAD

**Issue by ppedrot** [ocaml/opam-repository#5162]
When installing melt through opam, the compilation fails on file melt/tool.ml with the followin error:

```
/usr/bin/ocamlopt.opt -I /home/pm/.opam/system/lib/mlpost -I /home/pm/.opam/system/lib/bitstring -I /home/pm/.opam/system/lib/cairo unix.cmxa str.cmxa bigarray.cmxa cairo.cmxa bitstring.cmxa mlpost.cmxa latex/variable.cmx prelude/pqueue.cmx prelude/clist.cmx latex/latex.cmx melt/melt_common.cmx melt/mlpost_specific.cmx melt/melt.cmx melt_version.cmx totoconf.cmx melt/tool.cmx -o melt/tool.native
/usr/bin/ld: /home/pm/.opam/system/lib/cairo/libmlcairo.a(ml_cairo_ft.o): référence au symbole non défini «FcNameUnparse»
//usr/lib/x86_64-linux-gnu/libfontconfig.so.1: error adding symbols: DSO missing from command line
```

Note that manually adding the option `-ccopt -lfontconfig` to the above line makes it compile just fine. I am not sure who is the real culprit between cairo and melt though.

**Comment by taquangtrung** [comment]
I encountered the same problem when install melt in opam.
How did you manage to fix it?

The threw error message is:

=======================
# /home/trungtq/.opam/4.02.3/bin/ocamlopt.opt -c -I /home/trungtq/.opam/4.02.3/lib/mlpost -I /home/trungtq/.opam/4.02.3/lib/bitstring -I /home/trungtq/.opam/4.02.3/lib/cairo -I melt -I prelude -I meltpp -I latex -o melt/tool.cmx melt/tool.ml
# /home/trungtq/.opam/4.02.3/bin/ocamlopt.opt -I /home/trungtq/.opam/4.02.3/lib/mlpost -I /home/trungtq/.opam/4.02.3/lib/bitstring -I /home/trungtq/.opam/4.02.3/lib/cairo unix.cmxa str.cmxa bigarray.cmxa cairo.cmxa bitstring.cmxa mlpost.cmxa latex/variable.cmx prelude/pqueue.cmx prelude/clist.cmx latex/latex.cmx melt/melt_common.cmx melt/mlpost_specific.cmx melt/melt.cmx melt_version.cmx totoconf.cmx melt/tool.cmx -o melt/tool.native
# + /home/trungtq/.opam/4.02.3/bin/ocamlopt.opt -I /home/trungtq/.opam/4.02.3/lib/mlpost -I /home/trungtq/.opam/4.02.3/lib/bitstring -I /home/trungtq/.opam/4.02.3/lib/cairo unix.cmxa str.cmxa bigarray.cmxa cairo.cmxa bitstring.cmxa mlpost.cmxa latex/variable.cmx prelude/pqueue.cmx prelude/clist.cmx latex/latex.cmx melt/melt_common.cmx melt/mlpost_specific.cmx melt/melt.cmx melt_version.cmx totoconf.cmx melt/tool.cmx -o melt/tool.native
# /usr/bin/ld: /home/trungtq/.opam/4.02.3/lib/cairo/libmlcairo.a(ml_cairo_ft.o): undefined reference to symbol 'FcNameUnparse'
# //usr/lib/x86_64-linux-gnu/libfontconfig.so.1: error adding symbols: DSO missing from command line
# collect2: error: ld returned 1 exit status
# File "caml_startup", line 1:
# Error: Error during linking
# Command exited with code 2.
### stderr ###
# make: *** [world] Error 10

**Comment by ppedrot** [comment]
I did not fix it, for me melt is not installable through opam.

**Comment by taquangtrung** [comment]
Thanks for replying. Yeah, the same for me as well.

I tried to install ocaml-melt by using sudo apt-get isntall ocaml-melt but there are broken dependencies in my Linux system, thus it does not work.

So, now I am trying to fix the Makefile of melt under "~/.opam/4.02.3/build/melt..." but it does not work at this moment.

**Comment by ppedrot** [comment]
Note that I also reported this bug to the original author, just in case.
https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1516&group_id=76&atid=391
Maybe we should patch it ourselves?

**Comment by taquangtrung** [comment]
Thanks for reporting it. I notice that the melt module hasn't been updated since 2011

 I don't really understand about the way Ocamlbuild works, so current cannot change the Makefile or Ocamlbuild setting to make it work.

There is another option not using Ocamlbuild, as showed in the README file of melt. It can compile melt, but not really helpful for me.
       make -f noob.makefile
       make -f noob.makefile install

**Comment by OCamlPro-Henry** [comment]
I think the error belongs to the `cairo` package. It is one of its module that requires `fontconfig`.

I tried a fix in cairo's `./configure`, could you test: 
```
opam pin add cairo https://github.com/OCamlPro-Henry/ocaml-cairo.git
opam install melt
```
If it works, I don't know what's the best way to fix this. The `cairo` upstream project seems rather unmaintained.

**Comment by ppedrot** [comment]
It does work for me. Can't you fork the ```cairo``` package? I don't think it requires a lot of maintenance.

**Comment by taquangtrung** [comment]
I tried to install "melt" in Opam under OCaml 4.02.3 but it didn't work. So I guess that your fix hasn't been updated to Opam.

By the way, I used a workaround to install melt by upgrading the Linux system so that I can do "sudo apt-get install ocaml-melt".
But it is definitely better if "melt" can be supported smoothly in Opam.

**Comment by samoht** [comment]
Closing the issue as @OCamlPro-Henry have pushed a patch to fix it. Please re-open the issue if you still have that problem.
