### ISSUE TITLE
ocaml-4.02.3 fails to run in yosomite

### ISSUE THREAD

**Issue by vigneshr89** [ocaml/opam-repository#5273]
I tried to install ocaml via homebrew. 
*brew install ocaml*

It installed the latest version 4.02.3.  but when I tried ocaml -version it returns 
*_Fatal error: unknown C primitive `loat'_*

**Comment by dbuenzli** [comment]
I guess you are not reporting a problem about an ocaml installed through an opam switch here. Could you try to force a source install to see if that solves the problem:

    brew remove ocaml 
    brew install --build-from-source ocaml

**Comment by vigneshr89** [comment]
It solved the problem . Thank you. 
Actually I did , 
`*brew install opam*`. It had the problem.

**Comment by vigneshr89** [comment]
closing the issue as it is resolved.
