### ISSUE TITLE
Enable the Travis CI Trusty Beta?

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam-repository#5341]
See <https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta> and <https://docs.travis-ci.com/user/trusty-ci-environment/>.

**Comment by avsm** [comment]
Working on this -- I have a set of Docker containers that include this and other distros.  See https://github.com/avsm/ocaml-dockerfile/blob/master/.travis.yml for the WIP

**Comment by samoht** [comment]
Done.
