### ISSUE TITLE
Cannot install SSL in Mac OS X 10.11 with MacPorts

### ISSUE THREAD

**Issue by michipili** [ocaml/opam-repository#5512]
Installing SSL fails on Mac OS X (see version details below). The installation dies with

    [ERROR] The compilation of ssl failed at "./configure --prefix /opt/opam/4.02.3
        CFLAGS=-I/usr/local/opt/openssl/include".

On my system, openssl is installed with macports under `/opt/local` and the ssl.h header file is to be found under `openssl/ssl.h`.

- Mac OS X 10.11.3 (15D21)
- Opam 1.2.2
- ssl.0.5.2 (opam package)

**Comment by dsheets** [comment]
I believe the issue here is that `ssl` can only filter by `os` (`darwin` aka OS X) but there are now actually two different 'modern' OpenSSL installation on OS X -- via homebrew and via MacPorts. `ssl` now assumes you are using homebrew but obviously this is not always correct. We should determine a suitable package manager detection mechanism and use it in `ssl`'s `build` sequence. `conf-openssl` should also include a `depext` for MacPorts.

**Comment by michipili** [comment]
That is strange, because I could install ssl 5.0, but I cannot do it anymore since I upgraded my system. On a sensibly configured system, Autoconf macros should be able to locate openssl header files. In the opam file the line

     ["./configure" "--prefix" prefix "CFLAGS=-I/usr/local/opt/openssl/include"] { os = "darwin" }

displays an argument `"CFLAGS=-I/usr/local/opt/openssl/include"` which probably prevents the autoconf macros to actually detect the library. This should be fixed in the `configure.ac` file of the ssl project, but the opam file is not the place for this.

**Comment by dsheets** [comment]
What did you upgrade from? OS X 10.10? 10.10 shipped OpenSSL but 10.11 removed it. `ssl` was broken for everyone on 10.11 until the extra `CFLAGS` were added. I don't think `autoconf` macros can detect package-manager-specific include directories but I may be wrong.

**Comment by michipili** [comment]
I need to check this out but I would expect autoconf macros to use the PATH environment variable as a hint to look for libraries. If they do not, then it would be a reasonable approach to solve the problem – and the appropriate place, since detecting platform particularities to guarantee portability is the whole point of configure scripts.

**Comment by dsheets** [comment]
`PATH` is searched for executables. I ran OS X with MacPorts in a VM and tested your hypothesis. It does not work.

I have updated the `ssl` package in #5650 to include the MacPorts include directory as well and fix a couple of other minor issues. savonet/ocaml-ssl#22 tracks the upstream fix.

Thanks for your report!

**Comment by michipili** [comment]
@dsheets Fantastic, thank you for the good work!

Just out of curiosity, how did you run OS-X in a VM? (Travis?) I would like to be able to do the same on my desktop.

**Comment by dsheets** [comment]
Unfortunately, I used VMWare Fusion Pro 8 which is paid software. To run OS X in a VM, you need a Mac with OS X and VMWare Fusion (normal is about 60GBP, Pro is something like 200GBP). Fusion installs OS X from the recovery partition and running virtualized is allowed by Apple's EULA when done on Mac hardware.

**Comment by michipili** [comment]
Thank you for the details! :)
