### ISSUE TITLE
Acceptance of non OCaml projects

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam-repository#5555]
Since OCaml is technically not tied to opam packages, would opam maintainers accept packages that weren't OCaml based? Say I want to simple distribute a shell script? Can opam create a switch without being tied to an OCaml compiler?

**Comment by dsheets** [comment]
I think we're comfortable distributing packages for non-OCaml projects.

We generally try to discourage system-wide side effects in packages (like installing to `/usr/bin`).

You could probably get opam to use a "switch" that is not tied to an OCaml compiler but this will be a bit of a hack at the moment.

We don't currently have: an "opam-wide" (switch-free) installation capability, switches-as-packages, OCaml agnosticism

Please, feel free to open issues in the opam tracker for features that opam lacks which make it more useful for other languages and types of packages. Some of these things have been considered and some have been planned but nothing is present to really support non-OCaml packages as first-class, yet.

**Comment by avsm** [comment]
> I think we're comfortable distributing packages for non-OCaml projects.

Although for this specific remote (ocaml/opam-repository), there should be some link to the OCaml ecosystem.  I have a bunch of private remotes that I use for my own shell scripts and random stuff, but they're not submitted to `ocaml/opam-repository`

**Comment by agarwal** [comment]
@fxfactorial You might take a look at [biopam](https://github.com/solvuu/biopam), which is for non-OCaml bioinformatics tools. We defined a fake compiler, so it is possible to install packages without ever installing ocaml.
