### ISSUE TITLE
Jane street packages have ocaml-version < 4.03.0

### ISSUE THREAD

**Issue by chambart** [ocaml/opam-repository#5574]
Lots of jane street packages can build with OCaml 4.03.0, but all they are all restricted to < 4.03.0 since
this patch: https://github.com/ocaml/opam-repository/commit/5fd52d6b81718d85c6f5f471cd3132710a4e5c71

@diml Are you ok with removing this constraint ? I will make a pr for removing the constraints on packages that are know to work and import fixes from https://github.com/OCamlPro/opam-flambda-repository-overlay for some which don't.

We are using those packages for testing and benchmarks, so we know they work and ensure that they effectively keep working.

**Comment by diml** [comment]
Sure, no problem. I added the constraint everywhere following janestreet/sexplib#17. I didn't have time to test what worked and what didn't, but I have no problem removing it where approriate

**Comment by Freyr666** [comment]
>core is not available because your system doesn't comply with ocaml-version = "4.02.3"

As i can see here:

https://github.com/ocaml/opam-repository/tree/master/packages/core

there are some versions of this package with 4/03 support. How could i install core.113.33.02+4.03 for example with opam? Thanx/

**Comment by samoht** [comment]
This is not the case anymore, so closing.
