### ISSUE TITLE
conf-gmp installation fails in cygwin

### ISSUE THREAD

**Issue by thranur** [ocaml/opam-repository#5588]
the `conf-gmp` package fails in Cygwin even when `libgmp-devel` is installed, because the test command looks for `gmp.h` in `/usr/local/include` and not `/usr/include`, which is where Cygwin puts it (at least in my 32-bit Cygwin).

Is there a simple way to work around it? I tried manually editing the build line in the `.opam/repo/default/packages/conf-gmp/conf-gmp.1/opam` file, but it's still using the old command.

Also, I tried updating my opam to see if version 1.1 was available for my OPAM (1.2.2, installed with Protzenko's Ocaml for Windows installer, OCaml 4.02.3), but no other version was found.

**Comment by thranur** [comment]
Well, I found out how to use the local version:

```
cp -r .opam/repo/default/packages/conf-gmp/conf-gmp.1 .
[edit file to replace /usr/local/include with /usr/include]
opam pin add conf-gmp conf-gmp.1
[confirm and install]
```

But it would be better if both directories were included via `-I`.

**Comment by samoht** [comment]
I have a fork with some fixes for cygwin here: https://github.com/samoht/opam-repository-mingw

I'll create a PR to integrate that upstream (although I'm not totally happy with the fixes...)

**Comment by thranur** [comment]
Indeed, I confirm that using the mingw repository works and avoids all of these issues. I thought that Protzenko's OCaml installer with bundled OPAM was roughly equivalent, but so far it seems better to install OPAM using the instructions in @samoht's repository (or @fdopen's).

**Comment by samoht** [comment]
On Windows, it is currently advised to use https://fdopen.github.io/opam-repository-mingw/ which maintains a fork of the opam-repository which works pretty well on Cygwin/MinGW. We have plan to merge back the two repositories back to support Windows by default /cc @dra27
