### ISSUE TITLE
Package zarith 1.4.1 fails to install in Cygwin+MinGW

### ISSUE THREAD

**Issue by thranur** [ocaml/opam-repository#5591]
This is related to #5588 : because `gmp.h` is in `/usr/include` and not `/usr/local/include`, `zarith` also fails to find the `gmp` package.

Incidentally, the `opam` file already considers some OSes in a special manner (openbsd, freebsd and darwin), so it suffices to consider cygwin as one of these "special" OSes. The `CFLAGS` variable will then be set accordingly.

A second issue I had with zarith 1.4.1 was line 242 in the `configure` file:

    if test "$ocamllibdir" = "auto"; then ocamllibdir=`ocamlc -where`; fi

Due to Windows (and possibly a MinGW OCaml compiler) shenanigans, `ocamlc` introduces a `\r` at the end of the command, and so the `ocamllibdir` variable contains the `\r` which prevents the rest from working. I hacked a `| tr -d '\r'` after the `-where` and it worked, but it seems there is already a `echo_n()` function for that.

I didn't submit a pull request because I don't know the exact right way to fix these issues (e.g. I don't have time now to fix them the proper way), but after doing both these patches (and patching my `conf-gmp` as mentioned in #5588) I was able to install zarith on my Cygwin.

I didn't test its actual *usage* though.

**Comment by samoht** [comment]
On Windows, it is currently advised to use https://fdopen.github.io/opam-repository-mingw/ which maintains a fork of the opam-repository which works pretty well on Cygwin/MinGW. We have plan to merge back the two repositories back to support Windows by default /cc @dra27
