### ISSUE TITLE
broken constraints

### ISSUE THREAD

**Issue by yminsky** [ocaml/opam-repository#5641]
In particular, on my most recent update, I got this:

    $ opam update

    =-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
    [default] synchronized from https://opam.ocaml.org
    [WARNING] A conflict was detected in your installation. This can be caused by updated constraints or conflicts in your installed packages:
		- No package matches inotify.

    You should run "opam upgrade --fixup" to resolve the situation.

Then, when following the above instructions, I get this:

    $ opam upgrade --fixup
    The following actions will be performed:
      ⊘  remove    async_inotify       113.24.00               [conflicts with ppx_bench, async, ppx_inline_test]
      ⊘  remove    async_shell         113.24.00               [conflicts with ppx_bench, async, ppx_inline_test]
      ∗  install   base-ocamlbuild     base                    [required by ocamlbuild]
      ⊘  remove    inotify             2.1                     [conflicts with ocamlbuild]
      ⊘  remove    async_find          113.24.00               [conflicts with ppx_bench, async, ppx_inline_test]
      ⊘  remove    ppx_jane            113.24.01               [conflicts with ppx_inline_test, ppx_fail, ppx_compare, etc.]
      ⊘  remove    ppx_typerep_conv    113.24.00               [conflicts with ocamlbuild]
      ⊘  remove    ppx_sexp_message    113.24.00               [conflicts with ppx_here]
      ⊘  remove    ppx_let             113.24.00               [conflicts with ocamlbuild]
      ⊘  remove    ppx_expect          113.24.00               [conflicts with ppx_compare, ppx_inline_test]
      ⊘  remove    ppx_variants_conv   113.24.00               [conflicts with ocamlbuild]
      ⊘  remove    ppx_sexp_value      113.24.00               [conflicts with ppx_here]
      ⊘  remove    ppx_fields_conv     113.24.00               [conflicts with ocamlbuild]
      ⊘  remove    ppx_custom_printf   113.24.00               [conflicts with ocamlbuild]
      ⊘  remove    ppx_assert          113.24.00               [conflicts with ppx_compare, ppx_here]
      ⊘  remove    ppx_sexp_conv       113.24.00               [conflicts with ocamlbuild]
      ↻  recompile ocamlbuild          0                       [uses async_find]
      ↘  downgrade variantslib         113.24.00 to 109.15.03  [upstream changes]
      ↘  downgrade sexplib             113.24.00 to 113.00.00  [required by incremental, async_extended, core_bench, rpc_parallel]
      ↘  downgrade ppx_core            113.24.00 to 113.09.00  [required by ppx_pipebang, ppx_here, ppx_enumerate, etc.]
      ↘  downgrade fieldslib           113.24.00 to 113.00.00  [required by core_bench, incremental]
      ↘  downgrade bin_prot            113.24.00 to 113.00.00  [required by async_extended, core_bench]
      ↻  recompile oasis               0.4.5                   [uses ocamlbuild]
      ↻  recompile cppo                1.3.1                   [uses ocamlbuild]
      ∗  install   pa_test             112.24.00               [required by incremental]
      ∗  install   pa_structural_sexp  113.00.00               [required by core]
      ∗  install   custom_printf       113.00.00               [required by core_kernel]
      ↘  downgrade ppx_optcomp         113.24.00 to 113.09.00  [upstream changes]
      ↘  downgrade typerep             113.24.00 to 113.00.00  [upstream changes]
      ↻  recompile yojson              1.3.0                   [uses cppo]
      ↻  recompile utop                1.18.1
      ↻  recompile ocplib-endian       0.8                     [uses ocamlbuild]
      ↻  recompile js_of_ocaml         2.7
      ↘  downgrade ppx_driver          113.24.00 to 113.09.00  [required by ppx_pipebang, ppx_here, ppx_enumerate, etc.]
      ↘  downgrade core_kernel         113.24.00 to 113.00.00  [upstream changes]
      ↻  recompile ppx_deriving_yojson 2.4
      ↻  recompile merlin              2.3.1
      ↻  recompile xtmpl               0.13.0                  [uses js_of_ocaml]
      ↻  recompile xmldiff             0.5.0
      ↻  recompile d3                  0.2.2
      ↘  downgrade ppx_type_conv       113.24.00 to 113.09.00  [required by ppx_inline_test, ppx_compare, ppx_bench, etc.]
      ↘  downgrade ppx_pipebang        113.24.00 to 113.09.00
      ↘  downgrade ppx_here            113.24.00 to 113.09.00
      ↘  downgrade patience_diff       113.24.00 to 112.24.00  [required by patdiff]
      ↘  downgrade core                113.24.01 to 113.00.00  [required by incremental, core_bench, async_extended, etc.]
      ↘  downgrade async_kernel        113.24.00 to 113.00.00  [required by async]
      ↘  downgrade ppx_inline_test     113.24.00 to 113.09.00
      ↘  downgrade ppx_enumerate       113.24.00 to 113.09.00
      ↘  downgrade ppx_conv_func       113.24.00 to 113.09.00  [required by ppx_xml_conv]
      ↘  downgrade ppx_compare         113.24.00 to 113.09.00
      ↘  downgrade ppx_bin_prot        113.24.01 to 113.09.00
      ↘  downgrade ppx_fail            113.24.00 to 113.09.00
      ↘  downgrade textutils           113.24.00 to 112.17.00  [required by core_bench, async_extended, core_profiler]
      ↘  downgrade re2                 113.24.00 to 113.00.00  [required by core_profiler]
      ↘  downgrade incremental         113.24.00 to 113.00.00
      ↘  downgrade async_unix          113.24.00 to 113.00.00  [required by async]
      ↘  downgrade async_rpc_kernel    113.24.00 to 113.00.00  [upstream changes]
      ↘  downgrade ppx_bench           113.24.00 to 113.09.00
      ↘  downgrade ppx_xml_conv        113.24.00 to 113.09.00
      ↘  downgrade core_bench          113.24.00 to 112.35.00
      ↘  downgrade core_extended       113.24.00 to 113.00.00  [required by core_profiler, async_extended, patdiff]
      ↘  downgrade async_extra         113.24.00 to 113.00.00  [required by async]
      ↘  downgrade patdiff             113.24.00 to 113.00.00
      ↘  downgrade core_profiler       113.24.00 to 113.00.00
      ↘  downgrade async               113.24.00 to 113.00.00
      ↘  downgrade rpc_parallel        113.24.00 to 113.00.00
      ↘  downgrade async_extended      113.24.00 to 113.00.00
      ↻  recompile cstruct             1.8.0                   [uses async]
    ===== ∗  4   ↻  13   ↘  36   ⊘  15 =====
    Do you want to continue ? [Y/n]

How should users deal with these kinds of errors?  Is there any way of detecting them earlier?

**Comment by yminsky** [comment]
Also, this particular line looks suspicious:

    ↻  recompile ocamlbuild          0                       [uses async_find]

It's hard to believe that ocamlbuild depends on async_find.

**Comment by dsheets** [comment]
This is likely because I removed `darwin` from the supported `inotify` operating systems. I'll revert that change and we'll figure out where to go from there.

**Comment by dsheets** [comment]
#5622 caused the issue. #5642 reverted it. We should work on transitioning away from `async_inotify`'s dependency on `inotify` on OS X.

**Comment by yminsky** [comment]
I guess this is a request for us.  Can you enter a bug for it on github?

And thanks for the quick fix!

**Comment by yminsky** [comment]
Actually, re-opening.  The fix hasn't hit yet, as far as I can tell.  I get the same problem after updating.

**Comment by dsheets** [comment]
What is your opam remote stack? Is your primary opam remote a local git repository? Have you pulled a new upstream version?

What does `~/.opam/packages/inotify/inotify.2.1/opam` contain?

**Comment by dsheets** [comment]
`async_inotify` OS X support is now tracked at janestreet/async_inotify#3.

**Comment by yminsky** [comment]
OK, now it's fixed!  Thanks guys.
