### ISSUE TITLE
Changing the 'url' file does not trigger a new travis installation

### ISSUE THREAD

**Issue by lefessan** [ocaml/opam-repository#5676]
I have added the missing checksums for a set of packages, but I would like Travis to check that I didn't do a mistake by installing each package I modified.

**Comment by dsheets** [comment]
Do you still see that behavior? It looks like the builds are going OK.

Thanks for the addition of checksums!

**Comment by lefessan** [comment]
Well, most of them started a Travis build, but some didn't. Closing-reopening the PR started the build. Probably a problem with Travis.
Thx !
