### ISSUE TITLE
documentation missing in coq package

### ISSUE THREAD

**Issue by hendriktews** [ocaml/opam-repository#5772]
@clarus Thanks for you opam coq package! I would suggest to include the coq documentation in the package or to have a separate package for the documentation.

**Comment by hendriktews** [comment]
BTW, with documentation I mean the reference manual.

**Comment by clarus** [comment]
Thanks! Maybe we could add the documentation in the `build-doc` rule? I do not know the best practices for that and I have never made packages with documentation. By the way, what the would be the use case for installing the documentation?

**Comment by fsmith1024** [comment]
I sometimes need to work offline.  Having the documentation local is a big help in this case.

**Comment by dbuenzli** [comment]
Since it seems that `opam` is an [official way](https://coq.inria.fr/opam/www/using.html) of installing `coq` I think this kind of package enhancement requests should be handled upstream. I'm thus closing this.
