### ISSUE TITLE
Travis timeout for OPAM_VERSION=1.2.0 

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam-repository#5820]
See https://travis-ci.org/ocaml/opam-repository/builds/112757301

OCAML_VERSION=4.02 OPAM_VERSION=1.2.0  timed out after 48mins while the same OCaml version with OPAM_VERSION=1.2.2 finishes the job in 17mins.

Why the times are so different?  It seems OPAM_VERSION=1.2.0, OCaml compiler is compiled for each package test, but OPAM_VERSION=1.2.2 it is skipped.  Is it possible to skip repeating OCaml compilation for 1.2.0 too?

**Comment by yallop** [comment]
>  It seems OPAM_VERSION=1.2.0, OCaml compiler is compiled for each package test,

I think this has been fixed here: https://github.com/ocaml/opam-repository/commit/244036526f1986c4b07011d9648ab41a9c0780b5
