### ISSUE TITLE
utop not working after install through opam

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-repository#584]
Importing https://github.com/OCamlPro/opam/issues/570

> To reproduce:
> Run opam install utop (I did this on a clean install of opam v1.0.0 but I've noticed this problem on prior versions). This'll install packages lwt, among others.
> Run utop
> Result:
> Fatal error: unknown C primitive 'lwt_libev_init'
> I'm running this on a x86_64 machine running archlinux, with opam v1.0.0 installed through the AUR. I noticed the lwt install contains the configuration flag --disable-libev, which may or may not be related. FYI, installing utop directly from the AUR works fine.
> 
> Please let me know if you need any additional details. Thanks.

**Comment by micheleriva** [comment]
I ran in the same error after installing opam via mac ports on OSX.
I solved it by running

`$ eval opam config env`

without backticks!

**Comment by pmetzger** [comment]
I don't see how that can work without backticks. It makes no sense.

**Comment by micheleriva** [comment]
@pmetzger I have no Idea.
I'll attach here a couple of screenshot:

Without backticks:
<img width="697" alt="schermata 2018-10-05 alle 17 00 22" src="https://user-images.githubusercontent.com/14977595/46543094-4fa09480-c8c0-11e8-8d29-f2e88f0afd07.png">

With backticks:
<img width="697" alt="schermata 2018-10-05 alle 17 00 35" src="https://user-images.githubusercontent.com/14977595/46543115-5af3c000-c8c0-11e8-9393-afe743658157.png">

I finally solved it by running `eval opam config env >> ~/.zshrc`

**Comment by pmetzger** [comment]
So without backticks it's working fine, and with them it fails, as I expected. Without them it's just running the program and you might as well have done it without `eval`. With them, eval is then setting the variables.

Putting the output in your .zshrc is a terrible idea, because the next time you change your opam switch you'll be pointing to the wrong place. I suggest just doing what everyone else does and running `eval $(opam config env)` or what have you.

**Comment by dotrosedotnet** [comment]
I'm having the same experience on a new install on macos. is it copacetic to add `eval $(opam config env)` to my `.zshrc`? I mean, I do need to rerun the command if I want `utop` to work on a new terminal...

**Comment by pmetzger** [comment]
You need the terminal to have the opam setup information if you want opam based stuff to work; this has nothing to do with utop of course. So yes, every brand new terminal needs such a thing.

**Comment by dotrosedotnet** [comment]
thanks!
