### ISSUE TITLE
need for a conf-pkgconfig?

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam-repository#5843]
Some conf packages (in my case, `conf-ncurses` and `conf-nanomsg`) use `pkg-config` to check for the presence of their respective libraries. However, `pkg-config` is not always installed on the system, so I think they should depend on some `conf-pkgconfig`.

**Comment by OCamlPro-Henry** [comment]
There is a already a `conf-pkg-config`. It should indeed be added in many `conf-*`. See https://github.com/ocaml/opam-repository/pull/5837#discussion_r54594712

**Comment by c-cube** [comment]
Ok, thanks.
