### ISSUE TITLE
Create conf-bmake

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam-repository#5960]
A number of packages have a depext on `bmake` the BSD `make` tool. The system package for this tool is called `bmake` on OS X with homebrew package manager.

@michipili, as you are the major user of `bmake` for your opam packages, would you be willing to create and maintain a `conf-bmake` package to centralize this `bmake` dependency so that, e.g., OS X homebrew package name could be added in a single place?

**Comment by michipili** [comment]
Why not, but there is a major issue: I have no idea what this `conf-bmake` package would be expected to do. Should it replace or complement the `depexts` directives mentioning `bmake`? Would this package be expected to install `bmake` or only to check for its presence?

**Comment by dsheets** [comment]
It should replace `depexts` mentioning `bmake` and itself have (consolidated) depexts for `bmake`. It should check for the presence of `bmake` in `build`. Take a look at the other `conf-*` packages in the repo as a guide.

**Comment by michipili** [comment]
@dsheets Is ist possible that you assign the issue to me? This would help me not to loose it from sight. :)

**Comment by dsheets** [comment]
Done.

**Comment by dsheets** [comment]
Fixed in #6591.
