### ISSUE TITLE
opam install eliom fails with ocaml 4.02.3 system compiler

### ISSUE THREAD

**Issue by edwintorok** [ocaml/opam-repository#6012]
```
The following dependencies couldn't be met:
  - eliom -> camlp4 <= 4.02+6
  - eliom -> js_of_ocaml < 2.0
Your request can't be satisfied:
  - camlp4<=4.02+6 is not available because your system doesn't comply with !preinstalled & ocaml-version >= "4.02" & ocaml-version < "4.03".
  - js_of_ocaml<2.0 is not available because your system doesn't comply with ocaml-version <= "4.01.0".
No solution found, exiting
```

The installable camlp4 version is `4.02+system`, could the constraint be updated to allow either `<= 4.02+6` or `= 4.02+system`?
Constraint was introduced here: https://github.com/ocaml/opam-repository/commit/8ba252ef327d0d2f87fe69078f85991c52b7f433

To reproduce you can try any of these:
```
sudo docker run ocaml/opam:debian-9_ocaml-4.02.3 opam depext -i -u eliom
sudo docker run ocaml/opam:alpine opam depext -i -u eliom
```

**Comment by phongphan** [comment]
It's probably not gonna work due to ocsigen/eliom#277.

I encountered this too. And I have to switch away from `+system` as a workaround.
`opam switch 4.02.3`
then
`opam install eliom`

works for me.

**Comment by samoht** [comment]
Could you report that issue upstream?

```
$ opam info -f bug-reports eliom
https://github.com/ocsigen/eliom/issues/
```

Thanks!

**Comment by aBathologist** [comment]
For future seekers: on https://github.com/ocsigen/eliom/issues/324 @vasilisp explains that, for the time being, we either need to switch to 4.02.3 (as @phongphan advises) or, if we need 4.03.0, we must use Eliom `master`.
