### ISSUE TITLE
conf-pkg-config needs to be fixed for archlinux

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#6136]

**Comment by fxfactorial** [comment]
Its broken for ubuntu as well, I suspect for all Linuxes. 

What is the point of this package anyway? its effectively a no op

`available: [os = "darwin" | os = "freebsd" | os = "netbsd" | os = "openbsd" | os = "linux"]`

Also could there have been some kind of communication to tell `opam` users about this new proliferation of `conf-something` packages? Maybe `opam` can have some kind of MOTD.

**Comment by UnixJunkie** [comment]
Did you try this:

    opam depext conf-pkg-config
    opam install conf-pkg-config

It will be difficult to help you if you don't show what you tried and the results you got.

**Comment by fxfactorial** [comment]
@UnixJunkie Sorry I should have mentioned that yes i did try both. The problem went away only after doing a local pin.

**Comment by UnixJunkie** [comment]
https://github.com/ocaml/opam-repository/pull/6145
