### ISSUE TITLE
Recommended way to run a shell script in the opam file

### ISSUE THREAD

**Issue by thranur** [ocaml/opam-repository#6165]
In my opam package, I'm running a shell script by calling it directly: 

```
build: [ "./my_script.sh ]
```

It did work in some tests and local installations, but now while testing for OCaml 4.03+beta2, I tried path-pinning it locally and then installing it, but installation failed with:

```
[ERROR] The compilation of my-package failed at "./my_script.sh".
```

The error log mentions `command      ./my_script.sh` and `exit-code    127`. I couldn't reproduce the exact configuration I used before, but it did work when I needed it before.

After seeing how other people do in their packages, I noticed several who do it like this:

```
build: [ "sh" "./my_script.sh" ]
```

And if I do it like so, my script also works (without changing anything else).

I'd like to confirm if that is the preferred way (although several packages still use the "direct script" way and it seems to work), or if there are specific reasons to choose one over another.

**Comment by hannesm** [comment]
related is https://github.com/AltGr/Camelus/issues/6 - I clearly prefer `["sh" "-exc" "my_script.sh"]` (and run http://www.shellcheck.net/ on it before) :)

**Comment by thranur** [comment]
I found out that the error is that, in my current setting, the `.sh` file does not have execute permission.

Therefore, I'd consider that a more robust setting would be to not use `-c`, because it also requires the script to have execute permission. I agree about the `-ex` though, eventually even `-eux`.

Otherwise, should my script always have execute permission? I'm thinking about using it in other platforms and filesystems, such as Cygwin/NTFS, where the permissions are not necessarily preserved, and therefore might be lost during conversions.

Currently, I'll try `["sh" "-ex" "./my_script.sh]` (`./` to avoid having a similarly-named script somewhere else in the PATH), but if anyone has a reason why it shouldn't be used, I'd be interested.

**Comment by dbuenzli** [comment]
This seems to be an opam documentation issue I opened https://github.com/ocaml/opam/issues/2983 to track this so I'm closing this.
