### ISSUE TITLE
dbm.1.0 fails to make in mac osx

### ISSUE THREAD

**Issue by joaozeni** [ocaml/opam-repository#6177]
Hello,
I'm installing dbm on a mac, but it fails on make all, here is what i get when i try just opam install:

```
The following actions will be performed:
  ∗  install dbm 1.0

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[dbm] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[dbm: mkdir] Command started
+ mkdir "-p" "/Users/jgzeni/.opam/4.02.1/lib/dbm" (CWD=/Users/jgzeni/.opam/4.02.1/build/dbm.1.0)
[dbm: ./configure] Command started
+ ./configure  (CWD=/Users/jgzeni/.opam/4.02.1/build/dbm.1.0)
- Configuring for OCaml version 4.02.1
-
- Configuration for the "camldbm" library:
-         headers found in ......... /usr/include
-         options for compiling ....
-         options for linking ......
-
- Configuration successful
-
- hasgot.c:3:10: warning: implicit declaration of function 'dbm_open' is invalid in C99 [-Wimplicit-function-declaration]
-   (void) dbm_open("foo", 0, 0);
-          ^
- 1 warning generated.
[dbm: make all] Command started
+ make "all" (CWD=/Users/jgzeni/.opam/4.02.1/build/dbm.1.0)
- ocamlc -c -ccopt "" -ccopt "" cldbm.c
- cldbm.c:47:24: error: unknown type name 'DBM'
- static value alloc_dbm(DBM * db)
-                        ^
- cldbm.c:50:3: error: expected expression
-   DBM_val(res) = db;
-   ^
- cldbm.c:45:29: note: expanded from macro 'DBM_val'
- #define DBM_val(v) *((DBM **) &Field(v, 0))
-                             ^
- cldbm.c:50:3: error: use of undeclared identifier 'DBM'
- cldbm.c:45:23: note: expanded from macro 'DBM_val'
- #define DBM_val(v) *((DBM **) &Field(v, 0))
-                       ^
- cldbm.c:54:8: error: unknown type name 'DBM'
- static DBM * extract_dbm(value vdb)
-        ^
- cldbm.c:56:7: error: expected expression
-   if (DBM_val(vdb) == NULL) raise_dbm("DBM has been closed");
-       ^
- cldbm.c:45:29: note: expanded from macro 'DBM_val'
- #define DBM_val(v) *((DBM **) &Field(v, 0))
-                             ^
- cldbm.c:56:7: error: use of undeclared identifier 'DBM'
- cldbm.c:45:23: note: expanded from macro 'DBM_val'
- #define DBM_val(v) *((DBM **) &Field(v, 0))
-                       ^
- cldbm.c:57:10: error: expected expression
-   return DBM_val(vdb);
-          ^
- cldbm.c:45:29: note: expanded from macro 'DBM_val'
- #define DBM_val(v) *((DBM **) &Field(v, 0))
-                             ^
- cldbm.c:57:10: error: use of undeclared identifier 'DBM'
- cldbm.c:45:23: note: expanded from macro 'DBM_val'
- #define DBM_val(v) *((DBM **) &Field(v, 0))
-                       ^
- cldbm.c:66:3: error: use of undeclared identifier 'DBM'
-   DBM *db = dbm_open(file,flags,mode);
-   ^
- cldbm.c:66:8: error: use of undeclared identifier 'db'
-   DBM *db = dbm_open(file,flags,mode);
-        ^
- cldbm.c:66:13: warning: implicit declaration of function 'dbm_open' is invalid in C99 [-Wimplicit-function-declaration]
-   DBM *db = dbm_open(file,flags,mode);
-             ^
- cldbm.c:68:7: error: use of undeclared identifier 'db'
-   if (db == NULL)
-       ^
- cldbm.c:71:23: error: use of undeclared identifier 'db'
-     return (alloc_dbm(db));
-                       ^
- cldbm.c:77:3: warning: implicit declaration of function 'dbm_close' is invalid in C99 [-Wimplicit-function-declaration]
-   dbm_close(extract_dbm(vdb));
-   ^
- cldbm.c:78:3: error: expected expression
-   DBM_val(vdb) = NULL;
-   ^
- cldbm.c:45:29: note: expanded from macro 'DBM_val'
- #define DBM_val(v) *((DBM **) &Field(v, 0))
-                             ^
- cldbm.c:78:3: error: use of undeclared identifier 'DBM'
- cldbm.c:45:23: note: expanded from macro 'DBM_val'
- #define DBM_val(v) *((DBM **) &Field(v, 0))
-                       ^
- cldbm.c:88:12: warning: implicit declaration of function 'dbm_fetch' is invalid in C99 [-Wimplicit-function-declaration]
-   answer = dbm_fetch(extract_dbm(vdb), key);
-            ^
- cldbm.c:106:10: warning: implicit declaration of function 'dbm_store' is invalid in C99 [-Wimplicit-function-declaration]
-   switch(dbm_store(extract_dbm(vdb), key, content, DBM_INSERT)) {
-          ^
- cldbm.c:106:52: error: use of undeclared identifier 'DBM_INSERT'
-   switch(dbm_store(extract_dbm(vdb), key, content, DBM_INSERT)) {
-                                                    ^
- cldbm.c:125:52: error: use of undeclared identifier 'DBM_REPLACE'
-   switch(dbm_store(extract_dbm(vdb), key, content, DBM_REPLACE)) {
-                                                    ^
- cldbm.c:139:7: warning: implicit declaration of function 'dbm_delete' is invalid in C99 [-Wimplicit-function-declaration]
-   if (dbm_delete(extract_dbm(vdb), key) < 0)
-       ^
- cldbm.c:146:15: warning: implicit declaration of function 'dbm_firstkey' is invalid in C99 [-Wimplicit-function-declaration]
-   datum key = dbm_firstkey(extract_dbm(vdb));
-               ^
- cldbm.c:158:15: warning: implicit declaration of function 'dbm_nextkey' is invalid in C99 [-Wimplicit-function-declaration]
-   datum key = dbm_nextkey(extract_dbm(vdb));
-               ^
- 7 warnings and 16 errors generated.
- make: *** [cldbm.o] Error 2
[ERROR] The compilation of dbm failed at "make all".

#=== ERROR while installing dbm.1.0 ===========================================#
# opam-version 1.2.2
# os           darwin
# command      make all
# path         /Users/jgzeni/.opam/4.02.1/build/dbm.1.0
# compiler     4.02.1
# exit-code    2
# env-file     /Users/jgzeni/.opam/4.02.1/build/dbm.1.0/dbm-19794-865888.env
# stdout-file  /Users/jgzeni/.opam/4.02.1/build/dbm.1.0/dbm-19794-865888.out
# stderr-file  /Users/jgzeni/.opam/4.02.1/build/dbm.1.0/dbm-19794-865888.err
### stdout ###
# ocamlc -c -ccopt "" -ccopt "" cldbm.c
### stderr ###
# cldbm.c:139:7: warning: implicit declaration of function 'dbm_delete' is invalid in C99 [-Wimplicit-function-declaration]
# [...]
#       ^
# cldbm.c:146:15: warning: implicit declaration of function 'dbm_firstkey' is invalid in C99 [-Wimplicit-function-declaration]
#   datum key = dbm_firstkey(extract_dbm(vdb));
#               ^
# cldbm.c:158:15: warning: implicit declaration of function 'dbm_nextkey' is invalid in C99 [-Wimplicit-function-declaration]
#   datum key = dbm_nextkey(extract_dbm(vdb));
#               ^
# 7 warnings and 16 errors generated.
# make: *** [cldbm.o] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install dbm 1.0
No changes have been performed

=-=- dbm.1.0 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
=> This package relies on external (system) dependencies that may be missing. `opam depext dbm.1.0' may help you find the correct installation for your system.
'opam install -v dbm' failed.
```

I tried to execute both the command and make but none worked, i got the same error.
Also my Makefile.config seam to be the problem, it like this, even after configure:
OCAML_STDLIB=/Users/jgzeni/.opam/4.02.1/lib/ocaml
DBM_INCLUDES=
DBM_LINK=
DBM_DEFINES=

**Comment by joaozeni** [comment]
Well, i found the origin of the problem.
The include in the cldbm.c file is relative, #include <ndbm.h>.
When i change to the absolute path, #include "/usr/include/ndbm.h", it works.
Any ideas why is this happening?

**Comment by dsheets** [comment]
What version of OS X? What version of Xcode? Have you installed the command-line tools?

**Comment by joaozeni** [comment]
I'm in mac 10.11, xcode 7.1 and i have installed the command line tools.

**Comment by dsheets** [comment]
What says `clang -x c -v -E /dev/null`?

**Comment by joaozeni** [comment]
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -main-file-name null -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 264.3.101 -v -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0 -fdebug-compilation-dir /Users/jgzeni/.opam/4.02.1/build/dbm.1.0 -ferror-limit 19 -fmessage-length 272 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c /dev/null
clang -cc1 version 7.3.0 (clang-703.0.29) default target x86_64-apple-darwin15.0.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 329 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2

**Comment by dsheets** [comment]
Do you use MacPorts or homebrew? Do you have any dbm packages installed through that package manager?

**Comment by joaozeni** [comment]
Homebrew and yes i installed dbm through it.

**Comment by dsheets** [comment]
OS X ships `ndbm.h` (of some variety). It sounds like the version of dbm that you have installed via homebrew is insufficient (in some way).

**Comment by joaozeni** [comment]
But as i said, it is compiling when i pass the full path to ndbm.h. And if try go to the page and do a make install after compiling it works fine. If i could pass something like a -I command on the moment of the compilation it would work.

**Comment by dsheets** [comment]
`/usr/include/ndbm.h` is distributed with OS X. The version of `ndbm.h` distributed by homebrew is not compatible but takes precedence. Do you need the homebrew installation of `dbm`? If not, try uninstalling it and the OS X version will probably work. Otherwise, I think the error is correct -- the primary version installed on your system is not compatible with the bindings you are attempting to use and other dbm consumers may not be compatible with each other.

**Comment by joaozeni** [comment]
Well i solved it.
I deleted the homwbrew version of dbm, got the command line tools version, that was in /usr/include, and copied to the /usr/local/include. I guess it was problem in the presedence.
Thank you for the help.

**Comment by dsheets** [comment]
I'm glad it's working for you now. You shouldn't need a copy in `/usr/local/include`, though.

**Comment by joaozeni** [comment]
I just deleted /usr/local/include and worked. I guess that homebrew don't removed it and when i deleted it i thought a cp would be faster.
