### ISSUE TITLE
Camlp4 does not install well on Cygwin

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam-repository#6249]
On Appveyor, using Cygwin, `opam` does not install `camlp4` well — the `camlp4o` executable is not found.
See https://ci.appveyor.com/project/Chris00/ocaml-mindstorm/build/1.0.148#L2287

The [install script](https://github.com/Chris00/ocaml-mindstorm/blob/master/appveyor_install.cmd) is straightforward and used to work in the past.

**Comment by dbuenzli** [comment]
Don't know what to do with this. Maybe @dra27 has something to say ?

**Comment by dbuenzli** [comment]
Well rereading this, it seems to be a packaging issue. Ping @diml the maintainer of the `camlp4` package. @Chris00 can you meanwhile confirm that you are still seing the problem ?

**Comment by Chris00** [comment]
I don't because I moved away from camlp4 — it is no longer a dependency for this package.

**Comment by dbuenzli** [comment]
Without someone to test this and lack of CI testing, if nobody objects I move on to close this. This can certainly be revisited once we'll get proper `opam` windows support and CI testing.
