### ISSUE TITLE
What are the best practices to write conf-* packages regarding non-standard installation paths?

### ISSUE THREAD

**Issue by michipili** [ocaml/opam-repository#6271]
I want to install an opam package relying on 3rd-party libraries such as **gmp**. My system is OS-X with MacPorts, meaning that many 3rd-party software is available under the prefix `/opt/local` or any other prefix I would have seen fit.

Setting `CFLAGS` to `-I/opt/local/include` allows to install **conf-gmp** (the opam package) but installing **zarith** then fails. This is obviously because of the opam file setting this  variable:

```
build: [
  ["./configure"] { os != "openbsd" & os != "freebsd" & os != "darwin"}
  ["env" "LDFLAGS=-L/usr/local/lib" "CFLAGS=-I/usr/local/include" "./configure"] { os = "openbsd" | os = "freebsd" | os = "darwin"}
  [make]
]
```

(From `packages/zarith/zarith.1.4.1/opam`).

I think setting the variables `CFLAGS` and the related ones in the opam file, is broken, because it makes dubious assumption about the host system, and also it breaks all the work that people writing `configure` scripts do to prepare a flexible system.

AFAICT, and while I am not a huge fan of this, environment variables are the preferred way to pass these configuration details to `./configure` scripts, at least, GNU Autoconf generated ones, so we should probably avoid to tinker with them in _opam_ files. Maybe we could also use one of these neat opam variable as a recommended way to convey this information. What are our thoughts on this question?

**Comment by michipili** [comment]
Again, what would be the correct way to fix this, so that I can install **zarith**? I see  two possibilities that can be immediately applied:

1. One remove the `{ os = "openbsd" | os = "freebsd" | os = "darwin"}` specific line and let everyone who needs it pass the required parameters 
2. Add a further similar line that tries to match my system

I would prefer the first solution, but since that line os-specific line has been-commited, I would like to know why it has been committed. I do not think that the second solution is well maintainable. Sometimes, a bit of system-specific tweaking is required, but using this tweaking for software that uses (de facto) standard tools for its installation is a red herring to me.

**Comment by michipili** [comment]
The solution I proposed still has problems (#6780, #6775), so we need to figure out a better solution.

**Comment by michipili** [comment]
>How to detect third-party packages at compilation time


## Problem description

The **opam** community uses non-standardised heuristics to detect
third-party packages at compilation time.  An example of such
heuristic is assuming that **opam* reporting `darwin` as operating
system implies that the user is using **brew** and positioning
accordingly `CFLAGS` and `LDFLAGS` and other variables used by
*configure* scripts to locate their resources.


These heuristics have the following limitations:

1. They are inherently wrong, meaning that they are broken or hard to
   maintain on several platforms such as the various BSDs or other
   *darwin*-based configurations.

2. They are hard to circumvent, meaning that users affected by these
   broken heuristics have no choice but maintaining their own branch of
   the opam repository to use the mentioned software.


We want to address these issues so that:

1. Installing third party packages works “out of the box” for *all*
   users, regardless of their system.

2. It is easy to circumvent the information passed to `configure` so
   that a port maintainer can easily build OCaml software against a
   special branch of the third party software they are using.

I have started to write the **[opamconfig](https://github.com/michipili/opamconfig)** package to implement a
solution to this problem.


## We actually have two problems

To cleanly solve the problem, we need to understand it properly. Let
us pick the example of two packages I cannot install on my system,
**conf-gmp** and **zarith**.

The responsability of **conf-gmp** is to check the availability of the
**gmp** library before **zarith** can use it. Now look at how the
packages are built:

For **gmp** we have

~~~
build: [
  ["sh" "-exc" "cc -c $CFLAGS -I/usr/local/include test.c"]
]
~~~

and **zarith**

~~~
build: [
  ["./configure"] { os != "openbsd" & os != "freebsd" & os != "darwin"}
  ["env" "LDFLAGS=-L/usr/local/lib" "CFLAGS=-I/usr/local/include" "./configure"] { os = "openbsd" | os = "freebsd" | os = "darwin"}
  [make]
]
~~~

The problem concealed in these build instructions is that the
**conf-gmp** package checks that **gmp** can be used but leave as
responsability for packages relying on it, like **zarith** does, to
localise themselves the **gmp** package.  Actually, the **conf-gmp**
package should save the result of its work, so that the build
instructions for **zarith** are *os*-independant:

~~~
build: [
  ["env" "LDFLAGS=%{conf-gmp:ldflags}%" "CFLAGS=%{conf-gmp:cflags}%" "./configure"]
  [make]
]
~~~

A package relying on various third-party packages would easily use
them as:

~~~
build: [
  ["env" "LDFLAGS=%{conf-A:ldflags}% %{conf-B:ldflags}%" …]
  [make]
]
~~~

Now we can claim the first “best practice” that we want to discuss in
this ticket:

> OPAM packages relying on third-party software should delegate the
> task of detecting the presence and the relevant configuration
> parameters (e.g. as used by ./configure scripts) to specialised
> `conf-*` packages.
>
> In particular, non-`conf-*` packages using the *os* variable to
> specialise their build-instructions should trigger a linter warning
> or even an error.

Now, how to write `conf-*` packages so that they appropriately save
their configuration parameters?


## Using the os variable

Relying on the *os* variable to detect configuration parameters is the
current state of the affairs in our repository.  This does not work
well, see introduction.

## Refinement of the os variable

*This strategy does not work much better than using the os variable,
 the reader trusting this affirmation can jump to the next section.*

The most simple strategy to implement is to let the **opamconfig**
package refine the information conveyed by the *os* variable. For
instance the **opamconfig** would define a *platform* variable with
values like

  - darwin-macports
  - darwin-brew
  - darwin-fink
  - darwin-pkgsrc
  - freebsd-ports
  - freebsd-pkgsrc
  - …

and a special value, say *customised*, indicating that the user wants
to supply configuration variables to *configure* manually.

With this strategy, the build recipes for a the *conf-gmp* would look
like

    build: [
      ["sh" "-exc" "cc -c $CFLAGS -I/opt/local/include test.c"] { opamconfig:platform = "darwin-macports" }
      ["sh" "-exc" "cc -c $CFLAGS -I/usr/local/include test.c"] { opamconfig:platform != "darwin-macports" }
    ]

While this approach would be very near to the approach we currently
see in opam packages, it brings the following dilemma: If we choose to
be terce and to not repeat ourselves, then we need to deal with
complex, illegible and untestable boolean expressions to match the
right configuration for the *configure* script.  If we choose to be
very clear, then we need to have one build line per supported
platform, which looks a bit awkward and seems to work against the idea
of a generic configuration procedure: we do not take advantage of the
work of package developers sticking to “standard” packaging methods,
as we specialise build procedure for each platform.

**Summary** While a simple platform-based approach could work, it does
not seem desirable as it leads add a lot of information to build
recipes, most of which seems to be rahter easily predictable.


## Semi-automatic strategy

Headers for a C library *PACKAGE* are usually installed in a path of the form

    ${PREFIX}/include/${PACKAGEDIR}

where *PREFIX* is typically one of */usr/local* or */opt/local* and
*PACKAGEDIR* is an optional path component used to prevent pathname
collision.  To the best of my knowledge most systems never use
*PACKAGEDIR* and only **brew** makes a consistant use of it. Other
software artifacts like relocatable libraries are stored in paths
using a similar naming scheme.

Writing a `conf-*` package would require to implement the following
functionalitites:

1. Prepare a list of *PREFIX* and *PACKAGEDIR* values where the
   *PACKAGE* should be looked up.

2. Write a small program testing *PACKAGE* artifacts can be found
   with a given *PACKAGE* and *PACKAGEDIR*.

3. When software artifacts have been found, save the corresponding parameters
   in the `conf-*` package **opam** configuration.

4. When parameters used by the *configure* scripts are set by the
   environment when installing the `conf-*` package, these should be
   used (and stored) instead of using automatically detected
   parameters.  This provides the user with an easy way to circumvent
   auto-detection.

In my opinion, it makes sense to factorise 1, 3 and 4 in a software
package, and I have changed **opamconfig** to precisely do that.
Using this new version of **opamconfig** allows to write the build
rules for **conf-gmp** as follows:

    build: [
      ["opamconfig" "-f" "./conf-gmp.config" "sh" "-exc" "cc -c ${CFLAGS} test.c"]
    ]

Upon sucesful installation of the **conf-gmp** package, the following
configuration paramaters have been saved by **opamconfig** in the
**opam** configuration file for **conf-gmp**:

    % cat /opt/opam/4.02.3/lib/conf-gmp/opam.config
    cflags: "-I/opt/local/include/"
    cppflags: "-I/opt/local/include/"
    ldflags: "-L/opt/local/lib/"
    ocamlflags: "-ccopt -I/opt/local/include/ -cclib -L/opt/local/lib/"

These parameters can be used in packages depending on **conf-gmp** to
accurately locate that library, instead of trying to reproduce the
strategy used by **conf-gmp**

The **opamconfig** uses the following list of *PREFIX* values, as
defined by the *prefixdb* function in the code:

 - If the environment defines a variable *OPAMCONFIG_PREFIXDB* then
   its value is interpreted as a colon separated list of interesting
   *PREFIX* values.

- Otherwise an hard-coded list is used, that list is determined at the
  time where **opamconfig** is installed by looking for popular
  package managers in the path and deducing the corresponding *PREFIX*
  value.  See `configure.ac` and the *prefixdb__heuristic* function
  in `opamconfig.sh` for details.

If we want to use some experimental build of **gmp** we can pass its
installation *PREFIX* to **opamconfig** when we install **conf-gmp**
as:

    env OPAMCONFIG_PREFIXDB='/opt/gmp.master' opam reinstall conf-gmp

Assuming the build instructions using **opamconfig** as demonstrated
above, this would result in the following **opam** configuration file
for **conf-gmp**:

    % cat /opt/opam/4.02.3/lib/conf-gmp/opam.config
    cflags: "-I/opt/gmp-unstable/include/"
    cppflags: "-I/opt/gmp-unstable/include/"
    ldflags: "-L/opt/gmp-unstable/lib/"
    ocamlflags: "-ccopt -I/opt/gmp-unstable/include/ -cclib -L/opt/gmp-unstable/lib/"


Adopting the recommendation

> OPAM packages relying on third-party software should delegate the
> task of detecting the presence and the relevant configuration
> parameters (e.g. as used by ./configure scripts) to specialised
> `conf-*` packages.
>
> In particular, non-`conf-*` packages using the *os* variable to
> specialise their build-instructions should trigger a linter warning
> or even an error.

and using **opamconfig** as in the example above could help us to
provide **opam** users with a consistant, robust and flexible
experience when dealing with third-party packages.

It is possible to test **opamconfig** by pinning it to its [repository](https://github.com/michipili/opamconfig) version.

**Comment by michipili** [comment]
CC @avsm @dsheets @lefessan Because you were in #6703.
CC eeerh I would like to invite the authors of packages conf-gmp.1 faad.0.3.3 fdkaac.0.2.1 flac.0.1.2 ladspa.0.1.5 lame.0.3.3 lo.0.1.1 mysql.1.1.3 mysql.1.2.0 opus.0.1.1 schroedinger.0.1.1 speex.0.2.1 ssl.0.5.2 zarith.1.3 zarith.1.4 zarith.1.4.1 but there is no easy way to find their GitHub handles.

**Comment by michipili** [comment]
Invitation list

If you have some time, please add the handles of the following packages to the conversation. Use check-box to indicate that you processed to the invitation.

 - [ ] conf-gmp.1
 - [ ] conf-gmp.1
 - [ ] faad.0.3.3
 - [ ] faad.0.3.3
 - [ ] fdkaac.0.2.1
 - [ ] fdkaac.0.2.1
 - [ ] flac.0.1.2
 - [ ] flac.0.1.2
 - [ ] ladspa.0.1.5
 - [ ] ladspa.0.1.5
 - [ ] lame.0.3.3
 - [ ] lame.0.3.3
 - [ ] lo.0.1.1
 - [ ] lo.0.1.1
 - [ ] mysql.1.1.3
 - [ ] mysql.1.1.3
 - [ ] mysql.1.2.0
 - [ ] mysql.1.2.0
 - [ ] opus.0.1.1
 - [ ] opus.0.1.1
 - [ ] schroedinger.0.1.1
 - [ ] schroedinger.0.1.1
 - [ ] speex.0.2.1
 - [ ] speex.0.2.1
 - [ ] ssl.0.5.2
 - [ ] ssl.0.5.2
 - [ ] zarith.1.3
 - [ ] zarith.1.3
 - [ ] zarith.1.4
 - [ ] zarith.1.4
 - [ ] zarith.1.4.1
 - [ ] zarith.1.4.1

**Comment by dsheets** [comment]
@michipili this makes sense and I'm glad to see that you now use package managers in `PATH` to map to prefix directories. How are per-package prefixes handled?

I have a hard time understanding the behavior of the present version of `opamconfig`. Does it require `bmake` and `autoconf` to function? I'm reluctant to make `conf-*` packages dependent on those packages and a large shell script.

I really think you have a solid design and a good approach and I am completely convinced we need something like this. I wonder if some kind of "validation" action for opam packages would also be useful here so that `conf-*` packages that detect system packages can be re-validated for workingness at some later time without uninstalling/reinstalling. Your `opamconfig` system could then re-read its previous configuration and check that it still works.

I'm excited that you are working on this functionality and have a good opam integration strategy. I'm a bit concerned about the maintainability and dependencies of the `opamconfig` tool itself but I understand that it's an early draft.

Thanks for your hard work!

**Comment by michipili** [comment]
Thank you for your feedback David, it is much appreciated. It is definitely desirable that a package like **opamconfig** can be installed without any dependancy, so I will work on this. It would also be desirable to make it easier for developers or reviewers to have a design in the shell-script that allows an easy testing of the various functions. We also need to enrich the list of package managers the **opamconfig** package is aware of. I will take some time to prepare a roadmap addressing these issues and also enumerating `conf-*` packages needing attention. I will post here again when the roadmap has made some progress.

My approach to shell programming is to only process “UNIX data” at the shell level, esp. in variables (file names, pids, etc.) and to use programs or functions to perform complex treatments. I have written a short blog entry about this: http://michipili.github.io/shell/2015/04/12/shell-filter-programming.html    I am maintaining a rather large collection of shell scripts (moving to OCaml using [Rashell](https://github.com/michipili/rashell)) and write shell scripts “compilers” and based on this experience, it seems that the approach works very well.

**Comment by michipili** [comment]
> How are per-package prefixes handled?

To stay with the example of C header files, they are looked up in directories looking like `${PREFIX}/include/${PACKAGEDIR}` where *PACKAGEDIR* is left empty on many systems. For systems using a non-empty *PACKAGEDIR* the `-d` option must be used to present a list of candidate *PACKAGEDIR*: ( See https://github.com/michipili/opamconfig/blob/master/opamconfig.sh#L260)

So the build instruction for `conf-gmp` would more likely be:

~~~
build: [
  ["opamconfig" "-d" "gmp:" "-f" "./conf-gmp.config" "sh" "-exc" "cc -c ${CFLAGS} test.c"]
]
~~~

The colon is because the argument to `-d` is a colon-separated list of possible *PACKAGEDIR*s.  From time to time, distributions adopt names diverging from the upstream (e.g. to avoid name collisions) and we could imagine have several words in this list in some cases.

**Comment by michipili** [comment]
I prepared a list of tickets for each pending task and assigned each of them to the milestone [v0.2.0](https://github.com/michipili/opamconfig/milestone/1).

**Comment by michipili** [comment]
Hej @avsm @dsheets @lefessan @yallop !

I prepared a new *draft* of **[opamconfig](https://github.com/michipili/opamconfig)**. I addressed the points raised by David above, and provided a portable, ad-hoc, installation procedure without dependencies.

Those who wants to study or test it need *autoconf* (see https://github.com/michipili/opamconfig#studying-opamconfig-code) as I did not prepare a proper opam package for this  new version yet.

Also, I extensively reworked the documentation (README).

I'm looking forward to read your comments and questions!

**Comment by avsm** [comment]
Your continued iterations on this are hugely appreciated, @michipili! Will read shortly in detail and digest...

**Comment by ivg** [comment]
Oh, I somehow missed this discussion, looks like that I need to revisit my mail filters. We actually used the same approach in our conf-packages. Indeed, we made `conf-packages` responsible for estimating all possible flags, so that during opam installation we're trying not to rely on `pkg-config` or other packages.   In real life, it is not always true, for example, our `conf-llvm` actually defines two flags: `version` and `config`, the latter corresponds to a path to the `llvm-config` too, that it used by our configuration scripts to query for flags. In the ideal world, this should be done by a conf-package, but we still want to be installable on a systems without opam (apt-get, nix, etc), so we don't move to much configuration logic away from our `./configure` script.

**Comment by michipili** [comment]
@ivg Thank you for your feedback. Having two different persons trying to solve the same problem coming up with essentially the same solution and seeing it as viable is an encouraging hint! :)

**Comment by dbuenzli** [comment]
In https://github.com/ocaml/opam-repository/issues/3093#issuecomment-312929998 @ygrek suggests to simply leave this problem to the host system.

I suspect we may want to revisit all that once opam v2 becomes mainstream.

**Comment by dbuenzli** [comment]
To answer the original question. It seems the best practice is to do nothing and let end-users setup their `C_INCLUDE_PATH` and `LIBRARY_PATH` correctly if they install to non-standard locations. See the resolution in https://github.com/ocaml/opam-repository/issues/3093#issuecomment-327731293.

I hope this answers the question so I'm closing this. Feel free to reopen if you disagree.
