### ISSUE TITLE
Next: system is the most recent compiler 

### ISSUE THREAD

**Issue by Drup** [ocaml/opam-repository#6308]
According to the opam ordering `ocaml.system` is the most recent ocaml version. It's not very nice and really not what I expected.

**Comment by dbuenzli** [comment]
@drup can you confirm this report still makes sense  w.r.t. opam2 developments ? And doesn't this belong to the `opam` issue tracker ?

**Comment by Drup** [comment]
I decided (somewhat arbitrarily) to put all the issues related to the encoding scheme for ocaml compilers as package here, instead of the opam bug tracker. I don't think the problem has changed (it's simply due to the name @AltGr picked).

**Comment by AltGr** [comment]
`system` is no longer considered a version in opam 2, you have two different underlying packages (`ocaml-base-compiler.4.03.0` vs. `ocaml-system.4.03.0), and the wrapper `ocaml` package will be versionned as e.g. `4.03.0` (to allow `depends: "ocaml" { >= "4.03.0" }`). So this is solved.
