### ISSUE TITLE
Next: "last" compiler

### ISSUE THREAD

**Issue by Drup** [ocaml/opam-repository#6309]
Apparently, I can do that:

```
% opam switch install last --empty
% opam install ocaml.4.02.3
(one ocaml release later)
% opam install ocaml.4.03.0
```

However, I cannot do that:

```
% opam switch install 4.02.3
(one ocaml release later)
% opam install ocaml.4.03.0
```

It might be good to provide directly a "last" switch. :)
(`opam upgrade` works too, but https://github.com/ocaml/opam-repository/issues/6308)

**Comment by dbuenzli** [comment]
@drup can you confirm this report still makes sense  w.r.t. opam2 developments ?

**Comment by Drup** [comment]
Not sure. @AltGr are packages marked as compiler properly upgrade when asked explicitly, now ? Or at least fails with a decent error message ?

**Comment by AltGr** [comment]
You won't be able to rename your switch (ocaml/opam#2609), but yes, you can do:

    opam install ocaml.4.03.0 --unlock-base

(and if you don't specify the option, the conflict message will advertise it to you)
