### ISSUE TITLE
sha.1.9 fails to install

### ISSUE THREAD

**Issue by HenkPoley** [ocaml/opam-repository#6343]
Complains it cannot apply 'freebsd.patch' on this Ubuntu 14.04 system. Which seemingly makes sense. Though it could have something to do with not running the Linux kernel, but 'Windows Subsystem for Linux'.

sha.1.8 installs fine.

**Comment by dsheets** [comment]
It is probably a WSL issue. To be honest, I am amazed that you are running `opam` on WSL. I tried with 14316 but ran into Microsoft/BashOnWindows#104. What build are you on?

`freebsd.patch` is a file in the repository which is unconditionally applied and provides an `#ifdef` for FreeBSD's `endian.h` -- it should always exist.

Running an `strace` on the appropriate process and looking for its attempt to access `files/freebsd.patch` in the `packages/sha/sha.1.9` directory may be interesting.

This is almost certainly a WSL issue as I can build fine on Debian Jessie, Ubuntu 14.10, and OS X 10.11.

**Comment by HenkPoley** [comment]
Build 14332. If I run it with `OPAMVERBOSE=5 opam install sha.1.9` it tells me there is still a file move/rename problem.

<pre><code>- patching file bitfn.h
- patch: **** Can't rename file ./bitfn.h.oD2WyI4 to bitfn.h : Function not implemented</code></pre>

**Comment by dsheets** [comment]
Interesting. Perhaps `renameat` or `renameat2` is missing? `strace` output?

I'm waiting for my Insider Fast Track to get the drop from the mothership right now...

**Comment by HenkPoley** [comment]
Attached is output of: `cd ~/.opam/system/build/sha.1.9; strace -o patch.sha.1.9.bitfn.h.strace patch -p1 -i freebsd.patch 2> patch.sha.1.9.bitfn.h.err > patch.sha.1.9.bitfn.h.out`

[patch.sha.1.9.bitfn.h.err.txt](https://github.com/ocaml/opam-repository/files/240998/patch.sha.1.9.bitfn.h.err.txt)
[patch.sha.1.9.bitfn.h.out.txt](https://github.com/ocaml/opam-repository/files/241000/patch.sha.1.9.bitfn.h.out.txt)
[patch.sha.1.9.bitfn.h.strace.txt](https://github.com/ocaml/opam-repository/files/240999/patch.sha.1.9.bitfn.h.strace.txt)
