### ISSUE TITLE
install lablgtk 2.18.4 failed on Mac OS

### ISSUE THREAD

**Issue by syndory** [ocaml/opam-repository#6344]
Hi,
i have installed gtk+ via homebrew:    

    brew install gtk+

also i add PKG_CONFIG_PATH in ~/.zshrc:
    
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/x11/lib/pkgconfig

pkg-config works fine:

    $ pkg-config --libs libevent                                                                                             
    -L/usr/local/Cellar/libevent/2.0.22/lib -levent

but still cannot install lablgtk.

my env:
gtk+ version: 2.24.30
opam version: 1.2.2
homebrew version: 0.9.9
OS version: 10.11.4

please help me,
thx

**Comment by dbuenzli** [comment]
> please help me,

If you don't tell us what goes wrong it's going to be hard. E.g. provide us the output of `opam install lablgtk --verbose`

**Comment by syndory** [comment]
oh sorry, i forgot it.

i've found where the key is. 
i'm in China, so i install with proxychains:

    $ proxychains4 opam install lablgtk

it always says:
    
=-=- lablgtk.2.18.4 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
=> This package requires gtk+ 2.0 development packages installed on your system
=> To solve pkg-config issues, you may need to do
   'export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig' (macports)
   or 'export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig' (homebrew)
   and retry
    
after remove the proxychains4, all things go correctly.
you can close this issue, 
thank you : )

**Comment by syndory** [comment]
by the way, 

    $ proxychains opam install ocamlnet

works fine while 

    $ proxychains4 opam install lablgtk

always ask me to set the PKG_CONFIG_PATH variable.
