### ISSUE TITLE
RFC: `<package>.config` usage

### ISSUE THREAD

**Issue by ivg** [ocaml/opam-repository#6345]
This is more a question, rather than an issue report. 

I didn't manage to find any documentation about this file. So far I managed to infer from the source code, that I can define a package variables of `bool` or `string` type there, e.g.,

```
path: "/usr/bin/test"
used: true
```

One thing, that is left, is how to commit this file to the `opam-repository`. Should I just create an
`$opam/packages/$NAME/$NAME.$VERSION/$NAME.config` file? At least, this is what I inferred from the code. But I grepped through the `opam-repository` and didn't find any example of this.

As a background, I'm thinking that some of the configuration can be moved into `conf-*` packages. For example `<library>-conf` might contain  necessary `cflags`, `lflags` in it. It looks to me, that putting this into a `<package>.config` is a nice way to do things. Would it be an abuse of the mechanism?

Btw, the opam code is a real pleasure to read :)

**Comment by dbuenzli** [comment]
> As a background, I'm thinking that some of the configuration can be moved into conf-* packages. For example <library>-conf might contain necessary cflags, lflags in it.

Not sure this is a good idea if you want your packages to be able to function in non-opam managed settings (e.g. conversion of your packages to system packages). I think it's better to try to rely on pkg-config for these things.

Other than that you may want to have a look at this proposal https://github.com/ocaml/opam/issues/2247

**Comment by ivg** [comment]
> Not sure this is a good idea if you want your packages to be able to function in non-opam managed settings (e.g. conversion of your packages to system packages). I think it's better to try to rely on pkg-config for these things.

Of course I want them to operate in both environments, so my `setup` and `configuration` scripts will first look if these variables are already set up by the `opam`, and if they not, then fallback to xxx-config, environment variables, etc.  The problem, is that it is hard to control these scripts, if you're not calling `./configure` directly, e.g., when installing via `opam`. And I want to have some explicit opam-based channel of communication between a user, and mine configuration process. For example, my package depends on LLVM library, and there is no way to specify a user intent to use a particular version of the library, using opam (currently we use environment variables to override default behavior, that is kind of ugly). So, I thought, that if a user installs particular `llvm-conf-<ver>` package, this would be a great way to communicate his intention to the package configuration.

There is another use case, that's I'm more concerned about. We have a pluggable architecture, where some plugins are just wrappers around other programs, like `objdump`, `IDA`, etc. So far, these plugins are trying to find these programs in the run time, so they actually perform some configuration work at the plugin initialization time.  It looks to me as a bad separation of concerns. Also, they maybe installed on a system, that doesn't have the tool at all, so they become a rather useless packages. Even worse, sometimes the search for a tool may take a significant amount of time, so they become not only useless, but harmful. The solution that I'm thinking about, is to add `<tool>-conf` file, that will perform the search of the tool (or possible installation via `depext`) at the configuration time, and communicate the results to a plugin via `<tool>.config` file. I'm investigating other opportunities, how it can be made with opam, and it looks like, that your proposal, if it will be accepted, may help me a lot.

**Comment by dbuenzli** [comment]
> What would be the downsides of doing what @ivg suggests?

I'm not sure system packagers are very keen of having a mirror of OPAM virtual packages for packages they are providing themselves in the first place. 

While I'm fine with the idea of centralizing depexts in a single OPAM virtual package I think it's better if packages do not depend on another package to manage their configuration. We can always add more indirections to a system but I'm not sure it's a good approach for its understandability.

Regarding `opamconfig` specifically, it seems to be using everything I have been avoiding like the plague during all these years (e.g. `autoconf`, `awk`, shell scripts, etc.) and I have a lot of doubts about its portability on windows.

**Comment by michipili** [comment]
> I'm not sure system packagers are very keen of having a mirror of OPAM virtual packages for packages they are providing themselves in the first place.

I see. In some cases (*e.g.* GNU gmp) there is several distinct OCaml libraries relying on a third party package and it makes sense to single out the detection of path parameters to this package. In cases where a package provides canonical OCaml bindings to a third library, a separate virtual package is probably redondant.

This said, my question about the downsides was more on the “ if you want your packages to be able to function in non-opam managed settings”. What are the scenarios you can think of where saving path parameters to third-party packages could interact badly with the system package manager.

**opamconfig** is just a simple shell script to help virtual packages detect paths to third-party libraries. In case these libraries provide `pkg-config` information, this mechanism could be used instead. While **awk** and the **shell** itself have their shortcomings, they are “always here” which avoid pulling a lot of dependencies for a single simple tool. Regarding windows, I am mostly ignorant of **opam** deployments on these platforms.

**Comment by ivg** [comment]
The `.config` files approach worked perfectly for me. I'm closing the issue, as I myself, do not have any more questions. Those, who are interested in the topic, can continue to #6271. 

Thanks!
