### ISSUE TITLE
Testing against +flambda

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam-repository#6380]
We should probably test against `4.03.0+flambda` even if we mark it as a non-blocking failure.

**Comment by Chris00** [comment]
That's a good idea.  I am using it at the moment and `js_of_ocaml` does not install with that compiler.

**Comment by samoht** [comment]
Closing as this

**Comment by dbuenzli** [comment]
Flambda is being tested by the new CI (and is a blocking failure).
