### ISSUE TITLE
opam install cryptokit fails

### ISSUE THREAD

**Issue by gregtatcam** [ocaml/opam-repository#656]
Fails on MAC OS 10.6.8:

opam install cryptokitThe following actions will be performed:                                                                        - install cryptokit.1.6  
1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove

=-=-= Installing cryptokit.1.6 =-=-=
Downloading http://opam.ocamlpro.com/archives/cryptokit.1.6+opam.tar.gz.
The compilation of cryptokit.1.6 failed.
Uninstalling cryptokit.1.6:
  ocamlfind remove cryptokit

==== ERROR [while installing cryptokit.1.6] ====
Internal error:
  Wrong checksum for http://opam.ocamlpro.com/archives/cryptokit.1.6+opam.tar.gz
'opam install cryptokit' failed.

**Comment by Madicke-Diadji** [comment]
I'm a new in this domain and i need to install cryptoverif for my master . Can someone help me to install it (A video tutorial).
