### ISSUE TITLE
The repository has no story for reliable ocamlfindable scripting 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-repository#6579]
It is currently not possible to write OCaml scripts that use `ocamlfind` to tap into the OPAM installed packages of the current switch. The reason is the discrepancy between system switches and non-system one. The following script: 
```
#!/usr/bin/env ocaml
#use "topfind"

let () = print_endline "Yo!"
```
works with non-system switches but not with system switches. The reason is that `topfind` is found in non-system switches as it is installed in `lib/ocaml` which is in the default include path. It is not in system switches because it is in `lib/toplevel` which is not in the include path. While there is an `~/.ocamlinit` hack setup by `opam init` (IIRC) that works for interactive toplevel, this scheme doesn't work for scripts since ocaml in script mode does (rightly) not read `.ocamlinit` files.  

Personally, as already discussed somewhere else, I still think we should kill the idea of system switches which only bring newcomer trouble (this problem shows again that system compilers are not well tested paths). In any case here are two workable solutions: 

1. From 4.01 switches on. The switch environment could setup the horrible `OCAMLPARAM` environment variable as follows: `OCAMLPARAM="_,I=$OPAMROOT/system/lib/toplevel"`
2. The switch environment could setup the `OCAMLLIB` environment variable to point to `$OPAMSWITCH/lib/ocaml`, the system install OCaml `lib` directory should then be symlinked into that directory and the ocamlfind [`preinstalled:` instruction](https://github.com/ocaml/opam-repository/blob/master/packages/ocamlfind/ocamlfind.1.6.2/opam#L9) be adjusted accordingly.

**Comment by samoht** [comment]
An other (very hackish but maybe simpler) option would be to manually copy `topfind` in `/usr/loca/lib/ocaml`.

**Comment by dbuenzli** [comment]
I suspect we'll constantly run into permission issues.
