### ISSUE TITLE
CI scripts: Do not stop at the first failure

### ISSUE THREAD

**Issue by Drup** [ocaml/opam-repository#6601]
It would be nice if the CI scripts ran all the packages before failing. It would provide more feedback (and allow for exceptional failures of some packages ...)

**Comment by dbuenzli** [comment]
Isn't that the case in the new CI ?

**Comment by dbuenzli** [comment]
@drup I still don't understand exactly what you want here could you please give more details. Also does this issue concern the `opam-repository` or is something to file against the CI system ?

**Comment by Drup** [comment]
This bug report was done before the new CI system. So yes, let's close.

**Comment by dbuenzli** [comment]
Thanks !
