### ISSUE TITLE
the package deriving is broken with OCaml 4.03.0

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#6613]
# opam switch
    4.03.0        C 4.03.0        Official 4.03.0 release
    # opam --version
    1.2.2
    # nohup opam install -v deriving

nohup.out can be found here:
https://gist.github.com/UnixJunkie/e86571930e6757314cc0dad429e91d93

**Comment by UnixJunkie** [comment]
The shorter log is


   # opam install deriving
   The following actions will be performed:
     - install deriving 0.7
   
   =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
   [deriving] Archive in cache
   
   =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
   [ERROR] The compilation of deriving failed at "make".
   Processing  1/1: [deriving: ocamlfind remove]
   #=== ERROR while installing deriving.0.7 ======================================#
   # opam-version 1.2.2
   # os           linux
   # command      make
   # path         /home/berenger/.opam/4.03.0/build/deriving.0.7
   # compiler     4.03.0
   # exit-code    2
   # env-file     /home/berenger/.opam/4.03.0/build/deriving.0.7/deriving-30913-d2c37b.env
   # stdout-file  /home/berenger/.opam/4.03.0/build/deriving.0.7/deriving-30913-d2c37b.out
   # stderr-file  /home/berenger/.opam/4.03.0/build/deriving.0.7/deriving-30913-d2c37b.err
   ### stdout ###
   # Command line: camlp4 '-I' '/home/berenger/.opam/4.03.0/lib/ocaml/camlp4' '-I' '/home/berenger/.opam/4.03.0/lib/optcomp' '-I' '/home/berenger/.opam/4.03.0/lib/ocaml/camlp4' '-I' '/home/berenger/.opam/4.03.0/lib/ocaml/camlp4' '-parser' 'o' '-parser' 'op' '-printer' 'p' 'optcomp.cma' '-parser' 'Camlp4QuotationCommon' '-parser' 'Camlp4OCamlOriginalQuotationExpander' '-parser' 'Camlp4GrammarParser' 'syntax/common/pa_deriving_common.cma' 'syntax/std/pa_deriving_std.cma' 'syntax/classes/show_class.ml' > /tmp/ocamlppf11383
   # [...]
   # Command exited with code 2.
   # + ocamlfind ocamlopt unix.cmxa -I /home/berenger/.opam/4.03.0/lib/ocamlbuild /home/berenger/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /home/berenger/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
   # File "myocamlbuild.ml", line 507, characters 43-62:
   # Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
   # Use String.uncapitalize_ascii instead.
   # File "myocamlbuild.ml", line 520, characters 51-70:
   # Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
   # Use String.uncapitalize_ascii instead.
   # Makefile:7: recipe for target 'build' failed
   ### stderr ###
   # [...]
   # File "setup.ml", line 5927, characters 31-50:
   # Warning 3: deprecated: String.uncapitalize
   # Use String.uncapitalize_ascii instead.
   # File "setup.ml", line 5928, characters 31-48:
   # Warning 3: deprecated: String.capitalize
   # Use String.capitalize_ascii instead.
   # W: Cannot find source file matching module 'pa_deriving_common' in library pa_deriving_common
   # ocamlfind: Package `wikidoc' not found
   # E: Failure("Command ''/home/berenger/.opam/4.03.0/bin/ocamlbuild' syntax/common/pa_deriving_common.cma syntax/common/pa_deriving_common.cmxa syntax/common/pa_deriving_common.a syntax/common/pa_deriving_common.cmxs syntax/std/pa_deriving_std.cma syntax/std/pa_deriving_std.cmxa syntax/std/pa_deriving_std.a syntax/std/pa_deriving_std.cmxs syntax/classes/pa_deriving_classes.cma syntax/classes/pa_deriving_classes.cmxa syntax/classes/pa_deriving_classes.a syntax/classes/pa_deriving_classes.cmxs lib/deriving.cma lib/deriving.cmxa lib/deriving.a lib/deriving.cmxs lib/deriving_num.cma lib/deriving_num.cmxa lib/deriving_num.a lib/deriving_num.cmxs -use-ocamlfind -tag debug' terminated with error code 10")
   # make: *** [build] Error 1
   
   
   
   =-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
   The following actions failed
     - install deriving 0.7
   No changes have been performed

**Comment by UnixJunkie** [comment]
Sorry for the maybe stupid question, but
are people supposed to stop using deriving and use ppx_deriving instead ?

**Comment by vasilisp** [comment]
The [Ocsigen master branch](https://github.com/ocsigen/deriving) contains a fix for 4.03. I will try to do a bugfix release ASAP.

**Comment by vasilisp** [comment]
For PPX projects, I think `ppx_deriving` and `ppx_type_conv` are the way to go, but we still need `deriving` for Camlp4 projects. Also, there is at least one `ppx_deriving` plugin that uses the runtime parts of `deriving` ([`ppx_deriving_json`](https://github.com/ocsigen/js_of_ocaml/blob/master/lib/ppx/ppx_deriving_json.cppo.ml)). So there is still some need for `deriving`

**Comment by UnixJunkie** [comment]
Thanks for your answer ! And thanks for maintaining this library !
