### ISSUE TITLE
conf-ncurses fails to install on some systems (e.g. openSUSE)

### ISSUE THREAD

**Issue by timbertson** [ocaml/opam-repository#6800]
Opened to track http://lambda.jstolarek.com/2016/05/installing-ocaml-under-opensuse-11-4-or-the-compilation-of-conf-ncurses-failed/ (mentioned in #6791)

Regardless of _where_ the conf-ncurses dependency belongs, it should still work. I think the fix is as I ended up doing in https://github.com/ocaml/opam-repository/pull/6068

The basic idea is checking pkg-config first, but if that doesn't work, fall back to seeing if a trivial C file compiles after including some sane system include dirs. That way you either need pkg-config set up correctly _or_ ncurses already present in a default system directory. When I wrote conf-ncurses I was under the impression ncurses consistently provided .pc files, but sadly not.

Alternately we could extend `conf-ncurses.1+system` to cover OpenSUSE, but I don't know if that's possible, and it might still require manual intervention to actually install ncurses.

I hope to fix this myself sometime, but in the meantime I'm documenting the solution here for anyone else with the motivation to fix it. (Also I won't know if my fix actually works without someone to test on OpenSUSE)

**Comment by hugomg** [comment]
I think a better solution here would be to use `ncurses5-config` as a fallback for `pkg-config`. It [looks like](https://github.com/ocaml/opam-repository/issues/5880#issuecomment-222874579) its the official alternative for `pkg-config ncurses` in older versions of ncurses.

**Comment by timbertson** [comment]
does `ncurses5-config` wok out of the box? Or does it need to be opt-in via `--enable-pc-files` at compile time? I wasn't sure based on the comment you linked, but if it still requires custom compile-time settings then it's not much good for most users.

Can you confirm that `ncurses5-config` returns a 0 exit code on your system with the default ncurses install?

**Comment by hugomg** [comment]
Running only

**Comment by hugomg** [comment]
It seems that this problem got fixed in a recent patch by removing the pkg-config check: https://github.com/ocaml/opam-repository/commit/aabd225cb2f1c6e836cea7bb956fb944c4073731

I think this issue can be closed now.

**Comment by timbertson** [comment]
Great :)
