### ISSUE TITLE
Make camelus automatically ping the maintainer of a package when it's modified.

### ISSUE THREAD

**Issue by Drup** [ocaml/opam-repository#6819]
Note sure how feasible it is, but it would be very nice. 

Note that it's possible to cc members of an organization in github (`@ocsigen` works ...).

**Comment by dbuenzli** [comment]
That would be a good idea indeed, however I guess signing is anways going to change all that. In any case shouldn't that be filed on the https://github.com/AltGr/Camelus/ repo ?

**Comment by hannesm** [comment]
Signing will not change "all that".  Earlier I did some analysis to infer from git commits which GitHub ids are maintaining a package (see https://hannes.nqsb.io/Posts/Maintainers) - which may be useful to integrate into the repository at some point (there is even a PR https://github.com/ocaml/opam-repository/pull/8494 which was closed -- I can rerun the scripts, and put the maintainer GitHub ids into opam files if this is desired)

**Comment by dbuenzli** [comment]
> I can rerun the scripts, and put the maintainer GitHub ids into opam files if this is desired

I think this could be maybe useful on an `opamv2` repo e.g. via an `x-github-ping` field. The idea would be that people either specify this explicitely or camelus adds the thing to the `opam` file when he gets summoned. 

The question of whether this has to be discussed here or on camelus' respository remains.

**Comment by dbuenzli** [comment]
I have opened https://github.com/AltGr/Camelus/issues/16 to track this on @camelus' tracker.
