### ISSUE TITLE
ERROR while installing ppx_type_conv.113.33.01+4.03

### ISSUE THREAD

**Issue by gajaka** [ocaml/opam-repository#6839]
Hi guys, 
Here is an issue :
Opam version 4.03.0
OCaml version 4.03.0
I have updated opam and upgraded and seems to me core is broken.
It worked fine before upgrade.
Please advice.
Regards

opam install core failed during ppx_type_conv with the following error:

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of ppx_type_conv failed at "make".

#=== ERROR while installing ppx_type_conv.113.33.01+4.03 ======================#
 opam-version 1.2.2
 os           linux
 command      make
 path         /home/gajaka/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03
 compiler     4.03.0
 exit-code    2
 env-file     /home/gajaka/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-22462-335865.env
 stdout-file  /home/gajaka/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-22462-335865.out
 stderr-file  /home/gajaka/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-22462-335865.err

 Error: Signature mismatch:
 [...]
            unit -> deriver
 Command exited with code 2.
 + ocamlfind ocamlopt unix.cmxa -I /home/gajaka/.opam/4.03.0/lib/ocamlbuild /home/gajaka/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /home/gajaka/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
 File "myocamlbuild.ml", line 518, characters 43-62:
 Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
 Use String.uncapitalize_ascii instead.
 File "myocamlbuild.ml", line 531, characters 51-70:
 Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
 Use String.uncapitalize_ascii instead.

### stderr ###
[...]
 Use String.uncapitalize_ascii instead.
 File "setup.ml", line 5847, characters 11-28:
 Warning 3: deprecated: String.capitalize
 Use String.capitalize_ascii instead.
 File "setup.ml", line 5848, characters 11-30:
 Warning 3: deprecated: String.uncapitalize
 Use String.uncapitalize_ascii instead.
 W: Cannot find source file matching module 'ppx_type_conv' in library ppx_type_conv
 E: Failure("Command ''/home/gajaka/.opam/4.03.0/bin/ocamlbuild' src/ppx_type_conv.cma src/ppx_type_conv.cmxa src/ppx_type_conv.a src/ppx_type_conv.cmxs ppx_deriving_exporter/ppx_type_conv_deriving.cma ppx_deriving_exporter/ppx_type_conv_deriving.cmxa ppx_deriving_exporter/ppx_type_conv_deriving.a ppx_deriving_exporter/ppx_type_conv_deriving.cmxs -use-ocamlfind -tag debug' terminated with error code 10")
 make: *** [build] Error 1

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install core              113.33.02+4.03
  ∗  install core_kernel       113.33.01+4.03
  ∗  install ppx_assert        113.33.00     
  ∗  install ppx_bin_prot      113.33.00+4.03
  ∗  install ppx_compare       113.33.00+4.03
  ∗  install ppx_custom_printf 113.33.00+4.03
  ∗  install ppx_enumerate     113.33.00+4.03
  ∗  install ppx_expect        113.33.01+4.03
  ∗  install ppx_fields_conv   113.33.00+4.03
  ∗  install ppx_jane          113.33.00     
  ∗  install ppx_sexp_conv     113.33.01+4.03
  ∗  install ppx_sexp_message  113.33.00+4.03
  ∗  install ppx_sexp_value    113.33.00+4.03
  ∗  install ppx_typerep_conv  113.33.00+4.03
  ∗  install ppx_variants_conv 113.33.00+4.03
The following actions failed
  ∗  install ppx_type_conv 113.33.01+4.03
No changes have been performed

**Comment by NikitaPanteleev** [comment]
Just started to learn ocaml and have the same error during installation of core.

**Comment by gasche** [comment]
I hit the same problem as well when trying to install stuff on 4.03.

**Comment by whitequark** [comment]
I suspect this is fixed by  https://github.com/ocaml/opam-repository/pull/6861
