### ISSUE TITLE
New mail for no-maintainer packages

### ISSUE THREAD

**Issue by lefessan** [ocaml/opam-repository#6864]
Hi,

   When OPAM was first released, we populated the repository with many packages with "contact@ocamlpro.com" as maintainer, with the hope that the community would take over the maintenance of all these packages. After a few years now, there are still a few of them that are orphans. As OCamlPro does not have the manpower to do the maintenance for these packages, and we keep receiving queries for that, I would like to change the maintainer email for these packages with a better one. A natural one would be one of the "platform" mailing-lists, for example "platform@lists.ocaml.org". Would it be ok ? Should I use another one ? Any suggestion welcome !

**Comment by avsm** [comment]
Changing it certainly makes sense.  We could replace it with an explicit "opam-packages@lists.ocaml.org" mailing list that is used for general maintenance discussion of packages...

**Comment by gasche** [comment]
I'm fine with the change, but indeed I would rather use another mailing-list that "platform" that I think is more for high-level discussions. Another option would be to redirect to https://github.com/ocaml/opam-repository/issues instead of an email address (but maybe that would be bad for automated script contacting maintainers and stuff?).

**Comment by lefessan** [comment]
I am a bit worried by creating a new mailing-list where very few people are likely to register, so it will become a /dev/null at the end. Another solution would be an address with an auto-reply advising to create an issue on opam-repo.

**Comment by avsm** [comment]
We could juset the maintainer to a URL as well -- github.com/ocaml/opam-repository/issues
