### ISSUE TITLE
github package depends on lwt being built with optional camlp4 support

### ISSUE THREAD

**Issue by alainfrisch** [ocaml/opam-repository#6890]
As can be seen here: http://opam.ocamlpro.com/builder/html/github/github.1.0.0/13167b8dcc99545b531404be8fdb1f4b

The problem is that the github package depends on the lwt's syntactic support based on camlp4, but this is not built by lwt package when its optional dependency camlp4 is not installed.  I assume that the easiest step is to add a dependency to camlp4 on the OPAM github package.

**Comment by samoht** [comment]
This has been fixed in Github 2.0.0 so closing. /cc @dsheets

**Comment by dsheets** [comment]
It was fixed in 1.1.0.
