### ISSUE TITLE
ocaml 3.12 instal failure

### ISSUE THREAD

**Issue by tjim** [ocaml/opam-repository#6922]
Installing ocaml 3.12.1 fails because opam cannot retrieve a patch file

```
https://github.com/hhugo/ocaml/compare/3.12.1...fix-3.12.1.diff
```

Github says this does not exist, leading to a 404 error.
(opam 1.2.2 on Mac OS 10.11.5)

**Comment by dbuenzli** [comment]
This has been fixed by @dsheets in https://github.com/ocaml/opam-repository/commit/e221c807324dd0a024f615fbbd727899e1894053 so I think this can be closed.
