### ISSUE TITLE
dose3 5.0

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam-repository#6927]
I have a few issues with this package:
- it doesn't [seem to build currently](https://travis-ci.org/ocaml/opam/jobs/142771464) (!?)
- `5.0-rc1` is greater than `5.0`, which can lead to reverse "upgrades". Ironic since this is the package originally implementing our version ordering -- `5.0-rc1` should be replaced by `5.0~rc1` (or removed)
- why is the package `dose3` separate from package `dose` ? Shouldn't they at least conflict with each other, as they likely install the same files ?

cc @abate

**Comment by avsm** [comment]
Just ran into this issue also... also appear to be constraint issues with dose3.4.x and various versions of ocamlgraph.

**Comment by abate** [comment]
yes. I confirm this problem. I think it is due to the version 1.8.7 of ocamlgraph. I made a new release to fix this (5.0.1) and I'll upload the opam package soon.

**Comment by samoht** [comment]
Seems to be fixed by #7213 so closing.
