### ISSUE TITLE
Bad checksum in ocaml-ssl

### ISSUE THREAD

**Issue by seliopou** [ocaml/opam-repository#6959]
Got the following error during a CI build:

```
[ERROR] Bad checksum for
        /home/travis/.opam/packages.dev/ssl.0.5.2/ocaml-ssl-0.5.2.tar.gz:
          - 404f71d33885c985a8ff579996a5cda8 [expected result]
          - 0103b909e19ca9c6497a7ae696c16480 [actual result]
        This may be fixed by running `opam update`.
```

**Comment by samoht** [comment]
Look at the archive contents: this is due a a breakage in sourceforge hosting. My current workaround:

```
opam pin add ssl https://github.com/savonet/ocaml-ssl/releases/download/0.5.2/ocaml-ssl-0.5.2.tar.gz
```

/cc @smimram

**Comment by smimram** [comment]
Switching to github is a good idea, we are (slowly) trying to move away from sourceforge and use github for releases (and everything else)...

**Comment by samoht** [comment]
sourceforge seems to be back online, so closing.
