### ISSUE TITLE
Impossible to install async_ssl

### ISSUE THREAD

**Issue by vbmithr** [ocaml/opam-repository#6985]
/cc @diml 

```
+ /home/vb/.opam/4.02.3/bin/ocamlfind ocamlc -c -g -annot -bin-annot -no-alias-deps -thread -package variantslib -package typerep -package sexplib -package ppx_inline_test.runtime-lib -package ppx_expect.collector -package ppx_bench.runtime-lib -package ppx_assert.runtime-lib -package fieldslib -package ctypes.stubs -package ctypes -package bin_prot -pp 'ppx-jane -dump-ast -inline-test-drop -bench-drop -inline-test-lib fake_for_drop' -predicates custom_ppx -w -40 -I bindings -I namespace_wrappers -o bindings/ffi_bindings.cmo bindings/ffi_bindings.ml
File "bindings/config.h", line 1, characters 1-6:
optcomp: unknown directive
imported from file "bindings/ffi_bindings.ml", line 4
Command exited with code 2.
```

**Comment by diml** [comment]
Is this using the git repository? We recently switched to OCaml 4.03, but I forgot to update the constraint in the opam files. This will be done soon

**Comment by vbmithr** [comment]
On 18/07/2016 12:42, Jérémie Dimino wrote:
> Is this using the git repository? We recently switched to OCaml 4.03,
> but I forgot to update the constraint in the opam files. This will be
> done soon

Even on the main repository, I had to pin async_ssl to 113.33.3.
I don't have any more problem with this now, but clearly 113.33.5 does
not work at my place, but fails with the error msg I pasted above.

-- 
Vincent

**Comment by diml** [comment]
What version of ppx_optcomp do you have installed?

**Comment by vbmithr** [comment]
On 18/07/2016 14:29, Jérémie Dimino wrote:
> What version of ppx_optcomp do you have installed?

113.33.03

-- 
Vincent

**Comment by diml** [comment]
I can't reproduce the error
