### ISSUE TITLE
Force patches to apply with `-p1`

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam-repository#6998]
See https://github.com/ocaml/opam/issues/2576 for context.

Patches in repository packages are allowed at any depth, which means opam actually has to try `-p` with different values until one matches. This isn't very clean, and has some drawbacks, including clumsy error reporting.

Most of the patches in the repository seem to use `-p1` which matches what VC tools use and expect. A few have absolute paths starting with `/tmp/opam-xxxxx-xxxxx` (generated by some tool some time ago ?) and could be rewritten automatically. If some packages have a special, internal handling of patches, nothing prevents them from calling `patch` manually in their `build:` rules after all.

What do you think ?

**Comment by samoht** [comment]
Using `-p1` seems a good idea to me.

**Comment by dbuenzli** [comment]
I think this can be closed.
