### ISSUE TITLE
labltk

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#7061]
It's a minor issue but shouldn't ocamlbrowser ship separately from labltk?

**Comment by UnixJunkie** [comment]
Funny side effect: 'opam remove labltk' doesn't remove ocamlbrowser while it was just rendered non fonctional.

    # opam remove labltk
    The following actions will be performed:
      ⊘  remove labltk 8.06.0
    
    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    ⊘  removed   labltk.8.06.0
    Done.
    # which ocamlbrowser
    ~/.opam/4.02.3/bin/ocamlbrowser
    # ocamlbrowser 
    Fatal error: cannot load shared library dlllabltk
    Reason: dlllabltk.so: cannot open shared object file: No such file or directory

**Comment by samoht** [comment]
Closing this issue as it has been reported upstream.
