### ISSUE TITLE
[Question] OCaml Cordova plugins

### ISSUE THREAD

**Issue by dannywillems** [ocaml/opam-repository#7107]
I wrote a list of OCaml Cordova bindings (around 40 for the moment) you can find here : https://github.com/dannywillems/ocaml-cordova-plugin-list.

I chose to create one repo for one binding (update is easier, no need to download all code for only one plugin, easier to add a new binding and collaborate on it) and they can be installed with opam by adding the previous repository.

As it's released now for more than a month, I would like to merge each repository in this official opam repository to be able to use directly opam install.

Is there any problem if each binding has its own opam repo to merge it?

**Comment by avsm** [comment]
Wow, this is amazing! I see no problem with one opam package per binding.

**Comment by dannywillems** [comment]
@avsm great! I will do PR soon.
