### ISSUE TITLE
package qtest is incompatible with latest oasis (v0.4.7)

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#7305]
oasis 0.4.7 Dropped support for OASISFormat 0.2 and 0.1.

    # opam --version
    1.2.2
    # opam switch
    4.03.0        C 4.03.0        Official 4.03.0 release
    
    # opam install qtest
    The following actions will be performed:
      ∗  install qtest 2.1.1
    
    =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [qtest] Archive in cache
    
    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [ERROR] The compilation of qtest failed at "ocaml do.ml qtest build
            /home/berenger/.opam/4.03.0".
    Processing  1/1: [qtest: ocaml do.ml]
    #=== ERROR while installing qtest.2.1.1 =======================================#
    # opam-version 1.2.2
    # os           linux
    # command      ocaml do.ml qtest build /home/berenger/.opam/4.03.0
    # path         /home/berenger/.opam/4.03.0/build/qtest.2.1.1
    # compiler     4.03.0
    # exit-code    2
    # env-file     /home/berenger/.opam/4.03.0/build/qtest.2.1.1/qtest-25778-1872ec.env
    # stdout-file  /home/berenger/.opam/4.03.0/build/qtest.2.1.1/qtest-25778-1872ec.out
    # stderr-file  /home/berenger/.opam/4.03.0/build/qtest.2.1.1/qtest-25778-1872ec.err
    ### stdout ###
    # 
    # #### oasis setup ####
    # 
    ### stderr ###
    # E: OASIS format version '0.2' is not supported.
    # Exception: Failure "failed command".
    
    =-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    The following actions failed
      ∗  install qtest 2.1.1
    No changes have been performed

**Comment by UnixJunkie** [comment]
@c-cube @vincent-hugot

**Comment by samoht** [comment]
I think this is fixed by #7281
