### ISSUE TITLE
frama-c-base can't be installed with doc

### ISSUE THREAD

**Issue by rixed** [ocaml/opam-repository#7317]
The opam rules use "%{frama-c:doc}%" which expends to nothing which in turns yield the Makefile to mkdir an empty string, which fails.
Shouldn't it use "%{frama-c-base:doc}%" instead?

**Comment by dbuenzli** [comment]
This has been fixed in 1c22eacabd7a8ca1af5be3853ded6f9df6b0f711 and can be closed.
