### ISSUE TITLE
Is there a package which is a good citizen at installing/uninstalling its doc ?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#7319]
Preferably a library. I am looking for a good example to follow.
Thanks !

**Comment by UnixJunkie** [comment]
If ocp-browser can show the ocamldoc upon hitting space, I consider it is a very good citizen.

**Comment by samoht** [comment]
Look at the `odoc` package, a good example is [bos](http://erratique.ch/software/bos)
