### ISSUE TITLE
Is any zmq version supposed to install with OCaml 4.03.0 ?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#7334]
@andersfugmann 
Those versions don't have an ocaml-version constraint while I can't install them:
./packages/zmq/zmq.3.2-1/opam
./packages/zmq/zmq.3.2-0/opam
./packages/zmq/zmq.3.2-2/opam

    The following actions will be performed:
      ∗  install zmq 3.2-2
    
    =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [zmq] Archive in cache
    
    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [zmq: oasis setup] Command started
    + oasis "setup" (CWD=/home/berenger/.opam/4.03.0/build/zmq.3.2-2)
    - findlib: [WARNING] While parsing '/home/berenger/.opam/4.03.0/lib/ocp-index/META': Expected a '=' or a '(arguments,...)=' clause at line 2 position 37
    [zmq: ocaml setup.ml] Command started
    + ocaml "setup.ml" "-configure" "--prefix" "/home/berenger/.opam/4.03.0" (CWD=/home/berenger/.opam/4.03.0/build/zmq.3.2-2)
    - 
    - Configuration: 
    - ocamlfind: ........................................... /home/berenger/.opam/4.03.0/bin/ocamlfind
    - ocamlc: .............................................. /home/berenger/.opam/4.03.0/bin/ocamlc.opt
    - ocamlopt: ............................................ /home/berenger/.opam/4.03.0/bin/ocamlopt.opt
    - ocamlbuild: .......................................... /home/berenger/.opam/4.03.0/bin/ocamlbuild
    - Package name: ........................................ ZMQ
    - Package version: ..................................... 3.2
    - os_type: ............................................. Unix
    - system: .............................................. linux
    - architecture: ........................................ amd64
    - ccomp_type: .......................................... cc
    - ocaml_version: ....................................... 4.03.0
    - standard_library_default: ............................ /home/berenger/.opam/4.03.0/lib/ocaml
    - standard_library: .................................... /home/berenger/.opam/4.03.0/lib/ocaml
    - standard_runtime: .................................... /home/berenger/.opam/4.03.0/bin/ocamlrun
    - bytecomp_c_compiler: ................................. gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC
    - native_c_compiler: ................................... gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT
    - model: ............................................... default
    - ext_obj: ............................................. .o
    - ext_asm: ............................................. .s
    - ext_lib: ............................................. .a
    - ext_dll: ............................................. .so
    - default_executable_name: ............................. a.out
    - systhread_supported: ................................. true
    - Install architecture-independent files dir: .......... /home/berenger/.opam/4.03.0
    - Install architecture-dependent files in dir: ......... $prefix
    - User executables: .................................... $exec_prefix/bin
    - System admin executables: ............................ $exec_prefix/sbin
    - Program executables: ................................. $exec_prefix/libexec
    - Read-only single-machine data: ....................... $prefix/etc
    - Modifiable architecture-independent data: ............ $prefix/com
    - Modifiable single-machine data: ...................... $prefix/var
    - Object code libraries: ............................... $exec_prefix/lib
    - Read-only arch-independent data root: ................ $prefix/share
    - Read-only architecture-independent data: ............. $datarootdir
    - Info documentation: .................................. $datarootdir/info
    - Locale-dependent data: ............................... $datarootdir/locale
    - Man documentation: ................................... $datarootdir/man
    - Documentation root: .................................. $datarootdir/doc/$pkg_name
    - HTML documentation: .................................. $docdir
    - DVI documentation: ................................... $docdir
    - PDF documentation: ................................... $docdir
    - PS documentation: .................................... $docdir
    - findlib_version: ..................................... 1.6.2
    - is_native: ........................................... true
    - suffix_program: ...................................... 
    - Remove a file.: ...................................... rm -f
    - Remove a directory.: ................................. rm -rf
    - Turn ocaml debug flag on: ............................ true
    - Turn ocaml profile flag on: .......................... false
    - Compiler support generation of .cmxs.: ............... true
    - OCamlbuild additional flags: ......................... 
    - Build and run tests: ................................. true
    - Create documentations: ............................... true
    - Compile tests executable and library and run them: ... false
    - pkg_unix: ............................................ /home/berenger/.opam/4.03.0/lib/ocaml
    - pkg_uint_uint64: ..................................... /home/berenger/.opam/4.03.0/lib/uint
    - pkg_ounit: ........................................... /home/berenger/.opam/4.03.0/lib/oUnit
    - 
    [zmq: ocaml setup.ml] Command started
    + ocaml "setup.ml" "-build" (CWD=/home/berenger/.opam/4.03.0/build/zmq.3.2-2)
    - /home/berenger/.opam/4.03.0/bin/ocamlopt.opt unix.cmxa -I /home/berenger/.opam/4.03.0/lib/ocamlbuild /home/berenger/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/berenger/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
    - /home/berenger/.opam/4.03.0/bin/ocamlfind ocamlc -g -ccopt -Wall -ccopt -W -ccopt -Wextra -ccopt -O2 -c src/caml_zmq_stubs.c
    - + /home/berenger/.opam/4.03.0/bin/ocamlfind ocamlc -g -ccopt -Wall -ccopt -W -ccopt -Wextra -ccopt -O2 -c src/caml_zmq_stubs.c
    - In file included from src/caml_zmq_stubs.c:37:0:
    - src/uint64.h:15:29: error: unknown type name ‘uint64’
    -  value caml_uint_copy_uint64(uint64 i);
    -                              ^
    - src/caml_zmq_stubs.c: In function ‘caml_zmq_set_uint64_option’:
    - src/caml_zmq_stubs.c:137:5: error: unknown type name ‘uint64’
    -      uint64 val = CAML_UINT_Uint64_val(socket_option);
    -      ^
    - In file included from src/caml_zmq_stubs.c:37:0:
    - src/uint64.h:13:37: error: ‘uint64’ undeclared (first use in this function)
    -  #define CAML_UINT_Uint64_val(v) (*((uint64 *)Data_custom_val(v)))
    -                                      ^
    - src/caml_zmq_stubs.c:137:18: note: in expansion of macro ‘CAML_UINT_Uint64_val’
    -      uint64 val = CAML_UINT_Uint64_val(socket_option);
    -                   ^
    - src/uint64.h:13:37: note: each undeclared identifier is reported only once for each function it appears in
    -  #define CAML_UINT_Uint64_val(v) (*((uint64 *)Data_custom_val(v)))
    -                                      ^
    - src/caml_zmq_stubs.c:137:18: note: in expansion of macro ‘CAML_UINT_Uint64_val’
    -      uint64 val = CAML_UINT_Uint64_val(socket_option);
    -                   ^
    - src/uint64.h:13:45: error: expected expression before ‘)’ token
    -  #define CAML_UINT_Uint64_val(v) (*((uint64 *)Data_custom_val(v)))
    -                                              ^
    - src/caml_zmq_stubs.c:137:18: note: in expansion of macro ‘CAML_UINT_Uint64_val’
    -      uint64 val = CAML_UINT_Uint64_val(socket_option);
    -                   ^
    - src/caml_zmq_stubs.c: In function ‘caml_zmq_set_int64_option’:
    - src/caml_zmq_stubs.c:154:5: error: unknown type name ‘int64’
    -      int64 val = Int64_val(Field(socket_option, 1));
    -      ^
    - src/caml_zmq_stubs.c: In function ‘caml_zmq_get_uint64_option’:
    - src/caml_zmq_stubs.c:237:5: error: unknown type name ‘uint64’
    -      uint64 mark;
    -      ^
    - In file included from src/caml_zmq_stubs.c:15:0:
    - src/caml_zmq_stubs.c:244:17: warning: implicit declaration of function ‘caml_uint_copy_uint64’ [-Wimplicit-function-declaration]
    -      CAMLreturn (caml_uint_copy_uint64(mark));
    -                  ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:257:29: note: in definition of macro ‘CAMLreturnT’
    -    type caml__temp_result = (result); \
    -                              ^
    - src/caml_zmq_stubs.c:244:5: note: in expansion of macro ‘CAMLreturn’
    -      CAMLreturn (caml_uint_copy_uint64(mark));
    -      ^
    - src/caml_zmq_stubs.c: In function ‘caml_zmq_get_int64_option’:
    - src/caml_zmq_stubs.c:249:5: error: unknown type name ‘int64’
    -      int64 mark;
    -      ^
    - src/caml_zmq_stubs.c: In function ‘caml_zmq_event_recv’:
    - src/caml_zmq_stubs.c:496:5: error: unknown type name ‘zmq_event_t’
    -      zmq_event_t event;
    -      ^
    - src/caml_zmq_stubs.c:499:18: error: request for member ‘event’ in something not a structure or union
    -      switch (event.event) {
    -                   ^
    - In file included from src/caml_zmq_stubs.c:15:0:
    - src/caml_zmq_stubs.c:502:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.connected.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:503:44: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_fd(event.data.connected.fd));
    -                                             ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
    -  #  define Val_fd(x) Val_int(x)
    -                      ^
    - src/caml_zmq_stubs.c:503:32: note: in expansion of macro ‘Val_fd’
    -          Store_field(result, 1, Val_fd(event.data.connected.fd));
    -                                 ^
    - src/caml_zmq_stubs.c:507:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.connect_delayed.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:508:45: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_int(event.data.connect_delayed.err));
    -                                              ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:508:32: note: in expansion of macro ‘Val_int’
    -          Store_field(result, 1, Val_int(event.data.connect_delayed.err));
    -                                 ^
    - src/caml_zmq_stubs.c:509:67: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 2, caml_copy_string(zmq_strerror(event.data.connect_delayed.err)));
    -                                                                    ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:514:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.connect_retried.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:515:45: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_int(event.data.connect_retried.interval));
    -                                              ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:515:32: note: in expansion of macro ‘Val_int’
    -          Store_field(result, 1, Val_int(event.data.connect_retried.interval));
    -                                 ^
    - src/caml_zmq_stubs.c:520:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.listening.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:521:44: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_fd(event.data.listening.fd));
    -                                             ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
    -  #  define Val_fd(x) Val_int(x)
    -                      ^
    - src/caml_zmq_stubs.c:521:32: note: in expansion of macro ‘Val_fd’
    -          Store_field(result, 1, Val_fd(event.data.listening.fd));
    -                                 ^
    - src/caml_zmq_stubs.c:526:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.bind_failed.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:527:45: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_int(event.data.bind_failed.err));
    -                                              ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:527:32: note: in expansion of macro ‘Val_int’
    -          Store_field(result, 1, Val_int(event.data.bind_failed.err));
    -                                 ^
    - src/caml_zmq_stubs.c:528:67: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 2, caml_copy_string(zmq_strerror(event.data.bind_failed.err)));
    -                                                                    ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:533:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.accepted.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:534:44: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_fd(event.data.accepted.fd));
    -                                             ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
    -  #  define Val_fd(x) Val_int(x)
    -                      ^
    - src/caml_zmq_stubs.c:534:32: note: in expansion of macro ‘Val_fd’
    -          Store_field(result, 1, Val_fd(event.data.accepted.fd));
    -                                 ^
    - src/caml_zmq_stubs.c:539:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.accept_failed.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:540:45: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_int(event.data.accept_failed.err));
    -                                              ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:540:32: note: in expansion of macro ‘Val_int’
    -          Store_field(result, 1, Val_int(event.data.accept_failed.err));
    -                                 ^
    - src/caml_zmq_stubs.c:541:67: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 2, caml_copy_string(zmq_strerror(event.data.accept_failed.err)));
    -                                                                    ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:546:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.closed.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:547:44: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_fd(event.data.closed.fd));
    -                                             ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
    -  #  define Val_fd(x) Val_int(x)
    -                      ^
    - src/caml_zmq_stubs.c:547:32: note: in expansion of macro ‘Val_fd’
    -          Store_field(result, 1, Val_fd(event.data.closed.fd));
    -                                 ^
    - src/caml_zmq_stubs.c:552:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.close_failed.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:553:45: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_int(event.data.close_failed.err));
    -                                              ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:553:32: note: in expansion of macro ‘Val_int’
    -          Store_field(result, 1, Val_int(event.data.close_failed.err));
    -                                 ^
    - src/caml_zmq_stubs.c:554:67: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 2, caml_copy_string(zmq_strerror(event.data.close_failed.err)));
    -                                                                    ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:559:54: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 0, caml_copy_string(event.data.disconnected.addr));
    -                                                       ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - src/caml_zmq_stubs.c:560:44: error: request for member ‘data’ in something not a structure or union
    -          Store_field(result, 1, Val_fd(event.data.disconnected.fd));
    -                                             ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/memory.h:270:27: note: in definition of macro ‘Store_field’
    -    value caml__temp_val = (val); \
    -                            ^
    - /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    -  #define Val_int(x) Val_long(x)
    -                     ^
    - src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
    -  #  define Val_fd(x) Val_int(x)
    -                      ^
    - src/caml_zmq_stubs.c:560:32: note: in expansion of macro ‘Val_fd’
    -          Store_field(result, 1, Val_fd(event.data.disconnected.fd));
    -                                 ^
    - Command exited with code 2.
    - findlib: [WARNING] While parsing '/home/berenger/.opam/4.03.0/lib/ocp-index/META': Expected a '=' or a '(arguments,...)=' clause at line 2 position 37
    - E: Failure("Command ''/home/berenger/.opam/4.03.0/bin/ocamlbuild' src/libZMQB_stubs.a src/dllZMQB_stubs.so src/ZMQB.cma src/ZMQB.cmxa src/ZMQB.a src/ZMQB.cmxs test/test.native -tag debug' terminated with error code 10")
    [ERROR] The compilation of zmq failed at "ocaml setup.ml -build".
    [zmq: ocamlfind remove] Command started
    + ocamlfind "remove" "ZMQ" (CWD=/home/berenger/.opam/4.03.0/build/zmq.3.2-2)
    - ocamlfind: [WARNING] No such directory: /home/berenger/.opam/4.03.0/lib/ZMQ
    
    #=== ERROR while installing zmq.3.2-2 =========================================#
    # opam-version         1.2.2
    # os                   linux
    # command              ocaml setup.ml -build
    # path                 /home/berenger/.opam/4.03.0/build/zmq.3.2-2
    # compiler             4.03.0
    # exit-code            1
    # env-file             /home/berenger/.opam/4.03.0/build/zmq.3.2-2/zmq-13367-6d07ae.env
    # stdout-file          /home/berenger/.opam/4.03.0/build/zmq.3.2-2/zmq-13367-6d07ae.out
    # stderr-file          /home/berenger/.opam/4.03.0/build/zmq.3.2-2/zmq-13367-6d07ae.err
    ### stdout ###
    # [...]
    # /home/berenger/.opam/4.03.0/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
    #  #define Val_int(x) Val_long(x)
    #                     ^
    # src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
    #  #  define Val_fd(x) Val_int(x)
    #                      ^
    # src/caml_zmq_stubs.c:560:32: note: in expansion of macro ‘Val_fd’
    #          Store_field(result, 1, Val_fd(event.data.disconnected.fd));
    #                                 ^
    # Command exited with code 2.
    ### stderr ###
    # findlib: [WARNING] While parsing '/home/berenger/.opam/4.03.0/lib/ocp-index/META': Expected a '=' or a '(arguments,...)=' clause at line 2 position 37
    # E: Failure("Command ''/home/berenger/.opam/4.03.0/bin/ocamlbuild' src/libZMQB_stubs.a src/dllZMQB_stubs.so src/ZMQB.cma src/ZMQB.cmxa src/ZMQB.a src/ZMQB.cmxs test/test.native -tag debug' terminated with error code 10")
    
    
    
    =-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    The following actions failed
      ∗  install zmq 3.2-2
    No changes have been performed
    
    =-=- zmq.3.2-2 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    => This package relies on external (system) dependencies that may be missing.
       `opam depext zmq.3.2-2' may help you find the correct installation for your
       system.
    'opam install -v zmq.3.2-2' failed.

**Comment by copy** [comment]
I've been using ZMQ on 4.03 with this patch: [#23](https://github.com/issuu/ocaml-zmq/pull/32).

**Comment by andersfugmann** [comment]
Please see PR #7371
