### ISSUE TITLE
bolt.1.4 build failure on OS X

### ISSUE THREAD

**Issue by yallop** [ocaml/opam-repository#7436]
Travis log: https://travis-ci.org/ocaml/opam-repository/jobs/159805592
Discussion: https://github.com/ocaml/opam-repository/pull/7429#issuecomment-246989794

**Comment by samoht** [comment]
Could you report that upstream to http://bugs.x9c.fr/my_view_page.php ? /cc @Nyavlys

**Comment by yallop** [comment]
I think it's a problem the CI, not with Bolt.

**Comment by samoht** [comment]
Ha yes, sorry.

**Comment by dbuenzli** [comment]
Does anyone know what can be done here ? I'm not sure I understand the problem. `bolt` does have a `camlp4` dep.

**Comment by dbuenzli** [comment]
Since noone seems to know what this is about, I'm closing.
