### ISSUE TITLE
conf-pkg-config fails to install on debian linux

### ISSUE THREAD

**Issue by janrichter222** [ocaml/opam-repository#7448]
The command "opam install conf-pkg-config" fails, returning this message:

> =-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> Building conf-pkg-config.1.0:
>   pkg-config --help
> [ERROR] The compilation of conf-pkg-config.1.0 failed.

The package folder in the opam build directory is empty afterwards.

Platform: linux debian Jessie (8.5)
Ocaml version 4.02.3
Opam version 1.2.0

**Comment by samoht** [comment]
@UnixJunkie any idea of what could cause that?

**Comment by UnixJunkie** [comment]
@janrichter222 Can you run 'opam install -v conf-pkg-config' ?
Also, in a shell run those:
pkg-config --help
echo $?
and show us the output.

**Comment by UnixJunkie** [comment]
Maybe on your distro the command is pkgconfig instead of pkg-config.
Please let us know.

**Comment by janrichter222** [comment]
Part 1:
opam install -v conf-pkg-config
The following actions will be performed:
- install   conf-pkg-config.1.0
=== 1 to install ===

=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Building conf-pkg-config.1.0:
  pkg-config --help
[ERROR] The compilation of conf-pkg-config.1.0 failed.
Removing conf-pkg-config.1.0.
  Nothing to do.


#=== ERROR while installing conf-pkg-config.1.0 ===============================#
Internal error:
  "pkg-config": command not found.
'opam install -v conf-pkg-config' failed.
janrichter@ad653507pc:~$


Part 2:

pkg-config --help
bash: pkg-config: Command not found.
echo $?
127

**Comment by UnixJunkie** [comment]
Which distro are you using?

**Comment by janrichter222** [comment]
Debian. Looks like the package pkg-config was not installed. Now understand that a system dependency was not fulfilled. My error, I guess.

**Comment by UnixJunkie** [comment]
Try this: opam depext conf-pkg-config.
It should install it automatically for you.

**Comment by dbuenzli** [comment]
> Now understand that a system dependency was not fulfilled. My error, I guess.

Well not your error, the error message is a bit cryptic ('Internal error') and could be improved. 

Is there a reason why running `opam depext` is not suggested by OPAM ? It seems to me that this what usually happens when package with depexts fail.

**Comment by UnixJunkie** [comment]
I feel the depexts should be enforced. Especially for conf packages ...
