### ISSUE TITLE
cairo is broken on linux

### ISSUE THREAD

**Issue by SimonBoulier** [ocaml/opam-repository#7561]
In a fresh switch, `opam install cairo` fails with:

   ERROR while installing cairo.1.2.0
   opam-version 1.2.2
   os           linux
   command      ocamlopt.opt -shared -linkall -I src -ccopt -I/usr/include/cairo -ccopt -I/usr/include/glib-2.0 -ccopt -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -ccopt -I/usr/include/pixman-1 -ccopt -I/usr/include/freetype2 -ccopt -I/usr/include/libpng12 -o src/cairo.cmxs -cclib -Lsrc/ -cclib -lcairo src/cairo.cmxa
   path         /home/rascar/.opam/melt/build/cairo.1.2.0
   compiler     system (4.02.3)
   exit-code    127

I can't understand why.

Full log here: [log.txt](https://github.com/ocaml/opam-repository/files/506065/log.txt)

**Comment by dbuenzli** [comment]
Didn't understand the failure either but you may try your luck with `opam install cairo2`. @Chris00 might want enlight us on the exact difference between `cairo` and  `cairo2`. (The only thing I know is that the cairo backend that what contributed in one of my project was made using `cairo2`).

**Comment by SimonBoulier** [comment]
`cairo2` installs correctly but `melt` (the package I want to install) depends on `cairo` instead of `cairo2` and don't recognize it ...

**Comment by SimonBoulier** [comment]
The switch which I tried to use used the compiler of my system (which is 4.02.3).
But if I make a switch with another compiler (or even the same version but not this of the one system), it works well ...

**Comment by dbuenzli** [comment]
Note sure exactly what to do about this. If anybody has an idea please say, otherwise I'd move on to close this.

**Comment by SimonBoulier** [comment]
It will remain mysterious, but let's close it ...
