### ISSUE TITLE
bap 1.0.0 on osx failures

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-repository#7575]
Here are a few things that are failing /cc @ivg

# bap-byteweight

The install procedure is trying to `wget` data:
```
wget -O /Users/dbuenzli/.opam/4.03.0/share/bap/sigs.zip https://github.com/BinaryAnalysisPlatform/bap/releases/download/v1.0.0/sigs.zip
```
 `wget` doesn't exist on osx and an install procedure should not try to download things. I think you should either provide the data in the distribution or provide the through another package. In particular this will prevent to install the package in offline opams which is an important use case for air gap settings.

# bap-objdump

There seem to be an error in the way `configure` is invoked:

```
> opam install bap-objdump -v -v 
The following actions will be performed:
  ∗  install bap-objdump 1.0.0

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[bap-objdump] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
+ tar "xfz" "/Users/dbuenzli/.opam/archives/bap-objdump.1.0.0+opam.tar.gz" "-C" "/var/folders/g4/nl6g_ytj63bbn9d45_jhggxc0000gn/T/opam-24769-7afd23"
+ mv "/var/folders/g4/nl6g_ytj63bbn9d45_jhggxc0000gn/T/opam-24769-7afd23/bap-objdump.1.0.0" "/Users/dbuenzli/.opam/4.03.0/build/bap-objdump.1.0.0"
[bap-objdump: ./configure] Command started
+ ./configure "--prefix=/Users/dbuenzli/.opam/4.03.0" "--enable-objdump" "--objdump-targets=[]" "--objdump-path=" (CWD=/Users/dbuenzli/.opam/4.03.0/build/bap-objdump.1.0.0)
- none: option '--objdump-path' needs an argument.
- configure options:
[...]
```

# bap-llvm.1.0.0 

It seems configure fails to find `llvm`: 

```
- E:   Failed to find llvm library, consider using --with-llvm-version
-      or --with-llvm-config command line options, to point me on a
-      correct version of LLVM. 
```

Even though `opam depext` says:

```
> opam depext bap-llvm.1.0.0
# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - gmp
# All required OS packages found.
```

**Comment by ivg** [comment]
`ocamlbrew` support is ongoing, we are planning to add it in the next release, see BinaryAnalysisPlatform/bap#568. 

>  In particular this will prevent to install the package in offline opams which is an important use case for air gap settings.

This is a very good point! As you suggested, I have created a `bap-signatures` package (see PR #7576) that will download signatures using regular opam fetching procedure. 

Also, you may create any issues concerning bap and its installation directly in our [issue tracker][1], it will make it easier to track them and lower the traffic on this tracker. 

[1]: https://github.com/BinaryAnalysisPlatform/bap/issues

**Comment by dbuenzli** [comment]
Excellent. Is the `bap-objdump` failure also related to `brew` depexts ? If that's the case then I'll close this.

**Comment by ivg** [comment]
> Is the bap-objdump failure also related to brew depexts ? If that's the case then I'll close this.

Yep, the `conf-binutils` pacakge is responsible for populating the `path` variable, and it fails to do this on the `homebrew` environment.

We are mostly using `macports` in our team, that's why `homebrew` was left out. But it looks like, that it is quite popular across the universe, so we now decided to fix this issue.

**Comment by dbuenzli** [comment]
Ok thanks. So I'm closing this.
