### ISSUE TITLE
Bap-server introduces problems because an error in opam file 

### ISSUE THREAD

**Issue by Kakadu** [ocaml/opam-repository#7588]
See https://github.com/ocaml/opam/issues/2708

```
"cohttp" {>= "0.20.0 & <= 0.21.0"}
```

Please, fix complains of linter
@ivg

**Comment by ivg** [comment]
This packaged was not supposed to be a part of release :) But it slipped somehow and bypassed our linters. This issue will be resolved with #7591.

**Comment by AltGr** [comment]
In the meantime, I just fixed the syntax error in the repository through da1962e

**Comment by mechanics1080** [comment]
Help
