### ISSUE TITLE
the apron package doesn't install on freebsd

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-repository#7630]
Version opam: apron.20160125

/usr/bin/ld: cannot find -lmpfr

The lib is there:

/usr/local/lib/libmpfr.a

The header is there:

/usr/local/include/mpfr.h

**Comment by UnixJunkie** [comment]
@nberth

**Comment by nberth** [comment]
I think the issue comes from the way OCaml plugins are built. For now, #7640 should fix it.

**Comment by UnixJunkie** [comment]
thanks a lot Nicolas, I'll try it soon

**Comment by dbuenzli** [comment]
This has been fixed by #7640 and can be closed.
