### ISSUE TITLE
camlp4.4.04 failed to install

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam-repository#7791]
Failed to install at my workplace:

```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - camlp4.4.04
        (This may be fixed by running 'opam update')
```

This is due to the `git://` URL in `camlp4.4.04/url`.  Unfortunately `git://` is firewalled.  Could we have simple `https://` URL instead?

**Comment by dbuenzli** [comment]
This can be closed. It was fixed by 2233600fd3aa6c9c4437eb5d6fc5fdc424a08109 in which `camlp4.4.04+1` was removed and `camlp4.4.04+1` added with an http url.
