### ISSUE TITLE
broken redirect for versionless url

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam-repository#7804]
```
$ curl -s -I http://opam.ocaml.org/pkg/extunix | grep Location
Location: http://opam.ocaml.org/packages/extunix
$ curl -s -I http://opam.ocaml.org/pkg/extunix/ | grep Location
Location: http://opam.ocaml.org/packages/extunix/extunix.
```
The second one (note the trailing slash) doesn't work. Same for https://

**Comment by AltGr** [comment]
Probably something to fix here: https://github.com/ocaml/opam.ocaml.org/blob/master/nginx.conf ?

**Comment by dbuenzli** [comment]
Who do we need to ping to get this fixed ?

**Comment by dbuenzli** [comment]
It doesn't seem we are able to make any progress here. 

According to @dsheets this was broken when https://github.com/ocaml/opam2web/pull/139 was merged. 

I don't think this is an opam repository issue per se, so I suggest we find where this should actually be reported (I have no idea) and move on to close this.

**Comment by ygrek** [comment]
moved to https://github.com/ocaml/opam.ocaml.org/issues/19
