### ISSUE TITLE
Broken link and github tag for 4.04.0

### ISSUE THREAD

**Issue by dbaelde** [ocaml/opam-repository#7819]
The info page for ocaml 4.04.0 (https://opam.ocaml.org/packages/ocaml-src/ocaml-src.4.04.0/) indicates that is is based on the github tag 4.04, which does not exist (only 4.04.0 exists). Consequently, the link (https://opam.ocaml.org/packages/ocaml-src/ocaml-src.4.04.0/) is also broken.

**Comment by hannesm** [comment]
@dbaelde thanks for the report, I was annoyed by this as well, and fixed it in 040fabd, which was merged.  (and nice seeing you here again, I guess the last time was on the night train in 2012 from copenhagen to western germany ;)

**Comment by dbaelde** [comment]
@hannesm, thanks for the fix! It's funny that this should be the opportunity to "meet" again ;) I hope you're doing well. Cheers!
