### ISSUE TITLE
Broken URLs for wyrd packages

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam-repository#7834]
The address http://pessimization.com is silent; additionally, this causes a delay in the opam-repository updating scripts, because it has to wait for timeout.
Since the packages lack any maintainer data, they should probably be removed.

**Comment by AltGr** [comment]
While I am at it, here are the other failures:
  - [atdgen.1.2.2] https://github.com/MyLifeLabs/atdgen/archive/v1.2.2.tar.gz (download failed)
  - [coccinelle.1.0.2] https://github.com/coccinelle/coccinelle/archive/coccinelle-1.0.2.tar.gz (download failed)
  - [cordova-plugin-push-notifications.1.0] https://github.com/dannywillems/ocaml-cordova-plugin-push-notifications/archive/v1.0.tar.gz (Bad checksum, expected md5=52a5b3f2f88dde71d54f7af858864d25)
  - [cordova-plugin-push-notifications.1.1] https://github.com/dannywillems/ocaml-cordova-plugin-push/archive/v1.1.zip (Bad checksum, expected md5=71c9ad01ebb9a84e016d8dacdf2c2c03)
  - [cubicle.1.0] http://cubicle.lri.fr/cubicle-1.0.tar.gz (download failed)
  - [diy.5.01] http://diy.inria.fr/sources/diy-5.01.tar.gz (download failed)
  - [email_message.109.42.alpha1] https://github.com/janestreet-alpha/email_message/archive/109.42.alpha1.tar.gz (download failed)
  - [frama-c-base.20160501] http://frama-c.com/download/frama-c-Aluminium-20160501.tar.gz (download failed)
  - [frenetic.1.0] https://people.cs.umass.edu/~arjun/download/frenetic.1.0.tar.gz (download failed)
  - [lpi.0.0.1] https://github.com/baxtersa/lambda-pi/archive/v0.0.1.tar.gz (Bad checksum, expected md5=d415f6ca29f02fea9b432bf4951afeb0)
  - [mlorg.0.1.1] http://iuwt.fr/~asmanur/mlorg-0.1.tar.gz (download failed)
  - [mlorg.0.1.2] http://iuwt.fr/~asmanur/mlorg-0.1.2.tar.gz (download failed)
  - [ocaml-variants.4.00.1+BER] http://eneide.happyleptic.org/~rixed/metaocaml-opam/ber.patch (download failed)
  - [ocaml-zmq.0] https://github.com/pdhborges/ocaml-zmq/tarball/67586823edd (download failed)
  - [ocamltter.2.1.1] https://github.com/yoshihiro503/ocamltter/archive/2.1.1.tar.gz (Bad checksum, expected md5=b9f930166f6177f4b56d50c8124a762c)
  - [otr.0.3.2] https://github.com/hannesm/ocaml-otr/archive/0.3.2.tar.gz (Bad checksum, expected md5=5364379a7abfb4169dee39c7a67dd660)
  - [ox.1.0.0] https://people.cs.umass.edu/~arjun/download/ox.1.0.tar.gz (download failed)
  - [planets.0.1.13] http://planets.homedns.org/dist/planets-0.1.13.tgz (download failed)
  - [shcaml.0.1.3] http://www.eecs.harvard.edu/~tov/code/shcaml/shcaml-0.1.3.tar.gz (download failed)
  - [vrt.0.1.0] https://github.com/afiniate/vrt/archive/v0.1.0.tar.gz (download failed)
  - [wyrd.1.4.5] http://pessimization.com/software/wyrd/wyrd-1.4.5.tar.gz (download failed)
  - [wyrd.1.4.6] http://pessimization.com/software/wyrd/wyrd-1.4.6.tar.gz (download failed)
  - [zenon.0.7.1] https://pkgs.fedoraproject.org/repo/pkgs/zenon/zenon-0.7.1.tar.xz/cb8b35e2d55dabcc7d8a1e8b3600f68a/zenon-0.7.1.tar.xz (download failed)
  - [zephyrus.0.1] http://www.pps.univ-paris-diderot.fr/~qba/archives/2013.08.30/zephyrus-0.1.tar.gz (Bad checksum, expected md5=436086148dd6b21663998c780d440a6d)

**Comment by yallop** [comment]
The wyrd urls have been fixed (126d7f03, 0e7d4e22)

**Comment by AltGr** [comment]
Thanks!
