### ISSUE TITLE
functoria installation fails when ounit.1.1.2 is installed

### ISSUE THREAD

**Issue by rixed** [ocaml/opam-repository#7868]
Fails with:

```
# File "tests/test_functoria_command_line.ml", line 17, characters 5-11:
# Error: Unbound module OUnit2
# Command exited with code 2.
# Makefile:7: recipe for target 'build' failed
```

Not 100% sure but I think we need to add this declaration in functoria opam file:

```
depopts: ["ounit" {>= 2.0.0}]
```

**Comment by dbuenzli** [comment]
Ping @drup the maintainer of this package. Could you please look into this and adjust the constraints if needed.

**Comment by Drup** [comment]
(We should probably switch the maintainer to @mirage for that one)

**Comment by avsm** [comment]
Three PRs opened, should fix the lot of them. Thanks for the report!
