### ISSUE TITLE
omake.0.10.1 is totally broken

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam-repository#7960]
It is serious.

It still forgets to install library files under `$HOME/.opam/4.04.0/lib/omake`.

I strongly believe all the recent build failures of `omake` based packages are caused by this.  We should resign it until the package maintainer makes sure it builds packages successfully.

I confirmed this with `opam.1.2.2`.  It might be possible newer `opam`s can install `omake` properly, but I have never tried.

**Comment by camlspotter** [comment]
Please check #7964 . I have installed omake.0.10.1 with opam.1.2.2 and a clean switch 4.03.0. It does not install its important library files.

**Comment by fpottier** [comment]
I have just hit the same problem. Confirmed with clean 4.03.0 and clean 4.04.0.

**Comment by camlspotter** [comment]
I found the cause:  if `PREFIX` env var is defined, then `make install` uses it instead of the prefix given at `configure`.  Fix is PRed as https://github.com/ocaml/opam-repository/pull/8058

**Comment by camlspotter** [comment]
Now the issue is gone, by undefining `PREFIX`.  Unfortunately the behaviour of `omake.0.10.1` is a bit different from the previous version and causes strange incompatible cmi issues between byte and natives with my OMakefiles...
