### ISSUE TITLE
ppx_test.1.4.0 failure with omake 0.10.1

### ISSUE THREAD

**Issue by yallop** [ocaml/opam-repository#7995]
Symptoms:
```
# Error: Files ppx_test.cmo and /home/travis/.opam/4.03.0/lib/ppxx/ppxx.cmo
#        make inconsistent assumptions over interface Ppxx
# *** omake: targets were not rebuilt because of errors:
#    ppx/ppx_test.run
#       depends on: ppx
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=/home/travis/.opam/4.03.0\"' terminated with error code 2")
```

Travis build logs:
* https://travis-ci.org/ocaml/opam-repository/jobs/180491544

Discussion:
* [ppx_orakuda, ppx_test: relaxing ocaml-version constraints (#7857)](https://github.com/ocaml/opam-repository/pull/7857)
* [ppx_orakuda.3.0.1 ppx_test.1.4.0 work OCaml >= 4.03.0 (#7964)](https://github.com/ocaml/opam-repository/pull/7964)

Related:
* [omake.0.10.1 is totally broken (#7960)](https://github.com/ocaml/opam-repository/issues/7960)

/cc @rgrinberg, @camlspotter, @avsm

**Comment by rgrinberg** [comment]
Also the omake issue: https://github.com/ocaml-omake/omake/issues/71

**Comment by camlspotter** [comment]
This is a bug of OCamlPackage which does not work with parallel build.  `omake.0.10.1` builds things in parallel by default...

**Comment by camlspotter** [comment]
ppx_test.1.4.0 now uses its own fixed version of OCamlPackage, I guess it is now fixed.

**Comment by dbuenzli** [comment]
@camlspotter are you fully positive this is fixed ? If that is the case then this can be closed.

**Comment by camlspotter** [comment]
Yes, please close it.
