### ISSUE TITLE
Travis build on OSX lies about the OCaml version

### ISSUE THREAD

**Issue by smondet** [ocaml/opam-repository#7997]
Here
https://travis-ci.org/ocaml/opam-repository/builds/180773756

The last build says:

```
Setting environment variables from .travis.yml
$ export OCAML_VERSION=4.03
$ export OPAM_VERSION=1.2.2
```

but after building OCaml:

```
OCaml version
The OCaml toplevel, version 4.04.0
OPAM versions
1.2.2
```

**Comment by dbuenzli** [comment]
Looking at a recent build it seems that 4.03.0 is [being installed](https://travis-ci.org/ocaml/opam-repository/jobs/249532502#L909). Was this a glitch or do I misunderstand report ? If not I'd move on to close this.

**Comment by smondet** [comment]
Yes, works now. Closing. Thanks.
