### ISSUE TITLE
Alt-Ergo 0.99.1 package contains an invalid URL

### ISSUE THREAD

**Issue by fdupress** [ocaml/opam-repository#8002]
The source URL for alt-ergo.0.99.1 currently returns a 404 code. If the source archive has disappeared for good, the package should probably be removed from this repo and maintainers for packages that depend on Alt-Ergo 0.99.1 informed of the change.

**Comment by OCamlPro-Iguernlala** [comment]
I proposed the deletion of older versions of Alt-Ergo as they are "subsumed" by version 1.30. But the PR is not accepted yet:

https://github.com/ocaml/opam-repository/pull/7999

**Comment by fdupress** [comment]
Thanks. Deleting them from the repo would be a much better thing to do than leaving broken packages on, and infinitely better than leaving unpatched unsound versions of the prover lying around. You can quote me on this in the PR-related discussion.

**Comment by OCamlPro-Iguernlala** [comment]
I agree. Unsound versions should not be used. This is way I wanted to delete them.

**Comment by OCamlPro-Iguernlala** [comment]
(This issue can be closed)

**Comment by dbuenzli** [comment]
This issue should be closed.
