### ISSUE TITLE
Can't install `js_of_ocaml` with `--build-test`

### ISSUE THREAD

**Issue by OCamlPro-Henry** [ocaml/opam-repository#8048]
```
~ $ opam install -t js_of_ocaml
The actions to process have cyclic dependencies:
  - install bos.0.1.4 -> install base64.2.1.2 -> install js_of_ocaml.2.8.3 -> install mtime.0.8.3 -> install bos.0.1.4
  - install bos.0.1.4 -> install base64.2.1.2 -> install js_of_ocaml.2.8.3 -> install logs.0.6.2 -> install bos.0.1.4
```

`js_of_ocaml` does not have test dependencies per se, but I have a package with depends on `js_of_ocaml` and which also includes some test dependencies.

**Comment by OCamlPro-Henry** [comment]
@dbuenzli @AltGr any thoughs on this ? Is that something that @camelus should catch ?

**Comment by dbuenzli** [comment]
Sorry didn't see your ping. Tried this today I don't see this (the dep chain with `base64`  is dubious are you using the internal solver ?).

**Comment by OCamlPro-Henry** [comment]
Thanks for testing ! Indeed it works on my computer (with opam2 and aspcud) but it still fails on our CI. You might try to reproduce with : `docker run -it ocaml/opam opam install -t js_of_ocaml`.

@avsm is there anything specific to your docker image that might explain this failure ?

**Comment by avsm** [comment]
I'm not sure -- this seems like an opam 1.2 bug -- `docker run -it ocaml/opam-dev:ubuntu opam install -t js_of_ocaml` works with opam 2dev

**Comment by OCamlPro-Henry** [comment]
Ok thanks, since the repo seems OK I will close the issue.
