### ISSUE TITLE
OCaml compilers should install str.cmti

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam-repository#8049]
Many `.cmti` are already installed for the standard library but `str.cmti` is not.  Please fix that.

**Comment by dbuenzli** [comment]
I think this should have been solved by https://github.com/ocaml/ocaml/pull/827. If not report upstream.

**Comment by dbuenzli** [comment]
I think this can be closed.

**Comment by gasche** [comment]
I'm not sure actually where all `.cmti` that one would like are installed (I think people pointed out recently that some were omitted), but in any case this belongs to OCaml upstream rather than opam-repository I think.

**Comment by dbuenzli** [comment]
There is [MPR](https://caml.inria.fr/mantis/view.php?id=7556) but I checked `odig` against `4.05+rc1` and it seems both str.cmti and unix.cmti are installed.
