### ISSUE TITLE
Coqide 8.6, lablgtk without gtk-sourceview

### ISSUE THREAD

**Issue by jnarboux** [ocaml/opam-repository#8135]
Using Ubuntu 16.04.1 LTS Coqide 8.6 fails to install(@maximedenes) : 

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of coqide failed at "make install-ide-bin install-ide-files install-ide-info install-ide-devfile.
Processing  1/1: [coqide: rm]
=== ERROR while installing coqide.8.6 ========================================#
 opam-version 1.2.2
 os           linux
 command      make install-ide-bin install-ide-files install-ide-info install-ide-devfiles
 path         /home/jnarboux/.opam/system/build/coqide.8.6
 compiler     system (4.02.3)
 exit-code    2
 env-file     /home/jnarboux/.opam/system/build/coqide.8.6/coqide-14047-d2d111.env
 stdout-file  /home/jnarboux/.opam/system/build/coqide.8.6/coqide-14047-d2d111.out
 stderr-file  /home/jnarboux/.opam/system/build/coqide.8.6/coqide-14047-d2d111.err
 stdout ###
 make --warn-undefined-variable --no-builtin-rules -f Makefile.build install-ide-bin install-ide-files install-ide-info install-ide-devfiles
 make[1] : on entre dans le répertoire « /home/jnarboux/.opam/system/build/coqide.8.6 »
 install -d "/home/jnarboux/.opam/system/bin"
 install bin/coqide "/home/jnarboux/.opam/system/bin"
 Makefile.ide:128 : la recette pour la cible « install-ide-bin » a échouée
 make[1] : on quitte le répertoire « /home/jnarboux/.opam/system/build/coqide.8.6 »
 Makefile:153 : la recette pour la cible « submake » a échouée
### stderr ###
 install: impossible d'évaluer 'bin/coqide': Aucun fichier ou dossier de ce type
 make[1]: *** [install-ide-bin] Erreur 1
 make: *** [submake] Erreur 2
=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install coqide 8.6

lsb_release -d
Description:    Ubuntu 16.04.1 LTS

**Comment by jnarboux** [comment]
In fact the ./configure of Coq does not detect lablgtk2 :

- Incomplete LablGtk2 (via ocamlfind): no /home/jnarboux/.opam/system/lib/lablgtk2/gSourceView2.cmi.
- No such directory '/usr/lib/ocaml/lablgtk2' (in OCaml library).

The problem is that  having lablgtk package installed is not enough. One need one version compiled with support for gtksourceview. Is this information available in opam?

**Comment by maximedenes** [comment]
I don't understand how this is possible, since the coqide package does depend on the "conf-gtksourceview" virtual package, which I thought was precisely ensure that lablgtk is configured with sourceview. Does opam install gtk-sourceview succeed?

**Comment by maximedenes** [comment]
Also, in your two messages, you show two completely different errors. One is at `make install` time, the other at `./configure` time. Which one are you actually trying to solve?

**Comment by maximedenes** [comment]
Oh sorry, I got it. This is actually a limitation of the package. `configure.ml` does not ensure that CoqIDE is built. Here it says it won't be, but does not fail. Compilation goes on, until it tries to install CoqIDE.

**Comment by jnarboux** [comment]
Yes exactly.
First problem the ./configure should have failed.
Second problem: the depedency should express somehow the fact the lablgtk
should be compiled with support for gtksourceview.
The problem is that the lablgtk package you get using opam depends on the
linux distribution packages which are installed at compilation time...  the
same problem occurs IMHO with many source base distributions such as fink
etc... optional build dependency does mix well with opam packages.


2016-12-21 14:48 GMT+01:00 Maxime Dénès <notifications@github.com>:

**Comment by maximedenes** [comment]
Yes, but again, why did the `conf-gtksourceview` dependency fail to detect that?

**Comment by jnarboux** [comment]
Maybe : cong-gtksourceview has been installed at a time when gtksourceview
2.0 development packages were installed, but later an Ubuntu update has
removed the external packages,
opam does not know about the state of external packages.




2016-12-21 15:02 GMT+01:00 Maxime Dénès <notifications@github.com>:

**Comment by maximedenes** [comment]
Ok, so this would not be a Coq issue. From OPAM's standpoint, I guess if you are using system packages, you are (at least partially) responsible for installing the right ones. Wouldn't using a local switch solve your problem?

**Comment by jnarboux** [comment]
Let's close it. I solved my issue and I am not sure there is really something to fix in either opam nor opam packages, it seems to be a problem of the whole architecure mixing several package management systems.
Maybe the lablgtk package could test that the required files are really built, that the configure gives a result coherent with the depedency, to detect the errors earlier.
