### ISSUE TITLE
Move development compilers to their own repository

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam-repository#8141]
Follow-up of https://github.com/ocaml/opam/issues/2778 , posting here to track.

We may want to wait for opam 2.0, though, although it's not strictly required.

**Comment by dbuenzli** [comment]
This has been achieved via https://github.com/ocaml/opam-repository/pull/10385/. The compilers now live in https://github.com/ocaml/ocaml-pr-repository announce and discussion [here](https://discuss.ocaml.org/t/opam-compiler-prs-are-migrating-to-their-own-remote/905).
