### ISSUE TITLE
Opam 2.0: conf-* packages should probably not depend on `ocaml`

### ISSUE THREAD

**Issue by Drup** [ocaml/opam-repository#8236]
The migration script is a bit overzealous with dependency towards `ocaml`, I think the conf-* packages shouldn't have that dependency.

**Comment by AltGr** [comment]
It's very hard to know mechanically, and some of them do need it. Since this behaviour is consistent with opam 1.2, I chose to be prudent, and let us remove the unneeded dependencies once the repository has been statically migrated.
