### ISSUE TITLE
[WARNING] Directory /local/blanqui/.opam/4.02.3/lib/camlp5 is not empty, not removing

### ISSUE THREAD

**Issue by fblanqui** [ocaml/opam-repository#8262]
Hi. I would like to mention that I got the following warning:

09:12 ~ opam --version
1.2.2

09:11 ~ opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
...
[default] synchronized from https://opam.ocaml.org

...

Updates available for 4.02.3, apply them with 'opam upgrade':
===== ↻  7   ↗  8 =====
09:12 ~ opam upgrade
The following actions will be performed:
  ↻  recompile camlp4     4.02+7                [upstream changes]
  ↗  upgrade   camlp5     6.16 to 6.17        
 ...
===== ↻  7   ↗  8 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
...
[default] https://opam.ocaml.org/archives/camlp5.6.17+opam.tar.gz downloaded
...

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
...
[WARNING] Directory /local/blanqui/.opam/4.02.3/lib/camlp5 is not empty, not
          removing
⊘  removed   camlp5.6.16
...

**Comment by dbuenzli** [comment]
It seems that the latest version of `camlp5` still doesn't uninstall cleanly. 

Ping @mjustus the maintainer of the package and @hgouraud who seem to have added the uninstall instructions in 17f651528d53465ee7fed48f00792212ff20231c.


```
> opam remove camlp5
The following actions will be performed:
  ⊘  remove ledit  2.03                       [uses camlp5]
  ⊘  remove zenon  0.7.1                      [uses coq]
  ⊘  remove coq    8.6                        [uses camlp5]
  ⊘  remove camlp5 6.17 
===== ⊘  4 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[camlp5] Archive in cache
[coq] Archive in cache
[zenon] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
⊘  removed   ledit.2.03
⊘  removed   zenon.0.7.1
⊘  removed   coq.8.6
[WARNING] failure in package uninstall script, some files may remain:
          # opam-version 1.2.2
          # os           darwin
          # command      make uninstall
          # path         /Users/dbuenzli/.opam/4.03.0/build/camlp5.6.17
          # compiler     4.03.0
          # exit-code    2
          # env-file     /Users/dbuenzli/.opam/4.03.0/build/camlp5.6.17/camlp5-12139-d0f245.env
          # stdout-file  /Users/dbuenzli/.opam/4.03.0/build/camlp5.6.17/camlp5-12139-d0f245.out
          # stderr-file  /Users/dbuenzli/.opam/4.03.0/build/camlp5.6.17/camlp5-12139-d0f245.err
          ### stderr ###
          # Makefile:3: config/Makefile: No such file or directory
          # make: *** No rule to make target `config/Makefile'.  Stop.

[WARNING] Directory /Users/dbuenzli/.opam/4.03.0/lib/camlp5 is not empty, not removing
⊘  removed   camlp5.6.17
Done.
```

**Comment by dbuenzli** [comment]
Thanks @mjustus for the quick turnaround. In 1d7c0d35a9ff4e66319a3bd Justus gave up on `camlp5`'s package maintenance.  Thank you for your earlier work on the package Justus.

Since I believe this is an important package for `coq` users it would be good for someone to take over. I see that `camlp5` is now being developed [on github](https://github.com/camlp5/camlp5) so maybe @roglo himself wants to maintain the `camlp5` packages. If not maybe the maintainer of `coq` @maximedenes can suggest someone.

The person that wishes to take this role should simply add his email address in [this field](https://github.com/ocaml/opam-repository/blob/master/packages/camlp5/camlp5.7.00/opam#L2) of the package metadata (it is sufficient to do it only in the latest version).

**Comment by maximedenes** [comment]
Hello,

I don't see any reason why @roglo would not maintain the `camlp5` package. Otherwise, we'll see what we can do.
