### ISSUE TITLE
Citations of packages

### ISSUE THREAD

**Issue by bgraf** [ocaml/opam-repository#8331]
Some of the OCaml packages have a scientific background and published literature (e.g. ocamlgraph). It would be nice to have a feature that can at least generate citations regarding a specific package and version including its authors, release date and URL to the opam-website of the package.
Then these generated formats could be copied from the opam website or generated via the opam CLI.

This would give the OCaml community a consistent citation scheme for packages that may lack published papers. Additionally, published literature could be somehow linked to packages so that the resulting citation will show the actual literature.

When working with R, the `citation(..)` function struck me as rather handy. Example from R for an auto-generated citation and a citation of actual literature:

~~~~
> citation('corrplot')

  Taiyun Wei and Viliam Simko (2016). corrplot: Visualization of a
  Correlation Matrix. R package version 0.77.
  https://CRAN.R-project.org/package=corrplot

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {corrplot: Visualization of a Correlation Matrix},
    author = {Taiyun Wei and Viliam Simko},
    year = {2016},
    note = {R package version 0.77},
    url = {https://CRAN.R-project.org/package=corrplot},
  }
~~~~

~~~~
> citation('ggplot2')

  H. Wickham. ggplot2: Elegant Graphics for Data Analysis.
  Springer-Verlag New York, 2009.

A BibTeX entry for LaTeX users is

  @Book{,
    author = {Hadley Wickham},
    title = {ggplot2: Elegant Graphics for Data Analysis},
    publisher = {Springer-Verlag New York},
    year = {2009},
    isbn = {978-0-387-98140-6},
    url = {http://ggplot2.org},
  }
~~~~

Are there any recommendations for the format, way to implement it or arguments against it?

**Comment by avsm** [comment]
i don't know the best scheme for this yet, but wanted to voice my support for it as a very useful idea!

**Comment by bgraf** [comment]
Not sure whether I should have added this issue to the opam CLI's repository instead.

Anyway, a citation / BibTex generator would semantically best fit somewhere in the `opam show` command. It will display information about a specific package.

Here's some data: given the a rather fresh upgrade (1-2 days ago) and the most recent version of each package, we have:

* Number of packages: 1480
* Number of packages with author[s] specified: 1205 (81%)
* Number of packages where at least one specified author contains an @-sign: 674 (45%)
* Number of packages where at least one author name consists of greater equal five tokens: 94 (6%)

Given the different informations that authors provide in their opam-files, any implementation will need to resort to some kind of heuristic. Strip email-addresses, try to detect real persons vs. groups (The XYZ team) and other forms like "Real Name and the gang".

**Comment by emillon** [comment]
For the record, the Debian tries to solve this problem is by having [a file containing upstream metadata](https://wiki.debian.org/UpstreamMetadata). In particular the `Cite-As` and `Reference` fields may be relevant to this discussion.

**Comment by dbuenzli** [comment]
It seems that both what @bgraf @emillon are suggesting are better discussed on the `opam` issue tracker. If everyone agrees then I'll let you open an issue there and will proceed to close this.
