### ISSUE TITLE
why 2.36 installation failed

### ISSUE THREAD

**Issue by jnarboux** [ocaml/opam-repository#8353]
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of why failed at "make install".
Processing  1/1: [why: rm]
#=== ERROR while installing why.2.36 ==========================================#
# opam-version 1.2.2
# os           linux
# command      make install
# path         /home/jnarboux/.opam/system/build/why.2.36
# compiler     system (4.02.3)
# exit-code    2
# env-file     /home/jnarboux/.opam/system/build/why.2.36/why-27707-c61e7b.env
# stdout-file  /home/jnarboux/.opam/system/build/why.2.36/why-27707-c61e7b.out
# stderr-file  /home/jnarboux/.opam/system/build/why.2.36/why-27707-c61e7b.err
### stdout ###
# [...]
# if test -w "/home/jnarboux/.opam/system/lib/coq" ; then \
#   rm -f "/home/jnarboux/.opam/system/lib/coq"/user-contrib/Why*.v* ; \
#   rm -f "/home/jnarboux/.opam/system/lib/coq"/user-contrib/caduceus*.v* "/home/jnarboux/.opam/system/lib/coq"/user-contrib/Caduceus*.v* ; \
#   rm -f "/home/jnarboux/.opam/system/lib/coq"/user-contrib/jessie*.v* "/home/jnarboux/.opam/system/lib/coq"/user-contrib/Jessie*.v* ; \
#   mkdir -p "/home/jnarboux/.opam/system/lib/coq"/user-contrib/Why ; \
#   cp -f  "/home/jnarboux/.opam/system/lib/coq"/user-contrib/Why ; \
# else \
#   echo "Cannot copy to Coq standard library. Add \"-R /home/jnarboux/.opam/system/lib/why/coq Why\" to Coq options." ;\
# fi
# Makefile:803 : la recette pour la cible « install-coq-v8 » a échouée
### stderr ###
# cp: opérande de fichier cible manquant après '/home/jnarboux/.opam/system/lib/coq/user-contrib/Why'
# Saisissez « cp --help » pour plus d'informations.
# make: *** [install-coq-v8] Erreur 1

**Comment by jnarboux** [comment]
@claudemarche It seems that a target directory of a cp command is missing.

**Comment by claudemarche** [comment]
fixed in why master. Note: this error could happen only if Coq is installed but Why3 did not compile Coq realizations of the Why3 stdlib. This is unlikely to happen, so there might another problem in the process of installation of why3 via opam

**Comment by dbuenzli** [comment]
It seems that this has been fixed upstream and at least [two releases](https://scm.gforge.inria.fr/anonscm/gitweb?p=why/why.git;a=blob_plain;f=CHANGES;hb=HEAD) happenned since then; so I think this can be closed.
