### ISSUE TITLE
opam 1.2.2 fail to install melt

### ISSUE THREAD

**Issue by tddsg** [ocaml/opam-repository#8362]
Hello,

I tried to install the `melt` package using Opam 1.2.2 and always encountered the error

```
opam install melt
Your request can't be satisfied:
  - No package matches melt.

No solution found, exiting
```

This happens with both the two versions of my OCaml compiler 4.3.0 and 4.4.0.

It was used to be OK for me to install `melt` using opam (early 2016), 
so I wonder if there is something wrong with the current version of melt or opam?

**Comment by yallop** [comment]
`melt` [depends on `mlpost`](https://github.com/ocaml/opam-repository/blob/d6def012f6097315bab6838e0758e953523e4935/packages/melt/melt.1.4.0/opam#L18), which is [only available for OCaml versions below 4.03.0](https://github.com/ocaml/opam-repository/blob/d6def012f6097315bab6838e0758e953523e4935/packages/mlpost/mlpost.0.8.1/opam#L37).  So you should still be able to install `melt` with OCaml 4.02.3, but it's not expected to be installable on 4.03.0 or 4.04.0.

**Comment by tddsg** [comment]
Hi, Thanks for the update! 
Is this a temporary or a permanent decision for `melt` and `mlpost` to be not available in OCaml 4.03.0 and above?

**Comment by yallop** [comment]
@bobot, are there plans for a 4.03/4.04-compatible release of mlpost?

**Comment by dbuenzli** [comment]
It seems that since https://github.com/ocaml/opam-repository/commit/debd9e3f2b8d07a15b8f5a06837ee9d28791d23c at least 4.04 is supported. In any case the questions raised by @tddsg are to be answered by upstream and I think this can be closed.
