### ISSUE TITLE
Wrong error message when conf-gtksourceview fails to install

### ISSUE THREAD

**Issue by gallais** [ocaml/opam-repository#8449]
I've been trying to install `coqide` this evening and I kept getting errors on `conf-gtksourceview` despite the fact that I had the package `libgtksourceview2.0-dev` installed on my debian. See [1] for a typical failing build. Running the command `pkg-config gtksourceview-2.0` which AFAICT is supposed to be the failing one does not help at all: it exits almost immediately, and does not print anything.

After a lot of googling, I thought of checking coq's bug tracker and found [this thread](https://coq.inria.fr/bugs/show_bug.cgi?id=4307) from which I took the expanded `pkg-config --short-errors --print-errors "gtksourceview-2.0 >= 2.2.0"`. This one does print more information and ultimately led me to upgrade the package `x11proto-randr-dev` (upon which `xrandr` depends).

In short: `conf-gtksourceview` might fail to install not because `libgtksourceview2.0-dev` is missing but because other packages need to be upgraded. It would be nice to have that information (and the command-line to run to find the culprits) in the troubleshooting section.

[1]

    gallais@traba:~★ opam install coqide
    The following actions will be performed:
      ∗  install conf-gtksourceview 2             [required by coqide]
      ∗  install lablgtk            2.18.5        [required by coqide]
      ∗  install coqide             8.6   
    ===== ∗  3 =====
    Do you want to continue ? [Y/n] y

    =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [coqide] Archive in cache
    [lablgtk] Archive in cache

    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [ERROR] The compilation of conf-gtksourceview failed at "pkg-config gtksourceview-2.0".

    #=== ERROR while installing conf-gtksourceview.2 ==============================#
    # opam-version 1.2.2
    # os           linux
    # command      pkg-config gtksourceview-2.0
    # path         /home/gallais/.opam/4.03.0/build/conf-gtksourceview.2
    # compiler     4.03.0
    # exit-code    1
    # env-file     /home/gallais/.opam/4.03.0/build/conf-gtksourceview.2/conf-gtksourceview-30217-5f1023.env
    # stdout-file  /home/gallais/.opam/4.03.0/build/conf-gtksourceview.2/conf-gtksourceview-30217-5f1023.out
    # stderr-file  /home/gallais/.opam/4.03.0/build/conf-gtksourceview.2/conf-gtksourceview-30217-5f1023.err

    =-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    The following actions were aborted
      ∗  install coqide  8.6   
      ∗  install lablgtk 2.18.5
    The following actions failed
      ∗  install conf-gtksourceview 2
    No changes have been performed

    =-=- conf-gtksourceview.2 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    => This package requires gtksourceview 2.0 development packages installed on your system

**Comment by dbuenzli** [comment]
/cc @maximedenes 

I added the suggested `--short-errors --print-errors` to the configure invocation in #9699 so as potentially to fail in a less obscure fashion. I'm not sure if something better can be done so I'm going to close this. Feel free to reopen, comment or PR if you think this can be further improved.
