### ISSUE TITLE
Another acme? 

### ISSUE THREAD

**Issue by mmaker** [ocaml/opam-repository#8652]
hello!
I'm taking care to write an [`ACME`](https://en.wikipedia.org/wiki/Automated_Certificate_Management_Environment) client in ocaml.

I'd like to publish it in opam, since there's a command-line tool that allows to obtain/renew certificates from letsencrypt, and given that some folks around mirageos might need it, <https://github.com/mmaker/ocaml-acme>.

Ironically, there's already an "acme" [package](https://github.com/ocaml/opam-repository/blob/master/packages/acme/acme.0.1/opam) in opam from @raphael-proust , which deals with something completely different (a text editor). It provides also a module Acme, and the repository name is [ocaml-acme](https://github.com/raphael-proust/ocaml-acme/).

I'm not sure what's the best thing to do in order to publish it. Is there some convention to follow for these cases? 
I could rename the project to`letsencrypt`, `acmewastaken` or `realacme`, but at that point I shall change also the github.com url and the module name, or add acme to `conflicts`?
If so, what module name do you think I should give?

**Comment by dbuenzli** [comment]
> I could rename the project toletsencrypt, acmewastaken or realacme, but at that point I shall change also the github.com url and the module name

Yes.

> or add acme to conflicts?

That would be insane. Simply find another name.
