### ISSUE TITLE
JaneSt v0.9.0 packages can break output of `js_of_ocaml` in existing packages

### ISSUE THREAD

**Issue by smondet** [ocaml/opam-repository#8787]
Documenting the issue here, in case other people hit it.

Packages with a (transitive) dependency to `ppx_sexp_conv` (or maybe other JaneSt ppxs), that use `js_of_ocaml` need a new JS primitive.
`js_of_ocaml` only outputs a warning, so the package builds, but then the JS code fails with an exception at startup (that function must be called by some (generated?) module initialization code).

Cf. more details at https://github.com/janestreet/ppx_inline_test/issues/7

This fixed it for me (on `master`):

```
conflicts: [
  "ppx_inline_test" { >= "v0.9.0" }
  "ppx_sexp_conv" { >= "v0.9.0" }
]
```

(I think `"ppx_sexp_conv"` is the one that actually worked)

**Comment by hhugo** [comment]
This new primitive comes from base. One should pass the extra runtime file to js_of_ocaml (call js_of_ocaml with `+base/runtime.js`)

Alternatively, adding a single contraint on base should be enough. 
```
conflicts: [
  "base" { >= "v0.9.0" }
]
```

**Comment by dbuenzli** [comment]
What's the status of this ? @diml @avsm were the revdeps correctly contraints when v0.9.0 was merged into the repo ? If that is the case then I think this can be closed.

**Comment by dbuenzli** [comment]
This doesn't seem to be an issue with the repository per se. So I'm closing.
