### ISSUE TITLE
frama-c gui is not installed

### ISSUE THREAD

**Issue by mottainai** [ocaml/opam-repository#880]
When installing frama-c.20130601 under OSX 10.8.4 with opam, the Frama-C gui is not installed. (As an aside, I have no problem to install the coqide through opam.) 
The following excerpt from the output of "opam install --verbose frama-c.20130601" indicates the problem, but I have no idea ho to solve it.

Regards

Jens

configure: WARNING: lablgtksourceview2.cmxa not found
configure: WARNING: gui disabled because /Users/jens/.opam/system/lib/lablgtk2/lablgtksourceview2.cmxa missing.
configure: WARNING: gui disabled because /Users/jens/.opam/system/lib/lablgtk2/lablgtksourceview2.cmxa missing.
configure: WARNING: lablgnomecanvas.cmxa not found
configure: WARNING: gui disabled because /Users/jens/.opam/system/lib/lablgtk2/lablgnomecanvas.cmxa missing.

**Comment by lefessan** [comment]
Closing issue on an old package. Reopen if still relevant.
