### ISSUE TITLE
xmln.1.3.0 breaks lablgtk-extras1.5

### ISSUE THREAD

**Issue by ejgallego** [ocaml/opam-repository#8815]
Output:
```
Package xmlm found with version v1.3.0, but wanted >= 1.1
```
cc: @dbuenzli @zoggy 
cf: coq/coq#492

**Comment by maximedenes** [comment]
What should we do to get some feedback on this issue? It is breaking the build of Coq under OPAM.

**Comment by zoggy** [comment]
I'll make a new lablgtk-extras release right now.

**Comment by maximedenes** [comment]
Great, thanks a lot!

**Comment by zoggy** [comment]
https://github.com/ocaml/opam-repository/pull/8922 .
By the way, I moved lablgtk-extras for ocamlcore to https://github.com/zoggy/lablgtk-extras .

**Comment by ejgallego** [comment]
This is fixed thanks a lot!!
