### ISSUE TITLE
Explicitly disabling "... is not empty, not removing" warning

### ISSUE THREAD

**Issue by maroneze** [ocaml/opam-repository#8998]
The `frama-c-base` and `frama-c` packages use a non-standard configuration for their files: `frama-c-base` puts all of its files in subdirectories named `frama-c`. One consequence of this renaming is that, when package `frama-c` is uninstalled, nothing is removed. This is intentional, and it works, except that when doing `opam remove frama-c`, OPAM always emits warnings:

    Directory $OPAM/lib/frama-c is not empty, not removing
    Directory $OPAM/share/frama-c is not empty, not removing

The warning is not necessary here, because these files were installed by `frama-c-base`, and when this package is removed, those directories will be properly erased.

Is there a way to tell OPAM to explicitly avoid such warnings?

**Comment by dbuenzli** [comment]
This seems more to be a question for the `opam` the tool issue tracker. /cc @AltGr

**Comment by AltGr** [comment]
opam 2.0 tracks files and doesn't have this message anymore.
