### ISSUE TITLE
ocp-build.1.99.19-beta checksum wrong?

### ISSUE THREAD

**Issue by djs55** [ocaml/opam-repository#9110]
I see this:
```
=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] Bad checksum for /Users/djs/.opam/packages.dev/ocp-build.1.99.19-beta/1.99.19-beta.tar.gz:
          - c932e1d6a90c5a545c864c10a92f2af2 [expected result]
          - e4d5e3bc256091b5907a43613c33411c [actual result]
        This may be fixed by running `opam update`.

[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocp-build.1.99.19-beta
        (This may be fixed by running 'opam update')
```
When I `wget http://github.com/OCamlPro/ocp-build/archive/1.99.19-beta.tar.gz` and run `md5sum` myself I get the "actual" rather than the "expected" result also. Perhaps the github generated .tar.gz has changed since initial publication?

For now I'm using the previous version with `opam pin add ocp-build.1.99.18-beta`

**Comment by avsm** [comment]
see https://github.com/ocaml/opam-repository/pull/9097

**Comment by avsm** [comment]
which package pulls in this dependency for you @djs55?

**Comment by djs55** [comment]
Good question -- I suspect it was `ocp-indent`. I probably installed that in my opam root a while ago.

**Comment by dbuenzli** [comment]
In the current state of the repository this problem is solved and I think this can be closed.
