### ISSUE TITLE
Fedora CI failing

### ISSUE THREAD

**Issue by yallop** [ocaml/opam-repository#9115]
The Fedora datakit CI is failing [fairly consistently with messages like this](https://ci.ocaml.io/log/saved/docker-build-ecff66c2ede2344dd1e20aa84fd763d8/2e5e929b75182bdfff0039eb4a14ce7f6ef94411):

```
[WARNING] External solver failed with inconsistent return value. Request saved
          to "/home/opam/.opam/log/solver-error-42-1.cudf"
```

**Comment by avsm** [comment]
need to check if its only happening on opam2... probably some problem with the wrapper script.

**Comment by samoht** [comment]
This particular issues has been fixed, but there is now a new one, tracked by https://github.com/avsm/mirage-ci/issues/2
