### ISSUE TITLE
OpenSUSE repo's broken

### ISSUE THREAD

**Issue by itsnotv** [ocaml/opam-repository#9222]
These repositories are down(404) and I am unable to install opam.

http://download.opensuse.org/repositories/home:/ocaml/Debian_7.0/
http://download.opensuse.org/repositories/home:ocaml/CentOS_7/home:ocaml.repo

**Comment by itsnotv** [comment]
Also

http://software.opensuse.org/download.html?project=home%3Aocaml&package=opam (503)

**Comment by avsm** [comment]
Looks like they've been retired; that explains why the OpenSUSE CI tests were failing.

**Comment by javergar** [comment]
@avsm Any chance to get this fixed, any known workaround?

**Comment by samoht** [comment]
Tracked by https://github.com/avsm/mirage-ci/issues/4
