### ISSUE TITLE
missing package: ocaml-js-stdlib

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/opam-repository#9273]
The following packages have a dependency on `ocaml-js-stdlib`, which does not exist in `opam-repository`. Is this on purpose?

* `cordova-plugin-datepicker.1.0`
* `cordova-plugin-device-motion.1.0`
* `cordova-plugin-globalization.1.0`

cc @dannywillems

**Comment by dannywillems** [comment]
I can make a PR if it's very necessary. It was not done previously because it must be improved.

**Comment by avsm** [comment]
@dannywillems we need to keep the constraints in the main opam repository consistent, so we either need to remove the vestigial dependency until it is ready, or import the package.  Which one we do is up to you though -- if you feel it isnt ready then removing the dependency is fine.

**Comment by dannywillems** [comment]
@avsm I don't think I will work on ocaml-js-stdlib until a long time (as I don't write a lot of web app anymore). Maybe remove it in the opam files will be better. PR is coming.

**Comment by dannywillems** [comment]
See #9277 @avsm @damiendoligez
