### ISSUE TITLE
missing package: dsfo

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/opam-repository#9275]
The package `oml.0.0.7` test-depends on `dsfo`, which doesn't exist in `opam-repository`.

cc @rleonid

**Comment by dbuenzli** [comment]
Ping @rleonid the maintainer of the `dsfo` package. 

@samoht informs me that by policy the opam-repository is supposed to be a closed package universe. So could you please either publish `dfso` on the opam-repository or, if that's not possible, remove the your `dfso {test}` constraints and the `build-test:` section of your opam files.

Thanks.

**Comment by rleonid** [comment]
I'm sorry for the delay. I've submitted dsfo to opam https://github.com/ocaml/opam-repository/pull/9716 .

**Comment by dbuenzli** [comment]
No worries, we are just cleaning a bit the issue tracker. Thanks for the submission.

**Comment by dbuenzli** [comment]
Closed by #9716
