### ISSUE TITLE
missing package: oth

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/opam-repository#9276]
The following packages test-depend on `oth`, which doesn't exist in `opam-repository`.

* `lua_pattern.1.7`
* `snabela.1.0`

**Comment by dbuenzli** [comment]
Ping @orbitz the maintainer of `lua_pattern` and  @mmatalka (I presume, sorry if that's not the case) the maintainer of `snabela`. 

@samoht informs me that by policy the `opam-repository` is supposed to be a closed package universe. So could you please either publish `oth` on the opam-repository or, if that's not possible, remove the your `oth {test}` constraints and the `build-test:` section of your opam files.

Thanks.

**Comment by orbitz** [comment]
@dbuenzli Addressed in https://github.com/ocaml/opam-repository/pull/9718

**Comment by dbuenzli** [comment]
Fantastic ! Thanks for the quick turnaround.
