### ISSUE TITLE
dependency bug in mirage-profile

### ISSUE THREAD

**Issue by stedolan** [ocaml/opam-repository#9363]
I tried to install `charrua-core` on a clean 4.04 switch (well, `4.04.0+afl`) and it failed to install `mirage-profile` due to `ppx_cstruct` not being installed.

`ppx_cstruct` got pulled in by some other dependency, so it worked next time.

[full logs here](https://gist.github.com/stedolan/788fae4f185ebae1002eca34a708d4db)

**Comment by dbuenzli** [comment]
This has been solved by https://github.com/ocaml/opam-repository/commit/eb36bb6d7a77bf9ad89e81b37742c8bc4ac92cb6 and can be closed.
