### ISSUE TITLE
conf-gmp: fail on osx with MacPorts

### ISSUE THREAD

**Issue by mandel** [ocaml/opam-repository#9389]
On Mac osx, the MacPorts package manager install its packages in `/opt`.
Therefore, the compilation of the package `conf-gmp` fails because`gmp.h` is in the directory `/opt/local/include/` and not in `/usr/local/include`.

**Comment by dbuenzli** [comment]
Related to #3000. This `gmp` configuration issue seems to be un serpent de mer.

**Comment by dbuenzli** [comment]
Closed by #9728.

**Comment by antonvoo** [comment]
I put copies of the gmp include files in /usr/local/include but this did not solve the problem.
