### ISSUE TITLE
fix mlgmp failing to build

### ISSUE THREAD

**Issue by xnox** [ocaml/opam-repository#9634]
Below should fix https://github.com/ocaml/opam-repository/commit/49a5b8e0c94cff1a0009eba66fdb75a47500dd64

```
Description: Update extern declarations for [de]serialize functions to match ocaml 4.04 definitions.
Author: Dimitri John Ledkov <xnox@ubuntu.com>

--- mlgmp-20021123.orig/config.h
+++ mlgmp-20021123/config.h
@@ -58,11 +58,11 @@
 #define MPFR_SIZE_ARCH32 16
 #define MPFR_SIZE_ARCH64 24
 
-extern void serialize_int_4(int32 i);
+extern void serialize_int_4(int32_t i);
 extern void serialize_block_1(void * data, long len);
 
-extern uint32 deserialize_uint_4(void);
-extern int32 deserialize_sint_4(void);
+extern uint32_t deserialize_uint_4(void);
+extern int32_t deserialize_sint_4(void);
 extern void deserialize_block_1(void * data, long len);
 
 #endif /* SERIALIZE */
```

**Comment by dbuenzli** [comment]
ping @nberth who is the maintainer of the package and @monniaux who is the author.  Could please the patch make it upstream and be turned into a new release to support the latest OCaml releases ?

**Comment by dbuenzli** [comment]
Thanks @nberth for the quick turnaround.

**Comment by bluddy** [comment]
Thank @nberth. Would it be possible to start a github repo for mlgmp? It would make it easier to make these kinds of changes in the future.

**Comment by nberth** [comment]
Hi @bluddy. Yes this would indeed be easier. Yet note that I already maintain the more recent [mlgmpidl](https://opam.ocaml.org/packages/mlgmpidl/) package that fits pretty-much the same purpose as `mlgmp`. `mlgmpidl` has its [repository](https://github.com/nberth/mlgmpidl) on github already, and AFAIK interfaces of the bindings they provide are similar (modulo renamings).

**Comment by bluddy** [comment]
Thanks for letting me know, @nberth. A couple of points:

a. It would be really nice to have the github URL of the mlgmpild package in its opam file, so the repo can be easily found (use the 'dev-repo' field).
b. I'm not a consumer of mlgmp myself, but I'm assisting someone who just started working on a very large closed-source codebase which makes use of mlgmp. Therefore, it's not up to me to make the decision to switch. Up until this change in mlgmp, the organization using mlgmp was having serious issues finding an OCaml version that satisfied the constraints of mlgmp together with their other requirements. Thanks for incorporating the update -- they should now be able to use the latest version of OCaml.
c. Perhaps a note in mlgmp's README could suggest mlgmpidl as a newer replacement.
d. Regardless, I think every OPAM package (even outdated ones) should have a github repo available for contributions, bug reports, easy cloning, forking etc. It's just the modern way of doing open-source coding.

**Comment by monniaux** [comment]
On 03/07/2017 17:17, Yotam Barnoy wrote:
>
> Thank @nberth <https://github.com/nberth>. Would it be possible to
> start a github repo for mlgmp? It would make it easier to make these
> kinds of changes in the future.
>
Done.
>
https://github.com/monniaux/mlgmp

-- 
David Monniaux
directeur de recherche au CNRS, laboratoire VERIMAG
Université Grenoble Alpes
http://www-verimag.imag.fr/~monniaux/

**Comment by bluddy** [comment]
Awesome. Thanks!
