### ISSUE TITLE
Alpine 3.5 depext broken when combining mysql/mariadb and openssl

### ISSUE THREAD

**Issue by hcarty** [ocaml/opam-repository#9640]
The Alpine Linux 3.5 mariadb-dev package requires libressl-dev.  conf-ssl in opam depends on openssl-dev for Alpine.  Alpine 3.5 has both packages available but they conflict with one another, making it impossible to install OCaml bindings for MySQL/MariaDB and bindings for ssl at the same time.

One potential fix for this would be to change the alpine depext to use the libressl-dev package rather then openssl-dev.  Unfortunately libressl-dev is not available on Alpine pre-3.5.

**Comment by avsm** [comment]
For alpine it's probably ok to support the latest only, since it's used as a container os... 3.5+ is already two versions, so depending on libressl is fine by me

**Comment by hcarty** [comment]
Ok thanks @avsm - I'll make a PR to change the Alpine ssl depext to libressl.

**Comment by dbuenzli** [comment]
@hcarty we are keen on hearing back from you with a PR !

**Comment by hcarty** [comment]
Thanks for the ping @dbuenzli!  PR #9747 will hopefully take care of the issue.  Should work on Alpine 3.5, 3.6 and edge.
