### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-repository#9687]
Recent wandering into this issue tracker seem to indicate that there's a disconnection between people reporting issues and people fixing them: a lot of the open issues here are actually already fixed.

Even though I'm not sure people actually read them, I suggest adding CONTRIBUTING.md file to entice fixers to have a quick lookup on the issue tracker to see if their fix is not killing a few issues.

This could also be the opportunity to define a minimal format for people reporting issues to minimize the number of message that are needed to be able to issue a diagnostic. 

In particular it would be good to always ask for an `opam config report`. Though usually most of the info there can be inferred by looking at the user file paths (but that may change with opam2 local repos), it's useful to spot usage of internal solver problems and outdated report via the `last-update` field (which would benefit of being a git repository hash rather than a date see https://github.com/ocaml/opam/issues/2982).

**Comment by dbuenzli** [comment]
> In particular it would be good to always ask for an opam config report.

Now that I'm thinking of it, it seems better if install error reports do report all the relevant info, I'm going to alter https://github.com/ocaml/opam/issues/2982 to ask for this.

**Comment by samoht** [comment]
That seems like a very good idea. Would you be able to send a PR for this?

And thanks for your work on cleaning up issues, I will make a pass to close the ones that you pointed out.

**Comment by dbuenzli** [comment]
> Would you be able to send a PR for this?

Yes.
