### ISSUE TITLE
Fix logtk.0.8.1 constraints

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-repository#9733]
Ping @c-cube the maintainer of logtk. The package's constraints are completely wrong which shows up as false positives in the CI revdep testing.  

There have been a few unsuccessful attempts at fixing this in https://github.com/ocaml/opam-repository/pull/9731 and https://github.com/ocaml/opam-repository/pull/9322. But it seems doing this properly needs a bit more knowledge about the software and its actual dependencies. 

Could you please fix this ? Consult the CI logs of the mentioned PRs for actual errors.

**Comment by dbuenzli** [comment]
Closed by #9740.

**Comment by c-cube** [comment]
Apologies again for the mess.
