### ISSUE TITLE
Odd Invalid_argument failure with code built using 4.05+beta3+mingw64

### ISSUE THREAD

**Issue by johnwhitington** [ocaml/opam-repository#9780]
I don't know where to start with this one, so I'll start here and hope you can direct me to the right place. I just have a suspicion its not a compiler bug as such, because it works on Mac and Linux.

When running code which works on Mac/Linux 4.05.0+trunk, on Win64, I get...

```
Fatal error: exception Sys_error("\\:/OCaml64/home/JohnWhitington/.opam/4.05.0+beta3+mingw64/lib/ocaml\\camlinternalFormatBasics.ml: Invalid argument")
```

...which is particularly odd, not least because `camlinternalFormatBasics.ml` doesn't mention Invalid argument anywhere within its source. The code does use the `Format` module though, and I can confirm it isn't during module initialisation.

Unfortunately, this code depends on compiler-libs, so I can't try it with an earlier OCaml compiler version due to API differences.

Does anyone recognise this?

**Comment by dbuenzli** [comment]
I think http://discuss.ocaml.org or the ocaml mailing list would be a better place to post these kind of issues.
