### ISSUE TITLE
build success/failure report

### ISSUE THREAD

**Issue by fccm** [ocaml/opam-repository#982]
I would like to produce a complete exhaustive report of everything that builds "out-of-the-box" and everything that doesn't and when it doesn't with the error message.

Is there already a feature or a solution for this?

In case not, which method would you recommend?
a bash script? or an ocaml script?
When the build fails is there an easy way to get automatically the file that contains the errors?

**Comment by dbuenzli** [comment]
There is https://github.com/OCamlPro/opam-builder. I think this can be closed.

**Comment by gasche** [comment]
`opam-builder` continuously monitors the health of the whole repository on one specific machine (I think it's a Debian environment), while [ci.ocaml.io](https://ci.ocaml.io/pr) test PRs to opam-repository under many different distributions/systems for portability.
