### ISSUE TITLE
coq 8.6 install failure

### ISSUE THREAD

**Issue by cartazio** [ocaml/opam-repository#9841]
```
16:19:50 ~/l/m/mathcomp $ opam install "coq.8.6"
The following actions will be performed:
  ∗  install coq 8.6

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[coq] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of coq failed at "make -j1".
Processing  1/1: [coq: rm]
#=== ERROR while installing coq.8.6 ===========================================#
# opam-version 1.2.2
# os           darwin
# command      make -j1
# path         /Users/carter/.opam/system/build/coq.8.6
# compiler     system (4.04.2)
# exit-code    2
# env-file     /Users/carter/.opam/system/build/coq.8.6/coq-45134-e7966f.env
# stdout-file  /Users/carter/.opam/system/build/coq.8.6/coq-45134-e7966f.out
# stderr-file  /Users/carter/.opam/system/build/coq.8.6/coq-45134-e7966f.err
### stdout ###
# [...]
# OCAMLDEP  checker/indtypes.mli
# OCAMLDEP  checker/esubst.mli
# OCAMLDEP  checker/environ.mli
# OCAMLDEP  checker/declarations.mli
# OCAMLDEP  checker/closure.mli
# OCAMLDEP  checker/cic.mli
# OCAMLDEP  checker/check_stat.mli
# OCAMLDEP  checker/analyze.mli
# "/Users/carter/.opam/system/bin/ocamlfind" ocamlc -rectypes  -c grammar/compat5.ml
# OCAMLC -c -pp grammar/gramCompat.mlp
### stderr ###
# [...]
# File "tools/ocamllibdep.mll", line 188, characters 21-38:
# Warning 3: deprecated: String.capitalize
# Use String.capitalize_ascii instead.
# Error while loading "/Users/carter/.opam/system/lib/camlp5/pa_extend.cmo": interface mismatch on Pcaml.
# File "grammar/gramCompat.mlp", line 1:
# Error: Error while running external preprocessor
# Command line: "/usr/local/bin/camlp5o" -I "/Users/carter/.opam/system/lib/camlp5"  pa_extend.cmo q_MLast.cmo pa_macro.cmo -DOCAML404 -loc loc -impl 'grammar/gramCompat.mlp' > /var/folders/py/wgp_hj9d2rl3cx48yym_ynj00000gn/T/ocamlppfbf886
#
# make[1]: *** [grammar/gramCompat.cmo] Error 2
# make: *** [submake] Error 2

```

**Comment by dbuenzli** [comment]
It seems that you are using a `system` compiler and that you also have `camlp5` installed via your system packager which seems to lead in some of the tool being confused. 

I suggest you to use try a non system switch, system switches are notoriously brittle. Do: 

`opam switch 4.04.2 && eval $(opam config env) && opam install camlp5`

it worked here.

**Comment by dbuenzli** [comment]
Another option would be to try to use the system compiler but uninstall the system `camlp5` that you have installed.

**Comment by dbuenzli** [comment]
Also another reason of the failure maybe that you did not do an `eval $(opam config env)` before trying to install `coq`. If you didn't try the other solutions I mention could you please first try this and report if there's any other (because if there is in that case I'd something is wrong with coq's build system).

**Comment by dbuenzli** [comment]
@cartazio Did any of the things I mentioned work for you ?

**Comment by cartazio** [comment]
I got it working.

One thing that's not documented is what name spaces are assigned to coq
libs installed via opam.

Eg i was surprised that the mathcomp-ssreflect package has a mathcomp
prefix in how it's to be imported in coq.

Is there any clear way to look that up when I install stuff?

**Comment by dbuenzli** [comment]
Thanks for the answer. Could you however tell us what worked in the end ? 

Regarding the packaging structure of coq packages I'm afraid I don't know anything about coq so I can't really help you with that. I guess these questions may be better answered on the  [`coq-club` mailing list](https://coq.inria.fr/community) or on the issue tracker of  [OPAM coq repos](https://github.com/coq/opam-coq-archive).

**Comment by dbuenzli** [comment]
Without further information from the reporter it's difficult to know what went wrong exactly so I'm closing this.
