### ISSUE TITLE
Fail to detect that GnuTLS has been compiled without SRP support

### ISSUE THREAD

**Issue by Batouu** [ocaml/opam-repository#9865]
OS : Centos 7.2;
versions : ocamlnet-4.1.2 ; camlcrush-1.0.8; gnutls 3.3.8-12.el7_1.1

When i'm trying to compile camlcrush with the command "make", i got several errors caused by nettls-gnutls from ocamlnet. 

`./configure --with-idlgen --with-rpcgen --with-libnames="softhsm" --withssl --with-ssl-clientfiles='path;ca=/opt/pki/certs/ca.crt,cert=/opt/certs/camlcrushclt.crt,privkey=/opt/pki/certs/camlcrushclt.key' --with-client-socket=tcp,192.xxx.xxx.xx:4444

make[1] : on entre dans le répertoire « /opt/sources/caml-crush-1.0.8/src/pkcs11proxyd »
#Compile Server
ocamlfind ocamlopt -pp "camlp4o pa_macro.cmo -I . -DWITH_SSL " -package "netplex" -I ../filter/filter -I ../filter/frontend -package "nettls-gnutls" -I ../bindings-pkcs11 -I ../rpc-pkcs11 -o server -c ./server.ml
ocamlfind ocamlopt -I ../filter/filter -I ../filter/frontend -package "str,netplex,config-file" -package "nettls-gnutls" -linkpkg ../bindings-pkcs11/pkcs11.cmxa ../filter/backend/backend.cmx ../filter/filter/filter_common.cmx ../filter/filter/filter_actions.cmx ../filter/filter/filter_configuration.cmx ../filter/filter/filter.cmx ../filter/frontend/frontend.cmx ../rpc-pkcs11/pkcs11_rpclib.cmxa server.cmx -cclib -lpthread -cclib -lcamlidl -cclib -L../bindings-pkcs11 -ccopt -O2 -ccopt -fPIC -ccopt -fPIE -ccopt -Wl,-z,relro,-z,now -ccopt -fstack-protector -ccopt -DFORTIFY_SOURCE=2 -o pkcs11proxyd
/usr/lib64/ocaml/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): dans la fonction « abs_gnutls_srp_client_credentials_t_finalize »:
/opt/sources/ocamlnet-4.1.2/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:1894: référence indéfinie vers « gnutls_srp_free_client_credentials »
/usr/lib64/ocaml/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): dans la fonction « abs_gnutls_srp_server_credentials_t_finalize »:
/opt/sources/ocamlnet-4.1.2/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:1823: référence indéfinie vers « gnutls_srp_free_server_credentials »
/usr/lib64/ocaml/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): dans la fonction « net_gnutls_srp_allocate_client_credentials »:
/opt/sources/ocamlnet-4.1.2/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:6150: référence indéfinie vers « gnutls_srp_allocate_client_credentials »
/usr/lib64/ocaml/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): dans la fonction « net_gnutls_srp_set_client_credentials »:
/opt/sources/ocamlnet-4.1.2/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:6170: référence indéfinie vers « gnutls_srp_set_client_credentials »
/usr/lib64/ocaml/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): dans la fonction « net_gnutls_srp_allocate_server_credentials »:
/opt/sources/ocamlnet-4.1.2/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:6185: référence indéfinie vers « gnutls_srp_allocate_server_credentials »
/usr/lib64/ocaml/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): dans la fonction « net_gnutls_srp_set_server_credentials_file »:
/opt/sources/ocamlnet-4.1.2/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:6205: référence indéfinie vers « gnutls_srp_set_server_credentials_file »
/usr/lib64/ocaml/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): dans la fonction « net_gnutls_srp_server_get_username »:
/opt/sources/ocamlnet-4.1.2/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:6221: référence indéfinie vers « gnutls_srp_server_get_username »
/usr/lib64/ocaml/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): dans la fonction « net_gnutls_srp_set_prime_bits »:
/opt/sources/ocamlnet-4.1.2/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:6237: référence indéfinie vers « gnutls_srp_set_prime_bits »
/usr/lib64/ocaml/nettls-gnutls/libnettls-gnutls.a(nettls_gnutls_bindings_stubs.o): dans la fonction « net_gnutls_srp_verifier »:
/opt/sources/ocamlnet-4.1.2/src/nettls-gnutls/nettls_gnutls_bindings_stubs.c:6261: référence indéfinie vers « gnutls_srp_verifier »
collect2: erreur: ld a retourné 1 code d'état d'exécution
File "caml_startup", line 1:
Error: Error during linking
make[1]: *** [all] Erreur 2
make[1] : on quitte le répertoire « /opt/sources/caml-crush-1.0.8/src/pkcs11proxyd »
make: *** [server] Erreur 2
`
In order to proper compile camlcrush program, i had to comment all functions which caused errors defined into nettls-gnutls/.config.h .

This was suggested by @calderonth .

**Comment by dbuenzli** [comment]
I'm not sure this is related to the OCaml repository. If it is could you please give us more details.

**Comment by calderonth** [comment]
The bug is related to ocamlnet and should have been reported to ocamlnet
mailing list at ocamlnet-devel@lists.sourceforge.net.

Cheers,

Thomas

**Comment by dbuenzli** [comment]
Ok thanks @calderonth I'll let the reporter do this and close this.

**Comment by Batouu** [comment]
My apologizes, I will send the bug issue to ocamlnet-devel@lists.sourceforge.net.

**Comment by dbuenzli** [comment]
No problem.

**Comment by stephane-martin** [comment]
for reference: http://fa.caml.narkive.com/0IcfrE1b/caml-list-ocamlnet-and-missing-srp-functions-in-gnutls
