### ISSUE TITLE
`llvm` install fails on Ubuntu 16

### ISSUE THREAD

**Issue by vzaliva** [ocaml/opam-repository#9883]
`opam install llvm` on Ubuntu requires some OS dependencies and suggest `opam depext llvm.4.0.0`. Running it fails while executing this script: 
 https://gist.githubusercontent.com/jpdeplaix/8c67a7b7619983fb49a3e315bc53ae79/raw

In particular, it fails installing 'llvm-4.0-dev` package:

```
The following packages have unmet dependencies:
 llvm-4.0-dev : Depends: libjsoncpp0 (>= 0.6.0~rc2) but it is not installable
                Depends: llvm-4.0 (= 1:4.0~svn305264-1~exp1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by jpdeplaix** [comment]
This script is to be removed soon (#9856 have to merged first and then I'll make a PR secifically for llvm.4.0.0). But anyway, you don't really need ```ppa:likemartinma/devel``` so it can be removed and ```llvm-toolchain-trusty-4.0``` only works on Ubuntu Trusty (12.04) [1].
Depending on which version of Ubuntu you have (16.04 or 16.10), these command lines should do the trick:
```
sudo add-apt-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-UBUNTU-4.0 main'
curl -L http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install llvm-4.0-dev
```
Replace ```UBUNTU``` by your version. See http://apt.llvm.org/ to know the exact name.

[1]: This script was used to please Travis when submitting a package here.

**Comment by dbuenzli** [comment]
Thanks @jpdeplaix for the explanation. @vzaliva can you please tell us if this solves your issue ?

**Comment by vzaliva** [comment]
I am sorry, but since I reported this issue I realized and need llvm-3.8 not 4.0 which does not exhibit this problem. I already installed it and currently trying to switch to 4.0 will require me to reinstall some dependencies and will break my working environment. Because of this I am sorry I could not test the fix.

I hope my report was useful to other people who may want 4.0.

**Comment by dbuenzli** [comment]
Ok thanks for getting back to us. I'm closing this.
